export const meta = {
  name: 'completion-phase-3b',
  description: 'Completion phase 3b (after phase 3a and the tool patch): chapter 23 (reproduction, notebook 23a, glossary, index of checks and notebooks); notebook 00c report list; chapter 05 and its notebooks after the lead-check correction; LOVELOCK_GKD and its provenance after the comparison with the author - each with an adversarial verifier and one re-fix round',
  phases: [
    { title: 'Textbook', detail: 'chapter 23; 00c; chapter 05' },
    { title: 'Revision', detail: 'LOVELOCK_GKD and PROVENANCE_OF_THE_COMPUTATION after the author comparison' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const R = 'Revision'
const T = 'Revision/textbook'
const NOAGREE = "NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate, never accept an EULA); if a step needs that, stop that step and report it as an open item for the user."
const BOUND = `BOUNDED TASK (user, 2026-10-08: no hours-long agent jobs): work in small verified steps; after every step append one line to ${SP}/phase3b/<your label with ':' replaced by '-'>.progress.md (what is done, what is verified, what remains). Aim to finish within about 45 minutes of work. If the full task cannot be finished in that time, stop at a CONSISTENT, VERIFIED state (every file you leave must pass its own checks and tests) and list exactly what remains in open_items. Never leave a half-edited file. Do not commit (the lead commits and pushes). Run long jobs in the background and report their times; never wait idly.`
const STATE = `STATE (2026-10-08, phase 3b; committed and verified by the lead): the Revision record is complete through wave 2 (a4 on the author's T16 52/52 + 63/63; KS theory 46/46 + 58/58; KS cross-check 31/31; T3 + completion; dark sector both fields; ks_source; Lovelock/GKD; six documents registered in ${R}/pdf-specifications.json; Revision/notebooks/; the gate ${R}/verify_revision.{ps1,sh}). The lead-check record charge_conjugation_and_u1 was corrected (normal ordering adds no sign; only the local U(1) law is proved). The textbook tools were patched (${R}/workflows/completion/tools_patch.py: the shared troubleshooting step gives 'python -m jupyterlab' / 'python -m nbconvert --execute --inplace'; FACTS key work_folders; the PASS-line scanner reads normalised outputs) and every notebook was rebuilt with them. Read ${R}/README.md and ${T}/TEXTBOOK_SPEC.md first.`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const TBCOMMON = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree history or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R6: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3; R5: charge conjugation is a MATRIX; R6: a provenance file next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the run-instruction paragraph before each notebook, section 3; files and build, section 4). The shared tools in ${ROOT}/${T}/tools/ are used, never edited (report tool problems in open_items). Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase3b/<your label>/. Numbers only from Revision records or from the notebooks' own computations. Plain, precise English for a student who knows only school algebra and one-variable calculus. Other agents work in parallel: touch ONLY the files your task names.`
const QUOTES = `QUOTED CODE MUST MATCH THE NOTEBOOKS: run python ${T}/tools/audit/walkthrough_diff.py <chapter.md> <notebook.ipynb> <id> for every notebook of your chapter and check each report by hand. Allowed conventions: captions shortened with a separate line '...)', docstrings omitted, the generated set-up cell In [1] not quoted.`
const CHECKTAIL = `Rebuild every notebook whose builder you change (python ${T}/tools/nbkit.py build <builder> --date 2026-10-08) and run python ${T}/tools/nbkit.py check on every notebook of the chapter; ${QUOTES} Test-build the chapter with python ${T}/tools/check_chapter.py <chapter.md> until chapter_check=OK with no problem= or latex_warning= lines.`
const tbk = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const verify = (label, what, report) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}; adversarial verifier; do NOT edit files): ${what} The fixer's report (JSON): ${JSON.stringify(report || {}).slice(0, 30000)}\nCheck every claim in the files themselves, re-derive, re-read every number from its record, re-run the notebooks (nbkit check) and check_chapter. Report as findings ONLY real problems, with concrete evidence.`, { label, phase: 'Textbook', schema: FINDINGS })
const refix = (label, owns, v) => (v && v.findings && v.findings.length)
  ? tbk(label, `${owns} An adversarial verifier found these problems (JSON): ${JSON.stringify(v.findings).slice(0, 50000)}\nRe-verify each; fix the confirmed ones at the root; reject the others with evidence. ${CHECKTAIL} One line per finding in key_results: FIXED / REJECTED (reason).`)
  : v

const OWN23 = `You own ${T}/chapters/23-reproducing-everything.md (now a marked PLACEHOLDER) and the new notebook 23a (builder ${T}/notebooks/src/23a_<short>.py, ${T}/notebooks/23a*, ${T}/figures/23a*).`
const OWN00C = `You own ${T}/notebooks/src/00c_honesty_ledger.py, ${T}/notebooks/00c_honesty_ledger.{ipynb,PROVENANCE.md}, ${T}/figures/00c* and ${T}/chapters/00-how-to-use-this-book.md.`
const OWN05 = `You own ${T}/chapters/05-pin-spin-and-charge-conjugation.md and the builders/notebooks/PROVENANCE/figures of 05c and 05e (${T}/notebooks/src/05[ce]*.py, ${T}/notebooks/05[ce]*, ${T}/figures/05[ce]*).`

const results = await parallel([
  () => tbk('tb-23', `${OWN23} Write chapter 23, "Reproducing everything", per TEXTBOOK_SPEC section 5 (chapter 23) and the deep-dive standard: (1) every command that reproduces the book and its record, in dependency order, for Windows 11 (PowerShell), macOS (zsh) and Linux (bash): the Revision gate ${R}/verify_revision.{ps1,sh} (read its header: steps, options --dry-run/--steps/--fast, expected wall time per step) and, step by step, what it runs; every notebook of the book (nbkit check, one command per chapter group); the book assembly and the PDF build (TEXTBOOK_SPEC section 4); what each command prints when it works; how long it takes (read the measured times from the PROVENANCE files and the gate header, never invent); what to do when something fails. (2) Notebook 23a: a table of every notebook of the book (id, title, number of checks, figures, the last recorded nbkit check: date, result, seconds - read from each ${T}/notebooks/*.PROVENANCE.md nbkit-record line) and a timing bar chart, plus at least three more teaching figures (checks per chapter, figures per chapter, run time per chapter); by DEFAULT it reads the recorded check results (say so plainly in the notebook and the chapter: it does not re-run the other notebooks); with the environment variable BOOK_RERUN_ALL=1 it runs python ${T}/tools/nbkit.py check on every builder (in parallel, into a scratch folder) and tabulates the fresh results - state the measured time of that mode (run it once in the background and measure it). (3) The index of the checks of the Revision record (every check name of every ${R}/**/reports/*.json and report-like JSON, its report file, its verdict, and the chapters that cite it - generated by the notebook, printed as a table and written to a data file listed in FACTS files_written) and of the notebooks (id -> chapter section). Leave a section heading "23.N Glossary" with the single sentence "The glossary follows." at the END of the chapter; another agent fills it after you. Build 23a (nbkit build --date 2026-10-08, check), write its run-instruction paragraph, walk-through (every code line explained) and figure captions; exercises with worked answers; the proved/computed/assumed section. ${CHECKTAIL}`)
    .then(f => tbk('tb-23-glossary', `You own ONLY the glossary section at the end of ${T}/chapters/23-reproducing-everything.md (the heading "23.N Glossary" written by the previous agent; replace its placeholder sentence). TEXTBOOK_SPEC section 1(b): every technical word is defined at first use AND again in the glossary. Collect every technical word that the book defines (the "words used" sections 3 of every notebook, the bold first-use definitions of every chapter ${T}/chapters/*.md, and these words reported missing by the chapter fixers: brane / Z2 brane, principal part, Lax-Mizohata theorem, Euler density, Euler characteristic, signed permutation matrix, projector, chiral projectors, junction condition, brane tension, Legendre transform, vacuum, vacuum decay, false vacuum, tunnelling, barrier, cross-section, Bogoliubov coefficient, wave function of the universe, path integral, isometry, frame current q8, no-flux condition at the brane, Einstein-Hilbert Lagrangian, quantum cosmology, Wheeler-DeWitt equation, no-boundary proposal). Write one alphabetical entry per word: a plain-words definition consistent with the chapter that defines it (quote its meaning, do not invent a different one) and the section(s) where it is defined. Then test-build the chapter with python ${T}/tools/check_chapter.py until chapter_check=OK with no problem= or latex_warning= lines. The previous agent's report (JSON): ${JSON.stringify(f || {}).slice(0, 8000)}`))
    .then(g => verify('verify-tb-23', `Chapter 23 (${T}/chapters/23-reproducing-everything.md) and notebook 23a were written; the glossary was added. Check: every command is correct and complete for all three systems (run the Windows ones and, where possible, the bash ones; the gate with --dry-run), every time quoted is a measured one with its source, the 23a notebook (nbkit check; its default mode reads records and says so; the BOOK_RERUN_ALL mode is described truthfully), the index of checks is complete against the reports, the glossary definitions agree with the chapters that define the words and no defined word of the book is missing (sample at least 60 words across all chapters), check_chapter.`, g))
    .then(v => refix('refix:23', OWN23 + ' (and its glossary section)', v)),
  () => tbk('tb-00c', `${OWN00C} Notebook 00c (the honesty ledger) asserts the list of Revision reports ('the search finds exactly the 27 reports of the list') and its totals; wave 2 added reports (Revision/dark_sector/dirac16complex/reports/* and outputs/eos-summary.json, Revision/dark_sector/dirac16complex00/reports/*, Revision/field_equations_a4/ks_source/reports/ks-source-a4.json, Revision/pairing/kohn_sham/reports/{t3-rust-demo,t3-reference-demo,wolfram-t3-completion,python-t3-completion}.json, Revision/gkd_lovelock/comparison/author-comparison-report.json if present, Revision/notebooks reports if any) and changed counts (wolfram-t3.json, ks-crosscheck.json 31). Update REPORT_GROUPS, LEDGER rows (the dark-sector row's label: the hypotheses are now INVESTIGATED with stated results - not established; ks_source with the a4 row; the T3 demos and completion with the T3 row), README_ORDER and SUBJECTS to the complete current record, find every report by the same search the notebook uses (never hard-code a list that the search would contradict), rebuild 00c (nbkit build --date 2026-10-08), check it, and update chapter 00 where it quotes 00c's numbers (totals, rows, the walk-through of the changed cells: ${QUOTES}). The lead-check details printed by 00c changed (normal ordering; U(1) local law): re-quote and explain. Test-build chapter 00 with check_chapter.`)
    .then(f => verify('verify-tb-00c', `Notebook 00c and chapter 00 were updated to the complete wave-2 record. Check every report of ${R} is found and classified correctly, every total, every ledger label against R3 (nothing called proved or established that is not), the walk-through, nbkit check of 00a-00d, check_chapter.`, f))
    .then(v => refix('refix:00c', OWN00C, v)),
  () => tbk('tb-05', `${OWN05} The lead-check record was corrected (${R}/lead_checks/charge_conjugation_and_u1.py and reports/charge-conjugation-and-u1.json, commit 0eb99c0): the detail of bilinears_under_charge_conjugation no longer claims that normal ordering supplies one more sign (it now says normal ordering adds no sign: it subtracts the vacuum value, a number), and the detail of u1_noether_matrix_identity now says only the LOCAL law is proved (constancy of the total charge needs no flux through the brane z = pi/2). Chapter 05 (around 5.34 and its OPEN table row, lines ~3805, ~3840, ~4775) and notebooks 05c (builder line ~769) and 05e (builder lines ~26, ~1002, ~1157) describe the old remark as an OPEN contradiction for the record owner: update them to the corrected record (the contradiction is RESOLVED by the correction of 2026-10-08; keep the proof of 5.34 and the Fock-space computation of 05e, which now agree with the record), and fix any statement of total-charge conservation in chapter 05 the same way as chapters 10.2 and 18.21. Also search chapters 07, 10, 18 and 21 for sentences that quote the OLD record wording and list them (file, line) in open_items without editing them. ${CHECKTAIL}`)
    .then(f => verify('verify-tb-05', `Chapter 05 and notebooks 05c/05e were updated after the correction of the lead-check record (normal ordering adds no sign; only the local U(1) law is proved). Check every changed statement against the corrected record and against section 5.34 and Notebook 05e, that nothing still calls the remark an open contradiction, nbkit check of 05a-05f, the walk-through audit, check_chapter.`, f))
    .then(v => refix('refix:05', OWN05, v)),
  () => agent(`${NOAGREE}\nCONTEXT: repository ${ROOT} (git, branch main; Windows 11; Python 3.14; pdflatex). NEVER run git commands that change the index, the working tree history or the remote. BINDING: ${R}/SPEC.md and ${R}/README.md. HONESTY: numbers only from Revision outputs. Scratch only under ${SP}/phase3b/rev-lovelock-sync/. Other agents work in parallel: touch ONLY ${R}/docs/LOVELOCK_GKD.{md,tex,pdf}, its entry in ${R}/pdf-specifications.json (re-read the file right before --register; change only your entry), ${R}/tests/test_lovelock_gkd_publication.py and ${R}/gkd_lovelock/results/PROVENANCE_OF_THE_COMPUTATION.md.\n${STATE}\n${BOUND}\nTASK (rev-lovelock-sync): The comparison with the author's own stored outputs is now recorded in ${R}/gkd_lovelock/comparison/ (README, extract_author_curvature_outputs.wls, compare_with_author.py, author-curvature-outputs.json, author-comparison-report.json). Read it fully, re-run compare_with_author.py (it must reproduce its report byte for byte) and update ${R}/docs/LOVELOCK_GKD.md (the sentences that say the agreement with the author is NOT established; add a section or paragraph with the exact result: what was compared, the mapping, PASS/FAIL/NOT-AVAILABLE per object, what is still not established - e.g. no author output exists for the k = 2, 3 tensors if that is the finding) and ${R}/gkd_lovelock/results/PROVENANCE_OF_THE_COMPUTATION.md (the announced comparison now points to the record). Rebuild the PDF (verify mode until warning-free and two builds byte-identical; then --register), update the publication test (pins; read every quoted comparison number from author-comparison-report.json) and run it with REVISION_PDF_REBUILD=1 until it passes.`, { label: 'rev-lovelock-sync', phase: 'Revision', schema: RESULT }),
])
return { results }
