export const meta = {
  name: 'completion-phase-2b1',
  description: 'Completion phase 2b-1: Revision documents KOHN_SHAM_DEFLATING_FIELD and DARK_SECTOR_HYPOTHESES; textbook fixes 16 and 17; old Stage 4 diagnosis - small bounded agents',
  phases: [
    { title: 'Revision documents', detail: 'KS document, dark-sector document, wave-1 document updates' },
    { title: 'Notebooks and gate', detail: 'Revision notebooks (Kohn-Sham, dark sector); verify_revision.{ps1,sh} + test' },
    { title: 'Provenance', detail: 'rev-pairing-ks record incl. verify_t3_completion.wls' },
    { title: 'Textbook', detail: 'fix 16, 17; review then fix 19' },
    { title: 'Old Stage 4', detail: 'diagnose the three failing gauntlet comparisons, then fix at the root' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const R = 'Revision'
const T = 'Revision/textbook'
const NOAGREE = "NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate, never accept an EULA); if a step needs that, stop that step and report it as an open item for the user."
const BOUND = `BOUNDED TASK (user, 2026-10-08: no hours-long agent jobs): work in small verified steps; after every step append one line to ${SP}/phase2b/<your label>.progress.md (what is done, what is verified, what remains; ':' is not allowed in Windows file names, write '-'). Aim to finish within about 45 minutes of work. If the full task cannot be finished in that time, stop at a CONSISTENT, VERIFIED state (every file you leave must pass its own checks and tests) and list exactly what remains in open_items. Never leave a half-edited file. Do not commit (the lead commits and pushes). Run long jobs in the background and report their times; never wait idly.`
const STATE = `STATE (2026-10-08, phase 2b; all of it committed and verified by the lead): the a4 engine uses the author's T16 (Wolfram 52/52, sympy 63/63); KS theory 46/46 + 58/58; the full Kohn-Sham cross-check of the canonical matrix 31/31 (Revision/kohn_sham/reports/ks-crosscheck.json, 2026-10-08); dark sector: Revision/dark_sector/dirac16complex (derive 30/30, KS history 5/5, EoS 13/13, independent 9/9) and Revision/dark_sector/dirac16complex00 (see its README and reports); the a4 equations with the Kohn-Sham source: Revision/field_equations_a4/ks_source (see its README and reports); T3 completion: Revision/pairing/kohn_sham (t3-completion.json, Wolfram verify_t3_completion.wls, python check_t3_completion.py, numerics/ demos). Revision/docs/LOVELOCK_GKD and Revision/notebooks/ (infrastructure + the Lovelock notebook) were written in phase 2a: read them.`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const REVCOMMON = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main; Windows 11; Python 3.14 with numpy, sympy, mpmath, matplotlib, nbformat, nbclient - NO scipy; WolframScript 1.14 / Wolfram 15.0.1; Rust cargo 1.91; pdflatex MiKTeX). NEVER run git commands that change the index, the working tree or the remote (read-only git and clones into scratch are fine). The AUTHOR's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is read only. BINDING: ${ROOT}/${R}/SPEC.md (read it fully: the no-mixing rule, the author's metric and coordinate roles - x1..x3 space, x4 time, x5, x6, x7 the exponentially DEFLATING extra times (never static), x8 hidden - and sections 7-11) and ${ROOT}/${R}/README.md. NO-MIXING RULE: nothing from the old stages (artifacts/, provenance/, scripts/, wolfram/, notebooks/ at the root) is used as a Revision result. HONESTY: numbers only from Revision outputs (quote check counts exactly as the JSON reports give them); hypotheses investigated, never assumed; interpretation labelled; never "proved" for anything not proved. The author's private PDF (never committed, never quoted beyond these numbers): the Supernovae Unite constant-w fit w = -0.764; the CPL fit w(a) = w0 + wa (1 - a) with (w0, wa) = (-0.861, -0.60) (deep past w0 + wa = -1.461, phantom); thawing means wa < 0 in this convention. PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --specifications ${R}/pdf-specifications.json (verify mode until warning-free and two builds byte-identical; then --register; ${R}/pdf-specifications.json is SHARED: re-read it immediately before registering and change only your own entry). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2b/<your label>/. Other agents work in parallel: touch ONLY the files your task names.`
const TBCOMMON = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R6: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3 about pair creation and matter-antimatter; R5: charge conjugation is a MATRIX (calC_+ = C, calC_- = Gamma C); R6: a provenance file next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the run-instruction paragraph before each notebook, section 3; files and build, section 4). Also read ${ROOT}/Revision/SPEC.md sections 0-1 and ${ROOT}/Revision/README.md. The shared tools in ${ROOT}/${T}/tools/ are used, never edited (report tool problems in open_items). Tooling: Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks); Rust cargo 1.91 (crates Revision/gkd_lovelock/code, Revision/kohn_sham/solver carry their own [workspace]); pdflatex (MiKTeX). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2b/<your label>/. Numbers only from Revision records or from the notebooks' own computations (which must reproduce the Revision records where they overlap, with an assert naming the record file and check). Plain, precise English for a student who knows only school algebra and one-variable calculus.`
const QUOTES = `QUOTED CODE MUST MATCH THE NOTEBOOKS: run python ${T}/tools/audit/walkthrough_diff.py <chapter.md> <notebook.ipynb> <id> for every notebook of your chapter; it lists quoted blocks that no notebook cell contains (NO MATCH), wrong In [k] headings and unquoted cells. Check each report by hand (its section detection can be wrong when the chapter MENTIONS a walk-through before the real heading). Allowed conventions: captions shortened with a separate line '...)' (an inline 'save_figure(fig, "name", ...)' is NOT accepted - use the line form), docstrings omitted, the generated set-up cell In [1] not quoted. Every other mismatch must be fixed in the chapter (re-quote the notebook's current code and explain every new line).`
const FIXTAIL = `Re-verify each finding; fix every confirmed one at the root (rebuild changed notebooks with python ${T}/tools/nbkit.py build <builder> --date 2026-10-08 and check them; keep FACTS (final_lines, files_written) and every count consistent; delete stale figure files); reject unconfirmed ones with evidence. ALSO: run python ${T}/tools/nbkit.py check on EVERY notebook of the chapter (their Revision inputs changed in phase 1): rebuild any that fail and update the chapter text that quotes their output. ${QUOTES} Finally test-build the chapter alone with python ${T}/tools/check_chapter.py <chapter.md> until it prints chapter_check=OK with no problem= or latex_warning= lines. One line per finding in key_results: FIXED / REJECTED (reason).`
const rev = (label, ph, task) => agent(`${REVCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })
const tbk = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const DOCTAIL = `Follow the structure and style of the existing ${R}/docs/PAIR_CREATION_PROOFS.md (read it): numbered sections, every number read from a named report, a "what is proved / computed / assumed / not established" section, a complete reproduction section (exact commands in run order, expected output, run times). Build the PDF (verify mode until warning-free and two builds byte-identical), register it, write ${R}/tests/test_<document_lowercase>_publication.py in the style of ${R}/tests/test_pair_creation_proofs_publication.py (every number quoted in the document is read from its JSON report; registered sha256 and page count; MARKDOWN/TEX pins) and run it until it passes.`

const results = await parallel([
  () => rev('doc-kohn-sham', 'Revision documents', `Write ${R}/docs/KOHN_SHAM_DEFLATING_FIELD.md (+ tex, pdf, registered), deliverable 4 of SPEC section 10: the Kohn-Sham model of dirac16complex in the author's primordial field with the deflating extra times (from ${R}/kohn_sham/: ks-theory.json and the theory checks, the Rust solver and its reports, the independent reference, the full cross-check 31/31 and the refinement measurement, the results/ tables): the block reduction, the instantaneous ground and first excited states along the prescribed history a4 = A H x4, the Mermin thermodynamics, the adiabaticity and the Fermi-level crossings, the energy-momentum tensor profiles, the rescaling partners, the source conditions (the recorded states are NOT admissible sources of the a4 equations: ${R}/field_equations_a4/reports/ks-source-conditions.json and ${R}/field_equations_a4/ks_source/), T3 (pointer to PAIR_CREATION_PROOFS), what is not done (TDDFT, correlation, back-reaction). ${DOCTAIL}`),
  () => rev('doc-dark-sector', 'Revision documents', `Write ${R}/docs/DARK_SECTOR_HYPOTHESES.md (+ tex, pdf, registered), deliverable 5 of SPEC section 10: the two hypotheses of SPEC section 8 (Hypothesis for dirac16complex, Hypothesis00 for dirac16complex00), the lead's analysis of section 11 and what the computation found about each of its points, the observer assumption for rho_4 with the three definitions (A), (B), (C) and how every verdict depends on it, the method (exact derivations, conservation identities as checks, the Kohn-Sham history, the condensates, mixtures, the classical solutions of dirac16complex00 with Krein-signed energies, phantom conditions), the results for each field, the comparison with the Unite values (constant w = -0.764; CPL (-0.861, -0.60)), the verdict for dark energy and for dark matter for each field, stated exactly and honestly, and what remains open. Where a model's free parameters were CHOSEN so that it reproduces the Unite numbers (e.g. the populations M4 and M5 of dirac16complex00, and every mixture fraction fitted to w0 or to -0.764), say so explicitly: a model with as many tuned parameters as matched numbers reproduces them by construction and is NOT a prediction; and a ghost (negative-energy) component is a ghost-like sector, not an established physical state. Sources: everything under ${R}/dark_sector/ (both subfolders: READMEs, outputs, reports). ${DOCTAIL}`),
  () => tbk('fix:16', `You own chapter 16 (${T}/chapters/16-checking-the-solution-independently.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/16*.py, ${T}/notebooks/16*, ${T}/figures/16*). The cross-check report now has 31 checks (two new: thermo_levels, thermo_mu_rust_stated_bound; Revision/kohn_sham/reports/ks-crosscheck.json and Revision/kohn_sham/checker/README.md, rust-refinement.json grew new fields): notebook 16a pins (29, 29) and says '29 checks' - update the builders and the chapter to the current record (and teach the two new checks). The chapter's adversarial reviewer also found problems; they are in ${ROOT}/Revision/workflows/completion/review_16.json (fields severity, file, location, problem, evidence, fix): read ALL of it. ${FIXTAIL}`),
  () => tbk('fix:17', `You own chapter 17 (${T}/chapters/17-a4-equations-with-kohn-sham-source.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/17*.py, ${T}/notebooks/17*, ${T}/figures/17*). A4 SYNC: the a4 reports now have 52 (Wolfram) and 63 (sympy) checks and the engine uses the author's T16 (condensate witnesses S = 51200, 28800, 51200); the new Revision/field_equations_a4/ks_source/ (README, ks_source_a4.py, reports, results) specialises the a4 equations to the Kohn-Sham states - the chapter must teach its results (the x8 identity, the projection mismatch, the moment equations, the first integral and what can and cannot be integrated, with the stated approximation) where they belong, with a notebook computation if the chapter's examples need it. The chapter's adversarial reviewer also found problems; they are in ${ROOT}/Revision/workflows/completion/review_17.json: read ALL of it. ${FIXTAIL}`),
  () => agent(`${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main; Windows 11; Python 3.14; Rust cargo 1.91; WolframScript). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). Scratch only under ${SP}/phase2b/stage4/. Read files in chunks of at most 300 lines. The OLD Stage 4 (first edition, dirac16complex Kohn-Sham: handoff/specs/STAGE4_SPEC.md sections 7-8, scripts/ks_reference_*.py, studies/dirac16complex_cosmology (Rust), artifacts/dirac16complex/kohn-sham/, notebooks/dirac16complex_kohn_sham.ipynb with its runner and gauntlet, scripts/verify_stage4_kohn_sham.{ps1,sh}) was paused unfinished when the Revision replaced it; the user now wants every open stage completed. NEVER weaken a check or a tolerance to make it pass; fix causes.
${BOUND}
TASK (stage4-diagnose; do NOT edit repository files): The committed artifacts/dirac16complex/kohn-sham/notebook-report.json has verdict FAILURE: gauntlet rust_vs_reference_deltaSCF (worst 3.271e-06 vs tolerance 1.938e-06 at excited/m1_L3_N1016_lamm2_T0 and its _g601 twin), rust_vs_reference_eigenvalues (worst 1.541e-06 vs 1.054e-06 at excited/m1_L3_N1016_lamm2_T0_g601, eps -1.05374707), rust_vs_reference_particleHole (worst 4.126e-02 vs 1e-06 at the same states) and python_check_report SKIP (artifacts/dirac16complex/kohn-sham/python-check-report.json absent); four tests in tests/test_d16c_kohn_sham_notebook.py fail because of it; reference-summary.json was regenerated after the notebook ran (commit 33c07a3) and artifacts/dirac16complex/pair-creation/reference/reference-pairs-summary.json records old sha256 of scripts/ks_reference_solver.py and scripts/ks_reference_pairs.py. HANDOFF.md (search 'Stage 4') and notebooks/dirac16complex_kohn_sham.PROVENANCE.md (section 6) describe the state; the Revision found and fixed a related rule (the particle-hole occupation floor, commit 414d11e) and the Revision cross-check uses the tolerance rule |x_Rust - x_ref| <= 3(U_ref + U_Rust) + 1e-12 scale with MEASURED uncertainties. Diagnose each failure with data (re-run the two states with the Rust solver and the reference at 301 and 601 points and finer if needed, in scratch; compare the levels, the occupations and the particle-hole lists; measure both discretisation errors): is the Rust result wrong, the reference wrong, the comparison wrong (e.g. different particle-hole rules or labels), or the tolerance model wrong (an uncertainty that is not measured)? Also find out what the missing python-check-report.json is and which command makes it, and what regenerating the stale outputs requires. Deliver a precise, verified FIX PLAN: the exact code changes (file, function, lines, the new code) and the exact regeneration commands in order with their measured run times, and what each changed file affects (documents, PDFs, registries, tests, provenance files). key_results: one line per failure with the diagnosis and its evidence.`, { label: 'stage4-diagnose', phase: 'Old Stage 4', schema: RESULT }),
])
return { results }
