export const meta = {
  name: 'completion-phase-2b2',
  description: 'Completion phase 2b-2 (after T3 and the first Revision notebook): wave-1 document updates and README; Revision notebooks 2-3; the gate; T3 provenance; review and fix of textbook chapter 19 - small bounded agents',
  phases: [
    { title: 'Revision documents', detail: 'KS document, dark-sector document, wave-1 document updates' },
    { title: 'Notebooks and gate', detail: 'Revision notebooks (Kohn-Sham, dark sector); verify_revision.{ps1,sh} + test' },
    { title: 'Provenance', detail: 'rev-pairing-ks record incl. verify_t3_completion.wls' },
    { title: 'Textbook', detail: 'fix 16, 17; review then fix 19' },
    { title: 'Old Stage 4', detail: 'diagnose the three failing gauntlet comparisons, then fix at the root' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const R = 'Revision'
const T = 'Revision/textbook'
const NOAGREE = "NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate, never accept an EULA); if a step needs that, stop that step and report it as an open item for the user."
const BOUND = `BOUNDED TASK (user, 2026-10-08: no hours-long agent jobs): work in small verified steps; after every step append one line to ${SP}/phase2b/<your label>.progress.md (what is done, what is verified, what remains; ':' is not allowed in Windows file names, write '-'). Aim to finish within about 45 minutes of work. If the full task cannot be finished in that time, stop at a CONSISTENT, VERIFIED state (every file you leave must pass its own checks and tests) and list exactly what remains in open_items. Never leave a half-edited file. Do not commit (the lead commits and pushes). Run long jobs in the background and report their times; never wait idly.`
const STATE = `STATE (2026-10-08, phase 2b; all of it committed and verified by the lead): the a4 engine uses the author's T16 (Wolfram 52/52, sympy 63/63); KS theory 46/46 + 58/58; the full Kohn-Sham cross-check of the canonical matrix 31/31 (Revision/kohn_sham/reports/ks-crosscheck.json, 2026-10-08); dark sector: Revision/dark_sector/dirac16complex (derive 30/30, KS history 5/5, EoS 13/13, independent 9/9) and Revision/dark_sector/dirac16complex00 (see its README and reports); the a4 equations with the Kohn-Sham source: Revision/field_equations_a4/ks_source (see its README and reports); T3 completion: Revision/pairing/kohn_sham (t3-completion.json, Wolfram verify_t3_completion.wls, python check_t3_completion.py, numerics/ demos). Revision/docs/LOVELOCK_GKD and Revision/notebooks/ (infrastructure + the Lovelock notebook) were written in phase 2a: read them.`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const REVCOMMON = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main; Windows 11; Python 3.14 with numpy, sympy, mpmath, matplotlib, nbformat, nbclient - NO scipy; WolframScript 1.14 / Wolfram 15.0.1; Rust cargo 1.91; pdflatex MiKTeX). NEVER run git commands that change the index, the working tree or the remote (read-only git and clones into scratch are fine). The AUTHOR's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is read only. BINDING: ${ROOT}/${R}/SPEC.md (read it fully: the no-mixing rule, the author's metric and coordinate roles - x1..x3 space, x4 time, x5, x6, x7 the exponentially DEFLATING extra times (never static), x8 hidden - and sections 7-11) and ${ROOT}/${R}/README.md. NO-MIXING RULE: nothing from the old stages (artifacts/, provenance/, scripts/, wolfram/, notebooks/ at the root) is used as a Revision result. HONESTY: numbers only from Revision outputs (quote check counts exactly as the JSON reports give them); hypotheses investigated, never assumed; interpretation labelled; never "proved" for anything not proved. The author's private PDF (never committed, never quoted beyond these numbers): the Supernovae Unite constant-w fit w = -0.764; the CPL fit w(a) = w0 + wa (1 - a) with (w0, wa) = (-0.861, -0.60) (deep past w0 + wa = -1.461, phantom); thawing means wa < 0 in this convention. PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --specifications ${R}/pdf-specifications.json (verify mode until warning-free and two builds byte-identical; then --register; ${R}/pdf-specifications.json is SHARED: re-read it immediately before registering and change only your own entry). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2b/<your label>/. Other agents work in parallel: touch ONLY the files your task names.`
const TBCOMMON = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R6: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3 about pair creation and matter-antimatter; R5: charge conjugation is a MATRIX (calC_+ = C, calC_- = Gamma C); R6: a provenance file next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the run-instruction paragraph before each notebook, section 3; files and build, section 4). Also read ${ROOT}/Revision/SPEC.md sections 0-1 and ${ROOT}/Revision/README.md. The shared tools in ${ROOT}/${T}/tools/ are used, never edited (report tool problems in open_items). Tooling: Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks); Rust cargo 1.91 (crates Revision/gkd_lovelock/code, Revision/kohn_sham/solver carry their own [workspace]); pdflatex (MiKTeX). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2b/<your label>/. Numbers only from Revision records or from the notebooks' own computations (which must reproduce the Revision records where they overlap, with an assert naming the record file and check). Plain, precise English for a student who knows only school algebra and one-variable calculus.`
const QUOTES = `QUOTED CODE MUST MATCH THE NOTEBOOKS: run python ${T}/tools/audit/walkthrough_diff.py <chapter.md> <notebook.ipynb> <id> for every notebook of your chapter; it lists quoted blocks that no notebook cell contains (NO MATCH), wrong In [k] headings and unquoted cells. Check each report by hand (its section detection can be wrong when the chapter MENTIONS a walk-through before the real heading). Allowed conventions: captions shortened with a separate line '...)' (an inline 'save_figure(fig, "name", ...)' is NOT accepted - use the line form), docstrings omitted, the generated set-up cell In [1] not quoted. Every other mismatch must be fixed in the chapter (re-quote the notebook's current code and explain every new line).`
const FIXTAIL = `Re-verify each finding; fix every confirmed one at the root (rebuild changed notebooks with python ${T}/tools/nbkit.py build <builder> --date 2026-10-08 and check them; keep FACTS (final_lines, files_written) and every count consistent; delete stale figure files); reject unconfirmed ones with evidence. ALSO: run python ${T}/tools/nbkit.py check on EVERY notebook of the chapter (their Revision inputs changed in phase 1): rebuild any that fail and update the chapter text that quotes their output. ${QUOTES} Finally test-build the chapter alone with python ${T}/tools/check_chapter.py <chapter.md> until it prints chapter_check=OK with no problem= or latex_warning= lines. One line per finding in key_results: FIXED / REJECTED (reason).`
const rev = (label, ph, task) => agent(`${REVCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })
const tbk = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const DOCTAIL = `Follow the structure and style of the existing ${R}/docs/PAIR_CREATION_PROOFS.md (read it): numbered sections, every number read from a named report, a "what is proved / computed / assumed / not established" section, a complete reproduction section (exact commands in run order, expected output, run times). Build the PDF (verify mode until warning-free and two builds byte-identical), register it, write ${R}/tests/test_<document_lowercase>_publication.py in the style of ${R}/tests/test_pair_creation_proofs_publication.py (every number quoted in the document is read from its JSON report; registered sha256 and page count; MARKDOWN/TEX pins) and run it until it passes.`

const results = await parallel([
  () => rev('doc-updates', 'Revision documents', `Update the wave-1 documents ${R}/docs/DIRAC16COMPLEX_FIELD_THEORY.md, ${R}/docs/DIRAC16COMPLEX00_FIELD_THEORY.md and ${R}/docs/PAIR_CREATION_PROOFS.md with the wave-2 results: the a4 equations with the Kohn-Sham source (${R}/field_equations_a4/ks_source), the T3 completion (${R}/pairing/kohn_sham: t3-completion.json and its Wolfram and Python reports and numerics demos; add their counts to the count table of PAIR_CREATION_PROOFS section 9.1 and their commands to section 10 in the right order), the dark-sector verdicts (one paragraph each, pointing to DARK_SECTOR_HYPOTHESES), pointers to the new documents KOHN_SHAM_DEFLATING_FIELD, DARK_SECTOR_HYPOTHESES and LOVELOCK_GKD. Rebuild and re-register their three PDFs (re-read ${R}/pdf-specifications.json right before each registration; change only these three entries), update their publication tests (${R}/tests/test_*_publication.py: pins and quoted numbers) and run them until they pass. Also update ${R}/README.md: the folder table rows of kohn_sham/ (full cross-check 31/31), dark_sector/ (both hypotheses, with the report counts), field_equations_a4/ (ks_source), pairing/ (T3 completion), notebooks/, docs/ (all six documents) - every count read from its report.`),
  () => rev('revnb-ks-dark', 'Notebooks and gate', `Own ${R}/notebooks/ (created in phase 2a with its build tool ${R}/notebooks/tools/build_notebooks.py and the Lovelock notebook; read its README, tool, builder and PROVENANCE first) and ${R}/tests/test_revision_notebooks.py. Add, with the same tool and the same structure (numbered sections, complete Windows/macOS/Linux run instructions - never suggest 'python -m jupyter', which fails where the jupyter executables are not on PATH; use 'python -m jupyterlab' and 'python -m nbconvert' -, the words used, the physical situation, a Python driver cell that builds and runs the Revision Rust programs with subprocess into a scratch/output folder, the program reciting its configuration, tables, checks against the committed Revision records, teaching figures, a final "what this showed / did not show" section, a PROVENANCE file): (2) the Kohn-Sham states in the deflating field (Revision/kohn_sham: solver runs of a few canonical states, levels, profiles, the comparison with the committed results and with the cross-check), (3) the dark-sector hypotheses (Revision/dark_sector: the effective formulas, the w_eff histories under the three observer definitions, the condensate, mixtures, the Unite comparison). Build each twice (byte-identical), check, extend the test, run it.`),
  () => rev('gate', 'Notebooks and gate', `Own ${R}/verify_revision.ps1 and ${R}/verify_revision.sh (twins: same step list, same checks, same final line) and ${R}/tests/test_revision_gate.py. Read scripts/verify_stage3_dark_sector.sh and .ps1 for the structure only (run_logged-style logs under build/logs/, stop at the first failing step with <prefix>_failed_step=..., a final line). The gate re-runs EVERY Revision verifier and checker in dependency order (algebra Wolfram + sympy; theory scope + field theory Wolfram + sympy + compare; pairing Wolfram + sympy; field_equations_a4 Wolfram + sympy + ks-source-conditions + ks_source; kohn_sham theory Wolfram + sympy, the Rust solver build + its runs and determinism/Mermin reports, the reference, the cross-check and refinement; pairing/kohn_sham T3 + T3 completion + numerics demos; gkd_lovelock Rust + Wolfram + sympy + notebook reading; dark_sector both parts; lead_checks; the Revision notebooks check; the six document PDFs in verify mode) - read each folder's README for the exact commands, inputs, outputs and run times - and then requires that every committed output is byte-for-byte unchanged (git diff --quiet on the output paths, and a list of the paths that differ when not) and that every report's checks pass; then python -m unittest discover -s ${R}/tests (except the textbook test, which has its own build). Options: --dry-run (print the steps with their expected wall times), --steps a,b,c (run only those), --fast (skip the steps documented as longer than 5 minutes; print which were skipped). Final line revision_verification=OK (or =FAILED). Document the expected wall time per step in a header comment of both twins; do NOT edit ${R}/README.md (another agent owns it): put the text of a short "Reproduce everything" section for it into open_items. ${R}/tests/test_revision_gate.py: static checks always (both twins list the same steps; every step's command names an existing file; every Revision .wls and checker is covered), and with REVISION_GATE_FULL=1 runs the gate --fast. Run the gate --fast yourself (both twins: bash and PowerShell 7) and report the times; run the full gate once in the background if time allows and report.`),
  () => rev('prov-t3', 'Provenance', `Own ${R}/pairing/kohn_sham/wolfram/WOLFRAMSCRIPT_PROVENANCE.md, the execution-provenance record of the set rev-pairing-ks. The set now has a second script, verify_t3_completion.wls (with its outputs reports/wolfram-t3-completion.json and t3-completion.json): read the file fully and the new script, then extend the record to the WHOLE set: what each script computes, file hashes (sha256) and line counts of every script and input, outputs with sha256, expected output of each script (checks and failures), the ERROR exits, measured run times and memory, side effects (incl. WolframScript's two tmp_* files in %LOCALAPPDATA%\\Wolfram\\WolframScript\\WolframScriptTemporary and what an interrupted run leaves), complete Windows/macOS/Linux instructions, and a new verification record: follow the file LITERALLY in two fresh clones under ${SP}/phase2b/prov-t3/ (clone https://github.com/once-ere/Dirac_claude.git at the current origin/main), byte identity of every output with the committed files. The file must name the CURRENT sha256 of both scripts (tests/test_execution_provenance.py checks it). Also add the new script to provenance/EXECUTION_PROVENANCE_INDEX.md row 5 (scripts column, with <br> between scripts; update the checks column) and run python -m unittest discover -s tests -p "test_execution_provenance.py" until it passes.`),
  () => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (adversarial reviewer of chapter 19; do NOT edit files): Review chapter ${T}/chapters/19-t3-kohn-sham-universes.md and its notebooks (19a, 19b) against TEXTBOOK_SPEC and against the CURRENT Revision record of T3 (Revision/pairing/kohn_sham: t3-theory.json, t3-completion.json, both Wolfram and both Python reports, the numerics demos; the README): re-execute each notebook with python ${T}/tools/nbkit.py check <builder>; re-derive the key derivations; check every formula and number; the T3 statement exactly as proved (ASSUMED Z2 brane, transformed boundary conditions, (m, lambda, theta) -> (-m, +lambda, pi - theta), the prescribed background); the deep-dive standard; the run instructions; R2/R3/R5/R6 (overclaims about pair creation are MAJOR); exercises. ${QUOTES} Report only real problems with concrete evidence.`, { label: 'review:19', phase: 'Textbook', schema: FINDINGS })
    .then(r => (r && r.findings && r.findings.length)
      ? tbk('fix:19', `You own chapter 19 (${T}/chapters/19-t3-kohn-sham-universes.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/19*.py, ${T}/notebooks/19*, ${T}/figures/19*). Reviewer findings (JSON): ${JSON.stringify(r.findings).slice(0, 60000)}\n${FIXTAIL}`)
      : { files_changed: [], commands_run: [], all_checks_pass: !!r, failing: r ? [] : ['review:19 returned nothing'], key_results: [r ? 'review:19: no findings' : 'review:19: no result'], open_items: [], summary: r ? 'chapter 19 reviewed without findings' : 'review 19 failed' }),
])
return { results }
