export const meta = {
  name: 'completion-phase-2a',
  description: 'Completion phase 2a (independent of phase 1): the LOVELOCK_GKD document; textbook fixes of chapters 14 and 15; review and fix of chapters 18, 20, 21, 22 - small bounded agents',
  phases: [
    { title: 'Revision documents', detail: 'Revision/docs/LOVELOCK_GKD md+tex+pdf, registered, with its publication test' },
    { title: 'Textbook', detail: 'fix 14, 15; review then fix 18, 20, 21, 22' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const R = 'Revision'
const T = 'Revision/textbook'
const NOAGREE = "NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate, never accept an EULA); if a step needs that, stop that step and report it as an open item for the user."
const BOUND = `BOUNDED TASK (user, 2026-10-08: no hours-long agent jobs): work in small verified steps; after every step append one line to ${SP}/phase2/<your label>.progress.md (what is done, what is verified, what remains). Aim to finish within about 45 minutes of work. If the full task cannot be finished in that time, stop at a CONSISTENT, VERIFIED state (every file you leave must pass its own checks and tests) and list exactly what remains in open_items. Never leave a half-edited file. Do not commit (the lead commits and pushes).`
const STATE = "STATE (2026-10-08, phase 2a): the a4 engine uses the author's T16 from gammas.json (Wolfram 52/52, Python 63/63; a4-equations.json unchanged; condensate witness S = 51200, 28800, 51200); the Mermin repair is done (solver 42/42, determinism 14/14, KS theory 58/58); check_field_theory.py 70/70. PARALLEL WORK RUNNING NOW (do NOT touch their files): the phase-1 workflow edits Revision/kohn_sham/checker and reference, Revision/pairing/kohn_sham, Revision/field_equations_a4 (wolfram provenance, ks_source/), Revision/dark_sector, notebooks/, and textbook chapters 00-03, 05-13 with their notebooks; chapters 16, 17, 19 wait for phase 1. Touch only what your task names."
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const TBCOMMON = `
${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R6: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3 about pair creation and matter-antimatter; R5: charge conjugation is a MATRIX (calC_+ = C, calC_- = Gamma C; for real fields plain complex conjugation is the identity - never call it charge conjugation); R6: a provenance file X.PROVENANCE.md next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the complete self-contained run-instruction paragraph before each notebook, section 3; files and build, section 4). Also read ${ROOT}/Revision/SPEC.md sections 0-1 and ${ROOT}/Revision/README.md. The shared tools in ${ROOT}/${T}/tools/ are used, never edited (if a tool is wrong, report it in open_items). Tooling: Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks); Rust cargo 1.91 (crates ${ROOT}/Revision/gkd_lovelock/code, ${ROOT}/Revision/kohn_sham/solver carry their own [workspace]); pdflatex (MiKTeX). Deterministic outputs (LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2/<your label>/. Numbers only from Revision records or from the notebooks' own computations (which must reproduce the Revision records where they overlap, with an assert naming the record file and check). Plain, precise English for a student who knows only school algebra and one-variable calculus.`
const QUOTES = `QUOTED CODE MUST MATCH THE NOTEBOOKS: run python ${T}/tools/audit/walkthrough_diff.py <chapter.md> <notebook.ipynb> <id> for every notebook of your chapter; it lists quoted blocks that no notebook cell contains (NO MATCH), wrong In [k] headings and unquoted cells. Its section detection can be wrong when the chapter MENTIONS a walk-through before the real heading: check each report by hand. Allowed conventions: captions shortened with a line '...)', docstrings omitted, the generated set-up cell In [1] not quoted. Every other mismatch must be fixed in the chapter (re-quote the notebook's current code and explain every new line).`
const FIXTAIL = `Re-verify each finding; fix every confirmed one at the root (rebuild changed notebooks with python ${T}/tools/nbkit.py build <builder> --date 2026-10-08 and check them; keep FACTS (final_lines, files_written) and every count consistent; delete stale figure files); reject unconfirmed ones with evidence. ALSO: run python ${T}/tools/nbkit.py check on EVERY notebook of the chapter (inputs may have changed since they were built, e.g. the a4 reports now have 52/63 checks): rebuild any that fail and update the chapter text that quotes their output. ${QUOTES} Finally test-build the chapter alone with python ${T}/tools/check_chapter.py <chapter.md> until warning-free. One line per finding in key_results: FIXED / REJECTED (reason).`
const tbk = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const CH = { '14': 'kohn-sham-model', '15': 'solving-the-kohn-sham-equations', '18': 'pairing-theorems', '20': 'do-universes-come-in-pairs', '21': 'matter-and-antimatter', '22': 'open-problems' }
const owns = nn => `You own chapter ${nn} (${T}/chapters/${nn}-${CH[nn]}.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/${nn}*.py, ${T}/notebooks/${nn}*, ${T}/figures/${nn}*).`
const review = nn => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (adversarial reviewer of chapter ${nn}; do NOT edit files): Review chapter ${T}/chapters/${nn}-${CH[nn]}.md and its notebooks against TEXTBOOK_SPEC: re-execute each notebook with python ${T}/tools/nbkit.py check <builder>; re-derive the key derivations and check every formula and number against the Revision records it cites; the deep-dive standard (skipped steps, undefined words, unexplained code lines, figures without teaching captions); the run instructions; R2/R3/R5/R6 (overclaims about pair creation, matter-antimatter, dark energy are MAJOR); exercises and answers. ${QUOTES} Report only real problems with concrete evidence (file, location, quoted text, the record or computation that contradicts it).`, { label: `review:${nn}`, phase: 'Textbook', schema: FINDINGS })
const reviewFix = nn => review(nn).then(r => (r && r.findings && r.findings.length)
  ? tbk(`fix:${nn}`, `${owns(nn)} The chapter's adversarial reviewer found ${r.findings.length} problems (JSON): ${JSON.stringify(r.findings).slice(0, 60000)}\n${FIXTAIL}`)
  : { files_changed: [], commands_run: [], all_checks_pass: !!r, failing: r ? [] : [`review:${nn} returned nothing`], key_results: [r ? `review:${nn}: no findings` : `review:${nn}: no result`], open_items: [], summary: r ? `chapter ${nn} reviewed without findings` : `review ${nn} failed` })

const LOVELOCK_DOC = `${NOAGREE}
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). The AUTHOR's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is read only. BINDING: ${ROOT}/${R}/SPEC.md (read it fully; section 10 lists this document as deliverable 6) and ${ROOT}/${R}/README.md. NO-MIXING RULE: nothing from the old stages (artifacts/, provenance/, scripts/, wolfram/, notebooks/) is used as a Revision result. HONESTY: numbers only from Revision outputs; label interpretation; never "proved" for anything not proved. Read files in chunks of at most 300 lines. Scratch only under ${SP}/phase2/lovelock-doc/.
${STATE}
${BOUND}
TASK (lovelock-doc): Write the Revision document 6 of SPEC section 10, ${R}/docs/LOVELOCK_GKD.md, and build its .tex and .pdf. Source: everything under ${R}/gkd_lovelock/ (code/ - the pure-Rust generalized Kronecker delta and the Lovelock tensors; results/ - curvature.json, gkd-selftest.json, lovelock-tensors.json, lovelock-report.json, lovelock-components.md, python-lovelock-report.json, wolfram-gkd-report.json, PROVENANCE_OF_THE_COMPUTATION.md; verification/ - the Wolfram verifier (29 checks) and the sympy checker; notebook_reading/ - what the author's notebook computes and how it was read) and how ${R}/field_equations_a4 uses the Lovelock tensors. Content: the author's metric and coordinates (x5-x7 deflating extra times), the definition of the GKD and of the Lovelock tensors of order k = 1, 2, 3 with all index conventions and normalisations, how the code computes them (cite the source files and functions), every result with the numbers from the reports (quote the check counts of each report exactly as the JSON files give them), the independent verifications (Wolfram, sympy) and their scope, the comparison with the author's notebook, what is NOT established, and a complete reproduction section (exact commands, expected output, run times from the provenance files). Follow the structure and style of the existing ${R}/docs/PAIR_CREATION_PROOFS.md (read it). Build: python scripts/build_provenance_pdf.py ${R}/docs/LOVELOCK_GKD.md --developer-layout --specifications ${R}/pdf-specifications.json (verify mode until warning-free and two builds byte-identical; then --register; ${R}/pdf-specifications.json is shared: re-read it immediately before registering and change only your own entry). Write ${R}/tests/test_lovelock_gkd_publication.py in the style of ${R}/tests/test_pair_creation_proofs_publication.py (every number quoted in the document is read from its JSON report; the PDF is registered with the right sha256 and page count; MARKDOWN/TEX pins) and run it until it passes; also run python -m unittest ${R}/tests/test_gkd_lovelock.py (it must still pass). Update the docs row of ${R}/README.md (the line that lists the documents) for LOVELOCK_GKD only.`

phase('Textbook')
const results = await parallel([
  () => agent(LOVELOCK_DOC, { label: 'lovelock-doc', phase: 'Revision documents', schema: RESULT }),
  () => tbk('fix:14', `${owns('14')} The chapter's adversarial reviewer found 12 problems; they are in ${SP}/phase2/review_14.json (fields severity, file, location, problem, evidence, fix): read ALL of it. ${FIXTAIL}`),
  () => tbk('fix:15', `${owns('15')} The chapter's adversarial reviewer found 7 problems; they are in ${SP}/phase2/review_15.json (fields severity, file, location, problem, evidence, fix): read ALL of it. ${FIXTAIL}`),
  () => reviewFix('18'),
  () => reviewFix('20'),
  () => reviewFix('21'),
  () => reviewFix('22'),
])
return { results }
