export const meta = {
  name: 'completion-phase-1',
  description: 'Completion phase 1: Revision wave-1b full KS cross-check, wave-2 science (dark sector x2, a4 with KS source, T3), the two open provenance records, textbook chapter fixes 00-13 and the review/fix of chapter 11 - small bounded agents',
  phases: [
    { title: 'Revision science', detail: 'KS full cross-check; dark sector dirac16complex and dirac16complex00; a4 with the KS source; T3' },
    { title: 'Provenance', detail: 'rev-a4 record (patched engine); nb-kohn-sham fix' },
    { title: 'Textbook', detail: 'fixers for chapters 00-13; review and fix of chapter 11' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const R = 'Revision'
const T = 'Revision/textbook'
const W2COMMON = `
NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (e.g. never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate or accept an EULA); if a step needs that, stop that step and report it as an open item for the user.
RESTART NOTE: launched in a new session after wave 1b; files of an earlier wave-2 attempt may exist: inspect, verify and finish them, never trust them unchecked.
CONCURRENCY NOTE (2026-10-07): other workflows run at the same time. NEVER edit Revision/textbook/ (any file), Revision/tests/test_universes_in_pairs_textbook.py, provenance/, notebooks/, tests/: they belong to the textbook, execution-provenance and dirac-matrices workflows. Revision/pdf-specifications.json is shared: re-read it immediately before any change and change only your own entries. Read-only use of every file is fine.
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; read-only git is fine. You work ONLY inside ${ROOT}/${R}/ (plus scratch). BINDING: ${ROOT}/${R}/SPEC.md (read it fully: the no-mixing rule, the author's metric and coordinate roles - x5, x6, x7 are the exponentially DEFLATING extra times - and sections 7, 8, 9, 11) and ${ROOT}/${R}/README.md. Read every wave-1 result first: ${R}/algebra, ${R}/theory, ${R}/field_equations_a4, ${R}/pairing, ${R}/gkd_lovelock, ${R}/kohn_sham, ${R}/docs. NO-MIXING RULE: nothing from the old stages is used as a Revision result. HONESTY: numbers only from Revision outputs; hypotheses investigated, never assumed; interpretation labelled; never "proved" for anything not proved. The author's private PDF (never committed, never quoted beyond these numbers): the Supernovae Unite constant-w fit w = -0.764 (Unite SN alone, about 2 sigma from -1); the time-evolving CPL fit w(a) = w0 + wa (1 - a) with (w0, wa) = (-0.861, -0.60) (deep past w0 + wa = -1.46, phantom); quintessence rho = phidot^2/2 + V, P = phidot^2/2 - V; thawing means wa < 0 in this convention (the PDF's table states the opposite signs; the formula decides). Tooling as in wave 1 (PDFs via python scripts/build_provenance_pdf.py <md> --developer-layout --specifications ${R}/pdf-specifications.json [--register]). Deterministic outputs; checks in JSON reports. Read files in chunks of at most 300 lines. Scratch only under ${SP}/revision2/<label>/.
`
const TBCOMMON = `
NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (e.g. never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate or accept an EULA); if a step needs that, stop that step and report it as an open item for the user.
RESTART NOTE: this workflow was stopped once and relaunched; files of the earlier run may exist (e.g. Revision/textbook/tools/run_instructions.py, requirements.txt): inspect, verify and finish them, never trust them unchecked.
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R4: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3 about pair creation and matter-antimatter; R5: charge conjugation is a MATRIX (calC_+ = C, calC_- = Gamma C; for real fields plain complex conjugation is the identity - never call it charge conjugation); R6: a provenance file X.PROVENANCE.md next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the complete self-contained run-instruction paragraph before each notebook, section 3; files and build, section 4). Also read ${ROOT}/Revision/SPEC.md sections 0-1 and ${ROOT}/Revision/README.md. The shared tools in ${ROOT}/${T}/tools/ and their README are owned by the infra agent: use them, never edit them (if a tool is wrong, work around it locally and report it in open_items). Tooling: Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks); Rust cargo 1.91 (the Revision crates: ${ROOT}/Revision/gkd_lovelock/code, ${ROOT}/Revision/kohn_sham/solver; build with cargo build --release --manifest-path ...; a stray Cargo.toml sits above the repository, the crates carry their own [workspace]); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --number-sections-from-zero --specifications Revision/pdf-specifications.json (verify mode; only the assembly agent uses --register for the book). Deterministic outputs (two builds byte-identical, LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/textbook/<your label>/. Run long jobs and report their times; never wait idly. Numbers only from Revision records or from the notebooks' own computations (which must reproduce the Revision records where they overlap, with an assert naming the record file and check). Write in plain, precise English for a student who knows only school algebra and one-variable calculus.
`
const BOUND = "BOUNDED TASK (user, 2026-10-08: no hours-long agent jobs): work in small verified steps; after every step append one line to C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/phase1/<your label>.progress.md (what is done, what is verified, what remains). Aim to finish within about 45 minutes of work. If the full task cannot be finished in that time, stop at a CONSISTENT, VERIFIED state (every file you leave must pass its own checks and tests) and list exactly what remains in open_items. Never leave a half-edited file. Do not commit (the lead commits and pushes). NEVER accept licence terms, source agreements or any other agreement."
const STATE = "STATE (2026-10-08): the a4 engine now uses the author's T16 from gammas.json (Wolfram 52/52, Python 63/63; a4-equations.json unchanged; condensate witness S = 51200, 28800, 51200); wave-1b's Mermin repair is done (solver 42/42, determinism 14/14, KS theory 58/58, cross-check 29/29 on the representative subset); check_field_theory.py reproduces its report (70/70, comparison agree). Other agents work in parallel on other directories; touch only what you own."
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const rev = (label, ph, task) => agent(`${W2COMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })
const tbk = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const XCHECK = `You own ${R}/kohn_sham/reference/ and ${R}/kohn_sham/checker/ and their reports. The Rust solver was just repaired (Mermin mu; summary: ${'the Mermin repair is done and verified: see STATE'}). Extend the cross-check from the representative subset (18 of 75 ground, 8 of 135 thermal) to the FULL canonical matrix: every ground state, every thermal state, the exact-Fock variant SCF energies (not only the Delta E_x diagnostic), the rescaling partners, the particle-hole lists, the sea-hole diagnostic and the crossing demonstration. Keep the tolerance rule fixed BEFORE comparing (|x_Rust - x_ref| <= 3(U_ref + U_Rust) + 1e-12 scale with measured uncertainties); never weaken it. Make the reference repeat check reproducible (the checker creates and compares the repeat directory itself). Run in parallel processes; report the times. Report every failure honestly with a data-driven diagnosis; a Rust defect goes precisely into open_items and failing.`
const TASK_dark_sector_dirac16complex = `Own ${R}/dark_sector/dirac16complex/ (code, outputs, reports). Investigate the Hypothesis for dirac16complex (SPEC sections 8 and 11): the equation of state a 3-space observer infers as the extra times deflate and 3-space inflates (a = e^{a4}), for (i) the Kohn-Sham fermion gas of ${R}/kohn_sham (instantaneous states along a4; the 3-space pressure p3, the extra-time pressure p_t, the hidden pressure p8, rho; the 4-dimensional effective density rho_4 obtained by integrating over the hidden direction and the extra times, the dilution-inferred w_eff = -1 - (1/3) d ln rho_4 / d ln a and the ratio w = p3/rho), (ii) homogeneous condensates (the exact solutions of the field equations in this metric), (iii) mixtures; derive every effective formula exactly (sympy) before computing; the extra times x5..x7 are TIME-LIKE: integrating over them to define rho_4 (a compact range of time-like coordinates means closed time-like directions; a non-compact range needs a normalisation per unit extra-time volume) is an ASSUMPTION about the observer - state it, give the alternatives (per unit proper 7-volume, per unit extra-time coordinate volume) and show how the verdict depends on the choice; use the exact conservation identities nabla_mu T^mu_x4: d rho/d x4 = -3 a4' (p3 - p_t) and nabla_mu T^mu_x8: d p8/d x8 + 3 H cot z (2 p8 - p3 - p_t) = 0 (re-derive them) as checks of every source you use; compute w(a), its CPL tangent at a = 1 and fits over stated ranges of a, compare with w = -0.764 and (w0, wa) = (-0.861, -0.60); say exactly where a time-varying DARK-MATTER equation of state appears (expected: the gas, 1/3 -> 0) and whether any time-varying DARK-ENERGY equation of state near the Unite values appears, with the reasons; checks and an independent second implementation of the key numbers.`
const TASK_dark_sector_dirac16complex00 = `Own ${R}/dark_sector/dirac16complex00/. Investigate Hypothesis00 for the semi-classical dirac16complex00 field: classical solutions in the deflating field (homogeneous condensates, superpositions of good-sector modes, wave packets; the indefinite (Krein-signed) classical energy of modes of both Krein signs; the extra-time-momentum modes whose growth is driven by the deflation), the 3-space observer's equation of state as in the dirac16complex task (rho_4, w_eff, w = p3/rho) with the same stated observer assumptions and conservation checks, whether negative classical energy densities allow w < -1 (phantom) and a crossing of w = -1 near the Unite trajectory, and what that would require (a classical field with negative-energy components is a ghost-like sector: say so); CPL tangent and fits; comparison with w = -0.764 and (w0, wa) = (-0.861, -0.60); exact derivations (sympy) before numerics; checks and an independent second implementation of the key numbers.`
const TASK_a4_with_ks_source = `Own ${R}/field_equations_a4/ks_source/. Specialise the a4 field equations of ${R}/field_equations_a4/a4-equations.json to the Kohn-Sham states of ${R}/kohn_sham (the instantaneous energy-momentum tensor profiles as the source; the hidden-direction dependence the source must have versus the profiles actually computed - quantify the mismatch honestly) (the wave-1 fixer already showed in ${R}/field_equations_a4/reports/ks-source-conditions.json that every nonzero Kohn-Sham state depends on x8 and violates p3 + p_t = 2 p8, i.e. the x8 conservation identity d p8/d x8 + 3 H cot z (2 p8 - p3 - p_t) = 0 - start from that, verify it, and decide what, if anything, can still be integrated: e.g. hidden-direction averages with the violation quantified, stated as an approximation), for Einstein gravity and for Einstein-Lovelock with stated alpha_2, alpha_3, and integrate the a4 evolution equation where it is well defined (state the assumptions); does the dirac16complex source drive exponential deflation of the extra times? Report what the equations allow.`
const TASK_ks_pairing_T3 = `Own ${R}/pairing/kohn_sham/. T3 was already proved exactly by the wave-1 fixer there (Wolfram 10/10, sympy 13/13, t3-theory.json): verify that proof adversarially and complete it where needed, then make sure everything below exists. Prove T3 (the Kohn-Sham level pairing: the block map with the transformed boundary conditions maps the instantaneous Kohn-Sham problem with (m, lambda) to the one with (-m, +lambda) with equal energies and energy-momentum tensors) exactly (sympy/Wolfram) for the Revision Kohn-Sham model, and demonstrate it numerically with the Revision Rust solver and reference (+M and -M universes on the deflating slice series; the untransformed boundary condition as the negative control). The Kohn-Sham history a4 = A H x4 is a PRESCRIBED BACKGROUND (the states violate the a4 source conditions; ${R}/field_equations_a4/reports/ks-source-conditions.json): say so wherever it is used.`
const CHAPTERS = [{"nn": "00", "title": "How to use this book; installing the software; the honesty ledger (draft; the assembly agent finalises it)", "note": "A4 SYNC for this chapter: notebook 00c asserts the Revision/README.md report table against the reports; the a4 counts are now Wolfram 52, sympy 63 (README updated): rebuild 00c and update the chapter-00 totals that quote 00c's sums (around lines 1596 and 3056).", "n": 16}, {"nn": "01", "title": "Mathematics from zero I: numbers, complex numbers, vectors, matrices, indices, determinants, the generalized Kronecker delta", "note": "", "n": 8}, {"nn": "02", "title": "Mathematics from zero II: several variables, ODEs, Euler and RK4, convergence, the shooting method", "note": "", "n": 8}, {"nn": "03", "title": "Spacetime geometry and the author's metric; curvature", "note": "", "n": 9}, {"nn": "05", "title": "C, Gamma, B, S^ab; Pin(4,4) and Spin(4,4); the charge-conjugation MATRICES calC_+ = C and calC_- = Gamma C", "note": "", "n": 5}, {"nn": "06", "title": "Spinors in curved 4+4 space: vielbein, spin connection, gamma^mu Omega_mu = 3 H gamma^(x8)", "note": "", "n": 7}, {"nn": "07", "title": "The two fields and their Lagrangians; Grassmann numbers; Euler-Lagrange equations", "note": "", "n": 4}, {"nn": "08", "title": "Non-triviality, its exact scope, and well-posedness", "note": "", "n": 10}, {"nn": "09", "title": "The energy-momentum tensor, pressures, equations of state, conservation identities", "note": "A4 SYNC for this chapter: the a4 record now builds the condensate witnesses in the author's T16: S = 51200, 28800, 51200 (common factor 51200/1.28 = 28800/0.72 = 40000, was 160000); notebook 09c's prose 'its own (equivalent) Clifford representation' is now false. Rebuild 09c and correct chapter 09 (around line 2786).", "n": 8}, {"nn": "10", "title": "Canonical quantisation in 4+4: Krein space and the good sector", "note": "", "n": 9}, {"nn": "12", "title": "The field equations for a4: Einstein and Einstein-Lovelock", "note": "A4 SYNC for this chapter: the a4 reports now have 52 (Wolfram) and 63 (sympy) checks (chapter 12 around line 757 says 47 and 61); notebooks 12a-12d read the a4 reports: rebuild every one whose stored output changed and correct every quoted count.", "n": 12}, {"nn": "13", "title": "Many-body quantum mechanics and DFT from zero", "note": "", "n": 7}]

const QUOTES = `QUOTED CODE MUST MATCH THE NOTEBOOKS: run python Revision/textbook/tools/audit/walkthrough_diff.py <chapter.md> <notebook.ipynb> <id> for every notebook of your chapter; it lists quoted blocks that no notebook cell contains (NO MATCH), wrong In [k] headings and unquoted cells. Its section detection can be wrong when the chapter MENTIONS a walk-through before the real heading: check each report by hand. Deliberate conventions that are allowed: captions shortened with a line '...)', docstrings omitted, the generated set-up cell In [1] not quoted. Every other mismatch must be fixed in the chapter (re-quote the notebook's current code and explain every new line).`

const results = await parallel([
  () => rev('ks-full-crosscheck', 'Revision science', XCHECK),
  () => rev('dark-sector-dirac16complex', 'Revision science', TASK_dark_sector_dirac16complex),
  () => rev('dark-sector-dirac16complex00', 'Revision science', TASK_dark_sector_dirac16complex00),
  () => rev('a4-with-ks-source', 'Revision science', TASK_a4_with_ks_source),
  () => rev('ks-pairing-T3', 'Revision science', TASK_ks_pairing_T3),
  () => rev('provenance-rev-a4', 'Provenance', `You own ${R}/field_equations_a4/wolfram/WOLFRAMSCRIPT_PROVENANCE.md, the execution-provenance record of the set rev-a4 (its fix was held until the a4 patch was applied; it now is, commit e377368). Read it fully, the independent verifier's findings in ${SP}/phase1/verify_rev-a4.json, and the patched code. Update the file to the PATCHED set: what it computes (the author's T16 as the primary representation; the comparison basis and the exact intertwiner checks; SPEC section 2 now satisfied), file hashes and line counts, every input incl. gammas.json, outputs with sha256, expected output (checks: 52, failed: 0), the ERROR exits, measured run times and memory, side effects (incl. WolframScript's two tmp_* files in %LOCALAPPDATA%\\Wolfram\\WolframScript\\WolframScriptTemporary and what an interrupted run leaves), complete Windows/macOS/Linux instructions; fix every verifier finding. Any embedded comparison script must use FEGammaFrameComparison (FEGammaFrame is now T16 itself). Verify by following the file LITERALLY in a fresh clone under ${SP}/phase1/reva4/: byte identity of the outputs with the committed files.`),
  () => agent(`CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the history or the remote (read-only git and clones into scratch are fine). NEVER accept licence terms or agreements. The AUTHOR's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is read only. Other agents work in parallel elsewhere: touch only the file you own.
${BOUND}
TASK (provenance-nb-kohn-sham): You own notebooks/dirac16complex_kohn_sham.PROVENANCE.md (the execution-provenance record of the old Stage-4 Jupyter notebook). Its independent verifier's 9 findings are in ${SP}/phase1/verify_nb-kohn-sham.json: re-verify each in a fresh clone under ${SP}/phase1/nbks/ and fix the confirmed ones in the provenance file (the notebook and its outputs belong to the old Stage 4, which is paused by the user: do NOT change them; record measured truth, incl. the gauntlet's 2 failing checks). One line per finding: FIXED / REJECTED (reason).`, { label: 'provenance-nb-kohn-sham', phase: 'Provenance', schema: RESULT }),
  ...CHAPTERS.map(c => () => tbk(`fix:${c.nn}`, `You own chapter ${c.nn} (${T}/chapters/${c.nn}-*.md: "${c.title}"), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/${c.nn}*.py, ${T}/notebooks/${c.nn}*, ${T}/figures/${c.nn}*). The chapter's adversarial reviewer found ${c.n} problems; they are in ${SP}/phase1/review_${c.nn}.json (fields severity, file, location, problem, evidence, fix): read ALL of it. Re-verify each finding; fix every confirmed one at the root (rebuild changed notebooks with python ${T}/tools/nbkit.py build <builder> --date 2026-10-08 and check them; keep FACTS (final_lines, files_written) and every count consistent; delete stale figure files); reject unconfirmed ones with evidence. ${c.note} ${QUOTES} Finally test-build the chapter alone with python ${T}/tools/check_chapter.py ${T}/chapters/${c.nn}-*.md until warning-free, and run python ${T}/tools/nbkit.py check on every notebook of the chapter. One line per finding in key_results: FIXED / REJECTED (reason).`)),
  () => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (adversarial reviewer of chapter 11; do not edit files): Review chapter ${T}/chapters/11-*.md and its notebooks 11a-11c against TEXTBOOK_SPEC: re-execute each notebook with nbkit check; re-derive the key derivations and check every formula and number against the Revision records it cites; the deep-dive standard (skipped steps, undefined words, unexplained code lines, figures without teaching captions); the run instructions; R2/R3/R5/R6; exercises and answers. ${QUOTES} Report only real problems with concrete evidence.`, { label: 'review:11', phase: 'Textbook', schema: FINDINGS })
    .then(r => (r && r.findings && r.findings.length)
      ? tbk('fix:11', `You own chapter 11 (${T}/chapters/11-*.md), its notebook builders, notebooks and figures. Reviewer findings (JSON): ${JSON.stringify(r.findings).slice(0, 60000)}\nRe-verify each; fix confirmed ones at the root (rebuild notebooks with nbkit and check them; test-build the chapter warning-free with check_chapter.py); reject unconfirmed ones with evidence. One line per finding: FIXED / REJECTED (reason).`)
      : { files_changed: [], commands_run: [], all_checks_pass: true, failing: [], key_results: ['review:11: no findings'], open_items: [], summary: 'chapter 11 reviewed without findings' }),
])
return { results }
