"""Generate completion_phase_3a.js: resume the agents stopped by the session limit (2026-10-08 ~08:50) and add
the textbook tasks that no other agent owns.  Reuses the exact constants and task texts of phase 2b-1 / 2b-2."""
import re
import sys

REPO = "D:/Developer/github/Dirac_claude/Revision/workflows/completion/"
b1 = open(REPO + "completion_phase_2b1.js", encoding="utf-8").read()
b2 = open(REPO + "completion_phase_2b2.js", encoding="utf-8").read()


def header(src):
    return src[src.index("const ROOT ="):src.index("const results = await parallel([")]


def entries(src):
    body = src.split("const results = await parallel([", 1)[1].rsplit("])\nreturn { results }", 1)[0]
    return [e.rstrip().rstrip(",") for e in re.split(r"\n(?=  \(\) => )", body.strip("\n"))]


def task_text(entry):
    """The template-literal task text of a rev/tbk entry: the last backtick string argument."""
    m = re.search(r"(?:rev|tbk)\('([^']+)'(?:, '[^']+')?, `(.*)`\)\s*$", entry, re.S)
    return m.group(1), m.group(2)


H = header(b2)
E1 = {}
for e in entries(b1) + entries(b2):
    if e.lstrip().startswith("() => rev(") or e.lstrip().startswith("() => tbk("):
        label, text = task_text(e)
        E1[label] = text
    elif "review:19" in e:
        E1["review:19"] = e
    elif "stage4-diagnose" in e:
        E1["stage4-diagnose"] = e
for k in ["doc-updates", "revnb-ks-dark", "gate", "prov-t3", "fix:16", "fix:17", "review:19", "stage4-diagnose"]:
    assert k in E1, k

# the review:19 and stage4 entries are whole agent() calls; take their prompt template literal
rv19 = re.search(r"agent\(`(.*?)`, \{ label: 'review:19'", E1["review:19"], re.S).group(1)
st4 = re.search(r"agent\(`(.*?)`, \{ label: 'stage4-diagnose'", E1["stage4-diagnose"], re.S).group(1)

H = H.replace("const STATE = `STATE (2026-10-08, phase 2b; all of it committed and verified by the lead):",
              "const STATE = `STATE (2026-10-08 10:00, phase 3a; all of it committed and verified by the lead): Revision documents "
              "KOHN_SHAM_DEFLATING_FIELD, DARK_SECTOR_HYPOTHESES and LOVELOCK_GKD are written and registered (commits ecb53b4, ae627be);")
H = H.replace("<your label>.progress.md", "<your log name>.progress.md")

out = ["export const meta = {",
       "  name: 'completion-phase-3a',",
       "  description: 'Completion phase 3a: resume the agents stopped by the session limit (chapters 16, 17, 19 with adversarial fix-verifiers; "
       "old Stage 4 diagnose-fix-verify; Lovelock comparison with the author; wave-1 document updates; T3 provenance; Revision notebooks 2-3; the gate) "
       "and the textbook tasks no agent owns (charge-conservation qualification; chapter 22 dark-sector results)',",
       "  phases: [",
       "    { title: 'Revision', detail: 'document updates, T3 provenance, notebooks 2-3, gate, Lovelock comparison' },",
       "    { title: 'Textbook', detail: 'chapters 16, 17, 19 (fix, verify, re-fix); charge qualification; chapter 22' },",
       "    { title: 'Old Stage 4', detail: 'diagnose, fix at the root, verify' },",
       "  ],",
       "}",
       H.rstrip()]
out.append(r"""
const LOGDIR = `${SP}/phase2b`
const RESUME = (log) => `RESUME NOTE (2026-10-08 10:00): an earlier run of this exact task was STOPPED by a session limit (about 08:50) before it finished. Its progress log is ${LOGDIR}/${log}.progress.md: read it FIRST and keep appending to it. Files it edited may be in the working tree in a half-finished state (see git status / git diff): inspect them, re-verify every earlier edit against its source (never trust it unchecked), keep what is correct, repair what is not, then finish the task. Do not redo verified work needlessly. Its scratch folder ${LOGDIR}/${log}/ may hold useful intermediate files.`
const revR = (label, ph, log, task) => agent(`${REVCOMMON}\n${STATE}\n${BOUND}\n${RESUME(log)}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })
const tbkR = (label, log, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\n${RESUME(log)}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const tbkN = (label, task) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (${label}): ${task}`, { label, phase: 'Textbook', schema: RESULT })
const CH = { '16': '16-checking-the-solution-independently', '17': '17-a4-equations-with-kohn-sham-source', '19': '19-t3-kohn-sham-universes' }
const verifyFix = (nn, findingsSource, fixResult) => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (fix-verifier of chapter ${nn}; adversarial; do NOT edit files): A fixer claims to have fixed the review findings of chapter ${T}/chapters/${CH[nn]}.md. The findings: ${findingsSource}. The fixer's report (JSON): ${JSON.stringify(fixResult || {}).slice(0, 30000)}\nFor EVERY finding, check in the files themselves (not in the report) that the fix is real and correct, and that the fix did not introduce a new error (re-derive formulas, re-read numbers from the Revision records and from the notebooks' printed outputs). Run python ${T}/tools/nbkit.py check on every notebook of the chapter, the walk-through audit (${QUOTES}) and python ${T}/tools/check_chapter.py on the chapter. Report as findings ONLY what is still wrong (unfixed, wrongly fixed, newly broken), with concrete evidence; verified_ok lists the findings confirmed fixed.`, { label: `verify-fix:${nn}`, phase: 'Textbook', schema: FINDINGS })
const refix = (nn, v) => (v && v.findings && v.findings.length)
  ? tbkN(`refix:${nn}`, `You own chapter ${nn} (${T}/chapters/${CH[nn]}.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/${nn}*.py, ${T}/notebooks/${nn}*, ${T}/figures/${nn}*). An adversarial fix-verifier found these remaining problems (JSON): ${JSON.stringify(v.findings).slice(0, 50000)}\n${FIXTAIL}`)
  : { files_changed: [], commands_run: [], all_checks_pass: !!v, failing: v ? [] : [`verify-fix:${nn} returned nothing`], key_results: [v ? `verify-fix:${nn}: every finding confirmed fixed` : `verify-fix:${nn}: no result`], open_items: [], summary: v ? `chapter ${nn}: fixes verified` : 'no verifier result' }
""")

def js(s):
    return "`" + s + "`"

tasks = []
tasks.append("  () => revR('doc-updates', 'Revision', 'doc-updates', " + js(E1["doc-updates"]) + ")")
tasks.append("  () => revR('prov-t3', 'Revision', 'prov-t3', " + js(E1["prov-t3"]) + ")")
tasks.append("  () => revR('revnb-ks-dark', 'Revision', 'revnb-ks-dark', " + js(E1["revnb-ks-dark"] +
             " Do NOT edit provenance/EXECUTION_PROVENANCE_INDEX.md (another agent edits it): put the exact rows for your notebooks "
             "(section 4 of that file, numbered 25 and 26, in the format of row 24) into open_items; the lead adds them.") + ")")
tasks.append("  () => revR('gate', 'Revision', 'gate', " + js(E1["gate"] +
             " Include the new sets: Revision/dark_sector (both parts and the dirac16complex00 unittest), Revision/field_equations_a4/ks_source "
             "(script and its unittest), the T3 completion (verify_t3_completion.wls, check_t3_completion.py, numerics demos: the Rust demo "
             "needs --solver with the built solver and takes about 13 minutes, the reference demo about 5-7 minutes), the Revision notebooks "
             "(Revision/notebooks/tools/build_notebooks.py check <name> for every notebook), the comparison with the author (if "
             "Revision/gkd_lovelock/comparison/ exists when you finish; otherwise list it in open_items) and the six documents in verify mode.") + ")")
tasks.append(r"""  () => revR('lovelock-compare', 'Revision', 'lovelock-compare', `Own ONLY the new folder ${R}/gkd_lovelock/comparison/. NEVER modify the author's notebook ${ROOT}/Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb or any other author notebook (read only; Get/Import of the notebook expression in WolframScript, never NotebookOpen with saving, never NotebookSave). Never quote the author's private PDF. (The progress log of this task is in ${SP}/phase2/lovelock-compare.progress.md, not in phase2b: read and append there.) Carry out and record the comparison that ${R}/gkd_lovelock/results/PROVENANCE_OF_THE_COMPUTATION.md announces but that is recorded nowhere: the Revision's curvature and Lovelock results (${R}/gkd_lovelock/results/curvature.json, lovelock-tensors.json) against the author's OWN stored outputs. The earlier run found: the notebook_reading set reads 'Generalized _Kronecker_Delta_4+4.nb' (only kdelta/GKD outputs there, no metric or Lovelock cells); the main notebook Pair_Creation_...nb has 2127 cells (996 Input, 805 Output); rt[g] at In[214] computes ginv, Christoffel, Ricci, Riemann, RS, EinsteinG; In[238] rt[gtry] (no output); stored outputs Out[235] (gtry = MatrixMetric44), Out[535] (RS), Out[536] (EinsteinG); no Lovelock P2/P3 output was found in either notebook - re-check that. Write ${R}/gkd_lovelock/comparison/extract_author_curvature_outputs.wls (read-only; converts the stored OUTPUT boxes to exact expressions WITHOUT evaluating the notebook's definitions - MakeExpression/ToExpression with HoldComplete - and writes author-curvature-outputs.json: Out labels, cell indices, exact InputForm strings, the notebook sha256, the Wolfram version; deterministic, LF), ${R}/gkd_lovelock/comparison/compare_with_author.py (sympy: state the coordinate and function mapping between the author's gtry/MatrixMetric44 and the Revision metric, check it on the metric itself FIRST; then compare the Ricci scalar and every Einstein-tensor component EXACTLY, with every normalisation stated and applied, never fitted; one check per compared object, PASS / FAIL / NOT-AVAILABLE; report author-comparison-report.json) and README.md (what was read and how, the mapping, the result, commands and run times, side effects incl. WolframScript's two tmp_* files, what the comparison does NOT establish - e.g. no author output exists for the k = 2, 3 Lovelock tensors if that is confirmed). Run each program twice: byte-identical. A disagreement is a finding: report it with the data, never hide it or change conventions after the fact. In open_items give the exact sentences the lead must change in ${R}/docs/LOVELOCK_GKD.md and results/PROVENANCE_OF_THE_COMPUTATION.md, and the index row for the new .wls.`)""")
tasks.append("  () => tbkR('fix:16', 'fix-16', " + js(E1["fix:16"]) + ").then(f => verifyFix('16', `${ROOT}/Revision/workflows/completion/review_16.json plus the 31-check cross-check update`, f)).then(v => refix('16', v))")
tasks.append("  () => tbkR('fix:17', 'fix-17', " + js(E1["fix:17"]) + ").then(f => verifyFix('17', `${ROOT}/Revision/workflows/completion/review_17.json plus the A4 SYNC and the ks_source teaching`, f)).then(v => refix('17', v))")
tasks.append(r"""  () => agent(`""" + rv19.replace("TASK (adversarial reviewer of chapter 19", "${RESUME('review19')}\\nTASK (adversarial reviewer of chapter 19") + r"""`, { label: 'review:19', phase: 'Textbook', schema: FINDINGS })
    .then(r => (r && r.findings && r.findings.length)
      ? tbkN('fix:19', `You own chapter 19 (${T}/chapters/19-t3-kohn-sham-universes.md), its notebook builders, notebooks, PROVENANCE files and figures (${T}/notebooks/src/19*.py, ${T}/notebooks/19*, ${T}/figures/19*). Reviewer findings (JSON): ${JSON.stringify(r.findings).slice(0, 60000)}\n${FIXTAIL}`)
          .then(f => verifyFix('19', `the review findings (JSON): ${JSON.stringify(r.findings).slice(0, 30000)}`, f)).then(v => refix('19', v))
      : { files_changed: [], commands_run: [], all_checks_pass: !!r, failing: r ? [] : ['review:19 returned nothing'], key_results: [r ? 'review:19: no findings' : 'review:19: no result'], open_items: [], summary: r ? 'chapter 19 reviewed without findings' : 'review 19 failed' })""")
tasks.append(r"""  () => agent(`""" + st4.replace("TASK (stage4-diagnose;", "${RESUME('stage4-diagnose')}\\nTASK (stage4-diagnose;") + r"""`, { label: 'stage4-diagnose', phase: 'Old Stage 4', schema: RESULT })
    .then(d => d ? agent(`${NOAGREE}\nCONTEXT: repository ${ROOT} (git, branch main; Windows 11; Python 3.14; Rust cargo 1.91; WolframScript). NEVER run git commands that change the index, the working tree's history or the remote (read-only git is fine). Scratch only under ${SP}/phase3a/stage4-fix/. Read files in chunks of at most 300 lines. NEVER weaken a check or a tolerance; fix causes. NEVER modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/ (preserved by the user's order of 2026-10-02) and never the author's notebooks.\n${BOUND}\nTASK (stage4-fix): Complete the OLD Stage 4 (first edition, dirac16complex Kohn-Sham) by fixing the causes found by the diagnosis below, at the root, and regenerating every stale output in dependency order: the reference code (scripts/ks_reference_*.py) and its outputs (artifacts/dirac16complex/kohn-sham/reference/, reference-summary.json; artifacts/dirac16complex/pair-creation/reference/reference-pairs-summary.json, which records stale sha256 of scripts/ks_reference_solver.py and ks_reference_pairs.py), the Python check report artifacts/dirac16complex/kohn-sham/python-check-report.json, the notebook notebooks/dirac16complex_kohn_sham.ipynb with its runner, notebook-report.json and figures, the tests (tests/test_d16c_kohn_sham_*.py must pass, without weakening), the Stage-4 documents that quote changed numbers (find them with git grep; rebuild their PDFs and re-register them in provenance/pdf-specifications.json, changing only their entries), and the execution-provenance record notebooks/dirac16complex_kohn_sham.PROVENANCE.md (update it to the new state; it must name the current sha256 of the notebook). Long runs go to the background; if the whole regeneration cannot finish within the bound, stop at a CONSISTENT state (never leave half-regenerated outputs in the repository: generate into scratch and copy in only complete, verified sets) and list exactly what remains with the commands. The diagnosis (JSON): ${JSON.stringify(d).slice(0, 40000)}`, { label: 'stage4-fix', phase: 'Old Stage 4', schema: RESULT }) : null)
    .then(f => f ? agent(`${NOAGREE}\nCONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; do NOT edit files. Scratch only under ${SP}/phase3a/stage4-verify/.\n${BOUND}\nTASK (stage4-verify; adversarial): The old Stage-4 fixer reports (JSON): ${JSON.stringify(f).slice(0, 40000)}\nVerify every claim in the files and by running the commands yourself (in a fresh clone of the working tree's state under scratch where a run would write into the repository): the code change fixes the diagnosed cause and weakens no check or tolerance; the regenerated outputs are reproduced byte for byte by a re-run; notebook-report.json verdict and the gauntlet; python -m unittest discover -s tests -p "test_d16c_kohn_sham*.py"; the rebuilt PDFs in verify mode; the provenance record names the current sha256. Report as findings only what is wrong or unverified, with evidence.`, { label: 'stage4-verify', phase: 'Old Stage 4', schema: FINDINGS }) : null)""")
tasks.append(r"""  () => tbkN('tb-charge', `You own the chapters ${T}/chapters/00-how-to-use-this-book.md, 20-do-universes-come-in-pairs.md, 21-matter-and-antimatter.md and ${T}/chapters/abstract.md, and the builders/notebooks/PROVENANCE/figures of chapters 20 and 21 (${T}/notebooks/src/2[01]*.py, ${T}/notebooks/2[01]*, ${T}/figures/2[01]*) - NOT chapter 22 and NOT the notebooks of chapter 00. PHYSICS CORRECTION (found by the fixers of chapters 10 and 18, verified there): only the LOCAL U(1) law d_mu(cos z J^mu) = 0 is proved (lead check u1_noether_matrix_identity); the total charge of a slice is constant only if no charge flows through the brane z = pi/2 (the flow is sin z q8 with q8 = -i Psibar gamma^(x8) Psi; on the homogeneous solutions of chapter 18, Notebook 18c, q8 runs from -0.3454 to 0.3454, so the patch charge changes at the rate -V6 q8); the no-flux condition is ASSUMED or OPEN, never proved. Read chapter 18 section 18.21 and chapter 10 section 10.2 (both already corrected) first. Then correct EVERY unqualified claim of exact total-charge conservation in your files (at least chapter 00 line ~74; chapter 20 lines ~2833 and ~2842 (2787 already qualifies it); chapter 21 lines ~12, 3765, 4348, 4664, 4706, 4853 and its notebook builders such as 21b; abstract.md line ~5) - search them all (grep for 'conserved', 'conservation', 'no net charge'), qualify each precisely, keep the R3 honesty labels. Also: chapter 20 line ~2868 says Sakharov condition 2 'is not addressed', weaker than chapter 21's PROVED failure of condition 2 for the commuting field (C_+ exact, Proposition 2): align it. Rebuild every notebook whose builder you change (python ${T}/tools/nbkit.py build <builder> --date 2026-10-08) and check it; run the walk-through audit for changed notebooks (${QUOTES}); test-build each changed chapter with python ${T}/tools/check_chapter.py until chapter_check=OK with no problem= or latex_warning= lines. List every changed sentence (file, line, old -> new) in key_results. Also put into open_items the exact new wording for rule R3 of ${T}/TEXTBOOK_SPEC.md (the lead edits the spec).`)
    .then(f => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (verify-tb-charge; adversarial; do NOT edit files): A fixer qualified the claims of total U(1) charge conservation in chapters 00, 20, 21 and abstract.md (only the local law is proved; constancy needs no flux through the brane z = pi/2). Its report: ${JSON.stringify(f || {}).slice(0, 30000)}\nSearch the WHOLE book (${T}/chapters/*.md, ${T}/notebooks/src/*.py) for any remaining unqualified claim of exact total-charge conservation or 'no net charge can be generated' (report each with file and line; chapter 22 is handled by another agent - report its lines too, as one finding), check that every changed sentence is correct physics and consistent with chapters 10.2 and 18.21, re-run nbkit check for the changed notebooks and check_chapter for the changed chapters. Findings only for real problems, with evidence.`, { label: 'verify-tb-charge', phase: 'Textbook', schema: FINDINGS }))""")
tasks.append(r"""  () => tbkN('tb-22-dark', `You own chapter 22 (${T}/chapters/22-open-problems.md) and its notebook builders/notebooks/PROVENANCE/figures (${T}/notebooks/src/22*.py, ${T}/notebooks/22*, ${T}/figures/22*). (1) The dark-sector hypotheses are no longer 'being investigated, no results claimed': the Revision record now has results (${R}/dark_sector/dirac16complex and dirac16complex00: READMEs, outputs, reports; ${R}/docs/DARK_SECTOR_HYPOTHESES.md, registered). Rewrite the chapter's dark-sector part to teach them for a student who knows school algebra: the observer assumption for rho_4 (definitions A, B, C) and how every verdict depends on it, w_eff = X/E (A, B) and X/E - 1 (C) derived line by line, the Kohn-Sham gas (radiation-like, the brane band), the condensate, mixtures, dirac16complex00's modes and populations, the Unite comparison with EVERY tuned parameter labelled CHOSEN / by construction / NOT a prediction and ghost components labelled ghost-like, and what remains open - every number read from the records. Add a new notebook 22b (builder ${T}/notebooks/src/22b_<short>.py, built with python ${T}/tools/nbkit.py build ... --date 2026-10-08) that reproduces the key dark-sector numbers from the committed Revision outputs (asserting each against its record file and check) and draws at least four teaching figures (w_eff histories under A/B/C for the gas, the condensate, a mixture, the dirac16complex00 populations against the Unite CPL line); its run-instruction paragraph, walk-through (every code line explained) and figure captions in the chapter; update the chapter's proved/computed/assumed section and exercises (with worked answers). (2) Chapter 22 line ~1919 says the U(1) charge is exactly conserved: qualify it (only the local law d_mu(cos z J^mu) = 0 is proved; constancy of the total charge needs no flux through the brane z = pi/2, ASSUMED/OPEN; see chapters 10.2 and 18.21). Then nbkit check every notebook of the chapter, the walk-through audit (${QUOTES}), and check_chapter until chapter_check=OK with no problem= or latex_warning= lines.`)
    .then(f => agent(`${TBCOMMON}\n${STATE}\n${BOUND}\nTASK (verify-tb-22; adversarial; do NOT edit files): Chapter 22 (${T}/chapters/22-open-problems.md) was rewritten to teach the Revision dark-sector results and got a new notebook 22b. Fixer report: ${JSON.stringify(f || {}).slice(0, 30000)}\nCheck every formula (re-derive w_eff for A, B, C), every number against ${R}/dark_sector/** and ${R}/docs/DARK_SECTOR_HYPOTHESES.md, the honesty labels (tuned parameters, ghosts, observer assumption, nothing established), the notebook (nbkit check), the walk-through audit, the run instructions, the figures and captions, the exercises, check_chapter. Findings only for real problems, with evidence.`, { label: 'verify-tb-22', phase: 'Textbook', schema: FINDINGS }))
    .then(v => (v && v.findings && v.findings.length) ? tbkN('refix:22', `You own chapter 22 (${T}/chapters/22-open-problems.md) and its notebooks (${T}/notebooks/src/22*.py, ${T}/notebooks/22*, ${T}/figures/22*). An adversarial verifier found (JSON): ${JSON.stringify(v.findings).slice(0, 50000)}\n${FIXTAIL}`) : v)""")

out.append("const results = await parallel([\n" + ",\n".join(tasks) + ",\n])\nreturn { results }\n")
open(sys.argv[1], "w", encoding="utf-8", newline="\n").write("\n".join(out))
print("written", sys.argv[1], len(tasks), "tasks")
