"""Unit tests for the independent Stage-5 checker of dirac16complex00 (scripts/check_dirac16complex00.py).

Run from the repository root:
    python -m unittest discover -s tests -p "test_d16c_stage5_dirac16complex00.py" -v

The fast subset (every test whose name does not contain SLOW) runs in well under a minute: it calls
the check functions directly on flat space, the integer frame G4, the Stage-4 block basis and the
exact algebra, includes negative controls (a corrupted fixture, a wrong field-equation target, a wrong
mass sign, a wrong closed form and a wrong formula string are all detected), reproduces exported
Wolfram numbers from the documented random data, and verifies that the committed report is complete,
all true and generated by the current sources.  The SLOW test runs the command-line entry point in
--quick mode (about five minutes) and is skipped when the environment variable D16C_FAST=1 is set.
"""

import json
import os
import random
import sys
import tempfile
import unittest
from fractions import Fraction

import sympy as sp
from sympy import QQ

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "scripts"))
import check_dirac16complex00 as T  # noqa: E402

_ALG = None
_GEOS = None
_THEORY = None


def algebra():
    global _ALG
    if _ALG is None:
        _ALG = T.Algebra()
    return _ALG


def geos():
    global _GEOS
    if _GEOS is None:
        _GEOS = T.Geometries()
    return _GEOS


def theory():
    global _THEORY
    if _THEORY is None and os.path.exists(T.DEFAULT_THEORY):
        with open(T.DEFAULT_THEORY, "r", encoding="utf-8") as handle:
            _THEORY = json.load(handle)
    return _THEORY


class ExactToolTests(unittest.TestCase):

    def test_poly_arithmetic_and_derivations(self):
        x, y = T.Poly.var(0), T.Poly.var(1)
        p = x * x * y + x * 3 - 2
        self.assertEqual(p.nterms(), 3)
        d = p.partials()
        self.assertTrue((d[0] - (x * y * 2 + 3)).is_zero())
        self.assertTrue((d[1] - x * x).is_zero())
        # derivation with a chain rule: d/dx of U(S) with S = x y is U'(S) * y
        U0, U1 = T.Poly.var(5), T.Poly.var(6)
        S = x * y
        img = {0: T.Poly.const(1), 5: U1 * S.partials()[0]}
        q = (U0 * x).derivation(lambda v: img.get(v))
        self.assertTrue((q - (U0 + U1 * y * x)).is_zero())
        self.assertTrue((T.poly_rename(p, {0: 1, 1: 0}) - (y * y * x + y * 3 - 2)).is_zero())
        self.assertEqual(p.evaluate({0: Fraction(2), 1: Fraction(1, 2)}), Fraction(6))

    def test_dual_numbers_exact_linearisation(self):
        x = T.Dual(Fraction(3), 1)
        f = x * x / (x + 1)
        self.assertEqual(f.a, Fraction(9, 4))
        self.assertEqual(f.b, Fraction(15, 16))          # d/dx x^2/(1+x) = (x^2 + 2x)/(1+x)^2 at 3
        inv = T._mat_inverse_generic([[T.Dual(Fraction(2), 1), Fraction(1)], [Fraction(0), Fraction(1)]])
        self.assertEqual(inv[0][0].a, Fraction(1, 2))
        self.assertEqual(inv[0][0].b, Fraction(-1, 4))

    def test_lcg_reproduces_exported_scalar_densities(self):
        alg = algebra()

        def S_of(seed):
            data = T.lcg_field_data(seed)
            return sum((data[3][a] * alg.C[a][b] * data[0][b] for a in range(16) for b in range(16)), Fraction(0))
        self.assertEqual(S_of(61100), Fraction(-4303, 672))        # vielbein variation G1 p1 (theory export)
        self.assertEqual(S_of(63100), Fraction(5617, 567))         # homogeneous G3 t1 (theory export)
        S0 = S_of(62110)
        self.assertEqual(-Fraction(3, 7) * S0 + 3 * Fraction(5, 11) * S0 * S0, Fraction(923549, 26880))


class AlgebraTests(unittest.TestCase):

    def test_algebra_family(self):
        rec = T.Recorder()
        T.check_algebra(algebra(), rec)
        self.assertTrue(all(rec.checks.values()), rec.checks)
        facts = rec.measurements["algebra_leadFacts"]
        self.assertEqual(facts["BSignature"], [8, 8, 0])
        self.assertTrue(facts["gamma8Bgamma8EqualsMinusB"] and facts["Cgamma4EqualsIB"])

    def test_corrupted_fixture_is_detected(self):
        with open(T.DEFAULT_FIXTURE, "r", encoding="utf-8") as handle:
            fx = json.load(handle)
        fx["gamma"][2][0] = [-v for v in fx["gamma"][2][0]]
        with tempfile.TemporaryDirectory() as directory:
            path = os.path.join(directory, "fixture.json")
            with open(path, "w", encoding="utf-8") as handle:
                json.dump(fx, handle)
            self.assertFalse(T.Algebra(path).fixture_agreement()["gamma"])


class LagrangianTests(unittest.TestCase):

    def test_flat_symbolic_euler_lagrange_and_negative_control(self):
        flat = geos().flat()
        ok, d, sl = T.el_symbolic_point(flat, "quartic")
        self.assertTrue(ok, d)
        E = sl.euler_lagrange("chi")
        t_chi, _ = sl.targets()
        wrong = t_chi + T.np.einsum("ij,j->i", flat.gd.C, sl.psi) * sl.V.v("m") * 2    # m -> -m in the target
        self.assertFalse(T.polys_equal(E, wrong, flat.dom))
        ok_u, du, _ = T.el_symbolic_point(flat, "general")
        self.assertTrue(ok_u, du)

    def test_reality_real_restriction_and_relation_flat(self):
        flat = geos().flat()
        ok, d = T.reality_point(flat, random.Random(3))
        self.assertTrue(ok, d)
        ok, d = T.real_restriction_point(flat, False)
        self.assertTrue(ok, d)
        ok, d = T.relation_to_L1(flat)
        self.assertTrue(ok, d)

    def test_grassmann_statements(self):
        gd = geos().gd_qq
        ok, d = T.grassmann_flat_checks(gd, QQ(3, 7), QQ(5, 11))
        self.assertTrue(ok, d)
        ok, d = T.grassmann_mass_term(gd, 17)
        self.assertTrue(ok, d)
        self.assertEqual(d["powerMonomialCounts"][:3], [16, 120, 560])
        self.assertTrue(d["S17Zero"] and d["S16Nonzero"])
        ok, d = T.grassmann_real_flat(gd)
        self.assertTrue(ok, d)
        ok, d = T.grassmann_complex_decomposition(gd)
        self.assertTrue(ok, d)

    def test_commuting_mass_term_and_dispersion(self):
        ok, d = T.commuting_mass_term(algebra())
        self.assertTrue(ok, d)
        self.assertEqual([d[k]["S"] for k in ("e0+e4", "e8+e12", "e0+ie4")], ["-2", "2", "0"])
        ok, d = T.flat_dispersion(algebra())
        self.assertTrue(ok, d)
        self.assertEqual((d["dimensionOnShell_m1_k11234"], d["dimensionOffShell_k4_3"]), (8, 0))


class SpecificsTests(unittest.TestCase):

    def test_charge_indefinite(self):
        ok, d = T.check_charge_indefinite(algebra())
        self.assertTrue(ok, {k: v for k, v in d.items() if k != "statement"})

    def test_energy_unbounded_below(self):
        ok, d = T.check_energy_unbounded(algebra())
        self.assertTrue(ok)
        rhos = [e["rho"] for e in d["selfConsistentPlaneWavesPositiveLambda"]]
        self.assertEqual(rhos[0], "-56/75")
        self.assertEqual(d["limitMto0"], "-oo")
        self.assertEqual([e["rho"] for e in d["homogeneousNegativeLambda"]], ["1/2", "-40", "-4900"])

    def test_wrong_plane_wave_is_rejected(self):
        alg = algebra()
        u = [(Fraction(1), Fraction(0))] + [(Fraction(0), Fraction(0))] * 15
        kcov = [Fraction(v) for v in (1, 1, 2, 3, -4, 0, 0, 0)]
        self.assertFalse(all(a == 0 and b == 0 for a, b in T.dirac_residual(alg, u, kcov, Fraction(1))))


class GeometryAndVariationTests(unittest.TestCase):

    def test_g4_frame_matches_export_and_variation_closed_form(self):
        th = theory()
        E0 = T.g4_frame_data(1)[0]
        if th is not None:
            self.assertEqual([[int(v) for v in row] for row in E0], th["testGeometries"]["G4"]["E0"])
        rec = T.Recorder()
        d = T.check_g4_generic(geos(), rec)
        self.assertTrue(rec.checks["S5_geometry_G4Generic"], d)
        self.assertEqual((d["gUpper44"], d["scalarCurvature"]), ("-49", "82754"))
        geo = geos().g4(1)
        dom = geo.dom
        m, lam = dom.frac(3, 7), dom.frac(5, 11)
        off = T.lcg_field_data(61200)
        on = T.lcg_field_data(61250)
        psi = T.jet_from_derivatives(off[0], off[1], off[2], dom)
        chi = T.jet_from_derivatives(off[3], off[4], off[5], dom)
        psi_on, chi_on = T.G.solve_onshell(geo, T.jet_from_derivatives(on[0], on[1], on[2], dom),
                                           T.jet_from_derivatives(on[3], on[4], on[5], dom), m, lam, max_order=1)
        dd, _ = T.vielbein_variation_point(geo, psi, chi, m, lam, psi_on, chi_on, all_directions=False)
        self.assertTrue(all(v for v in dd.values() if isinstance(v, bool)), dd)
        # negative control: a wrong closed form (dropping the K term of dL/de) breaks the linearisation check
        lean = T.LeanLagrangian(geo, psi, chi, m, lam)
        good = lean.closed_form_dLde()
        e_d = [[T.Dual(lean.e0[i][j], 1 if (i, j) == (0, 1) else 0) for j in range(8)] for i in range(8)]
        self.assertTrue(dom.is_zero(lean.value(e=e_d)[0].b - good[0][1]))
        self.assertFalse(dom.is_zero(lean.value(e=e_d)[0].b - good[0][1] * 2))


class StaticChartTests(unittest.TestCase):

    def test_block_basis_equals_stage4_export(self):
        V, labels, seeds = T.block_basis(algebra())
        forms = T.block_forms(algebra(), V, labels)
        self.assertTrue(all(all(f["matches"].values()) and f["BtimesBlockIsKreinSign"] for f in forms))
        self.assertEqual(sorted(j * s2 for j, s2, s3 in labels), [-1] * 4 + [1] * 4)
        if os.path.exists(T.KS_THEORY):
            with open(T.KS_THEORY, "r", encoding="utf-8") as handle:
                ks = json.load(handle)
            self.assertEqual(T.parse_gq_matrix(ks["reduction"]["blockDiagonalisation"]["basisMatrixUnnormalised"]), V)

    def test_static_geometry(self):
        sw = T.StaticWarped(algebra())
        self.assertEqual(sw.R, -42 * sw.H ** 2)
        self.assertEqual([sp.simplify(sw.Gmixed[i, i] / sw.H ** 2) for i in range(8)], [15, 15, 15, 15, 21, 15, 15, 15])


class AgreementHelperTests(unittest.TestCase):

    def test_formula_parsers(self):
        m, S, lam, U0, U1 = sp.symbols("m S lam U0 U1")
        syms = {"m": m, "S": S, "lam": lam, "U0": U0, "U1": U1}
        e = T.parse_plain_formula(" -m S + 7 S U'(S) - 8 U(S) ", syms)
        self.assertEqual(sp.expand(e - (-m * S + 7 * S * U1 - 8 * U0)), 0)
        e = T.parse_plain_formula("(1/2)(m S + 2U - S U')", syms)
        self.assertEqual(sp.expand(e - (m * S + 2 * U0 - S * U1) / 2), 0)
        e = T.parse_plain_formula("(1/2)(m S + 2U + S U')", syms)            # a wrong formula is not equal
        self.assertNotEqual(sp.expand(e - (m * S + 2 * U0 - S * U1) / 2), 0)
        y = sp.Symbol("y", real=True)
        r = T.parse_mathematica_trig("(8*(25 - 9*Cos[8*y] + 12*Sin[8*y]))/5", y)
        self.assertEqual(sp.expand(r - sp.Rational(8, 5) * (25 - 9 * sp.cos(8 * y) + 12 * sp.sin(8 * y))), 0)

    def test_report_serialisation_is_deterministic(self):
        doc = {"schemaVersion": 1, "checks": {"S5_a": True}, "measurements": {"x": T.jsonable({"f": Fraction(1, 3), "_hidden": 1})}}
        self.assertEqual(T.canonical_json_bytes(doc), T.canonical_json_bytes(json.loads(T.canonical_json_bytes(doc))))
        self.assertEqual(doc["measurements"]["x"], {"f": "1/3"})
        lines, failed = T.report_lines({"checks": {"S5_a": True, "S5_b": False}, "measurements": {"m": 1}})
        self.assertEqual(failed, 1)
        self.assertIn("check_S5_b=false", lines)
        self.assertEqual(lines[-2:], ["check_count=2", "failed_check_count=1"])


class CommittedReportTests(unittest.TestCase):

    def test_committed_report_is_complete_true_and_current(self):
        path = T.DEFAULT_OUTPUT
        self.assertTrue(os.path.exists(path), "run scripts/check_dirac16complex00.py to create the report")
        with open(path, "r", encoding="utf-8") as handle:
            rep = json.load(handle)
        self.assertEqual(rep["schemaVersion"], 1)
        self.assertEqual(rep["producer"], T.PRODUCER)
        self.assertTrue(all(rep["checks"].values()), [k for k, v in rep["checks"].items() if not v])
        self.assertGreaterEqual(len(rep["checks"]), 49)
        self.assertIn(T.WOLFRAM_CHECK, rep["checks"])
        self.assertFalse(rep["measurements"]["quick"])
        self.assertEqual(rep["measurements"]["families"], list(T.FAMILIES))
        for rel, digest in rep["sourceSha256"].items():
            self.assertEqual(T.sha256_file(os.path.join(REPO, rel)), digest, rel)
        for rel, digest in rep["inputSha256"].items():
            self.assertEqual(T.sha256_file(os.path.join(REPO, rel)), digest, rel)
        with open(path, "rb") as handle:
            raw = handle.read()
        self.assertNotIn(b"\r\n", raw)
        self.assertEqual(raw, T.canonical_json_bytes(rep))


@unittest.skipIf(os.environ.get("D16C_FAST") == "1", "slow end-to-end test skipped (D16C_FAST=1)")
class EndToEndTests(unittest.TestCase):

    def test_SLOW_command_line_quick_mode(self):
        with tempfile.TemporaryDirectory() as directory:
            out = os.path.join(directory, "report.json")
            code = T.main(["--quick", "--output", out])
            self.assertEqual(code, 0)
            with open(out, "r", encoding="utf-8") as handle:
                rep = json.load(handle)
            self.assertTrue(all(rep["checks"].values()))
            self.assertTrue(rep["checks"][T.WOLFRAM_CHECK])


if __name__ == "__main__":
    unittest.main()
