export const meta = {
  name: 'a4-apply-sync',
  description: 'Apply the verified a4 author-T16 patch to the repository and bring every downstream record in line: the three Revision publications (+PDFs, test pins), the held rev-a4 provenance file, the dirac-matrices provenance file; fresh-clone verification',
  phases: [
    { title: 'Apply', detail: 'git apply, both engines twice, byte identity of a4-equations.json' },
    { title: 'Sync', detail: 'Revision publications; rev-a4 provenance; dirac matrices.md' },
    { title: 'Verify', detail: 'independent fresh-clone verifier' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/restart'
const A4 = 'Revision/field_equations_a4'
const PATCH = `${ROOT}/Revision/workflows/a4_patch/a4_author_gammas.patch`
const COMMON = `
NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate or accept an EULA); if a step needs that, stop that step and report it as an open item.
CONTEXT: repository ${ROOT} (git, branch main; remote https://github.com/once-ere/Dirac_claude.git). NEVER run git commands that change the index, the history or the remote (git apply to the working tree is allowed ONLY for the apply agent; read-only git and git clone into scratch under ${SP}/a4sync are fine). The author's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is READ ONLY. Other workflows run concurrently and own Revision/textbook/ (never edit it), the execution-provenance files of the OTHER sets, Revision/theory and Revision/kohn_sham (read only for you).
WHY (user's order and Revision/SPEC.md section 2): every calculation must use the AUTHOR's eight real 16x16 Dirac matrices T16 (Revision/algebra/gammas.json). The a4 engine was the one calculation using an equivalent Cl(1,1)^(x)4 basis; the verified patch ${PATCH} (sha256 starts 7af48ee9) switches both a4 engines to the author's T16 (comparison bases kept, labelled, with exact intertwiner checks). Facts measured by the patch's implementer: a4-equations.json stays BYTE-IDENTICAL; Wolfram report 47 -> 52 checks, Python 61 -> 63, all pass; the condensate witness S values become 51200, 28800, 51200 in the author's T16 (204800, 115200, 204800 were the Cl(1,1)^(x)4 normalisation: |v|^2 = 200 vs 400; w = {4,3,4} and S != 0 unchanged). HANDOFF.md section 0.4k lists every downstream place. Record measured truth; never weaken a check; deterministic outputs (LF).
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const run = (label, ph, task) => agent(`${COMMON}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })

phase('Apply')
const apply = await run('apply', 'Apply', `You own ${A4}/. First: git -C ${ROOT} apply --check "${PATCH}" (it must apply cleanly to the working tree; if ${A4} changed since the patch was made, stop and report). Then apply it, run the Wolfram verifier (as its header says) TWICE and the Python checker TWICE in ${ROOT}; confirm a4-equations.json is byte-identical to HEAD's blob (git show HEAD:${A4}/a4-equations.json | cmp) and between runs, the reports identical between runs, 52/52 and 63/63; run python -m unittest discover -s Revision/tests -k a4 and the a4-related tests; confirm the ERROR exits on a COPY (never break the real fixture). Also: add to ${A4}/README.md (and, if it can be done without changing any check verdict, to the detail text of condensate_diagonal_witness_exact) one sentence: the value of S scales with the arbitrary normalisation of the exact NullSpace vectors v1, v2 and therefore depends on the representation (51200, 28800, 51200 in the author's T16; 204800, 115200, 204800 in the comparison basis), while S != 0, its reality and the vanishing of the 15 bilinears do not; then re-run both engines twice again. If the prep workflow's fixer produced a newer patch at C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/restart/a4prep/a4_author_gammas.patch than ${PATCH}, compare them and use the newer verified one. Report the exact list of changed files.`)

phase('Sync')
const sync = await parallel([
  () => run('docs', 'Sync', `You own Revision/docs/DIRAC16COMPLEX00_FIELD_THEORY.{md,tex,pdf}, Revision/docs/DIRAC16COMPLEX_FIELD_THEORY.{md,tex,pdf}, Revision/docs/PAIR_CREATION_PROOFS.{md,tex,pdf}, their entries in Revision/pdf-specifications.json (re-read it right before changing it; change only these three entries) and the three tests Revision/tests/test_dirac16complex00_field_theory_publication.py, test_dirac16complex_field_theory_publication.py, test_pair_creation_proofs_publication.py. The apply agent reported: ${JSON.stringify(apply && { key: apply.key_results, failing: apply.failing, files: apply.files_changed }).slice(0, 6000)}. Update every number these documents and tests quote from the a4 reports to the measured new values (check counts 52/63; the witness S values 51200, 28800, 51200 with one sentence explaining that S is computed in the author's T16 and depends on the normalisation of the null vectors while w and S != 0 do not; the comparison basis gives the old values), and in PAIR_CREATION_PROOFS also the Kohn-Sham theory row (58 of 58: ks-theory-python.json) and section 10's run order (check_ks_source_conditions.py before check_ks_theory.py). ALSO: Revision/README.md line ~113 (the report-count table: Wolfram 52/52, sympy 63/63 for the a4 reports; textbook notebook 00c asserts this table against the reports); in DIRAC16COMPLEX00_FIELD_THEORY.md the table rows (about lines 786, 854, 860-861) that cite gamma_mu_anticommutes_with_Omega_mu_no_sum 'in a second representation', C_properties_own_rep and ownrep_* as the evidence: cite the author-T16 checks (clifford_relations_author_T16, C_properties_author_T16, authorT16_*) as the primary evidence and keep the own_rep checks as comparison only. Read each document's build instructions (headers of the tests) and rebuild + re-register each PDF exactly as they say, re-pin MARKDOWN_SHA256/TEX_SHA256, and run the three tests (with REVISION_PDF_REBUILD=1 where they support it). Every quoted number must come from a report file.`),
  () => run('rev-a4-provenance', 'Sync', `You own ${A4}/wolfram/WOLFRAMSCRIPT_PROVENANCE.md (the execution-provenance record of the set rev-a4; its fix stage was held for this patch). Read it fully, the independent verifier's findings for it under key verify:rev-a4 in ${ROOT}/Revision/workflows/state_restart/state_execution_provenance.json, and the apply agent's report: ${JSON.stringify(apply && { key: apply.key_results, files: apply.files_changed }).slice(0, 5000)}. Update the file to the PATCHED code: what the set computes (now with the author's T16; the comparison basis and the intertwiner checks; SPEC section 2 now satisfied), file hashes and line counts, every input incl. gammas.json, the outputs and their sha256, the expected output (52 checks), the new ERROR exits, measured run times and memory, side effects (incl. WolframScript's tmp_* files in %LOCALAPPDATA%\\Wolfram\\WolframScript\\WolframScriptTemporary and what an interrupted run leaves), complete Windows/macOS/Linux instructions; and fix every verifier finding. Points from the patch reviewers: FEGammaFrame/FEC are now the fixture's T16/sigma16; the Cl(1,1)^(x)4 basis is FEGammaFrameComparison/FECComparison; any embedded supplementary comparison script must use FEGammaFrameComparison (otherwise it compares T16 with itself); the spinor check list has 18 entries; the 52 checks; open items (b) and (c) about missing-package/unwritable-output exits are resolved by the patch. Verify by following the file LITERALLY in TWO fresh clones under ${SP}/a4sync/ (copy the uncommitted patched files in): byte identity of the outputs with the working tree.`),
  () => run('dirac-matrices', 'Sync', `You own provenance/dirac_matrices/ and provenance/dirac matrices.md (generated) and tests/test_dirac_matrices_provenance.py. After the a4 patch (apply agent: ${JSON.stringify(apply && apply.summary || '').slice(0, 1500)}), follow the file's own instructions: re-run BOTH .wls extractors (extract_from_author_notebook.wls and extract_repository_wolfram_gammas.wls) and then the builder; expected: every check passes (67 of 67 was measured in a scratch clone) and the answer becomes 'Instruction followed: yes' because every calculation now uses the author's T16. Run --check and the unittest; build twice for byte identity. Never weaken a check; record measured truth if anything differs.`),
])

phase('Verify')
const verify = await agent(`${COMMON}\nTASK (independent verifier; do NOT edit repository files): Copy the CURRENT working-tree versions of everything the agents changed (${JSON.stringify([apply, ...sync].filter(Boolean).flatMap(r => r.files_changed || [])).slice(0, 4000)}) into a NEW fresh clone under ${SP}/a4sync/verify and check: the a4 engines use the author's T16 (load and compare with provenance/dirac_matrices/author_notebook_T16.json under the map x1..x3 -> T16A[1..3], x4 -> T16A[4], x5..x7 -> T16A[5..7], x8 -> T16A[0]); both engines pass twice with a4-equations.json byte-identical to HEAD's; the three Revision publications quote only numbers present in the reports and their tests pass; the PDFs rebuild byte-identically and match the registry; the rev-a4 provenance file is correct when followed literally; 'provenance/dirac matrices.md' regenerates byte-identically and answers 'Instruction followed: yes' with every check passing; python -m unittest discover -s Revision/tests (except the textbook test, which another workflow owns) and tests/test_dirac_matrices_provenance.py pass. Report every problem as a finding with evidence.`, { label: 'verify', phase: 'Verify', schema: FINDINGS })
return { apply, sync, verify }
