export const meta = {
  name: 'deflation-spec-review',
  description: 'Adversarial review of handoff/specs/DEFLATION_SPEC.md from three angles (physics, faithfulness to the notebook and the user correction, feasibility against the code) before implementation',
  phases: [{ title: 'Review', detail: 'three independent reviewers' }],
}
const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const COMMON = `CONTEXT: repository ${ROOT} (read-only for you: do NOT edit any file, do NOT run git commands that change anything). The user corrected the project: "x5, x6, x7 are the three extra times that exponentially deflate. Fix this everywhere ... Redo the physics." The lead wrote ${ROOT}/handoff/specs/DEFLATION_SPEC.md (read it fully). Background: HANDOFF.md, handoff/specs/CONTRACT.md, STAGE2_SPEC.md, STAGE4_SPEC.md (sections 8-9), NUMERICS_CONTRACT.md, STAGE5_SPEC.md, handoff/surveys/survey_notebook-physics.md; documents provenance/DIRAC16COMPLEX_PRIMORDIAL_FIELD.md, DIRAC16COMPLEX_DARK_SECTOR_NUMERICS.md, DIRAC16COMPLEX_STUDENT_GUIDE.md, DIRAC16COMPLEX_KOHN_SHAM_PRIMORDIAL.md; code studies/dirac16complex_cosmology (exp1.rs ... exp5.rs), studies/dirac16complex_kohn_sham, scripts/ks_reference_solver.py, the Stage-2 Wolfram/sympy verifiers. Read files in chunks of at most 300 lines per call. Report only real problems with concrete evidence, each with the exact fix to the spec; also list what you checked and found right.`
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, section: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'section', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
phase('Review')
const lenses = [
  ['physics', 'PHYSICS: re-derive every formula and claim of the spec yourself (sympy in your scratch is allowed: write scripts only under the system temp directory): the linear member a4 = A t, gamma^mu Omega_mu = 3 H gamma^0 independent of a4 and Theta_4 = 0, the required source rho_req = -3H^2(7 + A^2)/kappa and the pressures, the warped y form with time-dependent a4, the claim that the Z2 brane extrinsic curvature and Israel stress are unchanged at every instant, the EXP-2 constraint value -3, the EXP-3 dilution S ~ 1/(a^3 c^3), the EXP-4 claim that the good-sector mode equation involves c only through the 7-volume (check the spin-connection term Theta, which now contains -3 H_c), the D8 claim that the instantaneous single-particle operator is the static one with a4,0 = a4(x4) and the E4.10 rescaling (Delta k e^{-a4}, l e^{a4}, lambda e^{3 a4}), and the adiabaticity criterion. Find every error.'],
  ['faithfulness', 'FAITHFULNESS: does the spec implement the user\'s correction ("x5, x6, x7 are the three extra times that exponentially deflate" + "Redo the physics") everywhere, without inventing physics the notebook does not have and without leaving any non-deflating model as canonical? Check every place in the documents, textbook chapters (provenance/textbook/chapters/) and code where the extra times are static, windowed, frozen or reversed, and whether the spec covers it (list any it misses). Check the notebook survey for how the notebook itself specifies a4 and the deflation rate (cell 100, ProductLog, superluminal deflation) and whether A = 1, 2 and the EXP-3/EXP-4 rate choices are faithful or need to be labelled as choices.'],
  ['feasibility', 'FEASIBILITY: for every decision D1-D14, find the code that must change (file, function), estimate the work and the run time on this machine from the committed summaries (solver step counts and wall times), and identify blockers: e.g. does the Kohn-Sham crate support a4_0 != 0 in every subcommand, does the reference solver, do the Stage-3 experiments have the hooks for c(t) in EXP-3/EXP-4, which checks and notebooks pin numbers that will change, which gates must be rerun. Propose the concrete work split into workflows (which agents, which files each owns, what can run in parallel without file conflicts).'],
]
const results = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}\nTASK (reviewer, lens ${k}): ${t}`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
return results
