export const meta = {
  name: 'lovelock-gkd-verification-and-docs',
  description: 'Independent sympy verification, Wolfram check that GKD equals the author kdelta, Jupyter notebook (rustSolveIt style), student provenance md/tex/pdf, four review lenses, fixer - for the Lovelock tensors computed by studies/lovelock_gkd',
  phases: [
    { title: 'Independent', detail: 'sympy checker; Wolfram GKD = kdelta' },
    { title: 'Notebook and docs', detail: 'Jupyter notebook; provenance document' },
    { title: 'Review', detail: 'correctness, honesty/provenance, pedagogy, reproducibility' },
    { title: 'Fix', detail: 'apply confirmed findings' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const ART = 'artifacts/lovelock-gkd'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; read-only git is fine. THE TASK (the author's words, abridged): refactor the author's Wolfram Language generalized Kronecker delta kδ[lower_, upper_] /; Length[lower] == Length[upper] := Det[Outer[delta, lower, upper]] into a pure Rust function GKD, and use GKD to calculate, with provenance, the three non-zero Lovelock tensors of Lovelock's equation (4.38) (A^{lh} = sqrt(g) sum_{k=1}^{m-1} α_(k) g^{jl} δ^{h h1...h2k}_{j j1...j2k} R^{j1j2}_{h1h2} ... R^{j(2k-1)j2k}_{h(2k-1)h2k} + λ sqrt(g) g^{lh}, m = n/2 = 4, so k = 1, 2, 3), writing out every component, for the author's 8x8 test metric diag(E^(2 a4[x4]) Sin[6 H x8]^(1/3) (x1,x2,x3), -1 (x4), -E^(-2 a4[x4]) Sin[6 H x8]^(1/3) (x5,x6,x7), Cot[6 H x8]^2 (x8)); PROVE that the calculation was done here and that the author's answers were not read; detailed instructions for an ignorant student; Jupyter notebooks in the style of the author's rustSolveIt repositories; markdown and LaTeX compiled to PDF provenance.
DONE BY THE LEAD (read first, do not change its results): studies/lovelock_gkd (pure Rust: src/gkd.rs GKD with its proof, src/poly.rs exact Laurent polynomials, src/geometry.rs metric/Christoffel/Riemann (MTW convention), src/lovelock.rs the sums, src/main.rs CLI: print-config, gkd-selftest, lovelock); outputs in ${ROOT}/${ART}/: curvature.json, lovelock-tensors.json (every component of P_(k)^h_j = δ^{h...}_{j...} R...R and A_(k)^{lh} = sqrt(g) g^{ll} P_(k)^h_l, k = 1,2,3, as Mathematica text, LaTeX and exact "monomials" [[num, den, [e_H, e_a4', e_a4'', e_a4''', e_a4'''', e_E, e_S, e_C]], ...] with E = e^{a4[x4]}, S = Sin[6 H x8]^(1/3), C = Cot[6 H x8]), lovelock-components.md, lovelock-report.json (19 checks, all true), gkd-selftest.json, PROVENANCE_OF_THE_COMPUTATION.md (read it: only the notebook's INPUT cells were read; results committed in commit 3e81eeb BEFORE any comparison with the author's answers). Build: cargo build --release --manifest-path studies/lovelock_gkd/Cargo.toml.
STRICT RULE: do NOT open, read, print or search the OUTPUT cells of any of the author's Mathematica notebooks (*.nb), nor the file Generalized_Kronecker_Delta.txt, nor any other file that could contain the author's answers for these tensors. The comparison with the author's answers is a separate, later step done by the lead. If a Rust bug is found, report it precisely (the lead fixes it); do not change studies/lovelock_gkd/src unless your task says so.
Tooling: Python 3.14 with sympy, numpy, matplotlib, nbformat/nbclient/ipykernel (check); WolframScript 1.14 (drops arguments after "--"); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> [--register] (read its header and the Markdown subset of scripts/build_dissertation_tex.py; for this document use --developer-layout); provenance/pdf-specifications.json is shared: re-read it immediately before registering and change only your entry. Read files in chunks of at most 300 lines per tool call. Scratch under ${SP}/lovelock_wf/<label>/.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

phase('Independent')
const [sym, wolf] = await parallel([
  () => agent(`${COMMON}
TASK (independent sympy verification). Own: scripts/check_lovelock_gkd.py, ${ART}/python-lovelock-report.json, tests/test_lovelock_gkd.py. Write an INDEPENDENT checker that shares no code with the Rust crate: (1) build the metric in sympy with symbols H, x4, x8 and the function a4(x4), compute the inverse, sqrt|det g|, the Christoffel symbols and R^a_{bcd} (MTW convention, stated) with sympy's own differentiation, and R^{ab}_{cd}; (2) implement the generalized delta LITERALLY as the author defined it, sympy.Matrix([[1 if l_i == u_j else 0 ...]]).det() (no permutation-sign shortcut; memoise by index lists to keep it fast), and compute P_(k)^h_j for k = 1, 2, 3 by summing over the nonzero R^{ab}_{cd} entries (a different enumeration from the Rust DFS is welcome); (3) independent routes: P_(1) = -4 G (Einstein from Ricci), and P_(2) from the classical Gauss-Bonnet tensor formula H^h_j = 2 (R R^h_j - 2 R^h_a R^a_j - 2 R^{h a}_{j b} R^b_a + R^{h a b c} R_{j a b c}) - 1/2 δ^h_j (R^2 - 4 R_{ab} R^{ab} + R_{abcd} R^{abcd}) with the relation P_(2) = -8 H (derive and state the normalisation yourself; if your derivation gives a different constant, report it with the derivation); (4) read ${ART}/lovelock-tensors.json, rebuild every component from its exact monomial list (E -> exp(a4(x4)), S -> sin(6 H x8)**(1/3), C -> cot(6 H x8), the a4 derivatives) and show that sympy's difference with your own result simplifies EXACTLY to 0 for all 3 x 64 mixed components and all 3 x 64 contravariant components (use trigsimp / rewrite as needed; additionally evaluate at 5 random rational points with high precision); also the Lovelock scalars L_(k) and the curvature.json Christoffels and Ricci; (5) write ${ART}/python-lovelock-report.json (checks with details, verdict), deterministic (two runs byte-identical); (6) tests/test_lovelock_gkd.py (unittest): runs the Rust binary (build if needed) and the checker, asserts all checks, determinism of both, and pins the sha256 of the committed outputs. Run everything; report the run times.`, { label: 'sympy-checker', phase: 'Independent', schema: RESULT }),
  () => agent(`${COMMON}
TASK (Wolfram check that GKD is the author's kδ). Own: wolfram/LovelockGKDCheck.wl (optional), scripts/verify_lovelock_gkd.wls, ${ART}/wolfram-gkd-report.json. Re-type the author's definition VERBATIM in your own script (from PROVENANCE_OF_THE_COMPUTATION.md: kδ[lower_, upper_] /; Length[lower] == Length[upper] := Det[Outer[delta, lower, upper]] with delta = KroneckerDelta on coordinate labels), then: (1) exhaustively compare kδ with GKD for all pairs of index lists of length 1, 2, 3 over 8 labels (GKD values: add a subcommand? NO - do not modify the Rust crate; instead write a small file of GKD values with the Rust binary through a tiny Rust test program under scratch that depends on the crate by path, or reproduce the GKD rule from studies/lovelock_gkd/src/gkd.rs in a separate exported table - state which), (2) 20,000 pseudo-random pairs of each length 4..7 (half permutations), (3) recompute P_(1)^h_j and P_(2)^h_j in Wolfram from YOUR OWN Christoffel/Riemann code for the metric with the verbatim kδ, summing over the nonzero R entries, and compare exactly (FullSimplify difference 0) with ${ART}/lovelock-tensors.json (rebuild from the monomial lists); for k = 3 compare at least the 8 diagonal components (they are the only nonzero ones) if the run time allows (report the time; use the verbatim kδ only where affordable and say where a faster equivalent is used). Write ${ART}/wolfram-gkd-report.json (checks, verdict) deterministically (two runs byte-identical). Run it.`, { label: 'wolfram-check', phase: 'Independent', schema: RESULT }),
])

phase('Notebook and docs')
const [nb, doc] = await parallel([
  () => agent(`${COMMON}
TASK (Jupyter notebook in the style of the author's rustSolveIt repositories). First read the author's notebooks in ${ROOT}/vendor/rustSolveIt/planet_Mercury/notebook/*.ipynb (the Win11 rustSolveIt repository, https://github.com/once-ere/rustSolveIt_Win11_SUNDIALS_7_8_0.git) and note their structure: numbered markdown sections (what the notebook computes, how to run it, the words used, the physical situation, how the notebook talks to the program), a Python driver cell that locates/builds the Rust binary and runs subcommands with subprocess, cells that make the program recite its configuration, tables and checks. The Mac and Linux variants (rustSolveIt_macos-silicon_SUNDIALS_7_8_0, rustSolveIt_linux_SUNDIALS_7_8_0) follow the same pattern; mention them for the run instructions. Own: notebooks/lovelock_gkd.ipynb, notebooks/build_lovelock_gkd_notebook.py (deterministic builder), tests/test_lovelock_gkd_notebook.py. The notebook, for an ignorant student: what a generalized Kronecker delta is (the author's definition, a 2x2 and a 3x3 example computed in the notebook both by the literal determinant and by GKD's permutation-sign rule), how GKD is derived from the determinant, the metric, building and running lovelock_gkd (print-config, gkd-selftest with --exhaustive-max 3 for speed, lovelock), loading the JSON outputs, displaying every component of the three tensors (mixed P and contravariant A) as rendered tables (sympy pretty/LaTeX), the checks of lovelock-report.json and (if present) python-lovelock-report.json and wolfram-gkd-report.json, a hand computation of one component of P_(1) from the listed Riemann entries, and the provenance note (what of the author's notebook was read). Execute it with nbclient (Python kernel) so the committed notebook contains outputs; the test re-executes it in scratch and checks that every cell runs without error and that the asserted numbers hold. Do not include anything from the author's notebook outputs.`, { label: 'jupyter', phase: 'Notebook and docs', schema: RESULT }),
  () => agent(`${COMMON}
TASK (the provenance document for an ignorant student). Own: provenance/LOVELOCK_GKD.md, its .tex and .pdf, its entry in provenance/pdf-specifications.json (re-read before registering; change only your entry), tests/test_lovelock_gkd_publication.py. Independent results of the other agents (truncated): sympy ${JSON.stringify(sym).slice(0, 2500)} wolfram ${JSON.stringify(wolf).slice(0, 2500)}. Write "The Lovelock tensors of the dirac16complex primordial metric, constructed with the generalized Kronecker delta GKD" with these sections: summary (what was computed, the three tensors, the verdict of every check); the task and the honesty/provenance rules (quote PROVENANCE_OF_THE_COMPUTATION.md; the commit order); from zero: indices and the summation convention, the metric and its inverse, sqrt g, coordinate derivatives of a4(x4), sin and cot, Christoffel symbols (the formula, then ALL 25 nonzero ones of this metric with b <= c, from curvature.json), the Riemann tensor (formula, convention, the meaning of R^{ab}_{cd}, how many nonzero entries, the distinct ones listed), the generalized Kronecker delta (the author's determinant definition, small worked examples, the proof that it equals the sign of the permutation or 0, GKD's algorithm and cost, the exhaustive tests), the Lovelock tensors (equation (4.38) with the image artifacts/lovelock-gkd/notebook-in68-image.png as a figure, why m = 4 and k = 1, 2, 3, why k = 4 gives nothing, the normalised E_(k) = -P_(k)/2^(k+1), the relation P_(1) = -4 G), the step-by-step construction of P_(k)^h_j with GKD (a fully worked example: P_(1)^{x4}_{x4} by hand from the listed Riemann entries), EVERY component of P_(1), P_(2), P_(3) (all 64 each, zeros stated) and of A_(1), A_(2), A_(3) (all 64 each) from lovelock-tensors.json, the Lovelock scalars L_(1..4); the checks and what each proves; the independent verifications (sympy, Wolfram); reproduction commands (PowerShell and Bash); the Jupyter notebook; what is NOT claimed (e.g. no Einstein-Lovelock solution is claimed here; the conventions; the comparison with the author's answers is a later, separate section to be added by the lead - leave a placeholder section "Comparison with the author's results" saying it is done after this document's first commit). Build the PDF with --developer-layout (verify mode until warning-free), register it, pin it in the test (pattern tests/test_d16c_primordial_publication.py), run the test.`, { label: 'document', phase: 'Notebook and docs', schema: RESULT }),
])

phase('Review')
const lenses = [
  ['correctness', 'Re-derive by hand (and with your own sympy in scratch) the Christoffel symbols, several Riemann components, the GKD proof, and at least two diagonal components of each of P_(1), P_(2), P_(3); check every formula and number of provenance/LOVELOCK_GKD.md and the notebook against the outputs; check the Gauss-Bonnet normalisation claim.'],
  ['honesty-provenance', 'Check that the provenance claims are true and checkable: what was read (inputs only), the commit order (git log), that no file of the deliverables contains or was derived from the author answers, that the checks prove what the document says they prove, that every claim is labelled correctly.'],
  ['pedagogy', 'Read provenance/LOVELOCK_GKD.md and the notebook as an ignorant student (school algebra and calculus of one variable): every notion defined before use, every step shown, the worked examples complete and correct, the instructions sufficient to construct every component by hand or by running the code.'],
  ['reproducibility', 'From a fresh copy of the working tree in scratch: build the crate, run every command of the document and the notebook, run the sympy checker and the Wolfram verifier, re-execute the notebook, rebuild the PDF in verify mode, run tests/test_lovelock_gkd*.py; compare outputs byte for byte with the committed files.'],
]
const reviews = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}
TASK (adversarial reviewer, lens ${k}; do not edit repository files): ${t} Report only real problems with concrete evidence.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
const findings = reviews.filter(Boolean).flatMap(r => r.findings || [])
log('lovelock review: ' + findings.length + ' findings')

phase('Fix')
let fix = null
if (findings.length) {
  fix = await agent(`${COMMON}
TASK (fixer). Findings (JSON): ${JSON.stringify(findings).slice(0, 80000)}
Re-verify each; fix confirmed ones at their root in the files of this workflow (scripts/check_lovelock_gkd.py, scripts/verify_lovelock_gkd.wls, the notebook and its builder, provenance/LOVELOCK_GKD.*, the tests); for a confirmed bug in studies/lovelock_gkd/src write the exact fix in key_results and do NOT apply it (the lead applies it and reruns); regenerate reports deterministically, rebuild and re-register the PDF, re-execute the notebook, rerun all tests. One line per finding: FIXED / REJECTED (reason) / RUST-BUG-FOR-LEAD (exact fix).`, { label: 'fix', phase: 'Fix', schema: RESULT })
}
return { sym, wolf, nb, doc, findings, fix }
