export const meta = {
  name: 'stage5-documents-review',
  description: 'Stage 5: the two provenance documents, the gate, four adversarial review lenses, one fixer',
  phases: [
    { title: 'Documents and gate', detail: 'DIRAC16COMPLEX00_FIELD_THEORY, DIRAC16COMPLEX_PAIR_CREATION, verify_stage5_pair_creation' },
    { title: 'Review', detail: 'proof rigour, physics, numerics, reproducibility' },
    { title: 'Fix', detail: 'verify and apply confirmed findings' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const ART = 'artifacts/dirac16complex/pair-creation'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main; do NOT commit, push, or run git commands that change the index or working tree; the lead commits). Stage 5 of the dirac16complex project. BINDING: ${ROOT}/handoff/specs/STAGE5_SPEC.md (task, honesty rule, theorems), ${ROOT}/handoff/specs/STAGE5_DOC_OUTLINE.md (document structure), ${ROOT}/handoff/specs/CONTRACT.md (section 11 errata), ${ROOT}/handoff/specs/STAGE4_SPEC.md (sections 8-9), ${ROOT}/HANDOFF.md section 4. The Stage-5 exact theory and numerics are FINAL: Wolfram wolfram/Dirac16Complex00.wl, wolfram/Dirac16ComplexPairing.wl with scripts/verify_dirac16complex00.wls, scripts/verify_dirac16complex_pairing.wls; sympy scripts/check_dirac16complex00.py, scripts/check_dirac16complex_pairing.py; numerics: the pairs subcommand of studies/dirac16complex_kohn_sham, the reference options in scripts/ks_reference_solver.py with scripts/ks_reference_pairs.py, the checker scripts/check_dirac16complex_pairs.py; all reports and outputs under ${ROOT}/${ART}/ (read every report before writing).
STAGE-4 IS PAUSED: never touch artifacts/dirac16complex/kohn-sham/**, scripts/verify_stage4_*, notebooks/*kohn_sham*, provenance/DIRAC16COMPLEX_KOHN_SHAM_*, or the Stage-1 files a stopped agent modified (scripts/verify_stage1_*, scripts/build_stage1_summary.py, provenance/DIRAC16COMPLEX_ARBITRARY_FIELD.*, tests/test_d16c_arbitrary_field_*). Never modify dirac-main/, vendor/, or the author's .nb notebook.
Tooling: WolframScript 1.14 drops arguments after "--"; Python 3.14 (numpy, sympy, mpmath, matplotlib; no scipy); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> [--register] (read its header and the Markdown subset of scripts/build_dissertation_tex.py, which supports images ![caption](path.png)); provenance/pdf-specifications.json is shared between the two document agents: re-read it immediately before registering and change only your entry. HONESTY: numbers only from the committed reports; theorems stated with their exact hypotheses; interpretation labelled as such; never write "proved" for anything not proved. Large files in chunks of at most 300 lines per tool call. Scratch only under ${SP}/stage5_tmp/<your label>/.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

phase('Documents and gate')
const firstWave = await parallel([
  () => agent(`${COMMON}
TASK (document A). Own: provenance/DIRAC16COMPLEX00_FIELD_THEORY.md, .tex, .pdf, its entry in provenance/pdf-specifications.json, tests/test_d16c_stage5_field_theory_publication.py. Write document A of STAGE5_DOC_OUTLINE.md completely (every section; every formula as verified in the reports; every number from them), build the PDF (verify mode until warning-free), register it, pin it in the test following tests/test_d16c_primordial_publication.py, run the test.`, { label: 'doc-field-theory', phase: 'Documents and gate', schema: RESULT }),
  () => agent(`${COMMON}
TASK (document B). Own: provenance/DIRAC16COMPLEX_PAIR_CREATION.md, .tex, .pdf, its entry in provenance/pdf-specifications.json, figures under ${ART}/figures/ (deterministic matplotlib, Agg, metadata Software None, generated by a script you own: scripts/build_dirac16complex_pairs_figures.py), tests/test_d16c_stage5_pair_creation_publication.py. Write document B of STAGE5_DOC_OUTLINE.md completely: the theorems with full proofs (as verified), the KS model of both fields, the numerical demonstration with tables and figures, the verification records, reproduction commands, and an explicit final section separating what is proved from interpretation (the notebook's hypothesis quoted). Cite and reconcile the Stage-1 statement (provenance/DIRAC16COMPLEX_ARBITRARY_FIELD.md, summary item 6 and Section 7.7: the chirality pairing is 'a structural property of the equations, not a claim that universes of masses +-M are created in pairs'): say precisely what Stage 5 adds (the pair corollaries and the KS-level results, with their hypotheses) and what remains unclaimed (a creation rate, amplitude or wave function). Build the PDF (verify mode until warning-free), register it, pin it, run the test.`, { label: 'doc-pair-creation', phase: 'Documents and gate', schema: RESULT }),
  () => agent(`${COMMON}
TASK (gate). Own: scripts/verify_stage5_pair_creation.ps1, scripts/verify_stage5_pair_creation.sh, scripts/verify_stage5_pair_creation_audit.py (if needed), tests/test_d16c_stage5_gate.py. Write the Stage-5 gate twins following the Stage-3 gate pattern exactly (tool resolution, run_logged, snapshot audit of committed paths, re-exec under PowerShell 7, never two gates at once, final line stage5_pair_creation_verification=OK): the two Wolfram verifiers (optional when wolframscript is absent, stated), the two sympy checkers, cargo fmt/clippy/test/build of the crate, the Rust pairs subcommand into build/ with byte comparison against the committed ${ART}/rust/, the reference pairs runner into build/ (or its checker's reproduction mode if a full run is long; state exactly what is re-run), the pairs checker, the figures script with a byte comparison, both PDFs in verify mode, a committed-unchanged audit, and python -m unittest discover -s tests -p "test_d16c_stage5*.py" -v. Test the scripts on the fast steps (a --steps or --dry-run option like the Stage-4 gate); document the expected wall time per step. Do not run the full gate before the documents exist; the lead runs it from a fresh clone.`, { label: 'gate', phase: 'Documents and gate', schema: RESULT }),
])

phase('Review')
const lenses = [
  ['proof-rigour', 'Check every theorem and proof of document B and every derivation of document A line by line against the Wolfram and sympy reports and re-derive the key steps yourself (the gamma^8 facts, the Lagrangian and EMT relations, the Pin reflection, the block map and the boundary-condition transformation, the expectation-rule signs, the Wick sign of the statistics). Flag any statement called proved that is not, any hidden hypothesis, any sign error, any overclaim about "creation".'],
  ['physics', 'Judge the physics: the definition and status of dirac16complex00, the reality and non-triviality claims, the real restriction versus the notebook, the KS model of the commuting field and its stated status, the meaning of the pair corollaries (zero total energy-momentum versus mirror pairs of equal energy), consistency with Stages 1-4 and with the notebook (quote cells).'],
  ['numerics', 'Re-run the cheap parts (the pairs subcommand for a subset into scratch, the reference runner for a subset, the checker), audit every number and figure quoted in both documents against the outputs, and test the pairing identities and the untransformed-BC control yourself.'],
  ['reproducibility', 'From a fresh copy of the working tree in scratch (copy the tree including uncommitted files; fetch the engine with scripts/setup_solver), run every command the documents give that finishes within about 20 minutes, build both PDFs in verify mode, run the fast steps of the Stage-5 gate and the Stage-5 unit tests. Report every failing or ambiguous step.'],
]
const reviews = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}
Documents, gate and code are written. TASK (adversarial reviewer, lens ${k}): ${t} Report only real problems with concrete evidence; do not edit repository files.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
const findings = reviews.filter(Boolean).flatMap(r => r.findings)
log('stage5 findings: ' + findings.length)

phase('Fix')
let fix = null
if (findings.length) {
  fix = await agent(`${COMMON}
TASK (fixer). Findings (JSON): ${JSON.stringify(findings).slice(0, 90000)}
Re-verify each; fix confirmed ones at their root (regenerate outputs deterministically, rebuild figures and PDFs, register, update pins); reject unconfirmed ones with evidence. Report one line per finding in key_results: FIXED / REJECTED (reason) / NEEDS-RERUN (command).`, { label: 'fix', phase: 'Fix', schema: RESULT })
}
return { firstWave, findings, fix }
