export const meta = {
  name: 'stage4-review-fix',
  description: 'Stage 4: four adversarial review lenses over the final Kohn-Sham code, outputs, notebooks and documents, then one fixer',
  phases: [
    { title: 'Review', detail: 'dft-physics, numerics, geometry-fidelity, student-reproducibility' },
    { title: 'Fix', detail: 'verify and apply confirmed findings' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const ART = 'artifacts/dirac16complex/kohn-sham'
const CRATE = 'studies/dirac16complex_kohn_sham'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main; do NOT commit, push, or run git commands that change the index or working tree). Stage 4 of the dirac16complex project: Kohn-Sham DFT ground and first excited states of the 16-component complex Grassmann spinor field of Pin(4,4) in the primordial gravitational field. BINDING: ${ROOT}/handoff/specs/STAGE4_SPEC.md (section 8 errata override earlier sections), ${ROOT}/handoff/specs/CONTRACT.md (section 11 errata), ${ROOT}/handoff/specs/NUMERICS_CONTRACT.md, ${ROOT}/HANDOFF.md sections 2 and 4.
EVERYTHING IS NOW FINAL AND COMMITTED-OR-STAGED IN THE WORKING TREE: exact theory (wolfram/Dirac16ComplexKohnSham.wl, scripts/verify_dirac16complex_kohn_sham.wls -> ${ART}/wolfram-kohn-sham-report.json; scripts/check_dirac16complex_kohn_sham_theory.py -> ${ART}/python-theory-report.json), the Rust solver ${CRATE} with canonical outputs ${ART}/rust/ (repeat and refined trees in ${SP}/stage4_tmp/rust/{repeat,refined}), the reference solver scripts/ks_reference_solver.py -> ${ART}/reference/, the cross-checker scripts/check_dirac16complex_kohn_sham.py -> ${ART}/python-check-report.json, the summary ${ART}/kohn-sham-summary.json, the notebooks notebooks/dirac16complex_kohn_sham.ipynb and notebooks/Dirac16ComplexKohnSham.nb with their builders/verifiers, the gate scripts/verify_stage4_kohn_sham.{ps1,sh}, and the documents provenance/DIRAC16COMPLEX_KOHN_SHAM_PRIMORDIAL.{md,tex,pdf} and provenance/DIRAC16COMPLEX_KOHN_SHAM_STUDENT_GUIDE.{md,tex,pdf} with their tests.
Known facts the lead established (verify them, do not assume): (1) at N = 1016 with -lambda_hat_2 the exact T = 0 aufbau does not converge on the continuation branch from lambda = 0; the ground state is converged with occupation smearing 1e-3 m at the physical T = 0; the aufbau count closes exactly at the 192-fold k = 0.935 band and the ensemble moves about 4.2 particles into the 8-fold k = 0 level 3.7e-3 m above; its KS gap and Delta-SCF refer to that ensemble; particle-hole pairs of T = 0 runs use an occupation floor 1e-12 in both solvers. (2) An exploratory reference run of that case on twice-finer grids (N0 = 120; evidence ${ROOT}/handoff/reviews/stage4_refgrid_N0120_exploratory.log) converged the exact T = 0 aufbau from its own starting point to a state with E about 1.01 m ABOVE the reported ground state (and about 0.73 m above the free state although the coupling is attractive); it was not analysed further. The reported ground state is the branch reached by continuation from lambda = 0 (Rust solve_ground). Whether the documents need to mention this, and how, is for the dft-physics lens to judge; they must not claim more than the log shows. (3) Energy per particle at N = 112 (Delta k = 0.25 m) and N = 896 (Delta k = 0.125 m) differ by 6.6%: finite shell spacing; moreover N = 896 at Delta k = 0.125 m is an OPEN shell of the T = 0 aufbau (80 of the 192 states of the k = 0.468 shell, filled equally), so its KS gap is 0 by definition. (4) For N >= 112 the average KS energy density is positive, opposite in sign to the required rho_req = -21H^2/kappa; for N = 8 with lambda > 0 the sign matches but the implied kappa is ~1e7 and w is not -5/7.
Rules: never modify dirac-main/, vendor/, the author's .nb input notebook at the repository root, or any Stage 1-3 file. Honesty: never report a check as passing unless computed; numbers in documents only from committed reports/outputs. Scratch only under ${SP}/stage4_tmp/<your label>/. Tooling: WolframScript 1.14 drops arguments after "--"; Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient; no scipy); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py. A full Rust "all" run takes about 4 hours and a full reference run several hours: rerun only what your lens needs, into scratch.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

phase('Review')
const lenses = [
  ['dft-physics', 'Re-derive independently: the reduction and boundary conditions, the Hartree-Fock exchange of the contact interaction and its exactly local uniform-gas form, the Mermin-Kohn-Sham functional and its derivatives, the energy-momentum tensor of the KS state; check that the pseudo-potential enters consistently (scalar M_eff vs vector v_x), that occupations, degeneracies (4-fold per block type at fixed k, 8-fold at k = 0), parity sectors and normal ordering are right, that the ground-state definition (continuation from lambda = 0) and the first-excited-state claims (KS gap, particle-hole list, Delta-SCF) are correct and not overstated, including the smeared N = 1016 case and the second SCF solution, and that the comparison with the required Einstein source is stated quantitatively and correctly.'],
  ['numerics', 'Re-run cheap pieces yourself (Rust print-config, spectrum and one scf run into scratch; the reference --quick self-tests; the cross-checker with --repeat/--refined on the scratch trees) and audit the rest from the outputs: convergence in y-grid (the _g601 runs), L, Delta k, SCF tolerance; shooting failures (missed levels, node counts), doublers in the reference, mixing artefacts, mu/N bisection; every Rust vs reference vs Mathematica deviation and every number quoted in both documents and in the notebook against the committed outputs.'],
  ['geometry-fidelity', 'Verify the geometric statements against the notebook field and Stage 2 (artifacts/dirac16complex/primordial-field/*, provenance/DIRAC16COMPLEX_PRIMORDIAL_FIELD.md): the y-coordinate and warp, the tip, both extensions, the Israel junction sign convention and brane stress, the curvature numbers, rho_req and p_req (p_req = +15H^2/kappa by the Stage-4 erratum); check that the documents describe the notebook faithfully and invent nothing.'],
  ['student-reproducibility', 'Follow the student guide literally from a fresh copy of the working tree in scratch (copy the tree including uncommitted files; fetch the engine with scripts/setup_solver): run every command it gives that finishes within about 20 minutes (skip and report the multi-hour ones, checking that their documented wall times are consistent with the logs), execute both notebooks headless, build both PDFs in verify mode, and run the fast steps of the Stage-4 gate. Report every failing, ambiguous or wrong step, every wrong expected output, every column table that does not match its CSV.'],
]
const reviews = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}
TASK (adversarial reviewer, lens ${k}): ${t} Report only real problems with concrete evidence (file, line, command output, numbers); do not edit repository files.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
const findings = reviews.filter(Boolean).flatMap(r => r.findings)
log('stage4 findings: ' + findings.length + ' (' + ['critical', 'major', 'minor'].map(s => s + ' ' + findings.filter(f => f.severity === s).length).join(', ') + ')')

phase('Fix')
let fix = null
if (findings.length) {
  fix = await agent(`${COMMON}
TASK (fixer). Findings of four adversarial reviewers (JSON): ${JSON.stringify(findings).slice(0, 90000)}
Re-verify each finding yourself; fix the confirmed ones at their root (code, outputs regenerated deterministically - never hand-edit an output; notebooks rebuilt and re-executed; figures regenerated; documents corrected; PDFs rebuilt and registered; test pins updated), and reject unconfirmed ones with evidence. If a fix needs a multi-hour Rust or reference rerun, do the code fix and the cheap verification, and list the exact rerun commands in open_items instead of running them. Report one line per finding in key_results: FIXED / REJECTED (reason) / NEEDS-RERUN (command).`, { label: 'fix', phase: 'Fix', schema: RESULT })
}
return { reviews, findings, fix }
