export const meta = {
  name: 'stage4-kohn-sham-primordial',
  description: 'Stage 4: Kohn-Sham DFT of dirac16complex in the primordial field: exact theory, Rust CVODE solver, reference solver, notebooks, documents, review, gate',
  phases: [
    { title: 'Build', detail: 'exact theory (Wolfram + sympy), Rust KS solver, independent reference solver' },
    { title: 'Integrate', detail: 'cross-checks Rust vs reference, checker, summary' },
    { title: 'Notebooks', detail: 'Jupyter and Mathematica' },
    { title: 'Documents', detail: 'results document and student guide' },
    { title: 'Review', detail: 'four adversarial lenses' },
    { title: 'Fix', detail: 'apply confirmed findings' },
    { title: 'Gate', detail: 'clean Stage-4 gate' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const ART = 'artifacts/dirac16complex/kohn-sham'
const CRATE = 'studies/dirac16complex_kohn_sham'

const COMMON = `
CONTEXT: repository ${ROOT} (git, main; do NOT commit or push). BINDING, read fully first: ${SP}/STAGE4_SPEC.md, then ${SP}/CONTRACT.md (with its section 11 errata), ${SP}/STAGE2_SPEC.md and the Stage-2 results in ${ROOT}/artifacts/dirac16complex/primordial-field/{wolfram-primordial-report.json,primordial-components.json} and ${ROOT}/provenance/DIRAC16COMPLEX_PRIMORDIAL_FIELD.md (if present), ${SP}/NUMERICS_CONTRACT.md (conventions: expectation-value rule, densities), and the Stage-3 crate ${ROOT}/studies/dirac16complex_cosmology (its src/lib.rs header documents the CVODE driver/spinor API to reuse by copying; the engine is ${ROOT}/vendor/rustSolveIt/sundials_rs, fetched by scripts/setup_solver; repo-root .cargo/config.toml pins +fma). Gamma matrices: ${ROOT}/artifacts/dirac16complex/arbitrary-field/algebra-fixture.json (exact; "gamma", "C", "chirality"; B = -i C gamma^4). Design probes that already passed: ${SP}/ks_probe.py (exchange = Hartree/8 on a filled shell; the 8-dim algebra), ${SP}/ks_probe2.py (2x2 block structure), ${SP}/ks_probe3.py (warped-form curvature, K^i_j = H, brane stress).
Other workflows are concurrently finishing Stage 1-3 documents/notebooks/gates: never touch files outside your ownership; never modify dirac-main, the .nb input, vendor/.
Tooling facts: WolframScript 1.14 drops arguments after "--" (pass paths positionally); Python 3.14 with numpy, sympy, mpmath, matplotlib, nbformat, nbclient (no scipy); pdflatex (MiKTeX); cargo/rustc 1.91; PDFs only via python scripts/build_provenance_pdf.py <md> [--register]; the Markdown subset of scripts/build_dissertation_tex.py (read its header; images via ![caption](path.png) if that extension landed - check the script). Deterministic outputs (LF, fmt_e(v,17) in Rust, json.dumps(indent=2) + newline in Python). Every verifier/checker prints check_<name>=true|false, measurement_<name>=..., check_count, failed_check_count and exits nonzero on failure, writing a JSON report {schemaVersion, producer, checks, measurements, sourceSha256}.
Honesty: never report a check as passing unless computed; if the spec's expectations are wrong, keep the check, record the measured truth, explain. Scratch only under ${SP}/stage4_tmp/<label>/.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, spec_problems: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'spec_problems', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

phase('Build')
const build = await parallel([
  () => agent(`${COMMON}
YOU OWN: ${ROOT}/wolfram/Dirac16ComplexKohnSham.wl, ${ROOT}/scripts/verify_dirac16complex_kohn_sham.wls, ${ROOT}/${ART}/wolfram-kohn-sham-report.json, ${ROOT}/${ART}/kohn-sham-theory.json.
TASK (exact theory, Wolfram): implement and verify, exactly (no floats; rational/algebraic points where needed): KS_geometry (warped form from the notebook metric with a4 constant; W^6; R = -42H^2; G^mu_nu; required source; extrinsic curvature K^i_j = H on the six warped directions; the Z2 brane Israel stress with an explicitly stated sign convention; the smooth extension E1), KS_reduction (ansatz removes the 3H gamma^0 term exactly; the reduced y-equation; exact simultaneous block diagonalisation of gamma^0, gamma^0 gamma^1, gamma^0 gamma^4, B, C into eight 2x2 blocks with an EXPLICIT exact basis (eigenvectors of J = gamma^0 gamma^1 gamma^4, gamma^2 gamma^3, gamma^5 gamma^6 or an equivalent set), the 2x2 matrices per block, how many inequivalent block types, the per-block number-density, scalar-density and y-current matrices, the multiplicity 8), KS_boundary (the y-current matrix; the Z2 parity conditions Psi(-y) = +-gamma^0 Psi(y) in 2x2 form; a bag condition at y = -L; proof that each kills the y-current), KS_exchange (Hartree-Fock energy of U = (lambda/2) S^2 for a general one-body density matrix rho: E_HF = (lambda/2)[Tr(BC rho)^2 - Tr(BC rho BC rho)] with the expectation rule; filled-shell result E_x = -E_H/8; the uniform-gas exchange energy density e_x(n,T) of the 8-fold degenerate relativistic gas: derive the spin-summed |ubar_p u_q|^2 kernel exactly and give e_x as a double quadrature with the T = 0 closed form if obtainable; the LDA potentials v_v = de_x/dn (and v_s); state the exact form the KS equation uses), KS_functional (the Mermin-Kohn-Sham free-energy functional F[{chi}, f] and the stationarity conditions: show the KS equations follow, incl. the Fermi-Dirac occupations; the Hellmann-Feynman/virial-type identity to be used as a numerical check), KS_emt (the Stage-2 EMT reduced to the KS state: rho(y), p_y, p_3, p_t in terms of the 2x2 orbitals; the proper-volume average; Z2-even/odd contributions). Export to kohn-sham-theory.json every explicit matrix (basis change, 2x2 blocks, current/density matrices) as exact rationals/Gaussian rationals so the Rust and Python solvers can load them. Run: wolframscript -file scripts/verify_dirac16complex_kohn_sham.wls ${ART}/wolfram-kohn-sham-report.json (positional path).`, { label: 'wolfram-theory', phase: 'Build', schema: RESULT }),
  () => agent(`${COMMON}
RESUME NOTE: an interrupted run may have left PARTIAL files in your ownership; inspect them first, keep what is correct, finish them (do not start over blindly). Write large files in chunks of at most 300 lines per Write/Edit call (a previous attempt died on the 64k output-token limit). Read STAGE4_SPEC.md section 8 (errata from the finished exact theory; the closed-form exchange makes exchange-table.json optional).
YOU OWN: ${ROOT}/scripts/check_dirac16complex_kohn_sham_theory.py, ${ROOT}/${ART}/python-theory-report.json, ${ROOT}/tests/test_d16c_kohn_sham_theory.py.
TASK (independent exact theory, sympy/stdlib; do not import Wolfram outputs as truth, but when ${ROOT}/${ART}/kohn-sham-theory.json exists, add check KS_agreesWithWolfram comparing basis/blocks/matrices up to the documented conventions, else record not-run): the same check families KS_geometry, KS_reduction (your own exact block diagonalisation), KS_boundary, KS_exchange (own derivation of the HF formula and the filled-shell 1/8; uniform-gas e_x(n,T) as a numerical double quadrature with mpmath at several (n,T) plus the T=0 closed form if you obtain one), KS_functional, KS_emt. Also produce ${ROOT}/${ART}/exchange-table.json: e_x(n,T) tabulated on a grid of proper densities and temperatures (units m = 1) with the quadrature error estimate, to be used by both solvers for the LDA (document the grid and interpolation). Fast unittest subset < 60 s.`, { label: 'python-theory', phase: 'Build', schema: RESULT }),
  () => agent(`${COMMON}
RESUME NOTE: an interrupted run may have left PARTIAL files in your ownership; inspect them first, keep what is correct, finish them (do not start over blindly). Write large files in chunks of at most 300 lines per Write/Edit call (a previous attempt died on the 64k output-token limit). Read STAGE4_SPEC.md section 8 (errata from the finished exact theory; the closed-form exchange makes exchange-table.json optional).
YOU OWN: ${ROOT}/${CRATE}/ (all files), ${ROOT}/scripts/generate_dirac16complex_ks_constants.py, ${ROOT}/${ART}/rust/ (outputs).
TASK (Rust Kohn-Sham solver on the pinned CVODE engine): crate layout like studies/dirac16complex_cosmology (own [workspace], path deps ../../vendor/rustSolveIt/sundials_rs/crates/{sundials_core,cvode_rs}, forbid(unsafe_code), deny(warnings), fmt/clippy clean, Cargo.lock committed; copy the driver/spinor/output modules you need and credit their origin in comments). Derive the 2x2 block reduction yourself numerically-exactly from the fixture (block-diagonalise with an exact/rational construction or with a documented orthonormal basis; verify the Clifford identities of the blocks to 1e-14) and, when ${ROOT}/${ART}/kohn-sham-theory.json exists, verify agreement with it (else record not-run). Implement STAGE4_SPEC sections 2-5: per (k-shell, parity) 2x2 eigenproblem by CVODE shooting in y from -L to 0 (bag condition at -L, parity matching at 0; eigenvalue by bracketing + secant on the matching function; lowest n_max levels; verify each level by the node-count/Sturm-like criterion), Fermi-Dirac occupations with mu by bisection at fixed N, proper densities (S_p, n_p with the e^{-6Hy} factor), Hartree mass shift, LDA exchange potential from ${ROOT}/${ART}/exchange-table.json (if absent: from your own quadrature of the spec formula; record which), Anderson/linear mixing, convergence < 1e-10, ΔSCF excited state, thermodynamics at T/m in {0,0.1,0.3,1}, EMT profiles and averages, L in {2,3,4}, Δk = 0.25 m, m/H in {1,3}, a4_0 in {0, 0.5} (rescaling check), couplings chosen per spec (report lambda-hat values and |lambda S_p|/m), N shells (at least 8, a mid-size, ~10^3). Subcommands: print-config, spectrum, scf, excited, thermo, emt, all; --output DIR; --rtol/--atol/--refined; last line SUCCESS/FAILURE. Deterministic CSV/JSON under ${ART}/rust/ (canonical). Unit tests: block Clifford identities; free-particle box eigenvalues vs the analytic 1D Dirac box spectrum for lambda = 0, k = 0; k != 0 confinement lowers/raises energies as expected; SCF for lambda = 0 reproduces the non-interacting fill; virial/Hellmann-Feynman identity; repeat byte identity. Run everything; report the physics numbers (ground-state energies, gaps, ΔSCF, w's, brane-localised fraction).`, { label: 'rust-ks', phase: 'Build', schema: RESULT }),
  () => agent(`${COMMON}
RESUME NOTE: an interrupted run may have left PARTIAL files in your ownership; inspect them first, keep what is correct, finish them (do not start over blindly). Write large files in chunks of at most 300 lines per Write/Edit call (a previous attempt died on the 64k output-token limit). Read STAGE4_SPEC.md section 8 (errata from the finished exact theory; the closed-form exchange makes exchange-table.json optional).
YOU OWN: ${ROOT}/scripts/ks_reference_solver.py, ${ROOT}/scripts/check_dirac16complex_kohn_sham.py, ${ROOT}/${ART}/reference/ (outputs), ${ROOT}/tests/test_d16c_kohn_sham_reference.py.
TASK (independent numpy reference solver + checker): implement the same KS problem (STAGE4_SPEC 2-5) with a DIFFERENT method: a matrix eigensolver in y on a doubler-free discretisation (Chebyshev collocation with the two spinor components on staggered/appropriate grids, or a finite-difference scheme with a Wilson-type term whose effect is shown to vanish under refinement) plus the same SCF loop; derive your own block reduction (numerically from the fixture; compare with kohn-sham-theory.json when present). Validate on lambda = 0, k = 0 (analytic 1D Dirac box spectrum), and by grid refinement. Write ks_reference_solver.py to produce ${ART}/reference/ outputs for the canonical parameter set of the spec. Then write check_dirac16complex_kohn_sham.py: it reads ${ART}/rust/ outputs (produced concurrently by the Rust agent; if absent when you finish, make the checker robust and record which comparisons ran) and checks: eigenvalue agreement per (k,parity,n) within a stated tolerance, density/M_eff profile agreement, E_0, gaps, ΔSCF, thermodynamics, EMT averages; internal identities (N conservation, current vanishing at boundaries, SCF stationarity/Hellmann-Feynman, entropy ≥ 0, C_V ≥ 0, Z2 parity purity, L-convergence trend); repeat byte identity and refined-tolerance convergence of the Rust outputs when directories are given (--repeat DIR --refined DIR); writes ${ART}/python-check-report.json.`, { label: 'python-reference', phase: 'Build', schema: RESULT }),
])

phase('Integrate')
const integ = await agent(`${COMMON}
Build reports: ${JSON.stringify(build.map(b => b ? { failing: b.failing, key: b.key_results, problems: b.spec_problems, summary: (b.summary || '').slice(0, 2500) } : null)).slice(0, 40000)}
TASK (integration; you may edit any Stage-4 file): rerun in order: wolframscript -file scripts/verify_dirac16complex_kohn_sham.wls ${ART}/wolfram-kohn-sham-report.json; python scripts/check_dirac16complex_kohn_sham_theory.py; cargo (fmt --check, clippy -D warnings, test --release, build --release) in ${CRATE}; the Rust binary all into ${ART}/rust and again into a scratch dir (byte identity) and with --refined into scratch; python scripts/ks_reference_solver.py; python scripts/check_dirac16complex_kohn_sham.py --repeat <scratch> --refined <scratch>; python -m unittest discover -s tests -p "test_d16c_kohn_sham*.py" -v. Resolve disagreements by finding the actual bug (never by loosening tolerances without a documented numerical reason). Write ${ART}/kohn-sham-summary.json (check counts per producer, key physics numbers, deviations Rust vs reference). Write the gate twins scripts/verify_stage4_kohn_sham.{ps1,sh} (pattern of scripts/verify_stage3_dark_sector.* if present, else verify_stage1_*; final line stage4_kohn_sham_verification=OK; include the notebook and PDF steps which will fail until those exist - say so).`, { label: 'integrate', phase: 'Integrate', schema: RESULT })

phase('Notebooks')
const nb = await parallel([
  () => agent(`${COMMON}
Integration: ${JSON.stringify(integ).slice(0, 12000)}
YOU OWN: ${ROOT}/notebooks/build_dirac16complex_kohn_sham_notebook.py, ${ROOT}/notebooks/dirac16complex_kohn_sham.ipynb, ${ROOT}/${ART}/figures/*.png, ${ROOT}/${ART}/notebook-report.json (reuse notebooks/run_notebook.py and notebooks/check_notebook.py from Stage 3 if present; else copy from vendor/rustSolveIt/planet_Mercury/notebook with attribution).
TASK: Jupyter notebook (python3 kernel, rustSolveIt planet_Mercury pattern: markdown lead-ins, driver cell with find_binary/run and the SUCCESS contract, gauntlet of asserts, lessons) presenting the complete numerical documentation: the problem, the reduced 2x2 equations, the pseudo-potential, running the Rust solver, reading outputs, recomputing key quantities independently in-cell, and the graphs: KS spectrum epsilon_n(k) per parity; density profiles n_c, n_p, S_p, M_eff, v_x vs y and vs z; ground-state energy vs N; KS gap and ΔSCF vs N and lambda; thermodynamics F, E, S, C_V vs T; EMT profiles rho, p_y, p_3, p_t and w vs y; brane localisation; L-convergence; Rust vs reference deviations. Deterministic PNGs (Agg, metadata Software None). Execute headless, audit, write notebook-report.json.`, { label: 'jupyter', phase: 'Notebooks', schema: RESULT }),
  () => agent(`${COMMON}
Integration: ${JSON.stringify(integ).slice(0, 12000)}
YOU OWN: ${ROOT}/scripts/build_dirac16complex_kohn_sham_mathematica_notebook.wls, ${ROOT}/scripts/verify_dirac16complex_kohn_sham_mathematica_notebook.wls, ${ROOT}/notebooks/Dirac16ComplexKohnSham.nb, ${ROOT}/${ART}/mathematica-report.json, ${ROOT}/${ART}/figures/mathematica/*.png.
TASK: generated Mathematica notebook (pattern of the Stage-3 builder/verifier scripts if present, else dirac-main's) that: loads wolfram/Dirac16ComplexKohnSham.wl; derives the 2x2 KS equations symbolically; solves the k = 0, lambda = 0 box problem analytically and the k != 0 single-particle eigenproblem with NDEigensystem or NDSolve shooting; runs a small self-consistent KS loop in Wolfram Language for one parameter set (N = 8, one lambda != 0, T = 0) and compares eigenvalues, M_eff(y), E_0 with the Rust outputs (RunProcess print-config SUCCESS check; Import CSV/JSON); plots; final notebookChecks association. Headless verification must pass.`, { label: 'mathematica', phase: 'Notebooks', schema: RESULT }),
])

phase('Documents')
const docs = await parallel([
  () => agent(`${COMMON}
Integration: ${JSON.stringify(integ).slice(0, 10000)} Notebooks: ${JSON.stringify(nb).slice(0, 8000)}
YOU OWN: ${ROOT}/provenance/DIRAC16COMPLEX_KOHN_SHAM_PRIMORDIAL.md (+ .tex/.pdf via build_provenance_pdf.py --register), ${ROOT}/tests/test_d16c_kohn_sham_publication.py.
TASK: the complete provenance document of all final ideas and results: (1) the static primordial field, its warped form, curvature, the tip and the brane (both extensions, Israel stress, the +-M pair remark labelled structural); (2) the sector and ansatz, the exact 2x2 reduction (explicit basis and matrices), boundary conditions; (3) the interacting (dirac16complex, primordial field) system: Hartree term, exact HF exchange of the contact interaction, the uniform-gas thermodynamics e_x(n,T), the Kohn-Sham fermion-gas thermodynamics pseudo-potential (definition, formulas, table/figure), the Mermin-KS functional and equations, what is neglected (correlation) and why; (4) numerical method (shooting with CVODE, SCF, reference solver, Mathematica cross-check) with all parameters; (5) results: ground state (spectra, profiles, energies, brane localisation, L-convergence), first excited state (KS gap, ΔSCF, particle-hole list), thermodynamics, EMT/equations of state in the primordial field, comparison with the required Einstein source, dependence on lambda sign (attractive collapse toward the tip vs repulsive expulsion) and on m/H; figures embedded; (6) verification records; (7) reproduction commands (PowerShell + Bash); (8) limitations and non-claims. Every number from the reports/outputs; label reconstructions and conventions. Register the PDF; pin in the test.`, { label: 'doc-main', phase: 'Documents', schema: RESULT }),
  () => agent(`${COMMON}
Integration: ${JSON.stringify(integ).slice(0, 10000)} Notebooks: ${JSON.stringify(nb).slice(0, 8000)}
YOU OWN: ${ROOT}/provenance/DIRAC16COMPLEX_KOHN_SHAM_STUDENT_GUIDE.md (+ .tex/.pdf, --register), ${ROOT}/tests/test_d16c_kohn_sham_student_guide_publication.py.
TASK: complete numerical documentation for an ignorant student: what DFT and Kohn-Sham are (from zero), why a fermion gas thermodynamics gives a pseudo-potential, the primordial field in plain words, the reduced 1D Dirac problem step by step (index by index state layout), shooting and bisection, self-consistency and mixing, Fermi-Dirac filling, ΔSCF, every command to install/build/run/check (all actually run by you from a scratch clone of the working tree), reading each output file (column tables), running both notebooks, exercises with answers (e.g. predict the lambda = 0 box levels; change N; change T), troubleshooting, glossary. Register; pin.`, { label: 'doc-student', phase: 'Documents', schema: RESULT }),
])

phase('Review')
const lenses = [
  ['dft-physics', 'Re-derive independently: the reduction and boundary conditions, the HF exchange and its uniform-gas LDA, the Mermin-KS functional derivatives, the EMT of the KS state; check that the pseudo-potential is used consistently (scalar vs vector), that occupations/degeneracies (8-fold, parity) and normal ordering are right, and that the ground/first-excited-state claims are correct and not overstated.'],
  ['numerics', 'Rebuild and rerun the Rust solver (repeat/refined), the reference solver and the checker; test convergence in y-grid, L, k-grid and SCF tolerance; look for shooting failures (missed levels: node counts), doublers in the reference solver, mixing artefacts, and mu/N bisection errors; verify Rust vs reference vs Mathematica deviations quoted in the documents.'],
  ['geometry-fidelity', 'Verify the geometric statements against the notebook field and Stage 2 (y-coordinate, warp, tip, z = pi/2 surface, both extensions, Israel junction sign convention, curvature numbers), and that the documents describe the notebook faithfully (no invented claims).'],
  ['student-reproducibility', 'Follow the student guide literally from a fresh clone of the working tree into a scratch directory; execute both notebooks headless; build both PDFs; run the Stage-4 gate. Report every failing/ambiguous step.'],
]
const reviews = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}
Documents and code are written. TASK (adversarial reviewer, lens ${k}): ${t} Report only real problems with concrete evidence; do not edit repository files.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
const findings = reviews.filter(Boolean).flatMap(r => r.findings)
log(`stage4 findings: ${findings.length}`)

phase('Fix')
let fix = null
if (findings.length) {
  fix = await agent(`${COMMON}
TASK (fixer): findings: ${JSON.stringify(findings).slice(0, 60000)}
Re-verify each; fix confirmed ones (regenerate outputs deterministically, re-execute notebooks, regenerate figures, rebuild/register PDFs, update test pins); reject unconfirmed ones with evidence. One line per finding: FIXED/REJECTED(reason).`, { label: 'fix', phase: 'Fix', schema: RESULT })
}

phase('Gate')
const gate = await agent(`${COMMON}
TASK (gate): from a clean build/ run powershell -NoProfile -ExecutionPolicy Bypass -File scripts/verify_stage4_kohn_sham.ps1 and bash scripts/verify_stage4_kohn_sham.sh; both must end with stage4_kohn_sham_verification=OK; then python -m unittest discover -s tests -v (report Stage-4 failures; fix genuine ones minimally). Report.`, { label: 'gate', phase: 'Gate', schema: RESULT })

return { build, integ, nb, docs, findings, fix, gate }
