export const meta = {
  name: 'stage5-theory-numerics',
  description: 'Stage 5: exact theory of dirac16complex00 and of the {+M,-M} pairing (Wolfram + independent sympy), then Kohn-Sham pairs numerics (Rust + reference + checker)',
  phases: [
    { title: 'Exact theory', detail: 'Wolfram packages and verifiers for dirac16complex00 and for the pairing theorems' },
    { title: 'Independent checks', detail: 'sympy/mpmath checkers with agreement against the Wolfram reports' },
    { title: 'Numerics', detail: 'Rust pairs subcommand, reference solver options, pairs checker' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const ART = 'artifacts/dirac16complex/pair-creation'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main; do NOT commit, push, or run git commands that change the index or working tree; the lead commits). Stage 5 of the dirac16complex project. BINDING, read fully first: ${ROOT}/handoff/specs/STAGE5_SPEC.md (the task, the honesty rule, the theorems T1-T4, the deliverables), then ${ROOT}/handoff/specs/CONTRACT.md (with its section 11 errata, especially E2 and E3 on the gamma^8 map and Pin characters), ${ROOT}/handoff/specs/STAGE2_SPEC.md, ${ROOT}/handoff/specs/STAGE4_SPEC.md (sections 1-9; section 8/9 errata override), ${ROOT}/handoff/specs/NUMERICS_CONTRACT.md, ${ROOT}/HANDOFF.md section 4. Existing exact machinery to reuse (read their headers; do not modify them): wolfram/Dirac16ComplexAlgebra.wl, wolfram/Dirac16ComplexGeometry.wl, wolfram/Dirac16ComplexPrimordial.wl, wolfram/Dirac16ComplexKohnSham.wl, scripts/d16c_exact.py, scripts/d16c_geometry_sympy.py, scripts/grassmann_algebra.py, scripts/check_dirac16complex_kohn_sham_theory.py; the exact fixture artifacts/dirac16complex/arbitrary-field/algebra-fixture.json (keys gamma, C, chirality, B, S); the Stage-4 exact export artifacts/dirac16complex/kohn-sham/kohn-sham-theory.json; the Stage-1..4 documents in provenance/ for the established results (quote, do not re-derive by hand without verifying).
Verified by the lead on the exact fixture (numerically): gamma^8 is Hermitian, (gamma^8)^2 = 1, anticommutes with every gamma^a, commutes with C and with every bivector gamma^a gamma^b; C is real symmetric with C^2 = 1; C gamma^a is real antisymmetric; B = -i C gamma^4 is Hermitian with B^2 = 1; gamma^8 B gamma^8 = -B; gamma^8 C gamma^a gamma^8 = -C gamma^a.
STAGE-4 IS PAUSED (suspended processes, uncommitted files of stopped agents): never touch artifacts/dirac16complex/kohn-sham/**, scripts/verify_stage4_*, notebooks/*kohn_sham*, provenance/DIRAC16COMPLEX_KOHN_SHAM_*, studies/dirac16complex_kohn_sham/tools/build_kohn_sham_summary.py, tests/test_d16c_kohn_sham_gate.py, or the Stage-1 files the stopped Stage-1 agent modified (scripts/verify_stage1_*, scripts/build_stage1_summary.py, provenance/DIRAC16COMPLEX_ARBITRARY_FIELD.*, tests/test_d16c_arbitrary_field_*). Never modify dirac-main/, vendor/, or the author's .nb notebook at the repository root.
Tooling facts: WolframScript 1.14 drops arguments after "--" (pass paths positionally); Python 3.14 with numpy, sympy, mpmath (no scipy); cargo/rustc 1.91, the engine in vendor/rustSolveIt (present); Windows 11, Git Bash. Deterministic outputs (LF, json.dumps(indent=2) + newline, sorted where order is not meaningful). Every verifier/checker prints check_<name>=true|false, measurement_<name>=..., check_count, failed_check_count, exits nonzero on failure, and writes a JSON report {schemaVersion, producer, checks, measurements, sourceSha256}. Exact where possible (rational/Gaussian-rational arithmetic, symbolic jets); floats only for numerics, labelled.
HONESTY: never report a check as passing unless computed; if the spec's expectation is wrong, keep the check, record the measured truth, explain it in spec_problems. Never call something proved that is not. Large files: write in chunks of at most 300 lines per tool call. Scratch only under ${SP}/stage5_tmp/<your label>/. Outputs of Stage 5 under ${ROOT}/${ART}/.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, spec_problems: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'spec_problems', 'summary'] }
const brief = r => r ? JSON.stringify({ summary: r.summary, key_results: r.key_results, spec_problems: r.spec_problems, files_changed: r.files_changed, failing: r.failing }).slice(0, 14000) : 'null (the agent failed)'

const wolfram00 = agent(`${COMMON}
TASK (exact theory of dirac16complex00 and of both Lagrangians, Wolfram). Own: wolfram/Dirac16Complex00.wl, scripts/verify_dirac16complex00.wls, ${ART}/wolfram-dirac16complex00-report.json, ${ART}/dirac16complex00-theory.json. Implement and verify exactly STAGE5_SPEC sections 1-3 for the COMMUTING field, side by side with the anticommuting dirac16complex where the statistics matters: (a) the Lagrangian (L1) with the explicit mass term -m sqrt|g| Psibar Psi: reality for commuting components (and the same for Grassmann, citing Stage 1), non-zero and non-trivial mass term (explicit exact configurations with Psibar Psi != 0; for the Grassmann field a nonzero element of the Grassmann algebra; the mass enters the flat-space dispersion k^2 = m^2); (b) the real restriction: for REAL COMMUTING Psi16 the notebook-type Lagrangian Psi^T sigma16 T16^a D_a Psi and the mass term Psi^T sigma16 Psi are non-trivial (not a total divergence, not identically zero), whereas for real Grassmann Psi16 the kinetic term is a divergence and the mass term vanishes (Stage 1) - prove both exactly, and state precisely how the real restriction relates to (L1); (c) non-trivial coupling to the spin connection and gravity (gamma^mu Omega_mu != 0 for explicit exact metric jets; the divergence identity; the Lichnerowicz formula with the exact sign; the Omega-dependent term in the field equation); (d) the Euler-Lagrange equations for commuting components (derive; identical in form to the Grassmann ones); (e) the EMT (vielbein variation), its symmetry, conservation on shell and trace, the current and its conservation, energy density, pressures, KE_L, PE_L, KE_H, PE_H, equations of state, all in an arbitrary field (exact symbolic jets as in Stage 1's Dirac16ComplexGeometry.wl); (f) for the commuting field: the charge density j^4 = Psibar gamma^4 Psi = i Psi^dagger B Psi is indefinite (B has signature (8,8)) and the classical energy is not bounded below (explicit exact plane-wave solutions of both signs in flat (4,4) space and their energy densities); (g) the primordial field: specialise (e) with Dirac16ComplexPrimordial.wl (the Stage-2 cosmological chart) and with the Stage-4 static warped form (reduced equations, the W^{-3} ansatz, the 2x2 blocks from kohn-sham-theory.json), giving rho, p's, w's, KE/PE of the homogeneous/mean-field configurations for both fields. Export every formula and matrix needed downstream to dirac16complex00-theory.json (exact rationals / Gaussian rationals). Run: wolframscript -file scripts/verify_dirac16complex00.wls ${ART}/wolfram-dirac16complex00-report.json (positional). All checks must pass; record every spec discrepancy.`, { label: 'wolfram-00', phase: 'Exact theory', schema: RESULT })

const wolframPair = agent(`${COMMON}
TASK (exact pairing theorems, Wolfram). Own: wolfram/Dirac16ComplexPairing.wl, scripts/verify_dirac16complex_pairing.wls, ${ART}/wolfram-pairing-report.json, ${ART}/pairing-theory.json. Prove exactly STAGE5_SPEC section 5 T1, T2, T3 and section 4's statistics sign, for BOTH fields: T1 (gamma^8 map) at the level of the Lagrangian density, the field equations and the EMT in an arbitrary gravitational field (symbolic vielbein jets as in Stage 1), the current and charge, the Krein metric B -> -B and what that does to expectation values and to the normal-ordered (Grassmann) EMT and Hamiltonian; the pair corollary (T^pair = 0, total charge 0) and its exact hypotheses (lambda -> -lambda; for lambda = 0 the same free field); T2 (a gamma^8 x Pin-reflection map (m, lambda) -> (-m, lambda); find the exact reflection(s) of character -1 that do it, the coordinate action, the EMT relation; connect with the Stage-4 result that Psi(-y) = +-gamma^0 Psi(y) is a symmetry iff the mass function is odd, i.e. the Z2 mirror universe of mass -M); T3 (Kohn-Sham level): using the exact block basis of artifacts/dirac16complex/kohn-sham/kohn-sham-theory.json, derive how the maps act on the 2x2 blocks (which unitary/antiunitary 2x2 map, e.g. sigma1 conjugation; how j, the parity conditions chi_2(0) = 0 / chi_1(0) = 0, the bag angle theta of (1 - Q(theta)) chi(-L) = 0, the densities n, s, t, c, the current matrices and the potentials M_eff, v_v transform), and prove that the KS equations, spectra, occupations, total energies, densities and EMT profiles of the (+M) problem map exactly onto those of the (-M) problem with the transformed boundary conditions, for both statistics (anticommuting exchange e_x = -(lambda/32)(n^2+S^2); commuting e_x^00 = +(lambda/32)(n^2+S^2)) - state exactly which of lambda, theta, parity must transform, and what fails if the -M universe keeps the untransformed boundary conditions; derive the pair totals at the KS level with the expectation rule. Statistics sign: prove on an exact finite-mode model that for a quasi-free (Gaussian) state with one-body density matrix rho, <(Psi^dagger A Psi)(Psi^dagger B Psi)> = Tr(A rho)Tr(B rho) - Tr(A rho B rho) for anticommuting and + for commuting complex fields (exact Fock/Gaussian computation, several rho), hence E_HF with the opposite exchange sign for dirac16complex00, filled shell E_x = +E_H/8, uniform gas e_x^00 = +(lambda/32)(n^2+S^2), v_v^00 = +(lambda/16) n, v_s^00 = +(lambda/16) S, M_eff^00 = m + (17/16) lambda S_p (verify against the Stage-4 derivation with only the sign changed; if the expectation-rule matrices make the statement different, record the exact truth). Export all maps and formulas to pairing-theory.json (exact). Run: wolframscript -file scripts/verify_dirac16complex_pairing.wls ${ART}/wolfram-pairing-report.json (positional).`, { label: 'wolfram-pairing', phase: 'Exact theory', schema: RESULT })

const python00 = wolfram00.then(r => agent(`${COMMON}
The Wolfram agent for dirac16complex00 finished; its report (JSON, truncated): ${brief(r)}
TASK (independent exact checker, sympy/mpmath/stdlib; do NOT import Wolfram outputs as truth). Own: scripts/check_dirac16complex00.py, tests/test_d16c_stage5_dirac16complex00.py, ${ART}/python-dirac16complex00-report.json. Re-derive independently STAGE5_SPEC sections 1-3 for the commuting field and the side-by-side Grassmann statements (use scripts/grassmann_algebra.py for Grassmann computations and d16c_exact.py / d16c_geometry_sympy.py where useful): reality, non-zero non-trivial mass term, the real restriction vs the notebook's Lg[] (commuting non-trivial vs Grassmann trivial), spin-connection coupling on explicit exact metric jets, EL equations, EMT symmetry/conservation/trace, current, KE/PE/rho/p/w, indefinite charge density and unbounded classical energy with explicit solutions, primordial specialisation (warped form and blocks). Add check S5_agreesWithWolfram comparing every exported formula/number of ${ART}/dirac16complex00-theory.json and the Wolfram report with your own (record not-run if absent). Fast unittest subset < 60 s.`, { label: 'python-00', phase: 'Independent checks', schema: RESULT }))

const pairRes = await wolframPair
const pb = brief(pairRes)

const pythonPair = agent(`${COMMON}
The Wolfram pairing agent finished; its report (JSON, truncated): ${pb}
TASK (independent exact checker of the pairing theorems and of the statistics sign, sympy/mpmath/stdlib; do NOT import Wolfram outputs as truth). Own: scripts/check_dirac16complex_pairing.py, tests/test_d16c_stage5_pairing.py, ${ART}/python-pairing-report.json. Re-derive independently T1, T2, T3 and the Wick-sign statement of STAGE5_SPEC (exact finite-mode Fock space for anticommuting fields - reuse the Stage-4 approach of scripts/check_dirac16complex_kohn_sham_theory.py - and exact Gaussian moment computation for commuting complex fields), the uniform-gas e_x for both statistics, the block-level maps and boundary-condition transformations; add check S5_pairingAgreesWithWolfram against ${ART}/pairing-theory.json and the Wolfram report. Fast unittest subset < 60 s.`, { label: 'python-pairing', phase: 'Independent checks', schema: RESULT })

const rustPairs = agent(`${COMMON}
The Wolfram pairing agent finished; its report (JSON, truncated): ${pb}. Read ${ROOT}/${ART}/pairing-theory.json for the exact block-level maps and boundary-condition transformations.
TASK (Rust numerics). Own: the Stage-5 additions to the crate studies/dirac16complex_kohn_sham (new module(s) and a new subcommand "pairs"; minimal additive changes elsewhere), ${ART}/rust/ (outputs), and the crate README section on Stage 5. Implement what the pairs computation needs: negative mass m < 0 (check every place that assumes m > 0: units "m = 1", coupling strengths per m^7, windows, branch classification against the free spectrum, zero-mode localisation e^{My}), the statistics option (dirac16complex: e_x = -(lambda/32)(n^2+S^2), M_eff = m + (15/16) lambda S_p, v_x = -(lambda/16) n_p; dirac16complex00: e_x = +(lambda/32)(n^2+S^2), M_eff = m + (17/16) lambda S_p, v_x = +(lambda/16) n_p - use the formulas as proved in pairing-theory.json), and the transformed boundary conditions of the -M universe (as derived exactly: parity sector and bag angle theta). HARD CONSTRAINT: the Stage-4 subcommands and their outputs must stay BYTE-IDENTICAL: new parameters default to the Stage-4 values and are NOT written into run.json/summary.json when default; prove it by running the Stage-4 subcommand spectrum and "excited --quick" and one scf run of the Stage-4 matrix into scratch and comparing bytes with the committed files under artifacts/dirac16complex/kohn-sham/rust/ (read-only; never write there); cargo fmt --check, clippy -D warnings, test --release must pass (add unit tests: the (+M) -> (-M) block map on the free spectrum; statistics sign; negative-mass free box spectrum vs the analytic one). The pairs subcommand: for both statistics, m in {1, 3} (and their negatives), L = 3, N in {8, 112} (closed shells of the Stage-4 reference; N_mid(m = 3) from the Stage-4 reference), lambda in {0, +-lambda_hat_1, +-lambda_hat_2} (the Stage-4 couplings of each (m, L, N); for dirac16complex00 use the same numerical lambda_hat values), T = 0 and T/m = 0.1 (one N), compute the KS ground state (continuation from lambda = 0 as in solve_ground), the first excited state (KS gap, particle-hole list with the occupation floor, Delta-SCF), EMT averages, for the +M universe, for the -M universe with the TRANSFORMED boundary conditions (and lambda as the theorem requires), and for the -M universe with the UNTRANSFORMED boundary conditions (control); write per-run directories and a pairs summary with the pairing deviations (spectra, E, gap, Delta-SCF, n/S profiles, EMT) and the pair totals (E, charge, EMT averages) as defined in pairing-theory.json. Deterministic output, last line SUCCESS/FAILURE, repeat byte identity and a --refined run into scratch (report the comparison).`, { label: 'rust-pairs', phase: 'Numerics', schema: RESULT })

const refPairs = agent(`${COMMON}
The Wolfram pairing agent finished; its report (JSON, truncated): ${pb}. Read ${ROOT}/${ART}/pairing-theory.json for the exact maps.
TASK (independent reference numerics and the pairs checker). Own: the Stage-5 additions to scripts/ks_reference_solver.py (options for negative mass, statistics sign, transformed boundary conditions; Stage-4 behaviour and outputs unchanged: default values, nothing new written when default; SOLVER_VERSION unchanged unless the Stage-4 numerics change - they must not), a runner scripts/ks_reference_pairs.py writing ${ART}/reference/ (the same run matrix as the Rust pairs subcommand of STAGE5_SPEC T4; the Rust agent is implementing it concurrently in studies/dirac16complex_kohn_sham - align labels with it by reading its code when it exists, else document yours), and the checker scripts/check_dirac16complex_pairs.py -> ${ART}/python-pairs-check-report.json: Rust vs reference agreement per run (tolerances as in scripts/check_dirac16complex_kohn_sham.py, including its measured-grid-uncertainty rule), the pairing identities (spectra, energies, gaps, Delta-SCF, profiles, EMT under the exact map) to solver precision, the untransformed-BC control (must show the documented differences), the pair totals, statistics-sign identities (e.g. lambda = 0 runs identical for both statistics; the lambda-linear energy shifts in the ratio implied by 15/16 vs 17/16 and -1/32 vs +1/32), repeat byte identity and refined convergence of the Rust outputs when directories are given. Verify Stage-4 byte-identity of the reference: rerun two Stage-4 reference runs with --config into scratch and compare with the committed artifacts/dirac16complex/kohn-sham/reference/<label>/ files (read-only). Unit tests tests/test_d16c_stage5_pairs.py (fast). Make the checker robust if the Rust outputs are absent when you finish (record which comparisons ran).`, { label: 'reference-pairs', phase: 'Numerics', schema: RESULT })

const [r00, rPy00, rPyPair, rRust, rRef] = await Promise.all([wolfram00, python00, pythonPair, rustPairs, refPairs])
return { wolfram00: r00, wolframPairing: pairRes, python00: rPy00, pythonPairing: rPyPair, rustPairs: rRust, referencePairs: rRef }
