export const meta = {
  name: 'textbook-wave-a',
  description: 'Textbook wave A: chapters 00-05 and 08-13 of the dirac16complex student textbook, and the assembler',
  phases: [
    { title: 'Chapters', detail: 'seven writers in parallel, each chapter test-built alone' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const CH = 'provenance/textbook/chapters'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main; do NOT commit, push, or run git commands that change the index or working tree). You are writing part of a TEXTBOOK for complete beginners about the dirac16complex project. BINDING, read fully first: ${ROOT}/handoff/specs/TEXTBOOK_SPEC.md (the request, the HONESTY RULE, audience, style, files, chapter plan with sources). Then read the sources named for your chapters completely: the provenance documents (provenance/DIRAC16COMPLEX_ARBITRARY_FIELD.md, DIRAC16COMPLEX_PRIMORDIAL_FIELD.md, DIRAC16COMPLEX_DARK_SECTOR_NUMERICS.md, DIRAC16COMPLEX_STUDENT_GUIDE.md), the specs (handoff/specs/CONTRACT.md with section 11 errata, STAGE2_SPEC.md, STAGE4_SPEC.md with sections 7-9, NUMERICS_CONTRACT.md, STAGE5_SPEC.md), the reports under artifacts/dirac16complex/* (numbers only from them; cite the file), README.md, HANDOFF.md, and the code where a chapter explains a computation. The author's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb is read-only (quote it only through the surveys in handoff/surveys/ or the provenance documents).
RULES: write ONLY your chapter files under ${ROOT}/${CH}/ (and the files explicitly assigned to you); never modify any other file. Other agents are concurrently working on Stage 4 and Stage 5 files - never touch them. Derivations complete and correct, every step; worked examples with small numbers; exercises with full answers at the end of each chapter; a "What we proved / what we assumed" paragraph per chapter; beginners' language; define every notion before use; counting from 0, x4 is time, eta = diag(+1,+1,+1,+1,-1,-1,-1,-1). Markdown subset of scripts/build_dissertation_tex.py (read its header): chapter heading "## N. Title", sections "### N.M Title", no deeper headings; $...$ and $$...$$; tables with equal cell counts; fenced code lines at most 89 characters, no tabs; figures only as a line ![caption](path.png) with an existing PNG path relative to the repository root. Test-build each chapter alone: copy it into ${SP}/textbook_tmp/<your label>/ with a first line "# Test" and run python scripts/build_provenance_pdf.py <that md> --developer-layout --repository-root ${ROOT} (verify mode, never --register) until the log is warning-free; if that script refuses a path outside provenance/, read its header and test the way it allows (e.g. a temporary copy under ${ROOT}/build/, which is git-ignored). Write large files in chunks of at most 300 lines per tool call. HONESTY: numbers only from committed reports; never write "proved" for anything not proved; label assumptions and hypotheses.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, chapters: { type: 'array', items: { type: 'object', properties: { file: { type: 'string' }, title: { type: 'string' }, sections: { type: 'array', items: { type: 'string' } }, approx_pages: { type: 'number' }, test_build_warning_free: { type: 'boolean' } }, required: ['file', 'title', 'sections', 'approx_pages', 'test_build_warning_free'] } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'chapters', 'open_items', 'summary'] }

phase('Chapters')
const tasks = [
  ['editor', `Chapters 00 (How to read this book; a DRAFT honesty ledger table: statement / status PROVED, COMPUTED, ASSUMED, HYPOTHESIS, OPEN / where verified; mark the Stage-5 rows "to be completed after Stage 5") and 01 (Mathematical toolkit from zero) -> ${CH}/00-how-to-read.md, ${CH}/01-mathematical-toolkit.md. ALSO own scripts/build_textbook.py (the assembler of TEXTBOOK_SPEC section 2: title block "# dirac16complex: a textbook for students", subtitle, abstract, then every ${CH}/NN-*.md in order into provenance/DIRAC16COMPLEX_TEXTBOOK.md; deterministic LF; checks that chapter numbers are consecutive, that every "Chapter N" and "Section N.M" reference resolves, that no section number repeats; --check mode that only validates; it must work with the chapters that exist so far and report the missing ones) and tests/test_d16c_textbook_assembler.py (fast unit tests of the assembler on synthetic chapters).`],
  ['clifford', `Chapters 02 (Clifford algebras and spinors from zero, up to the Pin(4,4)/Spin(4,4) representation theorem with its proof) and 03 (split octonions, the tau matrices, the Clifford and octonion pictures, the intertwiners) -> ${CH}/02-clifford-algebras-and-spinors.md, ${CH}/03-split-octonions.md.`],
  ['geometry', `Chapter 04 (Curved space from zero: manifolds and coordinates, metric, Christoffel symbols, geodesics in one worked example, curvature, Einstein and Einstein-Lovelock equations, vielbeins, the spin connection, the vielbein postulate, the spinor covariant derivative, why the notebook's contraction is wrong) -> ${CH}/04-curved-space.md.`],
  ['fieldtheory', `Chapters 05 (Classical field theory from zero; Grassmann numbers from zero; the triviality of the author's Lg[] for real Grassmann fields, with the proof) and 08 (Canonical quantization in 4+4: Hamiltonian form, anticommutators, Fock and Krein spaces, the good sector, the unstable extra-time modes) -> ${CH}/05-classical-field-theory.md, ${CH}/08-quantization.md.`],
  ['primordial', `Chapters 09 (The primordial gravitational field of the notebook, the Einstein-Lovelock equations and the required source, the notebook errata, the static warped form and the Z2 brane) and 10 (Solving differential equations on a computer from zero: ODEs, stiffness, BDF and CVODE, tolerances, reproducibility, independent checkers) -> ${CH}/09-primordial-field.md, ${CH}/10-numerical-ode.md.`],
  ['darksector', `Chapter 11 (The five dark-sector experiments EXP-1..EXP-5: set-up, equations, results with figures from artifacts/dirac16complex/numerics/figures/, and exactly what they show and do not show about dark matter and dark energy) -> ${CH}/11-dark-sector-experiments.md.`],
  ['dft', `Chapters 12 (Many-body quantum mechanics and DFT from zero: many-fermion wave functions, Slater determinants, Hartree and Hartree-Fock, Hohenberg-Kohn, Kohn-Sham, LDA, Mermin's finite-temperature functional, Delta-SCF, the Kohn-Sham gap) and 13 (The Kohn-Sham approximation for dirac16complex in the primordial field, from the reduction to 2x2 blocks to the ground and first excited states, thermodynamics and the Einstein source; use the committed Rust outputs under artifacts/dirac16complex/kohn-sham/rust/ and the exact theory reports; state honestly that the Stage-4 cross-check and gate were still being completed and cite the numbers as computed by the Rust solver with its own checks; figures only from existing PNGs) -> ${CH}/12-density-functional-theory.md, ${CH}/13-kohn-sham-primordial.md.`],
]
const results = await parallel(tasks.map(([label, task]) => () => agent(`${COMMON}
TASK (${label}): ${task}`, { label: 'chapter:' + label, phase: 'Chapters', schema: RESULT })))
return results
