export const meta = {
  name: 'textbook-wave-b-chapters',
  description: 'Textbook wave B: chapters 06, 07, 14, 15, 16, 17, 18, 19, 20, each written, adversarially reviewed (correctness + honesty + pedagogy) and fixed',
  phases: [
    { title: 'Write', detail: 'one writer per chapter (06+07 together)' },
    { title: 'Review', detail: 'one adversarial reviewer per chapter' },
    { title: 'Fix', detail: 'one fixer per chapter, test build warning-free' },
  ],
}

const ROOT = 'C:/Users/nsh/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/C--Users-nsh-Developer-github-Dirac-claude/cc75e05b-1dc1-4a82-a1dd-e65cb8479099/scratchpad'
const CH = 'provenance/textbook/chapters'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; read-only git is fine. You write part of a TEXTBOOK for complete beginners (school algebra and one-variable calculus only) about the dirac16complex project. BINDING, read fully first: ${ROOT}/handoff/specs/TEXTBOOK_SPEC.md (the request; the HONESTY RULE of section 0, which overrides everything; audience and style of section 1; the Markdown subset and build of section 2; the chapter plan of section 3). Read ALL existing chapters in ${ROOT}/${CH}/ (00-05, 08-13; they are being corrected in parallel by another workflow, so re-read the parts you rely on just before you finish) to match notation, conventions, cross-references and style: counting from 0, x4 the time, eta = diag(+1,+1,+1,+1,-1,-1,-1,-1), the notebook's gammas, C = gamma^0 gamma^1 gamma^2 gamma^3, gamma^8, B = -i C gamma^4, the Hermitian current J^mu = -i Psibar gamma^mu Psi with J^4 = Psi^dag B Psi, S = Psibar Psi, exercises "Exercise N.M" with answers "Answer N.M", "What we proved and what we assumed" section, chapter heading "## N. Title", sections "### N.M Title", nothing deeper, figures only as a line ![caption](existing/path.png) relative to the repository root.
SOURCES (read what your chapter needs, fully, in chunks of at most 300 lines per tool call): ${ROOT}/handoff/specs/STAGE5_SPEC.md, STAGE5_DOC_OUTLINE.md, MATTER_ANTIMATTER_SPEC.md, STAGE4_SPEC.md (sections 8 and 9, errata E4.1-E4.13), CONTRACT.md; the Stage-5 exact reports and theory files artifacts/dirac16complex/pair-creation/{wolfram-dirac16complex00-report.json, python-dirac16complex00-report.json, dirac16complex00-theory.json, wolfram-pairing-report.json, python-pairing-report.json, pairing-theory.json} and whatever Stage-5 numerical outputs exist under artifacts/dirac16complex/pair-creation/rust/ and reference/ (they may be INCOMPLETE: use only what is committed and complete, say exactly what is and is not computed); the packages wolfram/Dirac16Complex00.wl, wolfram/Dirac16ComplexPairing.wl and the checkers scripts/check_dirac16complex00.py, scripts/check_dirac16complex_pairing.py; the matter-antimatter analysis provenance/DIRAC16COMPLEX_MATTER_ANTIMATTER.md with artifacts/dirac16complex/matter-antimatter/*.json; the project documents provenance/DIRAC16COMPLEX_ARBITRARY_FIELD.md, DIRAC16COMPLEX_PRIMORDIAL_FIELD.md, DIRAC16COMPLEX_DARK_SECTOR_NUMERICS.md, DIRAC16COMPLEX_STUDENT_GUIDE.md, DIRAC16COMPLEX_KOHN_SHAM_PRIMORDIAL.md (if present); README.md, HANDOFF.md; the lead's verified notes ${SP}/stage5_lead_notes.md (gamma^8 facts, the T1/T2/T3 block-level analysis, the Wick sign of the statistics, the M2 charge-conjugation classification: only Psi -> e^{ia} Psi^* and e^{ia} gamma^8 Psi^*; commuting field exactly C-invariant; Grassmann field: exact CP, no exact C for m != 0; M3 invariant forms span{C P_-, C P_+}, all symmetric) and ${SP}/textbook_lead_review.md.
STATE OF THE PROJECT to state honestly where relevant: Stages 1-3 complete and verified by their gates from fresh public clones. Stage 4: exact theory 125/125 (Wolfram) and 157/157 (sympy); Rust solver complete (own checks spectrum 33, scf 137, excited 65, thermo 102, emt 60; repeat byte-identical, refined 5.96e-8); independent reference 56 runs; the final cross-checker artifacts/dirac16complex/kohn-sham/python-check-report.json gives 63 checks with 1 failed (canonical_eigenvalues: one deep state of the 301-point smeared N = 1016, -lambda_hat_2 run differs from the reference by 2.2e-6 against a tolerance of 1.05e-6; the Delta-SCF of that run now agrees after erratum E4.13); the Stage-4 gate has not been run. Stage 5: exact theory reports as committed (read their check counts); Kohn-Sham pair numerics partial (read what exists); the Stage-5 documents are not written. The matter-antimatter analysis: provenance/DIRAC16COMPLEX_MATTER_ANTIMATTER.md (read its final state; its reviewers found that the Fock-level (Krein) mapping rests on Stage-5 files and that the pair-cancellation reading has sign subtleties - follow the document's corrected text, and where it is still unsettled say OPEN).
HONESTY (TEXTBOOK_SPEC section 0, to the letter): the book must NOT state that the big bang creates universes in pairs, nor that the theory solves the matter-antimatter problem. It teaches the exact pairing theorems with their hypotheses, what they make consistent, and what is not derived (no creation process, rate or amplitude; no baryons, no baryon-number violation; for each field an exact charge-reversing symmetry, so Sakharov's second condition fails; exact U(1), so the first fails; no departure-from-equilibrium computation). Numbers only from committed files (name the file). Every derivation complete, step by step, for a beginner; worked examples with small numbers; exercises with complete answers.
FILES: write ONLY your assigned chapter file(s). Test-build each chapter alone from a copy under the git-ignored ${ROOT}/build/textbook_b/<label>/ whose first two lines are "# Test" and "## Test build", with: python scripts/build_provenance_pdf.py build/textbook_b/<label>/<file>.md --developer-layout --number-sections-from-zero (verify mode; only the registry checks may fail; the log must be warning-free). Scratch under ${SP}/textbook_b/<label>/.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, sections: { type: 'array', items: { type: 'string' } }, test_build_warning_free: { type: 'boolean' }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'sections', 'test_build_warning_free', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

const TASKS = [
  { label: 'fields', files: ['06-two-fields-and-lagrangians.md', '07-field-equations-and-emt.md'], task: `Chapter 6 "The two fields and their Lagrangians" (dirac16complex: second-quantized, complex Grassmann components; dirac16complex00: the classical commuting 16-component Pin(4,4) spinor, the analogue of Dirac's 1928 wave function; the Lagrangian of each with the coupling to gravity through the vielbein and the spin connection and with an explicit mass term linear in m and quadratic in the spinor; reality/Hermiticity; why the notebook's Lg[] is trivial for real Grassmann fields but not for commuting ones; the interaction U(S); the gamma^8 map of the Lagrangians) and Chapter 7 "Field equations, energy-momentum tensor and equations of state" (Euler-Lagrange equations of both fields in an arbitrary gravitational field, derived step by step; the energy-momentum tensor, its symmetry and conservation; kinetic and potential energy, energy density, pressures and equations of state; the homogeneous and the primordial specialisations; all as verified in the Stage-1 and Stage-5 reports, naming the checks).` },
  { label: 'dft00', files: ['14-kohn-sham-dirac16complex00.md'], task: `Chapter 14 "The Kohn-Sham approximation for dirac16complex00" (why a Kohn-Sham model of a commuting classical field needs a statement of what is being averaged; the Wick/Isserlis sign of the statistics derived from zero with a two-mode example: commuting Gaussian +Tr(A rho B rho), fermionic -; the exchange energy e_x^00 = +(lambda/32)(n^2 + S^2), M_eff^00 = m + (17/16) lambda S_p, v^00 = +(lambda/16) n, as verified in the Stage-5 reports; the status of the model; the ground and first excited states of both fields side by side where computed - otherwise say what is not computed).` },
  { label: 'pairs', files: ['15-pairing-theorems.md'], task: `Chapter 15 "The pairing theorems" (T1: L_{m,lambda}[gamma^8 Psi] = -L_{-m,-lambda}[Psi], T -> -T, J -> -J, the pair has zero total energy-momentum and charge in any gravitational field - classical bilinears; T2: gamma^8 combined with a Pin(4,4) reflection of character -1 gives (m, lambda) -> (-m, lambda) with L -> +L, the mirror map across the Z2 brane; T3: the Kohn-Sham level: the block map sigma_2 between blocks j and -j, sigma_2 h_j(M, v) sigma_2 = h_{-j}(-M, v), the boundary conditions (parity flips, the tip condition g0 <-> f0, the bag angle theta -> pi - theta), the expectation-value rule s = chi^dag (j sigma_2) chi flipping while n stays, hence the Kohn-Sham pairing (m, lambda) -> (-m, +lambda) with equal energies and energy-momentum; explain clearly why the field-level map (T1: opposite energy, lambda -> -lambda) and the Kohn-Sham map (T3: equal energy, same lambda) differ - classical bilinears versus the quantum expectation-value rule of Chapter 8; complete proofs for both fields, every hypothesis stated; the numerical Kohn-Sham demonstration with tables (and figures if committed) from the Stage-5 outputs, or an exact statement of what is not yet computed).` },
  { label: 'bigbang', files: ['16-pairs-of-universes.md'], task: `Chapter 16 "Does the big bang create universes in pairs?" (quote the notebook's hypothesis, cells 6, 7 and 17, through handoff/surveys/survey_notebook-physics.md, and Stage 1's sentence that the pairing is "a structural property of the equations, not a claim that universes of masses +-M are created in pairs"; state exactly what is PROVED (the pairing theorems of Chapter 15 and their corollaries), what is CONSISTENT (creation of a gamma^8 pair violates no conservation law; note that a pair with zero total energy-momentum is consistent only with a source-free gravitational field in the Einstein equations, while the static primordial field needs a nonzero source - discuss both readings honestly), and what is NOT DERIVED (no creation process, no rate, no amplitude, no wave function of the universe, no dynamical big bang); explain from zero what a calculation of pair creation would require (a quantum amplitude or a classical solution of the coupled equations), with the photon pair-creation analogy stated correctly (a photon needs a nucleus to take up momentum); every statement labelled PROVED / COMPUTED / ASSUMED / HYPOTHESIS / OPEN).` },
  { label: 'antimatter', files: ['17-matter-and-antimatter.md'], task: `Chapter 17 "Matter and antimatter" (the observed asymmetry from zero: what antimatter is, the absence of antimatter domains, the baryon-to-photon ratio eta ~ 6e-10 with the literature citation (Planck 2018 cosmological parameters, Astron. Astrophys. 641, A6 (2020), for Omega_b h^2, with the conversion to eta explained or cited); the Sakharov conditions (A. D. Sakharov, JETP Lett. 5, 24 (1967)) derived in plain words; why the Standard Model's CP violation is insufficient (literature consensus, cited); the universe/anti-universe class of ideas with L. Boyle, K. Finn, N. Turok, Phys. Rev. Lett. 121, 251301 (2018), described without claiming anything it does not say; then the exact analysis of this theory, agreeing with provenance/DIRAC16COMPLEX_MATTER_ANTIMATTER.md in every statement: M1 exact U(1) and charge conservation (with its boundary hypothesis), M2 the discrete symmetries (commuting field: exact C; Grassmann field: exact CP, no exact C for m != 0; the (4,4) subtlety that a rotation in Spin(4,4) reverses x4 and Q), M3 the allowed charge-violating terms (no Majorana mass for the Grassmann field; what exists), M4 the gamma^8 pair with opposite charge (field level; the Fock-level statement only as the document states it), M5 the labelled conditional scenario H1-H3 with its exact implication and the statement that eta is NOT predicted, M6 the Sakharov scorecard as a table; the conclusion stated plainly: the theory as built does not solve the matter-antimatter problem, and what would have to be added).` },
  { label: 'open', files: ['18-open-problems.md'], task: `Chapter 18 "Open problems and how a student could attack them" (every OPEN item of the book and of the project documents: an interacting quantum field theory and renormalisation; the extra-time instability and the (4,4) signature versus the observed world; what determines a4 and whether Einstein-Lovelock gravity with an acceptable source produces the primordial field; the Kohn-Sham sourcing question; the Stage-4 eigenvalue discrepancy and gate; the Stage-5 numerics; a creation amplitude for pairs of universes; baryogenesis in this framework; for each: why it is hard, what is known, a concrete first step a student could take, which files and tools of the repository to start from).` },
  { label: 'back', files: ['19-reproducing-everything.md', '20-glossary-and-check-index.md'], task: `Appendix 19 "Reproducing everything" (every command in PowerShell and in Bash, from a fresh clone: setup (Python packages, pdflatex, WolframScript, Rust, scripts/setup_solver), each stage's gate with its final OK line, expected outputs and measured wall times as recorded in README.md, HANDOFF.md and the gate headers, the Stage-4 and Stage-5 status stated honestly, the textbook's own build: python scripts/build_textbook.py then python scripts/build_provenance_pdf.py provenance/DIRAC16COMPLEX_TEXTBOOK.md --developer-layout --number-sections-from-zero) and Appendix 20 "Glossary and index of verifier checks" (every technical term of the book with a one- or two-sentence definition and the chapter where it is introduced - collect the terms from ALL chapters 00-18; an index of every check name cited anywhere in the book with its report file and the chapters citing it - verify each name exists in that report). Commands must be tested where they finish within about 5 minutes.` },
]

const results = await pipeline(
  TASKS,
  (t) => agent(`${COMMON}\nTASK (writer, ${t.label}): ${t.task}\nFiles: ${t.files.map(f => CH + '/' + f).join(', ')}.`, { label: 'write:' + t.label, phase: 'Write', schema: RESULT }),
  (w, t) => agent(`${COMMON}\nTASK (adversarial reviewer of ${t.files.map(f => CH + '/' + f).join(' and ')}; do not edit any file). Report only real problems with concrete evidence. Lenses: (1) CORRECTNESS - re-derive every derivation yourself (small sympy/numpy scripts in scratch), recompute every example, open every cited report and compare every number and check name; (2) HONESTY - anything called proved that is not, every hypothesis labelled, TEXTBOOK_SPEC section 0 followed to the letter, agreement with provenance/DIRAC16COMPLEX_MATTER_ANTIMATTER.md and the Stage-5 reports; (3) PEDAGOGY - every notion defined before use (here or in an earlier chapter), no skipped step, every exercise with a complete correct answer; (4) FORMAT - the Markdown subset, and one test build (see CONTEXT). Writer's report (truncated): ${JSON.stringify(w).slice(0, 4000)}`, { label: 'review:' + t.label, phase: 'Review', schema: FINDINGS }),
  (rv, t) => {
    const fs = (rv && rv.findings) || []
    if (!fs.length) return { label: t.label, fixed: [], note: 'no findings' }
    return agent(`${COMMON}\nTASK (fixer of ${t.files.map(f => CH + '/' + f).join(' and ')} ONLY). Re-verify each finding below; fix every confirmed one at its root (update the chapter's exercises, answers and "What we proved and what we assumed" section where they repeat a changed statement); reject unconfirmed ones with a reason. Then test-build until warning-free. One line per finding in key_results: FIXED / REJECTED (reason).\nFINDINGS (JSON): ${JSON.stringify(fs).slice(0, 80000)}`, { label: 'fix:' + t.label, phase: 'Fix', schema: { type: 'object', properties: { key_results: { type: 'array', items: { type: 'string' } }, test_build_warning_free: { type: 'boolean' }, summary: { type: 'string' } }, required: ['key_results', 'test_build_warning_free', 'summary'] } }).then(r => ({ label: t.label, findings: fs.length, ...(r || {}) }))
  },
)
return results
