export const meta = {
  name: 'dirac-matrices-audit-fix',
  description: 'Continuation of the dirac-matrices audit after the session limit: one fixer applies all 23 skeptic-confirmed findings (finishing the interrupted fixer\'s partial edits), then a fresh-clone verifier',
  phases: [
    { title: 'Fix', detail: 'one owner of the dirac-matrices files' },
    { title: 'Verify', detail: 'fresh clone, literal instructions, every claim' },
  ],
}
const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const NB = 'Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb'
const COMMON = `
NEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate or accept an EULA); if a step needs that, stop that step and report it as an open item.
CONTEXT: repository ${ROOT} (git, branch main; remote https://github.com/once-ere/Dirac_claude.git). NEVER run git commands that change the index, the working tree's history or the remote (read-only git, and git clone into a scratch folder under ${SP}, are fine). The AUTHOR's notebook ${ROOT}/${NB} is READ ONLY (wolframscript may Import it). Other workflows run concurrently and own Revision/textbook/, provenance/wolframscript/, the WOLFRAMSCRIPT_PROVENANCE.md / *.PROVENANCE.md files of the execution-provenance sets, notebooks/*.PROVENANCE.md, Revision/kohn_sham, Revision/theory, Revision/docs: never edit those.
THE USER'S ORDER (verbatim): "Verify that you have followed your instructions [Read, clearly understand and remember ${NB}], and are using eight, real-valued, 16 by 16, dirac matrices in these calculations; do this by creating a new provenance file named 'dirac matrices.md' (and add this file to repo) that explicitly proves they are real, satisfy correct anti-commutation relations; prove scaled commutators generate Pin(4,4); also display each of the eight, real-valued, 16 by 16, dirac matrices, along with their products and relevant projection matrices. If you failed to follow your instructions then explain and the QUIT."
FILES: ${ROOT}/provenance/dirac matrices.md (GENERATED; never hand-edit - change the generator and regenerate), ${ROOT}/provenance/dirac_matrices/extract_from_author_notebook.wls, ${ROOT}/provenance/dirac_matrices/author_notebook_T16.json, ${ROOT}/provenance/dirac_matrices/build_dirac_matrices_md.py, ${ROOT}/tests/test_dirac_matrices_provenance.py. Conventions: Revision/SPEC.md (x1..x8; eta = diag(+,+,+,-,-,-,-,+) in x1..x8; notebook frame index 0 = x8, 1-3 = x1-x3, 4 = x4, 5-7 = x5-x7). Honesty: record measured truth; never weaken a check to make it pass; never overclaim.
LEAD CONTEXT (2026-10-07): (a) the Revision a4 engine Revision/field_equations_a4/wolfram/FieldEquationsA4.wl and its Python twin currently use their OWN equivalent Cl(1,1)^(x)4 bases, not the author's T16 (a departure from SPEC section 2); a verified patch switching them to the author's T16 from gammas.json is being prepared and will be applied soon. The generated file must state the MEASURED current truth by COMPUTING it at build time (load/construct each gamma source and compare), so that after the patch a plain regeneration records the new truth without hand edits. (b) The answer to the user's question about following the instructions must be explicit and honest: every calculation uses eight real 16x16 Cl(4,4) matrices; all except the a4 engine (until patched) use the author's own T16; the a4 engine uses an equivalent basis (state the intertwiner check). (c) The consumer listing must not make --check fail when unrelated files change: base it on git ls-files at a stated scope or move it out of the checked text, and say how it is produced.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

phase('Fix')
const fix = await agent(`${COMMON}\nTASK (fixer): You own the FILES above. The 23 findings of the adversarial audit, each confirmed by at least one of two independent skeptics, are in ${SP}/audit_confirmed.json (fields lens, severity, file, location, problem, evidence, fix, votes): read ALL of it. IMPORTANT: an earlier fixer was interrupted by a session limit in the middle of this task; its partial edits are in the working tree (build_dirac_matrices_md.py was rewritten by about 1000 lines and the .md regenerated or partly regenerated, both committed as WIP snapshots). Inspect them with git diff fdba6bb -- provenance/dirac_matrices "provenance/dirac matrices.md" tests/test_dirac_matrices_provenance.py, keep what is correct, finish what is missing, fix what is wrong. Address EVERY finding at the root (one line per finding in key_results: FIXED / REJECTED (reason with evidence)): the 'scaled commutators' naming (S^AB only); exact statements and lemmas for the Pin(4,4) argument (block determinants nonzero on O(4,4), kernel exactly {+-I16}, four components, transitivity), stated as proved vs cited; a genuine irreducibility computation or merge; the bilinears (Psi^T sigma16 Psi vanishes for Grassmann Psi; Psibar Psi = Psi^dagger C Psi invariant because S^AB is real); B = -i C gamma^(x4) and the projectors (I +- B)/2, (I +- sigma16)/2 displayed with exact checks; comparisons with EVERY gamma source in the repository (gammas.json incl. its B and S fields, python-gammas.json, RevisionAlgebra.wl, check_pairing author_T16, the a4 engine's FEGammaFrame and own_rep with the intertwiner check, algebra-fixture.json incl. its comparison-only gammaClifford/gammaOctonion fields named as such, the Rust generated.rs constants in both studies crates, the six old Wolfram packages via wolframscript in the extraction step, the old Python constructions, the Revision Rust solver's reading of gammas.json); how T16A enters the author's own Lagrangian (curved T16^alpha = sum e_A^alpha T16A[A], cells and labels); the author's cell order 285/286 and the Notation/Symbolize setup documented; LF output for the JSON on every OS; byte-exact --check (read bytes); no crash on wrong matrices (report FAIL lines); the robust consumer listing; complete Windows/macOS/Linux instructions (python vs python3, sympy install incl. PEP 668 venv, wolframscript activation as a user step, the test command); measured run times and side effects (incl. bytecode caches); tool versions recorded. Never weaken a check. Then run the .wls and the builder, --check, and python -m unittest discover -s tests -p "test_dirac_matrices_provenance.py" -v (update the test to the new truth), and run the builder twice to confirm byte identity.`, { label: 'fix', phase: 'Fix', schema: RESULT })

phase('Verify')
const verify = await agent(`${COMMON}\nTASK (final verifier; do NOT edit repository files): The fixer reported (JSON): ${JSON.stringify(fix).slice(0, 30000)}\nThe confirmed findings are in ${SP}/audit_confirmed.json. Copy the CURRENT working-tree FILES into a NEW fresh clone under ${SP}/audit_verify_clone and follow the generated file's instructions LITERALLY (both commands, --check, the test); confirm byte identity of the regenerated .md and JSON with the working tree; check every FIXED claim against the files and every finding's fix; independently re-check that the eight matrices are real and satisfy the anticommutation relations, that the Pin(4,4) section claims exactly what is proved, and that the answer about following the instructions is explicit and true (including the a4 engine's basis as measured now). Report anything still wrong as findings; list what you verified in verified_ok.`, { label: 'verify', phase: 'Verify', schema: FINDINGS })
return { fix, verify }
