export const meta = {
  name: 'dirac-matrices-audit',
  description: 'Adversarial audit of provenance/dirac matrices.md: notebook fidelity, mathematics (Cl(4,4), Pin(4,4)), coverage of every calculation in the repository, reproducibility; skeptics per finding; fix; verify',
  phases: [
    { title: 'Review', detail: 'four independent lenses, read-only' },
    { title: 'Skeptics', detail: 'two refuters per finding' },
    { title: 'Fix', detail: 'one owner of the dirac-matrices files fixes confirmed findings' },
    { title: 'Verify', detail: 'fresh-clone verification of the fixes and the final file' },
  ],
}

const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const NB = 'Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb'

const COMMON = `
CONTEXT: repository ${ROOT} (git, branch main; remote https://github.com/once-ere/Dirac_claude.git). NEVER run git commands that change the index, the working tree's history or the remote (read-only git, and git clone into a scratch folder under ${SP}, are fine). The AUTHOR's notebook ${ROOT}/${NB} is READ ONLY - never modify it (wolframscript may Import it). Other workflows are running concurrently and own Revision/textbook/, provenance/wolframscript/, the *PROVENANCE.md files of the wolframscript sets, notebooks/*.PROVENANCE.md, provenance/EXECUTION_PROVENANCE_INDEX.md and tests/test_execution_provenance.py: never edit those.
THE USER'S ORDER (verbatim): "Verify that you have followed your instructions [Read, clearly understand and remember ${NB}], and are using eight, real-valued, 16 by 16, dirac matrices in these calculations; do this by creating a new provenance file named 'dirac matrices.md' (and add this file to repo) that explicitly proves they are real, satisfy correct anti-commutation relations; prove scaled commutators generate Pin(4,4); also display each of the eight, real-valued, 16 by 16, dirac matrices, along with their products and relevant projection matrices. If you failed to follow your instructions then explain and the QUIT."
THE FILES UNDER AUDIT: ${ROOT}/provenance/dirac matrices.md (generated; never hand-edit - change the generator and regenerate), ${ROOT}/provenance/dirac_matrices/extract_from_author_notebook.wls (evaluates the author's own input cells of the notebook in a fresh kernel, writes author_notebook_T16.json), ${ROOT}/provenance/dirac_matrices/build_dirac_matrices_md.py (35 exact checks, writes the .md; --check mode compares without writing), ${ROOT}/tests/test_dirac_matrices_provenance.py. Binding conventions: Revision/SPEC.md (author's coordinates x1..x8: x4 time, x5 x6 x7 the three EXTRA TIMES that deflate exponentially, x8 hidden; eta = diag(+,+,+,-,-,-,-,+) in x1..x8; notebook frame index 0 = x8, 1-3 = x1-x3, 4 = x4, 5-7 = x5-x7). Honesty: record measured truth; never weaken a check to make it pass; never overclaim (e.g. the scaled commutators alone generate only the identity component Spin_0(4,4) - the file says so).
wolframscript: "/c/Program Files/Wolfram Research/WolframScript/wolframscript" (Bash) ; python with sympy is installed.
`
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const VERDICT = { type: 'object', properties: { refuted: { type: 'boolean' }, reason: { type: 'string' }, evidence: { type: 'string' } }, required: ['refuted', 'reason', 'evidence'] }
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }

const LENSES = [
  ['notebook-fidelity', `Is the extraction faithful to the AUTHOR's notebook? (1) Use wolframscript to Import the notebook and list EVERY Input cell that assigns tau, OverBar[tau], T16^A / T16A, T16^alpha, sigma16, eta4488, s4by4, t4by4, Qa, Qb, P_L, P_R (also SetDelayed, Do/Table assignments): are any of them REDEFINED later in the notebook (e.g. the cell defining (T16^alpha)[8], or later cells redefining tau or the gammas in another basis)? Which definitions does the author's Lagrangian Lg[] and the field equations actually use? (2) The evaluation order: the notebook lists the sigma16 cell (285) before the T16A cell (286); the extractor evaluates 286 first - is that what the author's evaluation order (In[n] labels, CellLabel) was? (3) Compare the extracted matrices with the author's STORED Output cells (Out[...] displays of tau, T16A, sigma16, T16A[8], P_L, P_R where the notebook stores them) entry by entry. (4) Is the SuperscriptBox["T16","A"] -> T16A substitution the only change, and is it semantically neutral (check how the notebook's front end treated T16^A: Notation package / Symbolize, or InputAliases)? Report every discrepancy with the cell index, CellLabel and text.`],
  ['mathematics', `Try to REFUTE the mathematics independently, with your own code (do not import the builder): (1) reality and {Gamma_A, Gamma_B} = 2 eta_AB I16 for the matrices in author_notebook_T16.json; (2) the 256 products form a basis of M16(R); (3) S^AB = (1/4)[Gamma_A, Gamma_B] satisfy the so(4,4) relations with the sign convention stated; the action on the Gammas; the isomorphism spin(4,4) -> so(4,4); (4) the closed-form exponentials, the claim exp(theta S^AB) = Gamma_A Gamma(u) with the stated unit vector u (check all 28 generators, both signs of eta), the double cover; (5) the Pin(4,4) argument in the section "Why the scaled commutators generate Pin(4,4)": the definition of Pin(4,4) used, the four components and the (det, space-block, time-block) sign test (is the space-block determinant really nonzero on O(4,4) and constant on components?), transitivity of SO_0(4,4) on the quadrics eta(v,v) = +1 and -1 in R^(4,4) (connectedness), the claim that the group generated by exp(S^AB), Gamma_0 and Gamma_4 is all of Pin(4,4); the twisted-adjoint sign convention; (6) every statement of the "Answer in one paragraph" and the check table: is anything stated that is not proved, or proved but stated wrongly? (7) Is anything the user asked for missing (e.g. a proof that the commutators generate Pin(4,4) stated too weakly or too strongly; products or projection matrices that are "relevant" but not displayed, such as the chiral projectors in the author's own frame, the sigma16-related or B-related projectors used by the Revision record - check Revision/docs and Revision/SPEC.md for the projectors the calculations use).`],
  ['coverage', `"are using eight real-valued 16 x 16 Dirac matrices IN THESE CALCULATIONS": find EVERY place in the repository where gamma / Dirac / Clifford matrices are defined, hard-coded, constructed or loaded - Python (scripts/, Revision/, notebooks/, Revision/textbook/notebooks/src/, tests/), Wolfram (.wl, .wls, and project .nb notebooks under notebooks/), Rust (every Cargo crate: grep for 16x16 arrays, gamma, clifford, sigma16, T16), JSON fixtures, C/C++ if any. For each source: is it the author's eight real 16 x 16 matrices (same entries, with the documented coordinate map), or something else (complex matrices, 4 x 4 matrices, a different basis, a different ordering or sign, a different metric signature)? Run small comparisons where needed (load the fixture or construct the matrices and compare with provenance/dirac_matrices/author_notebook_T16.json). The file's section "Calculations that use these matrices" lists only files that contain the string gammas.json in .py/.wl/.wls - report every calculation that uses gamma matrices from another source and is NOT covered by the file's checks, with whether its matrices are equal.`],
  ['reproducibility', `Follow the "How to reproduce" section of provenance/dirac matrices.md LITERALLY in a NEW fresh clone under ${SP} (git clone https://github.com/once-ere/Dirac_claude.git): do the commands work exactly as written (including the file name with a space); is the printed output exactly as stated; are the run times and side effects as stated (list every file created or changed: git status in the clone); does the regenerated .md equal the committed one byte for byte; does the .wls reproduce author_notebook_T16.json byte for byte (line endings!); does the test pass. Check every displayed matrix in the .md against author_notebook_T16.json entry by entry (parse the code blocks), the 256 one-line products against products you compute, P_L and P_R. Check the Markdown is readable (headings, tables not broken by '|' in cells, code blocks closed) and that nothing in the text contradicts the checks. Check the instructions are complete for a student on Windows, macOS and Linux (wolframscript activation, python and sympy install).`],
]

phase('Review')
const judged = await pipeline(
  LENSES,
  ([k, t]) => agent(`${COMMON}\nTASK (adversarial reviewer, lens ${k}; do NOT edit any repository file; scratch work only under ${SP}/audit_${k}): ${t}\nReport only real problems with concrete evidence (commands and their output); list what you verified as correct in verified_ok.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS }),
  (rev, [k]) => parallel(((rev && rev.findings) || []).map((f, i) => () =>
    parallel(['re-derive or re-run it independently with your own code', 'check the cited evidence against the current files and the author notebook'].map((how, j) => () =>
      agent(`${COMMON}\nTASK (skeptic ${j + 1}; do NOT edit repository files; scratch under ${SP}/skeptic_${k}_${i}_${j}): try to REFUTE this ${k} finding by trying to ${how}: ${JSON.stringify(f)}. refuted=true only if it is wrong or not a real problem; give concrete evidence either way.`, { label: `skeptic:${k}:${i}:${j}`, phase: 'Skeptics', schema: VERDICT })))
      .then(vs => ({ ...f, lens: k, votes: vs.filter(Boolean), confirmed: vs.filter(Boolean).filter(v => !v.refuted).length >= 1 })))),
)
const all = judged.filter(Boolean).flat().filter(Boolean)
const confirmed = all.filter(f => f.confirmed)
log(`audit: ${all.length} findings, ${confirmed.length} confirmed by at least one skeptic`)
const verifiedOk = judged.length

phase('Fix')
let fix = { files_changed: [], commands_run: [], all_checks_pass: true, failing: [], key_results: ['no confirmed findings'], open_items: [], summary: 'nothing to fix' }
if (confirmed.length) {
  fix = await agent(`${COMMON}\nTASK (fixer): You own provenance/dirac_matrices/ (extract_from_author_notebook.wls, build_dirac_matrices_md.py, author_notebook_T16.json), provenance/dirac matrices.md (regenerate only, never hand-edit) and tests/test_dirac_matrices_provenance.py. Confirmed findings with skeptic votes (JSON): ${JSON.stringify(confirmed).slice(0, 80000)}\nRe-verify each finding yourself; fix confirmed ones at the root, in the generator (add checks, comparisons with every additional gamma source found by the coverage lens - load or construct them and compare entry by entry, with the coordinate map; add missing displays; correct any wrong or overclaimed statement; fix instructions). If a finding concerns code you do not own (another calculation using different matrices), do NOT edit it: record the measured truth in the generated file (which calculation, which matrices, equal or not) and report it in open_items. Never weaken a check. Then: re-run the .wls (if changed) and the builder; python provenance/dirac_matrices/build_dirac_matrices_md.py --check; python -m unittest discover -s tests -p "test_dirac_matrices_provenance.py" -v (update the test's expected check count and block count to the new truth). One line per finding in key_results: FIXED / REJECTED (reason).`, { label: 'fix', phase: 'Fix', schema: RESULT })
}

phase('Verify')
const verify = await agent(`${COMMON}\nTASK (final verifier; do NOT edit repository files): The fixer reported (JSON): ${JSON.stringify(fix).slice(0, 30000)}\nConfirmed findings were: ${JSON.stringify(confirmed.map(f => ({ lens: f.lens, problem: f.problem, fix: f.fix }))).slice(0, 30000)}\nCopy the CURRENT working-tree files provenance/dirac_matrices/*, "provenance/dirac matrices.md" and tests/test_dirac_matrices_provenance.py into a NEW fresh clone under ${SP}/verify_clone, then run the .wls and the builder exactly as the file's instructions say, the --check mode and the test; confirm byte identity of the regenerated .md and JSON; check every FIXED claim against the files; re-check that the eight matrices are real, satisfy the anticommutation relations, and that the Pin(4,4) section claims exactly what is proved. Report anything still wrong as findings.`, { label: 'verify', phase: 'Verify', schema: FINDINGS })
return { findings: all.length, confirmed: confirmed.length, confirmedList: confirmed.map(f => ({ lens: f.lens, severity: f.severity, problem: f.problem })), fix, verify }
