export const meta = {
  name: 'execution-provenance-cont',
  description: 'Test and verify that every wolframscript set and every existing Jupyter notebook executes correctly (fresh clone, twice, byte identity) and write a provenance file for each with student instructions, expected output and side effects; independent verification by following each provenance file literally',
  phases: [
    { title: 'Run and document', detail: 'one agent per set: execute in a fresh clone twice, diagnose, write the provenance file' },
    { title: 'Verify', detail: 'an independent agent follows each provenance file literally in another fresh clone' },
    { title: 'Fix', detail: 'fix confirmed problems' },
    { title: 'Index', detail: 'index of all provenance files and a test' },
  ],
}

const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'

const COMMON = `
CONTINUATION NOTE (2026-10-07 20:10): the previous run (wf_f856ecb5-265) was cut by a session limit; its finished results are in C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/state_wf_f856ecb5-265.json (keys 'run:<id>', 'verify:<id>', 'fix:<id>'). Files it left half-done may exist: inspect, verify, finish. Since then: (1) the lead FIXED scripts/verify_dirac16complex_primordial.wls (commit b980c80: package-existence check, AssociationQ guard, ERROR + exit 1 on unwritable output, non-True checks counted as failed; the report changes only in the script's own sha256; the Stage-2 publication and its PDF were updated and re-registered) - the old-primordial provenance file must now describe the FIXED script (sha256 values, expected output, the false-success row of Part 3.4 removed, the failure modes as measured now). (2) Revision wave 1b changed Revision/kohn_sham/theory/check_ks_theory.py (58 checks, new input ks-source-conditions.json) and the thermal Kohn-Sham outputs. (3) On Windows WolframScript writes tmp_* files to %LOCALAPPDATA%\\Wolfram\\WolframScript\\WolframScriptTemporary (an interrupted run leaves them): every provenance file's side-effects section must say so where it applies.\nNEVER accept licence terms, source agreements, cookie banners or any other agreement on the user's machine or accounts (e.g. never pass --accept-source-agreements / --accept-package-agreements to winget, never run wolframscript -activate or accept an EULA); if a step needs that, stop that step and report it as an open item for the user.
RESTART NOTE: this workflow was interrupted by a session limit and relaunched in a new session; provenance files and fixes of the earlier run may already exist (e.g. provenance/wolframscript/*.PROVENANCE.md): inspect, re-verify and finish them, never trust them unchecked.
CONTEXT: repository ${ROOT} (git, branch main; remote https://github.com/once-ere/Dirac_claude.git). NEVER run git commands that change the index, the working tree's history or the remote (read-only git and git clone into scratch are fine). THE USER'S TASK (verbatim): "Test and verify that each and every wolframscript set of scripts executes correctly, and provide a provenance file for each and every wolframscript set that includes instructions to the student for executing the wolframscript set, and explains the expected output and or side-effects of this execution. Test and verify that each and every Jupyter notebook executes correctly, and provide a provenance file for this Jupyter notebook that includes instructions to the student for executing the Jupyter notebook, and explains the expected output and or side-effects of this execution." RULES: execute in FRESH CLONES under ${SP}/execprov/<your label>/ (git clone https://github.com/once-ere/Dirac_claude.git, then copy over only the uncommitted files you need from ${ROOT}, saying which), never in ${ROOT} itself (another workflow is writing Revision/textbook/ there - never touch Revision/textbook/). Never modify the author's notebooks (Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb, "Generalized _Kronecker_Delta_4+4.nb"), dirac-main/, vendor/, private files (the Gmail PDF, prompt_*.txt, Generalized_Kronecker_Delta.*). Never weaken a check or a tolerance; record measured truth. If a script fails or does not reproduce its committed outputs: diagnose the root cause with evidence; you may fix an EXECUTION defect (a path, a missing directory, an environment assumption, nondeterministic output formatting) in the working tree ${ROOT}, re-verify the fix in a fresh clone plus a copy of the fix, and list the fix; a SCIENTIFIC discrepancy (a changed number, a failing physics check) is NOT fixed silently: report it in failing with the diagnosis and leave the committed outputs unchanged. Tooling: WolframScript 1.14 / Wolfram 15.0, Professional licence without a kernel limit (it drops arguments after "--"); Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; no scipy); Rust cargo 1.91; bash and PowerShell. Read files in chunks of at most 300 lines. Report measured run times; never wait idly.
PROVENANCE FILE CONTENT (Markdown, LF, deterministic; for a student who has never used Wolfram or Jupyter): (1) what the set/notebook is and what it computes, in plain words, and which documents cite its results; (2) its files: every script/package/notebook with its sha256 and line count, every input it reads (with sha256), every output it writes; (3) COMPLETE instructions to execute it, self-contained (never "see file X"): installing the free Wolfram Engine for Developers or Mathematica and activating wolframscript (or, for a notebook, Python with a private environment, the exact pip install commands with the versions used, JupyterLab, and Rust/other prerequisites if any), cloning the repository, the exact command(s) from the repository root for Windows PowerShell, macOS and Linux, what to do if it fails (the likely errors and fixes); (4) the EXPECTED OUTPUT: what is printed (the exact final verdict lines and check counts), the exit code, every report/output file written and how to check it (e.g. the summary line of the JSON), the measured run time on the verification machine (24 cores, Windows 11); (5) the SIDE EFFECTS: every file created or OVERWRITTEN in the repository (committed outputs that a run regenerates), temporary files and directories, Wolfram kernels started, network access (none expected), how to restore the committed state (git checkout -- <files>); (6) the VERIFICATION RECORD: the date 2026-10-02, the commit verified, the environment (OS, Wolfram/Python versions), two runs from a fresh clone and the byte-identity result for every output, the check counts, any fix made (with its diff summary) and any open discrepancy.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }

// [id, kind, what, provenance file]
const RUN_DONE = ["handoff-probes", "nb-dark-sector", "old-00", "old-algebra", "old-geometry", "old-kohn-sham", "old-matter-antimatter", "old-nb-build-dark", "old-nb-build-ks", "old-nb-verify-dark", "old-nb-verify-ks", "old-pairing", "old-primordial", "rev-a4", "rev-algebra", "rev-gkd-notebook-reading", "rev-gkd-verification", "rev-ks-theory", "rev-pairing", "rev-pairing-ks", "rev-theory"]
const VERIFY_DONE = {"old-nb-build-dark": 5, "rev-ks-theory": 6, "old-kohn-sham": 6, "rev-pairing-ks": 4, "old-primordial": 5, "rev-pairing": 5, "rev-algebra": 3, "rev-gkd-notebook-reading": 6, "old-00": 3, "old-algebra": 5, "rev-a4": 4, "old-pairing": 6, "old-matter-antimatter": 5, "old-geometry": 4, "nb-dark-sector": 5, "old-nb-verify-dark": 7, "old-nb-build-ks": 3}
const FIX_DONE = ["old-nb-build-dark", "rev-algebra", "rev-ks-theory", "rev-pairing-ks"]
const HELD = ["rev-a4"]
const SETS = [
  ['rev-algebra', 'wolfram', 'Revision/algebra/wolfram/ (verify_algebra.wls with RevisionAlgebra.wl; outputs Revision/algebra/gammas.json and reports/wolfram-algebra.json)', 'Revision/algebra/wolfram/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-theory', 'wolfram', 'Revision/theory/wolfram/ (verify_field_theory.wls - about 18 minutes - and verify_scope.wls, with RevisionFieldTheory.wl; outputs under Revision/theory/)', 'Revision/theory/wolfram/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-a4', 'wolfram', 'Revision/field_equations_a4/wolfram/ (verify_field_equations_a4.wls with its package)', 'Revision/field_equations_a4/wolfram/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-pairing', 'wolfram', 'Revision/pairing/wolfram/ (verify_pairing.wls with its package)', 'Revision/pairing/wolfram/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-pairing-ks', 'wolfram', 'Revision/pairing/kohn_sham/wolfram/ (the T3 verifier)', 'Revision/pairing/kohn_sham/wolfram/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-ks-theory', 'wolfram', 'Revision/kohn_sham/theory/ (verify_ks_theory.wls with its package; outputs ks-theory.json and reports)', 'Revision/kohn_sham/theory/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-gkd-verification', 'wolfram', 'Revision/gkd_lovelock/verification/ (verify_lovelock_gkd.wls with LovelockGKDCheck.wl)', 'Revision/gkd_lovelock/verification/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['rev-gkd-notebook-reading', 'wolfram', "Revision/gkd_lovelock/notebook_reading/ (lovelock_extract_nb_inputs.wls and lovelock_export_nb_image.wls: they READ the author's notebook, never modify it)", 'Revision/gkd_lovelock/notebook_reading/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['old-algebra', 'wolfram', 'scripts/verify_dirac16complex_algebra.wls with wolfram/Dirac16ComplexAlgebra.wl (old Stage 1)', 'provenance/wolframscript/verify_dirac16complex_algebra.PROVENANCE.md'],
  ['old-geometry', 'wolfram', 'scripts/verify_dirac16complex_geometry.wls with wolfram/Dirac16ComplexGeometry.wl (old Stage 1)', 'provenance/wolframscript/verify_dirac16complex_geometry.PROVENANCE.md'],
  ['old-primordial', 'wolfram', 'scripts/verify_dirac16complex_primordial.wls with wolfram/Dirac16ComplexPrimordial.wl (old Stage 2)', 'provenance/wolframscript/verify_dirac16complex_primordial.PROVENANCE.md'],
  ['old-kohn-sham', 'wolfram', 'scripts/verify_dirac16complex_kohn_sham.wls with wolfram/Dirac16ComplexKohnSham.wl (old Stage 4)', 'provenance/wolframscript/verify_dirac16complex_kohn_sham.PROVENANCE.md'],
  ['old-00', 'wolfram', 'scripts/verify_dirac16complex00.wls with wolfram/Dirac16Complex00.wl (old Stage 5)', 'provenance/wolframscript/verify_dirac16complex00.PROVENANCE.md'],
  ['old-pairing', 'wolfram', 'scripts/verify_dirac16complex_pairing.wls with wolfram/Dirac16ComplexPairing.wl (old Stage 5)', 'provenance/wolframscript/verify_dirac16complex_pairing.PROVENANCE.md'],
  ['old-matter-antimatter', 'wolfram', 'scripts/verify_dirac16complex_matter_antimatter.wls with wolfram/Dirac16ComplexMatterAntimatter.wl (old analysis; NOTE for the provenance file: its charge conjugations are matrices M Psi* and M Psibar^T - say so explicitly, consistent with Revision/lead_checks/charge_conjugation_and_u1.py)', 'provenance/wolframscript/verify_dirac16complex_matter_antimatter.PROVENANCE.md'],
  ['old-nb-build-dark', 'wolfram', 'scripts/build_dirac16complex_mathematica_notebook.wls (builds notebooks/Dirac16ComplexDarkSector.nb; old Stage 3) - run it in the fresh clone only and compare the built notebook with the committed one', 'provenance/wolframscript/build_dirac16complex_mathematica_notebook.PROVENANCE.md'],
  ['old-nb-verify-dark', 'wolfram', 'scripts/verify_dirac16complex_mathematica_notebook.wls (headless verifier of notebooks/Dirac16ComplexDarkSector.nb)', 'provenance/wolframscript/verify_dirac16complex_mathematica_notebook.PROVENANCE.md'],
  ['old-nb-build-ks', 'wolfram', 'scripts/build_dirac16complex_ks_mathematica_notebook.wls (builds notebooks/Dirac16ComplexKohnSham.nb; old Stage 4) - fresh clone only, compare with the committed notebook', 'provenance/wolframscript/build_dirac16complex_ks_mathematica_notebook.PROVENANCE.md'],
  ['old-nb-verify-ks', 'wolfram', 'scripts/verify_dirac16complex_ks_mathematica_notebook.wls (headless verifier of notebooks/Dirac16ComplexKohnSham.nb)', 'provenance/wolframscript/verify_dirac16complex_ks_mathematica_notebook.PROVENANCE.md'],
  ['handoff-probes', 'wolfram', 'handoff/tools/probe1.wls and probe2.wls (session probes: find out what they do, run them, document them honestly, including whether they are still needed)', 'handoff/tools/WOLFRAMSCRIPT_PROVENANCE.md'],
  ['nb-dark-sector', 'jupyter', 'notebooks/dirac16complex_dark_sector.ipynb (old Stage 3; its builder notebooks/build_dirac16complex_notebook.py, runner notebooks/run_notebook.py, checker notebooks/check_notebook.py; it may need the old solvers built by scripts/setup_solver.sh - find out from its first cells and the README)', 'notebooks/dirac16complex_dark_sector.PROVENANCE.md'],
  ['nb-kohn-sham', 'jupyter', 'notebooks/dirac16complex_kohn_sham.ipynb (old Stage 4; builder notebooks/build_dirac16complex_kohn_sham_notebook.py, checker notebooks/check_dirac16complex_kohn_sham_notebook.py; may need the old Kohn-Sham solver built)', 'notebooks/dirac16complex_kohn_sham.PROVENANCE.md'],
]

const results = await pipeline(
  SETS,
  ([id, kind, what, prov]) => RUN_DONE.includes(id) ? { files_changed: [prov], key_results: [`runner finished in the previous run; its report is under key run:${id} in C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/state_wf_f856ecb5-265.json`], open_items: [], all_checks_pass: true, failing: [], commands_run: [], summary: `${id}: runner done earlier` } : agent(`${COMMON}\nTASK (run and document ${id}): You own ${prov} (create it) and, only for execution defects, the files of this set. The set: ${what}. Read every file of the set fully (headers give the usage) and the documents that cite it. In a fresh clone: ${kind === 'jupyter' ? 'build any prerequisites the notebook needs exactly as a student would, execute the notebook headless (jupyter nbconvert --to notebook --execute into a copy, and the repository runner/checker if there is one) TWICE, compare the outputs with the committed notebook and the committed data it writes (normalise only execution counts/timestamps if the repository checker does so; say what you normalised)' : 'run every script of the set exactly as its usage says (from the repository root), TWICE, and compare every output file byte for byte with the committed one and between the two runs'}; record exit codes, printed verdict lines, check counts, run times and peak memory if measurable; list every file created or overwritten (git status --porcelain in the clone, plus temp files). Then write ${prov} with all six parts of the PROVENANCE FILE CONTENT. Report in key_results: EXECUTES OK / FAILS, reproduces byte-identically yes/no per output, run time, check counts.`, { label: `run:${id}`, phase: 'Run and document', schema: RESULT }),
  (r, [id, kind, what, prov]) => (id in VERIFY_DONE) ? { findings: VERIFY_DONE[id] ? [{ severity: 'major', file: prov, location: 'all', problem: `The independent verifier of ${id} finished in the previous run with ${VERIFY_DONE[id]} findings; read them in full under key verify:${id} in C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/state_wf_f856ecb5-265.json and treat each as a finding to re-verify.`, evidence: 'state file', fix: 'see the state file' }] : [], verified_ok: [] } : agent(`${COMMON}\nTASK (independent verifier of ${id}; do not edit files under ${ROOT}): Read ${ROOT}/${prov}. In a NEW fresh clone (plus a copy of ${prov} and of any uncommitted fix the runner made: ${JSON.stringify((r && r.files_changed) || [])}) follow its instructions LITERALLY as a student would (the commands exactly as written, for the shell of this machine; check the macOS/Linux variants by reading them carefully for errors). Verify: the commands work; the expected output (printed lines, check counts, exit code, files written) matches exactly what you observe; the side-effects list is complete (compare with git status --porcelain and temp files); the sha256 values match; the instructions are complete and self-contained for a beginner; nothing is claimed that is not true. Runner summary: ${JSON.stringify((r && r.summary) || '').slice(0, 1500)}. Report every mismatch as a finding with evidence.`, { label: `verify:${id}`, phase: 'Verify', schema: FINDINGS }),
  (v, [id, kind, what, prov]) => FIX_DONE.includes(id) ? { files_changed: [prov], commands_run: [], all_checks_pass: true, failing: [], key_results: [`fixer finished in the previous run; report under key fix:${id} in C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad/state_wf_f856ecb5-265.json`], open_items: [], summary: `${id}: fixed earlier` } : HELD.includes(id) ? { files_changed: [], commands_run: [], all_checks_pass: false, failing: [`${id}: fix stage HELD by the lead until the a4 author-gammas patch is applied; the lead runs it afterwards`], key_results: [], open_items: ['held'], summary: `${id}: held` } : (v && v.findings && v.findings.length)
    ? agent(`${COMMON}\nTASK (fix ${id}): You own ${prov} and, for execution defects only, the files of this set. Verifier findings (JSON): ${JSON.stringify(v.findings).slice(0, 40000)}\nRe-verify each in a fresh clone; fix confirmed ones at the root (the provenance file, or an execution defect); reject unconfirmed ones with evidence; re-run the affected commands. One line per finding: FIXED / REJECTED (reason).`, { label: `fix:${id}`, phase: 'Fix', schema: RESULT })
    : { files_changed: [], commands_run: [], all_checks_pass: true, failing: [], key_results: ['verifier: no findings'], open_items: [], summary: `${id}: verified without findings` },
)

phase('Index')
const index = await agent(`${COMMON}\nTASK (index and test): You own provenance/EXECUTION_PROVENANCE_INDEX.md and tests/test_execution_provenance.py. Results per set (truncated): ${JSON.stringify(results.map((r, i) => ({ id: SETS[i][0], prov: SETS[i][3], ok: r && r.all_checks_pass, key: r && r.key_results && r.key_results.slice(0, 5), failing: r && r.failing }))).slice(0, 20000)}\nAlso include, as its own row, the set provenance/dirac_matrices/ (extract_from_author_notebook.wls reads the author's notebook and evaluates the author's own cells that define the eight real 16 x 16 Dirac matrices; build_dirac_matrices_md.py proves them, 35 exact checks) whose provenance file is 'provenance/dirac matrices.md' (generated: never edit it by hand; verify it with: python provenance/dirac_matrices/build_dirac_matrices_md.py --check, and re-run the .wls in a fresh clone - it must reproduce author_notebook_T16.json byte for byte). Write the index: one row per wolframscript set and per Jupyter notebook (the set, its provenance file, EXECUTES OK / FAILS, byte-identical reproduction, run time, check counts, open discrepancies), plus a section listing the textbook notebooks of Revision/textbook/notebooks/ as "documented by their own X.PROVENANCE.md files (TEXTBOOK_SPEC R6), verified by the textbook workflow" without editing anything under Revision/textbook/. Search the repository yourself (excluding vendor/, dirac-main/, build/, target/) for EVERY .wls file and EVERY .ipynb file and make sure each one is covered by a provenance file; report any that is not. The test (unittest, fast by default): every .wls outside vendor/dirac-main/build is listed in some provenance file; every listed provenance file exists and names the sha256 of the current script/notebook files it documents (so a later edit forces an update); with EXECUTION_PROVENANCE_FULL=1 it re-runs the fast sets. Run the test.`, { label: 'index', phase: 'Index', schema: RESULT })
return { results: results.map((r, i) => ({ id: SETS[i][0], ok: r && r.all_checks_pass, summary: r && r.summary, failing: r && r.failing })), index }
