export const meta = {
  name: 'revision-wave-1b',
  description: 'Revision wave 1b: verify the wave-1 fixes, repair the Rust Mermin mu, cross-check the FULL Kohn-Sham matrix, settle the theory Wolfram/sympy comparison, fresh-clone reproduction gate, skeptic-verified review and fix',
  phases: [
    { title: 'Repair', detail: 'Rust Mermin mu; theory comparison; wave-1 fix verification' },
    { title: 'Cross-check', detail: 'full Kohn-Sham matrix against the reference, all quantities' },
    { title: 'Reproduce', detail: 'fresh clone + working tree, every verifier twice, byte identity, unittest' },
    { title: 'Review', detail: 'skeptics per item' },
    { title: 'Fix', detail: 'per-area fixers, fix verifier' },
  ],
}

const ROOT = 'D:/Developer/github/Dirac_claude'
// ROOT: the repository on the machine where these waves ran; SP: the scratchpad directory of the session that
// runs the script (set it in the session's own copy before launching; see Revision/README.md, workflows/).
const SP = '<SCRATCHPAD OF THE RUNNING SESSION>'
if (SP.startsWith('<')) throw new Error('set SP to the scratchpad directory of the running session')
const R = 'Revision'
const COMMON = `
WAVE 1B NOTE: wave 1 (algebra, theory, a4 equations, pairing, GKD verification, Kohn-Sham solver, reference, three documents) is finished and was reviewed once; you repair and verify it. Inspect the current files and git diff before changing anything.
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; read-only git is fine. You work ONLY inside ${ROOT}/${R}/ (plus scratch). BINDING: ${ROOT}/${R}/SPEC.md (read it fully first: the no-mixing rule of section 0, the author's metric and coordinate names of section 1 (x1..x3 3-space, x4 time, x5..x7 the exponentially DEFLATING extra times, x8 hidden), the conventions of sections 2-9) and ${ROOT}/${R}/README.md (the author's task verbatim and the answers already given). NO-MIXING RULE: nothing from the old stages (artifacts/, provenance/, studies/, scripts/ (except the generic PDF tooling), wolfram/, notebooks/) is copied into Revision or used as a result; you may READ old documents to recall a method, but every Revision statement is computed anew by Revision code; never import old Python modules or old Wolfram packages. HONESTY: numbers only from Revision outputs; theorems with exact hypotheses; never "proved" for anything not proved; the pair-creation request is answered by the pairing theorems plus an exact statement of what they do not establish. Private inputs never committed or quoted beyond what Revision/README.md quotes: the Gmail PDF, prompt files, dirac-main/, vendor/, Generalized_Kronecker_Delta.*. Tooling: Python 3.14 (sympy, numpy, mpmath, matplotlib, nbformat/nbclient; no scipy); WolframScript 1.14 (it drops arguments after "--"); Rust (cargo; give each new crate its own empty [workspace] table because a stray Cargo.toml sits above the repository; the SUNDIALS engine is at ${ROOT}/vendor/rustSolveIt/sundials_rs/crates/{sundials_core,cvode_rs} if needed); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --specifications ${R}/pdf-specifications.json [--register]. Deterministic outputs (two runs byte-identical, LF). Every check in a JSON report with name, verdict, detail. Read files in chunks of at most 300 lines. Scratch only under ${SP}/revision/<label>/. If a step needs a long computation, run it and report its time; never wait idly.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const VERDICT = { type: 'object', properties: { refuted: { type: 'boolean' }, reason: { type: 'string' }, evidence: { type: 'string' } }, required: ['refuted', 'reason', 'evidence'] }
const run = (label, ph, task) => agent(`${COMMON}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })
const W1 = args || {}

phase('Repair')
const [ksFix, theoryFix, w1verify] = await parallel([
  () => run('ks-mermin-fix', 'Repair', `You own ${R}/kohn_sham/solver/ and the Rust outputs (${R}/kohn_sham/results/, ${R}/kohn_sham/reports/ks-rust-solver.json, ks-rust-determinism.json). DEFECT found by the cross-check (${R}/kohn_sham/reports/ks-crosscheck.json, check thermo_state_functions): fn mermin in src/scf.rs finds the chemical potential mu by bisection on the direct sum g f - N, so in deeply activated thermal states (N8_lamm1_a00_T10: |mu_Rust - mu_root| = 8.27e-10, dN/dmu = 1.24e-6) mu and Omega are only accurate to eps N/(dN/dmu), and the canonical-vs-refined measure cannot reveal it because both runs carry the same rounding. Read the reference's well-conditioned residual (${R}/kohn_sham/reference, ks_fd.mermin_residual) for the IDEA only and implement your own well-conditioned root finding in Rust (e.g. a residual written as the deviation from the T = 0 filling with complementary Fermi factors, or in the log domain, so that N is not recovered by cancellation). Add a Rust unit test against high-precision roots that you compute independently (mpmath, 40 digits, a script under ${R}/kohn_sham/solver/tools/) for the worst states, and a solver check in the report. Re-run the canonical matrix, the repeat (byte-identical) and the refined run, regenerate ks-rust-determinism.json with compare_runs.py, and make the uncertainty measure sensitive to this error class (state how). ALSO (open item of the wave-1 fixer): ${R}/kohn_sham/ks-theory.json says 'a4 = A H x4 (A = 1 canonical)' without the label that this history is a PRESCRIBED BACKGROUND (the Kohn-Sham states violate the a4 source conditions: ${R}/field_equations_a4/reports/ks-source-conditions.json); add the label at its source (the generators in ${R}/kohn_sham/theory/, both engines), regenerate ks-theory.json and its reports, and since its sha256 is recorded by the solver, the reference and the checker, update those records in the same pass. Report every changed number (mu, Omega and anything derived) old -> new for the thermal states, and grep ${R}/docs and ${R}/kohn_sham for every place quoting a changed number (list them; do not edit documents).`),
  () => run('theory-reconcile', 'Repair', `You own ${R}/theory/ (the Wolfram and the sympy side). The wave-1 fixer reports this FIXED (finding 21: the energy_exchange parser reads both forms, the prose records are compared by re-derivation, 32/32 formula records agree): VERIFY that independently and finish whatever is missing. The original defect: a fresh-clone re-run of the committed state (commit 1c297d6) showed: python ${R}/theory/python/check_field_theory.py rewrites ${R}/theory/reports/python-field-theory.json differently from the committed file: comparison_with_wolfram.status becomes DISAGREEMENTS; the Wolfram summary is 84 checks (the committed sympy report had been compared with an older 82-check Wolfram run); the formula energy_exchange DISAGREES (Wolfram: d rho/d x4 = -3 a4' (p3 - p_t); the sympy side adds nabla_mu T^mu_x8 = 3 H cot z (2 p8 - p3 - p_t)); five formula keys are not compared (nontriviality, majorana_negative_control, exact_solutions, equation_of_state_definitions, hidden_direction_hermiticity); EMT_trace_G and EMT_trace_C have no sympy counterpart; the publication test test_dirac16complex_field_theory_publication.py fails (status DISAGREEMENTS). The wave-1 fixer may already have edited compare_wolfram.py and check_field_theory.py: read the current files and the git diff first. Then derive nabla_mu T^mu_nu for this metric yourself from scratch for the homogeneous source (rho, p3, p_t, p8 functions of x4 and x8); decide which statement is correct and complete (the x4 and the x8 components and their relation; the lead's independent sympy derivation found d rho/d x4 = -3 a4' (p3 - p_t) for x4 and d p8/d x8 + 3 H cot z (2 p8 - p3 - p_t) = 0 for x8, all other components identically zero - confirm or refute with your own derivation); make BOTH sides state the same complete identity; compare EVERY formula key (a not_compared entry only with a written justification); give EMT_trace_G/C sympy counterparts; regenerate all theory reports deterministically (two runs byte-identical; run the Wolfram verifier too); make every test in ${R}/tests pass. List every place in ${R}/docs that quotes the energy-exchange formula or a changed check count (do not edit documents).`),
  () => agent(`${COMMON}\nTASK (wave-1 fix verifier; do not edit files): The wave-1 review findings (27) and the fixer's report are in ${SP}/w1_args.json (keys findings, fixer; a copy is committed as ${R}/workflows/wave1_review_and_fix.json); read all of it. For every finding the fixer marked FIXED, check in the current files that it is fixed at the root and that the fix introduced no inconsistency (documents vs reports; python -m unittest discover -s ${R}/tests -v). For every REJECTED one, judge the rejection with your own evidence. Report remaining problems as findings (the Kohn-Sham Mermin mu defect and the theory Wolfram/sympy comparison are owned by other agents: do not report them).`, { label: 'wave1-fix-verifier', phase: 'Repair', schema: FINDINGS }),
])

phase('Cross-check')
const xcheck = await run('ks-full-crosscheck', 'Cross-check', `You own ${R}/kohn_sham/reference/ and ${R}/kohn_sham/checker/ and their reports. The Rust solver was just repaired (Mermin mu; summary: ${JSON.stringify(ksFix).slice(0, 4000)}). Extend the cross-check from the representative subset (18 of 75 ground, 8 of 135 thermal) to the FULL canonical matrix: every ground state, every thermal state, the exact-Fock variant SCF energies (not only the Delta E_x diagnostic), the rescaling partners, the particle-hole lists, the sea-hole diagnostic and the crossing demonstration. Keep the tolerance rule fixed BEFORE comparing (|x_Rust - x_ref| <= 3(U_ref + U_Rust) + 1e-12 scale with measured uncertainties); never weaken it. Make the reference repeat check reproducible (the checker creates and compares the repeat directory itself). Run in parallel processes; report the times. Report every failure honestly with a data-driven diagnosis; a Rust defect goes precisely into open_items and failing.`)

phase('Reproduce')
const repro = await agent(`${COMMON}\nTASK (reproduction gate; do not edit files under ${ROOT}; write only under ${SP}/revision/repro1b/): make a fresh git clone of https://github.com/once-ere/Dirac_claude.git into scratch, then copy the CURRENT working-tree ${R}/ over it (excluding target/ directories) so that the clone's ${R}/ equals the working tree. In it run EVERY Revision verifier and checker (python ${R}/algebra/python/check_algebra.py, ${R}/theory/python/check_field_theory.py, ${R}/field_equations_a4/python/check_field_equations_a4.py, ${R}/pairing/python/check_pairing.py, ${R}/kohn_sham/theory/check_ks_theory.py, ${R}/gkd_lovelock/verification/check_lovelock_gkd.py; every .wls verifier with wolframscript -file; the GKD Rust program; the Kohn-Sham Rust 'all' run and cargo test; the reference and the checker as documented), each TWICE; compare every output byte for byte with the working tree (git status / git diff in the clone after git add of the copied tree); run python -m unittest discover -s ${R}/tests -v; rebuild every PDF of ${R}/docs in verify mode. Grep for absolute paths and nondeterminism (timestamps, dict order, thread order). Report each non-reproduced file or failing test as a finding with the diff as evidence.`, { label: 'repro-gate', phase: 'Reproduce', schema: FINDINGS })

phase('Review')
const owners = ['kohn_sham', 'theory', 'kohn_sham']
// wave-1 fix verifier input: args = { findings, fixer }
const pending = [
  ...((w1verify && w1verify.findings) || []).map(f => ({ ...f, source: 'wave1-fix-verifier' })),
  ...((repro && repro.findings) || []).map(f => ({ ...f, source: 'repro-gate' })),
  ...[ksFix, theoryFix, xcheck].flatMap((r, i) => ((r && r.failing) || []).map(x => ({ severity: 'major', file: `${R}/${owners[i]}`, location: 'report', problem: x, evidence: x, fix: 'diagnose and repair at the root', source: 'failing-check' }))),
]
log(`wave 1b: ${pending.length} items to judge`)
const judged = await parallel(pending.map((f, i) => () =>
  parallel(['re-derive or re-run it independently', 'check the cited evidence in the current files'].map((how, j) => () =>
    agent(`${COMMON}\nTASK (skeptic ${j + 1}; do not edit files): try to REFUTE this item by trying to ${how}: ${JSON.stringify(f)}. refuted=true only if it is wrong or no longer a problem in the current files; concrete evidence either way.`, { label: `skeptic:${i}:${j}`, phase: 'Review', schema: VERDICT })))
    .then(vs => ({ ...f, votes: vs.filter(Boolean), confirmed: vs.filter(Boolean).filter(v => !v.refuted).length >= 1 }))))
const confirmed = judged.filter(Boolean).filter(f => f.confirmed)
log(`wave 1b: ${confirmed.length} of ${pending.length} confirmed`)

phase('Fix')
const area = f => /(^|\/)docs\//.test(f.file || '') ? 'docs' : /(notebooks\/|verify_revision|(^|\/)tests\/)/.test(f.file || '') ? 'other' : 'science'
const fixes = []
for (const a of ['science', 'docs', 'other']) {
  const mine = confirmed.filter(f => area(f) === a)
  if (!mine.length) continue
  const payload = JSON.stringify(mine)
  if (payload.length > 90000) log(`fix:${a}: payload ${payload.length} chars, split`)
  const parts = Math.ceil(payload.length / 90000)
  for (let c = 0; c < parts; c++) {
    const chunk = mine.slice(Math.floor(c * mine.length / parts), Math.floor((c + 1) * mine.length / parts))
    fixes.push(await run(`fix:${a}:${c}`, 'Fix', `Confirmed items with skeptic votes (JSON): ${JSON.stringify(chunk)}\nAlso the documents must quote the repaired numbers and formulas: places listed by the repair agents: ${JSON.stringify([ksFix, theoryFix].filter(Boolean).map(r => r.key_results)).slice(0, 8000)}\nFix each at its ROOT inside ${R}/ (regenerate reports deterministically, rebuild and re-register PDFs, rerun the affected tests; propagate changed numbers to every document that quotes them). One line per item in key_results: FIXED / REJECTED (evidence).`))
  }
}
const fixCheck = fixes.length ? await agent(`${COMMON}\nTASK (fix verifier; do not edit files): fixer reports ${JSON.stringify(fixes).slice(0, 60000)}. Check every FIXED claim in the files; run python -m unittest discover -s ${R}/tests -v; report what is still wrong.`, { label: 'fix-verifier', phase: 'Fix', schema: FINDINGS }) : null
return { ksFix, theoryFix, w1verify, xcheck, repro, judged, fixes, fixCheck }
