export const meta = {
  name: 'revision-wave-1',
  description: 'Revision/ wave 1: algebra (Wolfram + sympy), field theory of both fields, a4 field equations, pairing proofs, GKD verification, Kohn-Sham solver, three documents, reviews, fixer - all new, not mixed with the old stages',
  phases: [
    { title: 'Algebra', detail: 'gammas in the author coordinate order; Pin/Spin facts' },
    { title: 'Theory', detail: 'both fields: Lagrangian, EL, EMT, quantisation, non-triviality; a4 equations; pairing' },
    { title: 'GKD', detail: 'independent verification of the Lovelock tensors' },
    { title: 'Kohn-Sham', detail: 'exact reduction, Rust solver, reference, checker' },
    { title: 'Documents', detail: 'dirac16complex, dirac16complex00, pair-creation proofs' },
    { title: 'Review', detail: 'four lenses' },
    { title: 'Fix', detail: 'apply confirmed findings' },
  ],
}

const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/db1fcb32-bb14-4b52-b62c-37fb53990650/scratchpad'
const R = 'Revision'

const COMMON = `
RESTART NOTE: this is a relaunch after a pause; files written by an earlier, stopped run may exist (e.g. Revision/algebra/wolfram/RevisionAlgebra.wl): inspect them, verify them and finish them; never trust them unchecked.
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote; read-only git is fine. You work ONLY inside ${ROOT}/${R}/ (plus scratch). BINDING: ${ROOT}/${R}/SPEC.md (read it fully first: the no-mixing rule of section 0, the author's metric and coordinate names of section 1 (x1..x3 3-space, x4 time, x5..x7 the exponentially DEFLATING extra times, x8 hidden), the conventions of sections 2-9) and ${ROOT}/${R}/README.md (the author's task verbatim and the answers already given). NO-MIXING RULE: nothing from the old stages (artifacts/, provenance/, studies/, scripts/ (except the generic PDF tooling), wolfram/, notebooks/) is copied into Revision or used as a result; you may READ old documents to recall a method, but every Revision statement is computed anew by Revision code; never import old Python modules or old Wolfram packages. HONESTY: numbers only from Revision outputs; theorems with exact hypotheses; never "proved" for anything not proved; the pair-creation request is answered by the pairing theorems plus an exact statement of what they do not establish. Private inputs never committed or quoted beyond what Revision/README.md quotes: the Gmail PDF, prompt files, dirac-main/, vendor/, Generalized_Kronecker_Delta.*. Tooling: Python 3.14 (sympy, numpy, mpmath, matplotlib, nbformat/nbclient; no scipy); WolframScript 1.14 (it drops arguments after "--"); Rust (cargo; give each new crate its own empty [workspace] table because a stray Cargo.toml sits above the repository; the SUNDIALS engine is at ${ROOT}/vendor/rustSolveIt/sundials_rs/crates/{sundials_core,cvode_rs} if needed); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --specifications ${R}/pdf-specifications.json [--register]. Deterministic outputs (two runs byte-identical, LF). Every check in a JSON report with name, verdict, detail. Read files in chunks of at most 300 lines. Scratch only under ${SP}/revision/<label>/. If a step needs a long computation, run it and report its time; never wait idly.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const run = (label, phaseName, task) => agent(`${COMMON}\nTASK (${label}): ${task}`, { label, phase: phaseName, schema: RESULT })

// ---------------- Algebra ----------------
phase('Algebra')
const [algW, algP] = await parallel([
  () => run('algebra-wolfram', 'Algebra', `Own ${R}/algebra/wolfram/ (RevisionAlgebra.wl, verify_algebra.wls), ${R}/algebra/gammas.json (the fixture), ${R}/algebra/reports/wolfram-algebra.json. Re-construct the author's 16 x 16 gamma matrices T16 from the author's own formulas (the 4 x 4 blocks s4[h], t4[h] built from Signature[{h,p,q,4}] and the deltas, the tau matrices, sigma, taubar = sigma tau^T sigma, T16 = {{0, taubar},{tau, 0}}): you may read the INPUT cells of the author's notebook Pair_Creation_of_Universes_WaveFunctionOfUniverse-4+4-Einstein-Lovelock-Nash.nb (never modify it) or the formulas as recalled in provenance/textbook/chapters/03-split-octonions.md (method only). Map them to the author's coordinate order per SPEC section 2 (gamma^(x8) = T16[0], gamma^(x1..x3) = T16[1..3], gamma^(x4) = T16[4], gamma^(x5..x7) = T16[5..7]) and verify EXACTLY: the Clifford relation with eta = diag(+,+,+,-,-,-,-,+) in the order x1..x8; reality and the symmetry pattern; C (SPEC section 2) real symmetric, C^2 = 1, C gamma^a real antisymmetric; Gamma = diag(-I8, I8) anticommuting with every gamma^a; B Hermitian, B^2 = 1, signature (8,8); S^ab; irreducibility of the 16-dimensional representation under Pin(4,4) (commutant of all gamma^a has dimension 1) and its splitting under Spin(4,4) (commutant of all S^ab has dimension 2, spanned by the chiral projectors; the two 8-dimensional halves inequivalent: the space of intertwiners between them is 0). Write gammas.json (gamma, C, Gamma, B, S as exact integer/complex-rational arrays in the order x1..x8) deterministically.`),
  () => run('algebra-python', 'Algebra', `Own ${R}/algebra/python/ (check_algebra.py), ${R}/algebra/reports/python-algebra.json. INDEPENDENTLY of the Wolfram agent (do not read its files until your own construction is finished), re-construct the author's T16 from the same author formulas (see the Wolfram task: notebook input cells or the recalled formulas), map to the author's coordinate order, and verify exactly with sympy/fractions every fact listed for the Wolfram agent (Clifford relation, C, Gamma, B, S^ab, Pin irreducibility, Spin splitting into two inequivalent 8-dimensional parts). Then compare entry by entry with ${R}/algebra/gammas.json when it exists (wait for it by checking; if it is not there when you finish, write your own matrices to ${R}/algebra/reports/python-gammas.json and record the comparison as pending).`),
])

// ---------------- branches ----------------
const theoryBranch = async () => {
  phase('Theory')
  const theory = await parallel([
    () => run('theory-wolfram', 'Theory', `Own ${R}/theory/wolfram/ (RevisionFieldTheory.wl, verify_field_theory.wls), ${R}/theory/reports/wolfram-field-theory.json, ${R}/theory/field-theory.json (exact formulas for the documents). Using ${R}/algebra/gammas.json and the metric of SPEC section 1, derive and verify EXACTLY for BOTH statistics (Grassmann dirac16complex with an explicit Grassmann algebra; commuting dirac16complex00): the diagonal vielbein, the canonical spin connection omega_mu ab (vielbein postulate) and Omega_mu, every component; D_mu gamma^nu = 0 (covariant constancy); gamma^mu Omega_mu for this metric and the precise cancellation of the x4-direction terms (3 inflating vs 3 deflating directions) with the surviving hidden-direction term (proportional to H); the Lagrangian of SPEC section 3, its reality for both statistics, the total-divergence relation to the unsymmetrised form; the Euler-Lagrange equations gamma^mu D_mu Psi = (m + U'(S)) Psi (and the adjoint) written out explicitly in this metric (all 16 components or in block form); NON-TRIVIALITY [1] and [2]: the gravitational terms in the field equations are nonzero for H != 0 or a4 not constant and vanish only in flat 4+4 space - prove it; self-consistency (the conserved current J^mu = -i Psibar gamma^mu Psi and its exact conservation identity; integrability); the negative control: the author's Majorana-type Lg[] (Psi^T C gamma^mu D_mu Psi with real components) is a total derivative for Grassmann components; the symmetric energy-momentum tensor by vielbein variation, its explicit components in this metric, kinetic and potential parts, rho = -T^{x4}_{x4}, p3, p_t (extra times), p8, the trace, the on-shell homogeneous forms rho = m S + U, p = S U' - U, w; the conservation nabla_mu T^mu_nu = 0 on shell (exact at test points with exact solutions or by the divergence identity in general). Canonical quantisation facts for dirac16complex (SPEC section 6): the momentum, the anticommutator with B, the proof that no positive inner product exists (indefinite Krein form), the good sector, the expectation-value rule. Every result as a named check in the report; the formulas in field-theory.json.`),
    () => run('theory-sympy', 'Theory', `Own ${R}/theory/python/ (check_field_theory.py and helpers, including your own Grassmann algebra), ${R}/theory/reports/python-field-theory.json. INDEPENDENTLY of the Wolfram agent (no shared code; you may read its report only at the end to compare), verify every item listed for the theory-wolfram agent with sympy for both statistics, using ${R}/algebra/gammas.json (cross-checked against your own construction if ${R}/algebra/reports/python-gammas.json exists). At the end compare every formula of ${R}/theory/field-theory.json (when it exists) with yours and record agreement check by check.`),
    () => run('a4-equations', 'Theory', `Own ${R}/field_equations_a4/ (wolfram/, python/, reports/, a4-equations.json). Derive exactly the field equations for a4[x4] (SPEC section 5): Einstein-Lovelock gravity sum_{k=1}^{3} alpha_k E_(k) + Lambda = kappa T with E_(k) = -P_(k)/2^(k+1) and the Lovelock tensors P_(k) of ${R}/gkd_lovelock/results/lovelock-tensors.json (computed with GKD; rebuild them from their exact monomial lists; ALSO recompute at least P_(1) and P_(2) independently in your own code as a check); the independent components (x1=x2=x3, x4, x5=x6=x7, x8, x4-x8), the a4 EVOLUTION equation (3-space minus extra-time component, a4'' sourced by kappa (p3 - p_t)), the CONSTRAINT (x4 component), the x8 component and the conditions on the x8-dependence of the source; for a general homogeneous source (rho, p3, p_t, p8 functions of x4 and x8), then for each field: dirac16complex (T as expectation values; leave the Kohn-Sham specialisation as a formula to be filled by the Kohn-Sham branch) and dirac16complex00 (classical bilinears, e.g. a homogeneous condensate), and Einstein gravity (alpha_2 = alpha_3 = 0) as a special case; which a4 the equations allow, in particular the exponentially deflating member a4 = A H x4 and the source it requires. Wolfram and an independent sympy check in two separate files; reports with named checks.`),
    () => run('pairing-wolfram', 'Theory', `Own ${R}/pairing/wolfram/, ${R}/pairing/reports/wolfram-pairing.json, ${R}/pairing/pairing-theory.json. Prove and verify exactly, for both statistics, in the metric of SPEC section 1 AND in a general (test) gravitational field: T1 (chirality map Gamma: L_{m,lambda}[Gamma Psi] = -L_{-m,-lambda}[Psi]; EL equations, T_mu nu -> -T_mu nu, J -> -J; the pair (Psi with (m,lambda), Gamma Psi with (-m,-lambda)) has zero total energy-momentum and charge for classical bilinears), T2 (Gamma combined with a Pin(4,4) reflection of character -1: (m, lambda) -> (-m, lambda), L -> +L, the mirror across the Z2 brane at the patch end z = pi/2 of the hidden coordinate), the quantum-level reading (the image field Gamma Psi carries the Krein metric -B; its own generators; no cancellation between two independently quantised universes) and an exact list of what the theorems do NOT establish (no creation process, rate or amplitude). Uses ${R}/algebra/gammas.json.`),
    () => run('pairing-sympy', 'Theory', `Own ${R}/pairing/python/, ${R}/pairing/reports/python-pairing.json. INDEPENDENTLY verify every item of the pairing-wolfram task with sympy (no shared code); compare with ${R}/pairing/pairing-theory.json at the end.`),
  ])
  phase('Documents')
  const docs = await parallel([
    ['doc-dirac16complex', `${R}/docs/DIRAC16COMPLEX_FIELD_THEORY.md (+ .tex, .pdf, registered in ${R}/pdf-specifications.json): the fermion dirac16complex field (16 complex anticommuting components; Pin(4,4) irrep; two inequivalent 8-dimensional Spin(4,4) irreps) in the author's primordial field: the Lagrangian, the coupling through the canonical spin connection, the exact covariant field equations (Euler-Lagrange) written out, non-triviality [1] with its proof, self-consistency, the energy-momentum tensor OPERATOR (canonical quantisation in 4+4, normal ordering, the Krein structure), kinetic energy, potential energy, pressure, energy density and equations of state, the field equations for a4[x4] with dirac16complex as the source, every formula with its check names, reproduction commands, what is not claimed.`],
    ['doc-dirac16complex00', `${R}/docs/DIRAC16COMPLEX00_FIELD_THEORY.md (+ .tex, .pdf, registered): the 'semi-classical' dirac16complex00 field (16 complex commuting components transforming as a Pin(4,4) spinor) in the author's primordial field: the Lagrangian, the coupling, the exact field equations, non-triviality [2] with its proof, self-consistency, the energy-momentum tensor (classical bilinears), kinetic and potential energy, pressure, energy density, equations of state, the field equations for a4[x4] with dirac16complex00 as the source, check names, reproduction, what is not claimed.`],
    ['doc-pair-proofs', `${R}/docs/PAIR_CREATION_PROOFS.md (+ .tex, .pdf, registered): the exact proof results for both fields (T1, T2, the quantum reading, and - if ${R}/kohn_sham results exist by then - a pointer to the Kohn-Sham level T3, otherwise T3 stated as to be added), each theorem with its complete proof and every hypothesis, the verification records, and a final section "What is proved and what is not": the author's request "PROVE that Universes of masses {+mass, -mass} are created in pairs" is answered exactly - the pairing theorems are proved; no creation process, rate or amplitude follows from these equations.`],
  ].map(([label, task]) => () => run(label, 'Documents', `Write ${task} Read every report of ${R}/algebra, ${R}/theory, ${R}/field_equations_a4 and ${R}/pairing first; numbers and formulas only from them. Build the PDF with --developer-layout --specifications ${R}/pdf-specifications.json (verify mode until warning-free), then --register (re-read the registry first; change only your entry). Write a publication test ${R}/tests/test_<document>_publication.py (md -> tex equals the builder output, the PDF registered, key statements present) and run it.`)))
  phase('Review')
  const lenses = [
    ['correctness', 'Re-derive the key steps yourself (vielbein, spin connection, gamma^mu Omega_mu, the Euler-Lagrange equations, the reality of L, the EMT, the a4 equations, T1/T2) and check every formula and number of the three documents against the Revision reports.'],
    ['honesty', 'Hunt for overclaims and for any mixing with the old stages (a number or file of the old stages used as a Revision result); the pair-creation answer exactly as SPEC section 0/9 demands; every hypothesis labelled.'],
    ['physics', 'Judge the physics: the non-triviality claims [1] and [2], the Krein structure, the semi-classical status of dirac16complex00, the a4 equations and which a4 they allow (the exponentially deflating extra times), consistency with the author metric and coordinate roles.'],
    ['reproducibility', 'From a fresh copy of the working tree in scratch, run every verifier, checker and test of Revision/algebra, theory, field_equations_a4, pairing, gkd_lovelock and the documents; rebuild the PDFs in verify mode; compare outputs byte for byte.'],
  ]
  const reviews = await parallel(lenses.map(([k, t]) => () => agent(`${COMMON}\nTASK (adversarial reviewer, lens ${k}; do not edit files): ${t} Report only real problems with concrete evidence.`, { label: 'review:' + k, phase: 'Review', schema: FINDINGS })))
  const findings = reviews.filter(Boolean).flatMap(r => r.findings || [])
  phase('Fix')
  const fix = findings.length ? await run('fix', 'Fix', `Findings (JSON): ${JSON.stringify(findings).slice(0, 80000)}\nRe-verify each; fix confirmed ones at their root inside ${R}/ (regenerate reports deterministically, rebuild and re-register PDFs, rerun tests); reject unconfirmed ones with evidence. One line per finding in key_results: FIXED / REJECTED (reason).`) : null
  return { theory, docs, findings, fix }
}

const ksBranch = async () => {
  phase('Kohn-Sham')
  const exact = await run('ks-exact', 'Kohn-Sham', `Own ${R}/kohn_sham/theory/ (Wolfram + an independent sympy file), ${R}/kohn_sham/reports/ks-theory-*.json, ${R}/kohn_sham/ks-theory.json. For dirac16complex in the author's metric (SPEC sections 1, 7): the hidden coordinate y (sin z = e^{6Hy}), the warped form with time-dependent a4, the stationary-slice ansatz at a fixed instant (instantaneous problem with a4,0 = a4(x4)), the removal of the spin connection by W^{-3}, the reduction of the 16-component Dirac operator to 2 x 2 blocks (find a basis that block-diagonalises gamma^(x8), gamma^(x8)gamma^(x1), gamma^(x8)gamma^(x4), C, B; the block labels and their relation to Gamma), the exact local exchange energy of the contact interaction in the uniform 8-fold gas (derive anew: Hartree-Fock with U = lambda/2 S^2, angular averaging) and the Kohn-Sham potentials, the boundary conditions (the Z2 mirror at y = 0, labelled ASSUMED; a regular tip at y = -L), the exact a4-rescaling identity between slices (a4,0 versus Delta k e^{-a4,0}), the instantaneous energy-momentum tensor of a Kohn-Sham state (rho, p3, p_t, p8 profiles) and the formulas the Rust solver must implement, the adiabaticity measure along a4 = A H x4. Checks in the reports; formulas in ks-theory.json for the solver.`)
  const rust = await run('ks-rust', 'Kohn-Sham', `Own ${R}/kohn_sham/solver/ (a NEW Rust crate, own empty [workspace]; you may read the old studies/dirac16complex_kohn_sham to recall the method but write the Revision crate anew and never import old code), outputs under ${R}/kohn_sham/results/. Implement SPEC section 7 from ${R}/kohn_sham/ks-theory.json: shooting (or the method you justify) for the 2 x 2 block equations in y with the Z2 and tip boundary conditions, the lattice of 3-space momenta, self-consistency with Anderson mixing, exact exchange, Mermin finite temperature, ground state and first excited state (Kohn-Sham gap, Delta-SCF, particle-hole list), thermodynamics, the energy-momentum tensor profiles; the INSTANTANEOUS states along the deflating history a4,0 in {0, 0.5, 1, 1.5, 2} (A = 1) for N in {8, a closed-shell middle value, a large closed-shell value} and couplings {0, +-lambda_1, +-lambda_2} calibrated as you document, with the adiabaticity measure; own checks (exact rescaling identity between slices, N conservation, EMT identities, free-field analytic spectra), repeat byte-identical, refined-tolerance run. Run the canonical matrix and report the times.`)
  const ref = await run('ks-reference', 'Kohn-Sham', `Own ${R}/kohn_sham/reference/ (an independent Python reference solver with a DIFFERENT discretisation, e.g. finite differences with Richardson extrapolation) and ${R}/kohn_sham/checker/ (a cross-checker comparing the Rust results with the reference within stated tolerances that include measured grid uncertainties), reports under ${R}/kohn_sham/reports/. Rust results (truncated): ${JSON.stringify(rust).slice(0, 3000)}. Run a representative subset of the matrix (state which) and the checker; report every failure honestly with its diagnosis; never weaken a tolerance to make a check pass.`)
  return { exact, rust, ref }
}

const gkdBranch = async () => {
  phase('GKD')
  return await run('gkd-verification', 'GKD', `Own ${R}/gkd_lovelock/verification/ and ${R}/gkd_lovelock/results/{python-lovelock-report.json, wolfram-gkd-report.json}. The files in ${R}/gkd_lovelock/verification_unfinished/ were written by a stopped agent and are UNVERIFIED: read them, finish or rewrite them as an independent sympy checker (own Christoffel/Riemann; the generalized delta evaluated LITERALLY as the determinant Det[Outer[delta, lower, upper]] of the author's definition; P_(2) also by the classical Gauss-Bonnet formula with the normalisation derived; exact comparison with the monomial lists of ${R}/gkd_lovelock/results/lovelock-tensors.json for all 3 x 64 mixed and 3 x 64 contravariant components) and a Wolfram check (the author's kδ re-typed verbatim compared with GKD on all index lists of length 1-3 and random ones up to 7; P_(1), P_(2) recomputed in Wolfram with kδ). Move the finished files to ${R}/gkd_lovelock/verification/, delete verification_unfinished/ when everything is replaced, run both, deterministic reports, a unittest ${R}/tests/test_gkd_lovelock.py. NEVER read the author's answers (output cells of the author's notebooks, Generalized_Kronecker_Delta.*).`)
}

const [T, K, L] = await parallel([() => theoryBranch(), () => ksBranch(), () => gkdBranch()])
return { algebra: { algW, algP }, theory: T, kohnSham: K, gkd: L }
