export const meta = {
  name: 'textbook-universes-in-pairs',
  description: 'The new deep-dive student textbook "Universes in Pairs" (md/tex/pdf) with a complete executed Jupyter notebook for every example, run instructions before each notebook, many plots; built from the Revision record; reviewed adversarially',
  phases: [
    { title: 'Infra', detail: 'nbkit, run-instruction generator, renderer, assembler, requirements, pilot through the PDF' },
    { title: 'Chapters', detail: 'per chapter: notebooks -> writer -> adversarial reviewer -> fixer' },
    { title: 'Assembly', detail: 'chapter 23, final ledger, assembled book, PDF, registration, tests' },
    { title: 'Book review', detail: 'six lenses, two skeptics per finding' },
    { title: 'Book fix', detail: 'per-chapter fixers, rebuild, fix verifier' },
  ],
}

const ROOT = 'D:/Developer/github/Dirac_claude'
const SP = 'C:/Users/nsh/AppData/Local/Temp/claude/D--Developer-github-Dirac-claude/9e0a6725-1ba0-4d61-be26-82d9c70a6ded/scratchpad'
const T = 'Revision/textbook'

const COMMON = `
RESTART NOTE: this workflow was stopped once and relaunched; files of the earlier run may exist (e.g. Revision/textbook/tools/run_instructions.py, requirements.txt): inspect, verify and finish them, never trust them unchecked.
CONTEXT: repository ${ROOT} (git, branch main). NEVER run git commands that change the index, the working tree or the remote (read-only git is fine). BINDING SPEC: ${ROOT}/${T}/TEXTBOOK_SPEC.md - read it COMPLETELY first (rules R0-R4: never modify the original textbook provenance/DIRAC16COMPLEX_TEXTBOOK.* or provenance/textbook/; the correct physics is the Revision record with the author's coordinates x1..x8 - x5, x6, x7 are the three EXTRA TIMES that DEFLATE EXPONENTIALLY, x8 hidden, x4 time; the HONESTY rule R3 about pair creation and matter-antimatter; R5: charge conjugation is a MATRIX (calC_+ = C, calC_- = Gamma C; for real fields plain complex conjugation is the identity - never call it charge conjugation); R6: a provenance file X.PROVENANCE.md next to every notebook; the deep-dive technique of section 1; one complete executed notebook per example, section 2; the complete self-contained run-instruction paragraph before each notebook, section 3; files and build, section 4). Also read ${ROOT}/Revision/SPEC.md sections 0-1 and ${ROOT}/Revision/README.md. The shared tools in ${ROOT}/${T}/tools/ and their README are owned by the infra agent: use them, never edit them (if a tool is wrong, work around it locally and report it in open_items). Tooling: Python 3.14 (numpy, sympy, mpmath, matplotlib, nbformat, nbclient, ipykernel, jupyterlab; NO scipy, NO Wolfram inside notebooks); Rust cargo 1.91 (the Revision crates: ${ROOT}/Revision/gkd_lovelock/code, ${ROOT}/Revision/kohn_sham/solver; build with cargo build --release --manifest-path ...; a stray Cargo.toml sits above the repository, the crates carry their own [workspace]); pdflatex (MiKTeX); PDFs only via python scripts/build_provenance_pdf.py <md> --developer-layout --number-sections-from-zero --specifications Revision/pdf-specifications.json (verify mode; only the assembly agent uses --register for the book). Deterministic outputs (two builds byte-identical, LF). Read files in chunks of at most 300 lines. Scratch only under ${SP}/textbook/<your label>/. Run long jobs and report their times; never wait idly. Numbers only from Revision records or from the notebooks' own computations (which must reproduce the Revision records where they overlap, with an assert naming the record file and check). Write in plain, precise English for a student who knows only school algebra and one-variable calculus.
`
const RESULT = { type: 'object', properties: { files_changed: { type: 'array', items: { type: 'string' } }, commands_run: { type: 'array', items: { type: 'string' } }, all_checks_pass: { type: 'boolean' }, failing: { type: 'array', items: { type: 'string' } }, key_results: { type: 'array', items: { type: 'string' } }, open_items: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' } }, required: ['files_changed', 'commands_run', 'all_checks_pass', 'failing', 'key_results', 'open_items', 'summary'] }
const FINDINGS = { type: 'object', properties: { findings: { type: 'array', items: { type: 'object', properties: { severity: { type: 'string', enum: ['critical', 'major', 'minor'] }, file: { type: 'string' }, location: { type: 'string' }, problem: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['severity', 'file', 'location', 'problem', 'evidence', 'fix'] } }, verified_ok: { type: 'array', items: { type: 'string' } } }, required: ['findings', 'verified_ok'] }
const VERDICT = { type: 'object', properties: { refuted: { type: 'boolean' }, reason: { type: 'string' }, evidence: { type: 'string' } }, required: ['refuted', 'reason', 'evidence'] }
const run = (label, ph, task) => agent(`${COMMON}\nTASK (${label}): ${task}`, { label, phase: ph, schema: RESULT })

const CHAPTERS = [
  ['00', 'How to use this book; installing the software; the honesty ledger (draft; the assembly agent finalises it)', ['00a']],
  ['01', 'Mathematics from zero I: numbers, complex numbers, vectors, matrices, indices, determinants, the generalized Kronecker delta', ['01a', '01b', '01c']],
  ['02', 'Mathematics from zero II: several variables, ODEs, Euler and RK4, convergence, the shooting method', ['02a', '02b']],
  ['03', "Spacetime geometry and the author's metric; curvature", ['03a', '03b']],
  ['04', "Clifford algebra Cl(4,4) and the author's T16", ['04a']],
  ['05', 'C, Gamma, B, S^ab; Pin(4,4) and Spin(4,4); the charge-conjugation MATRICES calC_+ = C and calC_- = Gamma C', ['05a', '05b', '05c']],
  ['06', 'Spinors in curved 4+4 space: vielbein, spin connection, gamma^mu Omega_mu = 3 H gamma^(x8)', ['06a']],
  ['07', 'The two fields and their Lagrangians; Grassmann numbers; Euler-Lagrange equations', ['07a', '07b']],
  ['08', 'Non-triviality, its exact scope, and well-posedness', ['08a']],
  ['09', 'The energy-momentum tensor, pressures, equations of state, conservation identities', ['09a', '09b']],
  ['10', 'Canonical quantisation in 4+4: Krein space and the good sector', ['10a']],
  ['11', 'GKD and the Lovelock tensors', ['11a', '11b']],
  ['12', 'The field equations for a4: Einstein and Einstein-Lovelock', ['12a', '12b', '12c']],
  ['13', 'Many-body quantum mechanics and DFT from zero', ['13a', '13b']],
  ['14', 'The Kohn-Sham model of dirac16complex in the deflating primordial field', ['14a', '14b']],
  ['15', 'Solving the Kohn-Sham equations along the deflating history', ['15a', '15b', '15c', '15d']],
  ['16', 'Checking the solution independently: the reference solver and the cross-check', ['16a']],
  ['17', 'The a4 equations with the Kohn-Sham source: a prescribed background', ['17a']],
  ['18', 'The pairing theorems T1, T2 and Q', ['18a']],
  ['19', 'T3: the Kohn-Sham universes of mass +M and -M', ['19a']],
  ['20', 'Do universes come in pairs? What the equations prove and what they do not', ['20a']],
  ['21', 'Matter and antimatter from zero: what this theory explains and what it does not (charge conjugation is a MATRIX, R5)', ['21a', '21b', '21c']],
  ['22', 'Open problems and how a student could attack them', ['22a']],
]

// ---------------- Infra ----------------
phase('Infra')
const infra = await run('infra', 'Infra', `You own ${T}/tools/ (nbkit.py, run_instructions.py, render_notebook.py, assemble_textbook.py, check_chapter.py, README.md), ${T}/requirements.txt, ${T}/notebooks/src/00a_check_installation.py with its executed notebook ${T}/notebooks/00a_check_installation.ipynb and its figures, a PILOT chapter file ${T}/chapters/00-how-to-use-this-book.md (a short draft; the chapter-00 writer completes it later), and ${ROOT}/Revision/tests/test_universes_in_pairs_textbook.py (initial version). Build, following TEXTBOOK_SPEC sections 2-4 exactly:
(1) nbkit.py - a notebook is defined in a builder file by a list of markdown and code cells plus a FACTS dict (id, title, packages, needs_rust with the crate manifest paths and binary names, expected run time, files written, the final PASS lines the student must see, notebook-specific troubleshooting); nbkit inserts the standard section 2 "How to run this notebook" markdown (from run_instructions) and the same instructions as # comments at the top of the first code cell together with a standard, self-contained preamble (imports, the repository root found by walking up from the notebook folder, a save_figure(fig, name, caption) helper that writes ${T}/figures/<id>_<k>_<name>.png with dpi 150 and metadata stripped and records the caption in a sidecar ${T}/figures/<id>.captions.json, and shows the figure inline); executes with nbclient (kernel python3, timeout per notebook from FACTS, cwd = the notebooks folder, MPLBACKEND set so that inline PNGs are deterministic), normalises (no timing metadata, fixed kernelspec and language_info, sorted keys, LF), writes the .ipynb, and offers --check (rebuild into scratch and compare byte for byte with the committed notebook and figures). Enforce: source lines <= 89 characters, no tabs, ASCII in code cells, every code cell preceded by a markdown cell.
(2) run_instructions.py - the template of TEXTBOOK_SPEC section 3, COMPLETE and SELF-CONTAINED (never "see section X" or "see file Y"): requirements with pinned versions, git clone, private environment creation and package installation for Windows PowerShell, macOS zsh and Linux bash (exact commands), Rust installation and the exact cargo build commands when needed, starting JupyterLab in the right folder, Run > Run All Cells, the headless alternative (jupyter nbconvert --to notebook --execute --inplace ...), run time, files written, the final lines to expect, troubleshooting. Three renderings from the same facts: the book paragraph, the notebook markdown section, the code comments.
(3) render_notebook.py - the executed notebook -> the book's markdown for the marker <!-- NOTEBOOK NN<x> -->: the section "How to run Notebook NN<x>" (the paragraph), then "Notebook NN<x>: complete text" with every cell in order (markdown cells as fenced text blocks, code cells as fenced python blocks headed In [k]:, text outputs as fenced text blocks headed Out [k]:, and each saved figure as a book figure line with its caption from the sidecar). Section headings must fit the chapter's "### N.M" numbering: the renderer takes the next section numbers from the chapter.
(4) assemble_textbook.py - builds ${T}/UNIVERSES_IN_PAIRS_TEXTBOOK.md (title block per TEXTBOOK_SPEC R1, abstract, chapters 00..23 in order, markers expanded) with every check of section 4 and a --check mode; check_chapter.py - test-build ONE chapter alone (with its notebooks expanded) in scratch through scripts/build_provenance_pdf.py in a throw-away registry copy, reporting warnings.
(5) requirements.txt pinned to the installed versions (numpy, sympy, mpmath, matplotlib, jupyterlab, nbformat, nbclient, ipykernel and what they need to run).
(6) The PILOT: notebook 00a (prints the versions of Python and every package and of cargo if present, draws two simple teaching plots, ends with PASS lines), the draft chapter 00 with the marker, assembled into a book with just chapter 00, built through the PDF builder in VERIFY mode on a scratch registry copy until warning-free, two builds byte-identical; nbkit --check reproduces the notebook byte for byte. Read scripts/build_dissertation_tex.py's header and test what it accepts (long fenced blocks, In/Out headings, figures, underscores, unicode) and constrain the tools accordingly.
(6b) PROVENANCE (TEXTBOOK_SPEC R6): nbkit writes X.PROVENANCE.md next to every notebook from the FACTS and the recorded execution (what it computes and from which Revision records; the complete student instructions; the expected output: every PASS line, every figure with caption, key numbers; the side effects: every file created or overwritten, Rust build directories and binaries, caches, network access, measured run time and peak memory; the environment versions; sha256 of the notebook and each figure; the nbkit --check result); deterministic (no wall-clock date inside the file other than the recorded verification date passed explicitly), and nbkit --check also checks the provenance file.
(7) tools/README.md: the exact API and the workflow for chapter agents (how to write a builder, how to build and check a notebook, how to place markers, how to test-build a chapter), with a complete minimal example.`)

// ---------------- Chapters ----------------
phase('Chapters')
const chapterResults = await pipeline(
  CHAPTERS,
  ([nn, title, nbs]) => run(`nb:${nn}`, 'Chapters', `You own the notebooks ${nbs.map(n => `${T}/notebooks/src/${n}_*.py and ${T}/notebooks/${n}_*.ipynb`).join(', ')} and their figures ${T}/figures/${nn}*. Chapter ${nn}: "${title}". Read TEXTBOOK_SPEC section 5 for chapter ${nn} (its examples and its Revision sources - read those sources FULLY), ${T}/tools/README.md, and the original textbook's corresponding chapter in provenance/textbook/chapters/ for pedagogy only (translate its x0..x7 indices to the author's x1..x8 and replace any static/frozen extra-time model by the deflating one). Infra summary: ${JSON.stringify(infra && infra.summary || '').slice(0, 1500)}. Write one builder per example (${nbs.join(', ')}; you may add examples - letters after the last - if the chapter needs more worked examples; every example of the chapter must have its notebook) and build every notebook with nbkit (executed, with outputs). Each notebook: the rustSolveIt-style numbered sections of TEXTBOOK_SPEC section 2, small cells each preceded by a markdown cell, comments on every non-obvious line, asserts with printed PASS lines (naming the Revision record file and check wherever the computation reproduces one - and it must reproduce the Revision numbers it overlaps), and MANY TEACHING PLOTS saved with save_figure and good captions (at least 4 figures for the chapter in total; more where they teach). Notebooks that run the Revision Rust programs build them with cargo inside the notebook when the binary is missing and say so in their FACTS. Run nbkit --check on every notebook (byte-identical rebuild) and report run times, figure count, PASS counts.`),
  (nbRes, [nn, title, nbs]) => run(`write:${nn}`, 'Chapters', `You own ${T}/chapters/${nn}-*.md (chapter ${nn}: "${title}"; create it, or complete the pilot draft for chapter 00). The notebooks and figures of this chapter are finished: ${JSON.stringify(nbRes && { key: nbRes.key_results, open: nbRes.open_items, files: nbRes.files_changed } || {}).slice(0, 6000)}. Read TEXTBOOK_SPEC completely (sections 1, 3 and 4 above all), ${T}/tools/README.md, every notebook of this chapter (all cells and outputs), the chapter's Revision sources FULLY, and the original textbook's chapter for pedagogy only. Write the chapter with the DEEP-DIVE technique: motivation in plain words; every notion defined before use; every derivation line by line, each line followed by the rule that produced it; the place of each notebook as a marker <!-- NOTEBOOK ${nn}<x> --> followed by a section "Line-by-line walk-through of Notebook ${nn}<x>" explaining EVERY line or small group of lines of EVERY code cell; every figure of the chapter included with a caption that says what is plotted, the axes and units, and what the student should see and why; statuses PROVED / COMPUTED / ASSUMED / HYPOTHESIS / OPEN with the record file and check; the closing "What we proved, what we computed, what we assumed"; at least 5 exercises with complete worked answers. Obey R3 exactly where the chapter touches pair creation or matter-antimatter. Test-build the chapter alone with tools/check_chapter.py until warning-free; report its page count.`),
  (wRes, [nn, title, nbs]) => agent(`${COMMON}\nTASK (adversarial reviewer of chapter ${nn}; do not edit files): Review chapter ${T}/chapters/${nn}-*.md and its notebooks ${nbs.join(', ')} (and any added ones) against TEXTBOOK_SPEC. (a) Re-execute every notebook of the chapter with nbkit --check from a clean state (byte identity) and report its time; (b) re-derive the chapter's key derivations yourself and check every formula and number against the Revision records it cites; (c) the deep-dive standard: any skipped step, any undefined word, any code line not explained in the walk-through, any figure without a teaching caption; (d) the run-instruction paragraph and the notebook's own instructions: complete and self-contained for Windows, macOS and Linux (try the commands that can be tried here), no reference to any other place; (e) R2 (author's coordinates, deflating extra times, no old-stage result), R3 (no overclaim about pair creation or matter-antimatter) and R5 (charge conjugation as a MATRIX; never 'complex conjugation is charge conjugation'); (e2) R6: every notebook's PROVENANCE.md exists, is complete (instructions, expected output, side effects) and matches a fresh execution; (f) exercises and answers correct. Writer summary: ${JSON.stringify(wRes && wRes.summary || '').slice(0, 1500)}. Report only real problems with concrete evidence.`, { label: `review:${nn}`, phase: 'Chapters', schema: FINDINGS }),
  (rev, [nn, title, nbs]) => (rev && rev.findings && rev.findings.length)
    ? run(`fix:${nn}`, 'Chapters', `You own chapter ${nn} (${T}/chapters/${nn}-*.md), its notebook builders and notebooks (${nbs.join(', ')} and added ones) and its figures. Reviewer findings (JSON): ${JSON.stringify(rev.findings).slice(0, 60000)}\nRe-verify each finding; fix confirmed ones at the root (rebuild the notebooks with nbkit and --check them, re-test-build the chapter warning-free); reject unconfirmed ones with evidence. One line per finding in key_results: FIXED / REJECTED (reason).`)
    : { files_changed: [], commands_run: [], all_checks_pass: true, failing: [], key_results: ['no findings'], open_items: [], summary: `chapter ${nn}: no reviewer findings` },
)
log(`chapters done: ${chapterResults.filter(Boolean).length} of ${CHAPTERS.length}`)

// ---------------- Assembly ----------------
phase('Assembly')
const assembly = await run('assembly', 'Assembly', `You own ${T}/chapters/23-*.md with notebook 23a (${T}/notebooks/src/23a_*.py: runs every notebook of the book headless with nbkit --check and shows a table and a timing bar chart), the FINAL honesty ledger table in chapter 00 (edit only that table and the chapter-00 lines that point to it), ${T}/UNIVERSES_IN_PAIRS_TEXTBOOK.{md,tex,pdf}, its registry entry in Revision/pdf-specifications.json (edition universes-in-pairs-textbook; re-read the registry first and change only this entry) and ${ROOT}/Revision/tests/test_universes_in_pairs_textbook.py. Chapter results (truncated): ${JSON.stringify(chapterResults.map((r, i) => ({ ch: CHAPTERS[i][0], ok: r && r.all_checks_pass, key: r && r.key_results && r.key_results.slice(0, 6) }))).slice(0, 12000)}. Write chapter 23 (reproducing everything; glossary of every technical word of the book with a plain definition; index of notebooks and of Revision checks cited) with the deep-dive standard; finalise the ledger; run assemble_textbook.py (all checks), build the PDF in verify mode until warning-free and two builds byte-identical, then --register; finish the test (assembler output equals the committed .md; every fast notebook rebuilds byte-identically by default, all with REVISION_NOTEBOOKS_FULL=1; the PDF registered with its page count and sha256) and run it. Report pages, chapters, sections, notebooks, figures, total notebook run time.`)

// ---------------- Book review ----------------
phase('Book review')
const lenses = [
  ['correctness', 'Re-derive the key derivations of every chapter and check every formula and number against the Revision records; check the notebooks compute what the text says.'],
  ['honesty', 'R3, R2 and R5: hunt for any statement that plain complex conjugation is charge conjugation, for any overclaim about pair creation, the big bang, matter-antimatter, the Kohn-Sham background, non-triviality, quantum positivity; any old-stage result or the old x0..x7 numbering; any static or frozen extra times.'],
  ['deep-dive', 'Read the book as the student: any notion used before it is defined, any skipped step, any derivation line without its rule, any code line not explained, any exercise without a complete answer, any figure that does not teach.'],
  ['instructions', 'For EVERY notebook: its X.PROVENANCE.md (R6) exists and is complete and correct (instructions, expected output, side effects, hashes match the committed files); the paragraph just before its text is complete and self-contained (no reference to any other place in the book or any other file), correct for Windows, macOS and Linux; the same instructions are in the notebook (markdown section 2 and code comments); follow them literally in a fresh scratch environment for at least three notebooks of different kinds (pure Python, sympy-heavy, Rust-running) and report every step that fails.'],
  ['reproducibility', 'From a fresh git clone of https://github.com/once-ere/Dirac_claude.git plus a copy of the current working-tree Revision/ (excluding target/), rebuild every notebook with nbkit --check, re-run the assembler --check and the PDF build in verify mode, run python -m unittest discover -s Revision/tests; report every non-reproduced file.'],
  ['figures', 'Every figure: present in the book, readable (axes labelled with units, legend, title), caption accurate, numbers in it consistent with the text; count figures per chapter against the target (at least 4 per chapter, at least 100 in the book) and name chapters that need more plots and which plots would teach.'],
]
const judged = await pipeline(
  lenses,
  ([k, t]) => agent(`${COMMON}\nTASK (whole-book adversarial reviewer, lens ${k}; do not edit files): ${t} Book: ${T}/UNIVERSES_IN_PAIRS_TEXTBOOK.md (+ .pdf), chapters ${T}/chapters/, notebooks ${T}/notebooks/. Report only real problems with concrete evidence; name the chapter file in "file".`, { label: 'book-review:' + k, phase: 'Book review', schema: FINDINGS }),
  (rev, [k]) => parallel(((rev && rev.findings) || []).map((f, i) => () =>
    parallel(['re-derive or re-run it independently', 'check the cited evidence in the current files'].map((how, j) => () =>
      agent(`${COMMON}\nTASK (skeptic ${j + 1}; do not edit files): try to REFUTE this ${k} finding by trying to ${how}: ${JSON.stringify(f)}. refuted=true only if it is wrong or not a real problem; concrete evidence either way.`, { label: `skeptic:${k}:${i}:${j}`, phase: 'Book review', schema: VERDICT })))
      .then(vs => ({ ...f, lens: k, votes: vs.filter(Boolean), confirmed: vs.filter(Boolean).filter(v => !v.refuted).length >= 1 })))),
)
const all = judged.filter(Boolean).flat().filter(Boolean)
const confirmed = all.filter(f => f.confirmed)
log(`book review: ${all.length} findings, ${confirmed.length} confirmed`)

// ---------------- Book fix ----------------
phase('Book fix')
const chOf = f => { const m = String(f.file || '').match(/(?:chapters\/|notebooks\/(?:src\/)?|figures\/)(\d\d)/); return m ? m[1] : 'book' }
const groups = {}
confirmed.forEach(f => { (groups[chOf(f)] = groups[chOf(f)] || []).push(f) })
const fixes = await parallel(Object.keys(groups).filter(g => g !== 'book').map(g => () =>
  run(`book-fix:${g}`, 'Book fix', `You own chapter ${g} (${T}/chapters/${g}-*.md, its notebook builders, notebooks and figures). Confirmed whole-book findings with skeptic votes (JSON): ${JSON.stringify(groups[g]).slice(0, 60000)}\nFix each at the root (rebuild and --check the notebooks; add the plots asked for; re-test-build the chapter warning-free); reject only with evidence. One line per finding: FIXED / REJECTED (reason).`)))
const rebuild = await run('book-rebuild', 'Book fix', `You own the book-level files (${T}/tools/ for bug fixes only, ${T}/UNIVERSES_IN_PAIRS_TEXTBOOK.{md,tex,pdf}, the registry entry universes-in-pairs-textbook, the book test). Book-level confirmed findings (JSON): ${JSON.stringify(groups.book || []).slice(0, 40000)}\nChapter fixers' reports (truncated): ${JSON.stringify(fixes.filter(Boolean).map(r => r.key_results)).slice(0, 20000)}\nFix the book-level findings; then re-assemble (all checks), rebuild the PDF in verify mode until warning-free and byte-identical, re-register, run python -m unittest discover -s Revision/tests and every notebook's nbkit --check. Report pages, figures, notebooks.`)
const fixCheck = await agent(`${COMMON}\nTASK (fix verifier; do not edit files): fixer reports ${JSON.stringify([...fixes.filter(Boolean), rebuild].map(r => r && r.key_results)).slice(0, 50000)}. Check every FIXED claim in the files, re-run the assembler --check, the book test and three notebooks' --check; report what is still wrong.`, { label: 'book-fix-verifier', phase: 'Book fix', schema: FINDINGS })
return { infra, chapters: chapterResults.map((r, i) => ({ ch: CHAPTERS[i][0], ok: r && r.all_checks_pass, summary: r && r.summary })), assembly, findings: all.length, confirmed: confirmed.length, fixes, rebuild, fixCheck }
