import numpy as np, json, itertools
np.set_printoptions(linewidth=200, precision=6, suppress=True)
fx=json.load(open(r'C:/Users/nsh/Developer/github/Dirac_claude/artifacts/dirac16complex/arbitrary-field/algebra-fixture.json'))
g=[np.array(m,dtype=float) for m in fx['gamma']]
C=np.array(fx['C'],dtype=float); eta=np.diag([1,1,1,1,-1,-1,-1,-1.])
assert all(np.allclose(g[a]@g[b]+g[b]@g[a],2*eta[a,b]*np.eye(16)) for a in range(8) for b in range(8))
B=-1j*C@g[4]
# --- (2) 1D KS reduction: stationary equation in y with k along x1 (good sector, a4=0, W=1 at the point):
# gamma^0 (d_y chi) + gamma^1 * kappa * chi = (M - i E gamma^4)... derive: Dirac eq gamma^mu D_mu Psi = M Psi with Psi = e^{-iEx4}chi(y)e^{ikx1}:
# gamma^0 chi' + i k gamma^1 chi - i E gamma^4 chi = M chi  (after W-rescaling; gamma^4 d_4 -> -iE gamma^4)
# => chi' = gamma^0 (M chi - i k gamma^1 chi + i E gamma^4 chi)   (gamma^0^2 = +1)
# The matrices gamma^0, gamma^0 gamma^1, gamma^0 gamma^4 : find the commutant / block structure.
A0=g[0]; A1=g[0]@g[1]; A4=g[0]@g[4]
def commutant_dim(mats):
    n=16; rows=[]
    for M in mats:
        # X M - M X = 0, X flattened row-major: (I kron M^T - M kron I) vec? use explicit
        L=np.kron(np.eye(n),M.T)-np.kron(M,np.eye(n))  # acts on vec(X) with vec row-major? use column-major consistent: vec(XM)= (M^T kron I) vec(X), vec(MX)=(I kron M)vec(X)
        L=np.kron(M.T,np.eye(n))-np.kron(np.eye(n),M)
        rows.append(L)
    L=np.vstack(rows); s=np.linalg.svd(L,compute_uv=False); return int(np.sum(s<1e-9))
print("commutant dim of {g0, g0g1, g0g4}:",commutant_dim([A0,A1,A4]))
print("commutant dim of {g0, g0g1, g0g4, C}:",commutant_dim([A0,A1,A4,C]))
# Are the y-ODE matrices simultaneously block-diagonalizable into 4x4 blocks? check: algebra generated by A0,A1,A4 dimension
def algebra_dim(gens):
    basis=[np.eye(16)]
    frontier=[np.eye(16)]
    while frontier:
        new=[]
        for Bm in frontier:
            for G in gens:
                Mx=Bm@G
                # test independence
                V=np.array([b.flatten() for b in basis+[Mx]])
                if np.linalg.matrix_rank(V,tol=1e-9)>len(basis):
                    basis.append(Mx); new.append(Mx)
        frontier=new
    return len(basis)
print("dim of algebra generated by g0,g0g1,g0g4:",algebra_dim([A0,A1,A4]))
# --- (3) exchange structure of (lambda/2)(Psibar Psi)^2 for a uniform gas: E_HF = (lambda/2)[S^2 - Tr(rho C rho C)] with rho = sum_occ u u^dag (per volume)
# rest gas at k=0: occupied 8 positive-energy states -> rho = P_+ (projector onto E>0 rest states) times n/8 ; use h0 = -i m g4 with m=1
h0=-1j*g[4]; w,v=np.linalg.eigh(h0); P=v[:,w>0]@v[:,w>0].conj().T
S=np.trace(B@C@P).real   # <Psibar Psi> = Tr(B C rho) with expectation rule u^dag B M u -> Tr(B M rho)
ex=np.trace(B@C@P@B@C@P).real
print("rest gas: S per state-sum = Tr(BC P) =",S," exchange Tr(BCP BCP)=",ex, " ratio ex/S^2 =",ex/S**2)
# moving gas along x1 with k: h = -i m g4 - g4 g1 k
for k in (0.5,1.0,3.0):
    h=-1j*g[4]-g[4]@g[1]*k; w,v=np.linalg.eigh(h); P=v[:,w>0]@v[:,w>0].conj().T
    S=np.trace(B@C@P).real; ex=np.trace(B@C@P@B@C@P).real; E=np.sqrt(1+k*k)
    print(f"k={k}: S={S:.6f} (8m/E={8/E:.6f}) exchange={ex:.6f} ex/S^2={ex/S**2:.6f}")
