#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Independent exact checker of the matter-antimatter theorems M1-M4 (and the exact
content of M5/M6) of handoff/specs/MATTER_ANTIMATTER_SPEC.md, for BOTH statistics:

  dirac16complex    Grassmann-odd complex components (scripts/grassmann_algebra.py)
  dirac16complex00  commuting complex components (the CPoly class below)

Nothing produced by Wolfram is used as truth.  The gamma matrices are rebuilt from
CONTRACT section 1 (exact integers) and merely compared with the committed fixture
artifacts/dirac16complex/arbitrary-field/algebra-fixture.json.  Every solution space
is an exact nullspace over QQ (sympy DomainMatrix); every Lagrangian statement is a
polynomial identity in an explicit jet algebra with exact rational / Gaussian-rational
coefficients, in explicit curved gravitational fields built here from vielbein jets.

HONESTY.  The statement "the theory solves the matter-antimatter problem" is NOT
provable and is not claimed.  What this checker establishes (by computation):

  M1  L of STAGE5_SPEC (L1) is invariant under Psi -> e^{i alpha} Psi for every U(S);
      Noether current N^mu = i sqrt|g| Psibar gamma^mu Psi; the off-shell Noether
      identity d_mu N^mu = -sum(dPsi E + dPsi^* E^*) holds exactly on jets in curved
      fields (both statistics), hence d_mu(sqrt|g| j^mu) = 0 on shell: Q is conserved
      and no dynamics of L changes Q inside one universe.  The divergence identity
      d_mu(sqrt|g| gamma^mu) = sqrt|g| [gamma^mu, Omega_mu] is proved for arbitrary
      first vielbein jets (linearity: all 512 basis directions, exact integers).
  M2  Exact solution spaces of the charge-conjugation intertwining conditions, their
      action on L, K, S and j for both statistics; Pin(4,4) reflections with
      coordinate reflections (both lifts), time reversal (linear and antilinear), the
      CPT-like total inversion; the complete character table of the 1024 discrete
      maps generated by axis reflections, the internal chirality map and complex
      conjugation (matrix criterion, validated by jet computations).
  M3  Exact classification of Spin_0(4,4)-invariant bilinear forms (nullspace of
      S^{ab T} M + M S^{ab} = 0), their symmetry, their Pin(4,4) characters, which
      Psi^T M Psi and Psi^T M gamma^mu D_mu Psi survive for each statistics (U(1)
      charge 2), plus explicit Spin-invariant quartic examples of charge 2 and 4.
  M4  gamma^8: j -> -j, S -> S, K -> -K, L_{m,lam} -> -L_{-m,-lam}, EL and T_{mu nu}
      pairing (field level, curved jets, both statistics); exact good-sector mode facts
      at the Krein level (gamma^8 h_k(m) gamma^8 = h_k(-m), B -> -B); the Krein-level
      particle/antiparticle mapping is taken from the Stage-5 pairing-theory.json when
      it is present and final, and is recorded as OPEN otherwise.
  M5  The implication (H1-H3 are HYPOTHESES; none is derived here) is recorded with
      its exact ingredient (Q[gamma^8 Psi] = -Q[Psi]); eta ~ 6e-10 is NOT predicted.
  M6  Sakharov scorecard assembled from the computed checks.

Conventions (CONTRACT.md with errata section 11; STAGE5_SPEC.md):
  eta = diag(+1,+1,+1,+1,-1,-1,-1,-1), gamma^a = [[0, taubar_a],[tau_a, 0]],
  C = gamma^0 gamma^1 gamma^2 gamma^3, Psibar = Psi^dagger C, B = -i C gamma^4,
  gamma^8 = gamma^0 ... gamma^7, S^{ab} = (1/4)[gamma^a, gamma^b],
  Omega_mu = (1/2) omega_{mu ab} S^{ab}, omega_{mu ab} = eta_{ac} omega_mu^c_b,
  L = sqrt|g| [ (1/2)(Psibar gamma^mu D_mu Psi - (D_mu Psibar) gamma^mu Psi)
                - m Psibar Psi - U(Psibar Psi) ],  U = (lam/2) S^2 (+ (mu3/3) S^3
  in the U(1) and Noether checks, to exhibit a general U).
  Kinetic part K (weighted by sqrt|g|), scalar S = Psibar Psi, current
  j^mu = Psibar gamma^mu Psi (the Hermitian Stage-1 current is J^mu = -i j^mu).
  A map with K -> sigma_K K and S -> sigma_S S sends L_{m,lam} to
  sigma_K L_{sigma_S sigma_K m, sigma_K lam} (U even); j^4 -> q j^4.

Prints ``check_<name>=true|false``, ``measurement_<name>=...``, ``check_count``,
``failed_check_count``; exits nonzero on failure; writes
artifacts/dirac16complex/matter-antimatter/python-matter-antimatter-report.json.
When artifacts/dirac16complex/matter-antimatter/matter-antimatter-theory.json exists
(Wolfram), the check MA_agreesWithWolfram compares it with the results derived here;
otherwise measurement wolframAgreement=not-run.

Usage: python scripts/check_dirac16complex_matter_antimatter.py [--output PATH]
       [--theory PATH] [--fixture PATH] [--pairing PATH] [--families M1,M2,M3,M4]
       [--quick] [--no-write]
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import os
import random
import sys
import time
from fractions import Fraction

import numpy as np
import sympy as sp
from sympy import QQ
from sympy.polys.matrices import DomainMatrix

SCRIPT_DIRECTORY = os.path.dirname(os.path.abspath(__file__))
REPOSITORY_ROOT = os.path.dirname(SCRIPT_DIRECTORY)
sys.path.insert(0, SCRIPT_DIRECTORY)

from grassmann_algebra import GaussianRational, Grassmann, JetSpace, euler_lagrange_all  # noqa: E402
from grassmann_algebra import JetGrassmann  # noqa: E402

ARTIFACT_DIRECTORY = os.path.join(REPOSITORY_ROOT, "artifacts", "dirac16complex", "matter-antimatter")
DEFAULT_OUTPUT = os.path.join(ARTIFACT_DIRECTORY, "python-matter-antimatter-report.json")
DEFAULT_THEORY = os.path.join(ARTIFACT_DIRECTORY, "matter-antimatter-theory.json")
DEFAULT_FIXTURE = os.path.join(REPOSITORY_ROOT, "artifacts", "dirac16complex", "arbitrary-field",
                               "algebra-fixture.json")
PAIRING_DIRECTORY = os.path.join(REPOSITORY_ROOT, "artifacts", "dirac16complex", "pair-creation")
DEFAULT_PAIRING = os.path.join(PAIRING_DIRECTORY, "pairing-theory.json")
DEFAULT_PAIRING_REPORT = os.path.join(PAIRING_DIRECTORY, "wolfram-pairing-report.json")
PRODUCER = "scripts/check_dirac16complex_matter_antimatter.py"
SOURCE_FILES = ["scripts/check_dirac16complex_matter_antimatter.py", "scripts/grassmann_algebra.py"]
FAMILIES = ["M1", "M2", "M3", "M4"]
WOLFRAM_CHECK = "MA_agreesWithWolfram"
ETA = (1, 1, 1, 1, -1, -1, -1, -1)
SEED = 20260930
HALF = Fraction(1, 2)
I_UNIT = GaussianRational(Fraction(0), Fraction(1))
# exact unit-modulus phase e^{i alpha} with cos alpha = 3/5, sin alpha = 4/5
PHASE = GaussianRational(Fraction(3, 5), Fraction(4, 5))
MASS = Fraction(3, 2)
LAMBDA = Fraction(5, 7)
MU3 = Fraction(2, 3)
STATISTICS = ("grassmann", "commuting")


def relative(path):
    try:
        return os.path.relpath(os.path.abspath(path), REPOSITORY_ROOT).replace(os.sep, "/")
    except ValueError:
        return path.replace(os.sep, "/")


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for block in iter(lambda: handle.read(1 << 16), b""):
            digest.update(block)
    return digest.hexdigest()


class Recorder:
    """Named sub-checks (all computed, never assumed) and measurements of one family."""

    def __init__(self, family):
        self.family = family
        self.checks = {}
        self.measurements = {}

    def check(self, name, value, detail=None):
        key = "MA_%s_%s" % (self.family, name)
        if key in self.checks:
            raise KeyError(key)
        self.checks[key] = bool(value)
        if detail is not None:
            self.measurements[name] = detail
        return bool(value)

    def measure(self, name, value):
        if name in self.measurements:
            raise KeyError(name)
        self.measurements[name] = value
        return value

    def ok(self):
        return all(self.checks.values())


# ---------------------------------------------------------------------------
# 1. Gamma matrices from CONTRACT section 1 (own construction, exact integers)
# ---------------------------------------------------------------------------

def permutation_signature(sequence):
    """Mathematica Signature: sign of the sorting permutation, 0 if an entry repeats."""
    items = list(sequence)
    if len(set(items)) != len(items):
        return 0
    sign = 1
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            if items[i] > items[j]:
                sign = -sign
    return sign


def contract_gammas():
    """gamma^a = [[0, taubar_a], [tau_a, 0]] exactly as in CONTRACT section 1."""
    def qa(h):
        return np.array([[permutation_signature((h, p, q, 4)) for q in range(1, 5)] for p in range(1, 5)],
                        dtype=np.int64)

    def qb(h):
        return np.array([[(1 if (p == 4 and q == h) else 0) - (1 if (p == h and q == 4) else 0)
                          for q in range(1, 5)] for p in range(1, 5)], dtype=np.int64)

    zero4 = np.zeros((4, 4), dtype=np.int64)
    eye4 = np.eye(4, dtype=np.int64)
    tau = {0: np.eye(8, dtype=np.int64)}
    for h in (1, 2, 3):
        s4 = qa(h) - qb(h)
        t4 = qa(h) + qb(h)
        tau[h] = np.block([[zero4, s4], [s4, zero4]])
        tau[7 - h] = np.block([[zero4, t4], [-t4, zero4]])
    tau[7] = tau[1] @ tau[2] @ tau[3] @ tau[4] @ tau[5] @ tau[6]
    sigma = np.block([[zero4, eye4], [eye4, zero4]])
    taubar = {0: np.eye(8, dtype=np.int64)}
    for a in range(1, 8):
        taubar[a] = sigma @ tau[a].T @ sigma
    zero8 = np.zeros((8, 8), dtype=np.int64)
    return [np.block([[zero8, taubar[a]], [tau[a], zero8]]) for a in range(8)]


def parse_rational(value):
    if isinstance(value, int):
        return Fraction(value)
    if isinstance(value, str):
        return Fraction(value)
    raise TypeError("unexpected fixture entry %r" % (value,))


def fixture_matrix(rows):
    return [[parse_rational(v) for v in row] for row in rows]


class Algebra:
    """The exact Clifford module and the derived matrices (numpy int64 where integral)."""

    def __init__(self, fixture_path=DEFAULT_FIXTURE):
        self.fixture_path = fixture_path
        self.gam = contract_gammas()
        self.eta = np.diag(ETA).astype(np.int64)
        self.I16 = np.eye(16, dtype=np.int64)
        g = self.gam
        self.C = g[0] @ g[1] @ g[2] @ g[3]
        self.g8 = g[0] @ g[1] @ g[2] @ g[3] @ g[4] @ g[5] @ g[6] @ g[7]
        # 4 S^{ab} = [gamma^a, gamma^b] (integer); S4[a][b] for all ordered pairs
        self.S4 = [[g[a] @ g[b] - g[b] @ g[a] for b in range(8)] for a in range(8)]
        self.pairs = [(a, b) for a in range(8) for b in range(a + 1, 8)]
        # B = -i C gamma^4 = (real 0, imaginary -C gamma^4)
        self.B_imag = -(self.C @ g[4])
        self.Cg = [self.C @ g[a] for a in range(8)]
        self.Cg8 = self.C @ self.g8

    def gamma_lower(self, a):
        return ETA[a] * self.gam[a]

    def fixture_agreement(self):
        """Compare own construction with the committed fixture (not used as input)."""
        with open(self.fixture_path, "r", encoding="utf-8") as handle:
            fx = json.load(handle)
        out = {}
        out["gamma"] = all(fixture_matrix(fx["gamma"][a]) == self.gam[a].tolist() for a in range(8))
        out["C"] = fixture_matrix(fx["C"]) == self.C.tolist()
        out["chirality"] = fixture_matrix(fx["chirality"]) == self.g8.tolist()
        out["eta"] = fixture_matrix(fx["eta"]) == self.eta.tolist()
        s_ok = True
        for entry in fx["S"]:
            a, b = entry["a"], entry["b"]
            s_ok = s_ok and fixture_matrix(entry["matrix"]) == \
                [[Fraction(int(v), 4) for v in row] for row in self.S4[a][b].tolist()]
        out["S"] = s_ok and len(fx["S"]) == 28
        out["B"] = fixture_matrix(fx["B"]["real"]) == np.zeros((16, 16), dtype=np.int64).tolist() and \
            fixture_matrix(fx["B"]["imag"]) == self.B_imag.tolist()
        return out


# ---------------------------------------------------------------------------
# 2. Exact linear algebra (sympy DomainMatrix over QQ, sparse)
# ---------------------------------------------------------------------------

def to_qq(v):
    v = Fraction(v)
    return QQ(v.numerator, v.denominator)


def exact_nullspace(rows, ncols):
    """Basis (list of Fraction lists) of {x in QQ^ncols : sum_j row[j] x_j = 0 for every row}.
    ``rows`` is an iterable of dicts {column: rational}."""
    sdm = {}
    for row in rows:
        entries = {j: to_qq(v) for j, v in row.items() if v != 0}
        if entries:
            sdm[len(sdm)] = entries
    if not sdm:
        return [[Fraction(int(i == j)) for j in range(ncols)] for i in range(ncols)]
    basis = DomainMatrix(sdm, (len(sdm), ncols), QQ).nullspace()
    return [[Fraction(int(v.numerator), int(v.denominator)) for v in row] for row in basis.to_list()]


def exact_rank(vectors, ncols):
    """Rank over QQ of a list of Fraction vectors."""
    sdm = {}
    for vec in vectors:
        row = {j: to_qq(v) for j, v in enumerate(vec) if v != 0}
        if row:
            sdm[len(sdm)] = row
    if not sdm:
        return 0
    return DomainMatrix(sdm, (len(sdm), ncols), QQ).rank()


def primitive_integer(vec):
    """Scale a rational vector to coprime integers with the first nonzero entry positive."""
    den = 1
    for v in vec:
        v = Fraction(v)
        den = den * v.denominator // int(np.gcd(den, v.denominator))
    ints = [int(Fraction(v) * den) for v in vec]
    g = 0
    for v in ints:
        g = int(np.gcd(g, abs(v)))
    ints = [v // g for v in ints] if g else ints
    first = next((v for v in ints if v != 0), 0)
    return [-v for v in ints] if first < 0 else ints


def matrix_equations(terms, n=16):
    """Rows of the linear system sum_k (L_k X R_k)_{ij} = 0 (all i, j) for the unknown n x n
    matrix X (unknown index i*n + j).  ``terms`` = list of (coefficient, L, R); L or R None
    means the identity."""
    rows = []
    for i in range(n):
        for j in range(n):
            row = {}
            for coeff, left, right in terms:
                lrow = [(p, left[i][p]) for p in range(n) if left[i][p] != 0] if left is not None else [(i, 1)]
                rcol = [(q, right[q][j]) for q in range(n) if right[q][j] != 0] if right is not None else [(j, 1)]
                for p, lv in lrow:
                    for q, rv in rcol:
                        key = p * n + q
                        row[key] = row.get(key, 0) + Fraction(coeff) * Fraction(int(lv)) * Fraction(int(rv))
            rows.append(row)
    return rows


def vec_to_matrix(vec, n=16):
    return [[vec[i * n + j] for j in range(n)] for i in range(n)]


def matrix_to_vec(mat, n=16):
    return [Fraction(mat[i][j]) if isinstance(mat[i][j], Fraction) else Fraction(int(mat[i][j]))
            for i in range(n) for j in range(n)]


def proportional(vec, target):
    """True if vec = c * target for some nonzero rational c (target nonzero)."""
    c = None
    for v, t in zip(vec, target):
        v = Fraction(v)
        t = Fraction(t)
        if t == 0:
            if v != 0:
                return False
            continue
        r = v / t
        if c is None:
            c = r
        elif r != c:
            return False
    return c is not None and c != 0


def span_equal(basis, expected, ncols):
    """span(basis) == span(expected) over QQ."""
    rb = exact_rank(basis, ncols)
    rexp = exact_rank(expected, ncols)
    rj = exact_rank(list(basis) + list(expected), ncols)
    return rb == rexp == rj


def is_symmetric_int(m):
    return bool(np.array_equal(m, m.T))


def is_antisymmetric_int(m):
    return bool(np.array_equal(m, -m.T))


# ---------------------------------------------------------------------------
# 3. Commuting polynomial algebra (dirac16complex00) with the Grassmann API
# ---------------------------------------------------------------------------

class CPoly:
    """Commutative polynomial in generators; monomials are sorted tuples WITH repetition.
    Same method names as grassmann_algebra.Grassmann, so the Lagrangian code and
    grassmann_algebra.JetSpace.total_derivative work for both statistics."""

    __slots__ = ("terms",)

    def __init__(self, terms=None):
        self.terms = {} if terms is None else terms

    @staticmethod
    def gen(i, coeff=1):
        return CPoly({(i,): coeff}) if coeff != 0 else CPoly()

    @staticmethod
    def scalar(c):
        return CPoly({(): c}) if c != 0 else CPoly()

    def copy(self):
        return CPoly(dict(self.terms))

    def _iadd_term(self, m, c):
        if m in self.terms:
            v = self.terms[m] + c
            if v == 0:
                del self.terms[m]
            else:
                self.terms[m] = v
        elif c != 0:
            self.terms[m] = c

    def __add__(self, other):
        if not isinstance(other, CPoly):
            other = CPoly.scalar(other)
        r = self.copy()
        for m, c in other.terms.items():
            r._iadd_term(m, c)
        return r

    __radd__ = __add__

    def __neg__(self):
        return CPoly({m: -c for m, c in self.terms.items()})

    def __sub__(self, other):
        if not isinstance(other, CPoly):
            other = CPoly.scalar(other)
        return self + (-other)

    def scale(self, s):
        out = {}
        for m, c in self.terms.items():
            v = c * s
            if v != 0:
                out[m] = v
        return CPoly(out)

    def __mul__(self, other):
        if not isinstance(other, CPoly):
            return self.scale(other)
        r = CPoly()
        for m1, c1 in self.terms.items():
            for m2, c2 in other.terms.items():
                r._iadd_term(tuple(sorted(m1 + m2)), c1 * c2)
        return r

    def __rmul__(self, other):
        return self.scale(other)

    def __pow__(self, k):
        r = CPoly.scalar(1)
        for _ in range(k):
            r = r * self
        return r

    def is_zero(self, zero_test=None):
        return len(self.terms) == 0

    def __eq__(self, other):
        if not isinstance(other, CPoly):
            other = CPoly.scalar(other)
        return (self - other).is_zero()

    __hash__ = None

    def nterms(self):
        return len(self.terms)

    def generators(self):
        s = set()
        for m in self.terms:
            s.update(m)
        return s

    def left_derivative(self, k):
        """Ordinary partial derivative (no signs for commuting generators)."""
        out = CPoly()
        for m, c in self.terms.items():
            r = m.count(k)
            if r:
                pos = m.index(k)
                out._iadd_term(m[:pos] + m[pos + 1:], c * r)
        return out

    right_derivative = left_derivative

    def apply_generator_map_derivation(self, gmap):
        out = CPoly()
        for m, c in self.terms.items():
            for pos, g in enumerate(m):
                h = gmap(g)
                if h is None:
                    continue
                out._iadd_term(tuple(sorted(m[:pos] + (h,) + m[pos + 1:])), c)
        return out

    def apply_even_derivation(self, image):
        out = CPoly()
        for m, c in self.terms.items():
            for pos, g in enumerate(m):
                img = image(g)
                if img is None or img.nterms() == 0:
                    continue
                term = CPoly({m[:pos] + m[pos + 1:]: c}) * img
                for mm, cc in term.terms.items():
                    out._iadd_term(mm, cc)
        return out

    def conjugate(self, gconj, cconj=None):
        out = CPoly()
        for m, c in self.terms.items():
            cc = c.conjugate() if isinstance(c, GaussianRational) else c
            out._iadd_term(tuple(sorted(gconj(g) for g in m)), cc)
        return out


ALGEBRAS = {"grassmann": Grassmann, "commuting": CPoly}


def linear_element(alg, coeffs, gens):
    """sum_k coeffs[k] theta_{gens[k]}."""
    out = alg()
    for c, g in zip(coeffs, gens):
        if c != 0:
            out._iadd_term((g,), c)
    return out


def gen_list(alg, gens):
    return [alg.gen(g) for g in gens]


def matvec_elements(alg, mat, elems):
    """(mat . elems)_i = sum_j mat[i][j] elems[j] for algebra elements (a linear combination)."""
    out = []
    for i in range(len(mat)):
        acc = alg()
        for j in range(len(elems)):
            c = mat[i][j]
            if c != 0:
                for mm, cc in elems[j].terms.items():
                    acc._iadd_term(mm, cc * c)
        out.append(acc)
    return out


def scale_elements(elems, c):
    return [e.scale(c) for e in elems]


def add_elements(a, b):
    return [x + y for x, y in zip(a, b)]


def form(alg, X, left, right):
    """sum_{i,j} left_i X_ij right_j with the products taken in this order."""
    total = alg()
    for i in range(len(left)):
        if left[i].nterms() == 0:
            continue
        acc = alg()
        for j in range(len(right)):
            c = X[i][j]
            if c != 0:
                for mm, cc in right[j].terms.items():
                    acc._iadd_term(mm, cc * c)
        if acc.nterms():
            prod = left[i] * acc
            for mm, cc in prod.terms.items():
                total._iadd_term(mm, cc)
    return total


def substitute(F, alg, image):
    """Algebra homomorphism theta_g -> image(g) (linear elements), factor order kept."""
    out = alg()
    cache = {}
    for m, c in F.terms.items():
        prod = alg.scalar(c)
        for g in m:
            if g not in cache:
                cache[g] = image(g)
            prod = prod * cache[g]
            if prod.nterms() == 0:
                break
        for mm, cc in prod.terms.items():
            out._iadd_term(mm, cc)
    return out


def elements_equal(a, b):
    return (a - b).is_zero()


def sign_relation(new, old):
    """+1 if new == old, -1 if new == -old, 0 otherwise; None if old is zero."""
    if old.nterms() == 0:
        return None
    if elements_equal(new, old):
        return 1
    if elements_equal(new, -old):
        return -1
    return 0


# ---------------------------------------------------------------------------
# 4. Gravitational fields: exact first-order jets of every coefficient at x = 0
# ---------------------------------------------------------------------------

def frac_inverse(matrix):
    """Exact Gauss-Jordan inverse of a square Fraction matrix (list of lists)."""
    n = len(matrix)
    aug = [[Fraction(v) for v in row] + [Fraction(int(i == j)) for j in range(n)] for i, row in enumerate(matrix)]
    for col in range(n):
        piv = next(r for r in range(col, n) if aug[r][col] != 0)
        aug[col], aug[piv] = aug[piv], aug[col]
        pv = aug[col][col]
        aug[col] = [v / pv for v in aug[col]]
        for r in range(n):
            if r != col and aug[r][col] != 0:
                f = aug[r][col]
                aug[r] = [a - f * b for a, b in zip(aug[r], aug[col])]
    return [row[n:] for row in aug]


def frac_det(matrix):
    n = len(matrix)
    a = [[Fraction(v) for v in row] for row in matrix]
    det = Fraction(1)
    for col in range(n):
        piv = next((r for r in range(col, n) if a[r][col] != 0), None)
        if piv is None:
            return Fraction(0)
        if piv != col:
            a[col], a[piv] = a[piv], a[col]
            det = -det
        det *= a[col][col]
        for r in range(col + 1, n):
            f = a[r][col] / a[col][col]
            if f != 0:
                a[r] = [x - f * y for x, y in zip(a[r], a[col])]
    return det


def obj(array_like):
    return np.array(array_like, dtype=object)


def to_lists(array):
    """numpy object/int array -> nested lists of exact Python numbers."""
    return [[(Fraction(int(v)) if isinstance(v, (int, np.integer)) else v) for v in row] for row in array]


class Geometry:
    """Vielbein e_mu^a(x) = E0 + x^l E1[l] + (1/2) x^l x^k E2[l][k] (rows mu, columns a) and
    the exact values and first derivatives at x = 0 of sqrt|g|, gamma^mu, Omega_mu and the
    Lagrangian coefficient matrices (canonical spin connection of CONTRACT section 4)."""

    def __init__(self, alg, name, E0, E1, E2):
        self.alg = alg
        self.name = name
        eta = obj([[Fraction(ETA[i]) if i == j else Fraction(0) for j in range(8)] for i in range(8)])
        E0 = obj([[Fraction(v) for v in row] for row in E0])
        E1 = obj([[[Fraction(v) for v in row] for row in E1[l]] for l in range(8)])          # [l, mu, a]
        E2 = obj([[[[Fraction(v) for v in row] for row in E2[l][k]] for k in range(8)] for l in range(8)])
        self.E0, self.E1, self.E2 = E0, E1, E2
        Einv = obj(frac_inverse(E0.tolist()))                                                   # [a, mu]
        dEinv = obj([-(Einv.dot(E1[l]).dot(Einv)) for l in range(8)])                          # [k, a, mu]
        g0 = E0.dot(eta).dot(E0.T)
        dg = obj([E1[l].dot(eta).dot(E0.T) + E0.dot(eta).dot(E1[l].T) for l in range(8)])     # [l, mu, nu]
        ddg = obj([[E2[l, k].dot(eta).dot(E0.T) + E1[l].dot(eta).dot(E1[k].T) + E1[k].dot(eta).dot(E1[l].T)
                    + E0.dot(eta).dot(E2[l, k].T) for k in range(8)] for l in range(8)])       # [l, k, mu, nu]
        ginv = Einv.T.dot(eta).dot(Einv)
        dginv = obj([-(ginv.dot(dg[k]).dot(ginv)) for k in range(8)])
        # T[mu, nu, s] = d_mu g_{nu s} + d_nu g_{mu s} - d_s g_{mu nu}
        T = obj([[[dg[m, n, s] + dg[n, m, s] - dg[s, m, n] for s in range(8)] for n in range(8)] for m in range(8)])
        Gam = np.einsum("rs,mns->rmn", ginv, T) * HALF                                          # Gamma^r_{mn}
        dGam = []
        for k in range(8):
            Tk = obj([[[ddg[k, m, n, s] + ddg[k, n, m, s] - ddg[k, s, m, n] for s in range(8)]
                       for n in range(8)] for m in range(8)])
            dGam.append((np.einsum("rs,mns->rmn", dginv[k], T) + np.einsum("rs,mns->rmn", ginv, Tk)) * HALF)
        dGam = obj(dGam)
        # omega_mu^a_b = e_b^nu (Gamma^r_{mu nu} e_r^a - d_mu e_nu^a)
        om = np.einsum("bn,rmn,ra->mab", Einv, Gam, E0) - np.einsum("bn,mna->mab", Einv, E1)
        dom = []
        for k in range(8):
            dom.append(np.einsum("bn,rmn,ra->mab", dEinv[k], Gam, E0) + np.einsum("bn,rmn,ra->mab", Einv, dGam[k], E0)
                       + np.einsum("bn,rmn,ra->mab", Einv, Gam, E1[k]) - np.einsum("bn,mna->mab", dEinv[k], E1)
                       - np.einsum("bn,mna->mab", Einv, E2[k]))
        dom = obj(dom)
        etad = np.array([Fraction(v) for v in ETA], dtype=object)
        omlow = om * etad[None, :, None]
        domlow = dom * etad[None, None, :, None]
        S4 = obj([[alg.S4[a][b].tolist() for b in range(8)] for a in range(8)])                 # 4 S^{ab}
        G = obj([alg.gam[a].tolist() for a in range(8)])
        C = obj(alg.C.tolist())
        self.Omega = np.einsum("mab,abij->mij", omlow, S4) * Fraction(1, 8)                     # [mu, i, j]
        self.dOmega = obj([np.einsum("mab,abij->mij", domlow[k], S4) * Fraction(1, 8) for k in range(8)])
        self.gup = np.einsum("am,aij->mij", Einv, G)                                            # gamma^mu
        self.dgup = obj([np.einsum("am,aij->mij", dEinv[k], G) for k in range(8)])            # [k, mu, i, j]
        self.glow = np.einsum("ma,a,aij->mij", E0, etad, G)                                     # gamma_mu
        det0 = frac_det(E0.tolist())
        sign = 1 if det0 > 0 else -1
        self.sqrtg = sign * det0
        self.dsqrtg = [self.sqrtg * sum(Einv.dot(E1[k])[i, i] for i in range(8)) for k in range(8)]
        self.g0, self.ginv, self.Gam, self.omlow, self.domlow = g0, ginv, Gam, omlow, domlow
        self.Einv, self.dEinv, self.dg = Einv, dEinv, dg
        self.C = C
        # Lagrangian coefficient jets: dict {(): value, (k,): d_k value}
        sg, dsg = self.sqrtg, self.dsqrtg
        slash = sum(self.gup[m].dot(self.Omega[m]) for m in range(8))                         # gamma^mu Omega_mu
        slashR = sum(self.Omega[m].dot(self.gup[m]) for m in range(8))                        # Omega_mu gamma^mu
        self.slash, self.slashR = slash, slashR
        self.A = []
        for m in range(8):
            jet = {(): to_lists(C.dot(self.gup[m]) * sg)}
            for k in range(8):
                jet[(k,)] = to_lists(C.dot(self.gup[m]) * dsg[k] + C.dot(self.dgup[k, m]) * sg)
            self.A.append(jet)
        self.Bm = {(): to_lists(C.dot(slash) * sg)}
        self.Bp = {(): to_lists(C.dot(slashR) * sg)}
        self.Mc = {(): to_lists(C * sg)}
        self.sq = {(): sg}
        for k in range(8):
            ds = sum(self.dgup[k, m].dot(self.Omega[m]) + self.gup[m].dot(self.dOmega[k, m]) for m in range(8))
            dsR = sum(self.dOmega[k, m].dot(self.gup[m]) + self.Omega[m].dot(self.dgup[k, m]) for m in range(8))
            self.Bm[(k,)] = to_lists(C.dot(slash) * dsg[k] + C.dot(ds) * sg)
            self.Bp[(k,)] = to_lists(C.dot(slashR) * dsg[k] + C.dot(dsR) * sg)
            self.Mc[(k,)] = to_lists(C * dsg[k])
            self.sq[(k,)] = dsg[k]

    def matrix_checks(self):
        """Exact consistency of the geometry at x = 0."""
        out = {}
        out["inverseMetric"] = all(v == (1 if i == j else 0) for i, row in enumerate(self.ginv.dot(self.g0))
                                   for j, v in enumerate(row))
        out["omegaAntisymmetric"] = all(self.omlow[m, a, b] == -self.omlow[m, b, a]
                                        for m in range(8) for a in range(8) for b in range(8)) and \
            all(self.domlow[k, m, a, b] == -self.domlow[k, m, b, a]
                for k in range(8) for m in range(8) for a in range(8) for b in range(8))
        ok = True
        for m in range(8):
            for n in range(8):
                val = self.dgup[m, n] + sum(self.Gam[n, m, l] * self.gup[l] for l in range(8)) + \
                    self.Omega[m].dot(self.gup[n]) - self.gup[n].dot(self.Omega[m])
                ok = ok and all(v == 0 for v in val.flat)
        out["gammaCovariantlyConstant"] = ok
        lhs = sum(self.gup[m] * self.dsqrtg[m] + self.dgup[m, m] * self.sqrtg for m in range(8))
        rhs = (self.slash - self.slashR) * self.sqrtg
        out["divergenceIdentity"] = all(v == 0 for v in (lhs - rhs).flat)
        out["gammaMuOmegaMuNonzeroEntries"] = int(sum(1 for v in self.slash.flat if v != 0))
        out["riemannProxyOmegaGradientNonzero"] = int(sum(1 for v in self.dOmega.flat if v != 0))
        return out


def random_matrix(rng, lo, hi, density=1.0):
    return [[(rng.randint(lo, hi) if rng.random() < density else 0) for _ in range(8)] for _ in range(8)]


def geometry_generic(alg, seed=SEED):
    """G_A: a non-diagonal curved vielbein with space-space, space-time and time-time mixing."""
    rng = random.Random(seed)
    E0 = [[int(i == j) for j in range(8)] for i in range(8)]
    for (i, j, v) in ((0, 4, 1), (1, 5, -1), (2, 3, 1), (4, 6, 1), (3, 7, -1), (5, 6, 1), (0, 2, -1), (6, 7, 1)):
        E0[i][j] = v                                               # strictly upper triangular: det = 1
    E1 = [random_matrix(rng, -1, 1, 0.6) for _ in range(8)]
    E2 = [[None] * 8 for _ in range(8)]
    for l in range(8):
        for k in range(l, 8):
            E2[l][k] = random_matrix(rng, -1, 1, 0.3)
            E2[k][l] = E2[l][k]
    return Geometry(alg, "G_A_generic_nondiagonal", E0, E1, E2)


def geometry_diagonal(alg):
    """G_B: diagonal vielbein depending on x0 and x4 only (primordial-type); every reflection of
    x1, x2, x3, x5, x6, x7 is an isometry fixing x = 0."""
    h0 = [2, 1, 1, 1, 1, 1, 1, 1]
    d0 = [1, Fraction(1, 2), Fraction(1, 2), Fraction(1, 2), 0, Fraction(-1, 3), Fraction(-1, 3), Fraction(-1, 3)]
    d4 = [0, 1, 1, 1, 0, -1, -1, -1]
    E0 = [[h0[i] if i == j else 0 for j in range(8)] for i in range(8)]
    E1 = [[[0] * 8 for _ in range(8)] for _ in range(8)]
    for i in range(8):
        E1[0][i][i] = d0[i]
        E1[4][i][i] = d4[i]
    E2 = [[[[0] * 8 for _ in range(8)] for _ in range(8)] for _ in range(8)]
    for i in range(8):
        E2[0][0][i][i] = Fraction(i % 3, 2)
        E2[4][4][i][i] = Fraction(1 if i in (1, 2, 3) else 0)
        E2[0][4][i][i] = E2[4][0][i][i] = Fraction(-1 if i in (5, 6, 7) else 0, 2)
    return Geometry(alg, "G_B_diagonal_x0_x4", E0, E1, E2)


def divergence_identity_all_directions(alg, E0, notebook_contraction=False):
    """Proof of d_mu(sqrt|g| gamma^mu) = sqrt|g| [gamma^mu, Omega_mu] and D_mu gamma^nu = 0 at a
    point with e(0) = E0 (integer, |det| = 1) for ARBITRARY first derivatives d_l e_nu^a: both
    sides are linear in the 512 numbers d_l e_nu^a, so it suffices to verify all 512 basis
    directions.  Exact int64 arithmetic after multiplying by 16.  With notebook_contraction=True
    the mixed omega_mu^a_b replaces omega_{mu ab} (negative control; must fail)."""
    E0 = np.array(E0, dtype=np.int64)
    einv_f = frac_inverse(E0.tolist())
    assert all(v.denominator == 1 for row in einv_f for v in row)
    Einv = np.array([[int(v) for v in row] for row in einv_f], dtype=np.int64)
    det0 = int(frac_det(E0.tolist()))
    assert abs(det0) == 1
    eta = np.diag(ETA).astype(np.int64)
    G = np.array(alg.gam, dtype=np.int64)
    S4 = np.array([[alg.S4[a][b] for b in range(8)] for a in range(8)], dtype=np.int64)
    ginv = Einv.T @ eta @ Einv
    npd = 512
    BE = np.zeros((npd, 8, 8, 8), dtype=np.int64)                 # [p, l, nu, a]
    for p in range(npd):
        l, rest = divmod(p, 64)
        nu, a = divmod(rest, 8)
        BE[p, l, nu, a] = 1
    dg = np.einsum("plma,ab,nb->plmn", BE, eta, E0) + np.einsum("ma,ab,plnb->plmn", E0, eta, BE)
    # T[p, m, n, s] = dg[p, m, n, s] + dg[p, n, m, s] - dg[p, s, m, n]
    Tt = dg + np.transpose(dg, (0, 2, 1, 3)) - np.transpose(dg, (0, 2, 3, 1))
    Gam2 = np.einsum("rs,pmns->prmn", ginv, Tt)                   # 2 Gamma^r_{mn}
    om2 = np.einsum("bn,prmn,ra->pmab", Einv, Gam2, E0) - 2 * np.einsum("bn,pmna->pmab", Einv, BE)
    omlow2 = om2 * np.array(ETA, dtype=np.int64)[None, None, :, None]
    antisym = bool(np.array_equal(omlow2, -np.transpose(omlow2, (0, 1, 3, 2))))
    # negative control: the notebook contraction (mixed omega_mu^a_b with S^{ab}, CONTRACT 3.4)
    omega_used = om2 if notebook_contraction else omlow2
    Om16 = np.einsum("pmab,abij->pmij", omega_used, S4)           # 16 Omega_mu
    gup = np.einsum("am,aij->mij", Einv, G)
    dEinv = -np.einsum("ab,plbc,cm->plam", Einv, BE, Einv)        # d_l e_a^mu, [p, l, a, mu]
    dgup = np.einsum("plam,aij->plmij", dEinv, G)                  # d_l gamma^mu
    dsq = np.einsum("ab,plba->pl", Einv, BE)                      # |det| = 1: d_l sqrt|g| = tr(Einv d_l E)
    lhs16 = 16 * (np.einsum("pm,mij->pij", dsq, gup) + np.einsum("pmmij->pij", dgup))
    rhs16 = np.einsum("mij,pmjk->pik", gup, Om16) - np.einsum("pmij,mjk->pik", Om16, gup)
    div_ok = bool(np.array_equal(lhs16, rhs16))
    comm = np.einsum("pmij,njk->pmnik", Om16, gup) - np.einsum("nij,pmjk->pmnik", gup, Om16)
    dgamma16 = 16 * dgup + 8 * np.einsum("pnml,lij->pmnij", Gam2, gup) + comm
    cov_ok = bool(not np.any(dgamma16))
    nontrivial = int(np.count_nonzero(np.any(Om16 != 0, axis=(1, 2, 3))))
    return {"directions": npd, "omegaAntisymmetric": antisym, "divergenceIdentity": div_ok,
            "gammaCovariantlyConstant": cov_ok, "directionsWithNonzeroOmega": nontrivial}


class FlatGeometry:
    """Flat space in Cartesian coordinates, e_mu^a = delta: gamma^mu = gamma^a, Omega = 0."""

    def __init__(self, alg):
        self.alg = alg
        self.name = "flat"
        C = obj(alg.C.tolist())
        self.C = C
        self.gup = obj([alg.gam[a].tolist() for a in range(8)])
        self.glow = obj([(ETA[a] * alg.gam[a]).tolist() for a in range(8)])
        self.Omega = obj([np.zeros((16, 16), dtype=np.int64).tolist() for _ in range(8)])
        self.g0 = obj([[Fraction(ETA[i]) if i == j else Fraction(0) for j in range(8)] for i in range(8)])
        self.sqrtg = Fraction(1)
        zero = [[Fraction(0)] * 16 for _ in range(16)]
        self.A = []
        for m in range(8):
            jet = {(): to_lists(C.dot(self.gup[m]))}
            for k in range(8):
                jet[(k,)] = zero
            self.A.append(jet)
        self.Bm = {(): zero}
        self.Bp = {(): zero}
        self.Mc = {(): to_lists(C)}
        self.sq = {(): Fraction(1)}
        for k in range(8):
            self.Bm[(k,)] = zero
            self.Bp[(k,)] = zero
            self.Mc[(k,)] = zero
            self.sq[(k,)] = Fraction(0)


# ---------------------------------------------------------------------------
# 5. Field components, the Lagrangian L1, current, EMT (both statistics)
# ---------------------------------------------------------------------------

JET_KEYS = [()] + [(k,) for k in range(8)]


def field_components(alg, js):
    """Generator lists: P (Psi), Ps (Psi^*), dP[mu], dPs[mu] (first jets)."""
    return {"P": gen_list(alg, js.gens("psi")), "Ps": gen_list(alg, js.gens("psis")),
            "dP": [gen_list(alg, js.gens("psi", (m,))) for m in range(8)],
            "dPs": [gen_list(alg, js.gens("psis", (m,))) for m in range(8)]}


def potential(alg, S, lam, mu3):
    """U(S) = (lam/2) S^2 + (mu3/3) S^3 and U'(S) = lam S + mu3 S^2."""
    S2 = S * S
    U = S2.scale(lam * HALF)
    Up = S.scale(lam)
    if mu3:
        U = U + (S2 * S).scale(Fraction(mu3) / 3)
        Up = Up + S2.scale(mu3)
    return U, Up


def scalar_S(alg, geo, comps):
    return form(alg, to_lists(geo.C), comps["Ps"], comps["P"])


def lagrangian(alg, geo, comps, m, lam, mu3=0, keys=None):
    """Jet parts {key: element} of L (L1) and the pieces K (sqrt|g|-weighted kinetic) and S."""
    keys = [()] if keys is None else list(keys)
    P, Ps, dP, dPs = comps["P"], comps["Ps"], comps["dP"], comps["dPs"]
    S = scalar_S(alg, geo, comps)
    U, _ = potential(alg, S, lam, mu3)
    out = {}
    kin = {}
    for key in keys:
        K = alg()
        for mu in range(8):
            K = K + form(alg, geo.A[mu][key], Ps, dP[mu]) - form(alg, geo.A[mu][key], dPs[mu], P)
        K = K + form(alg, geo.Bm[key], Ps, P) + form(alg, geo.Bp[key], Ps, P)
        K = K.scale(HALF)
        kin[key] = K
        out[key] = K - form(alg, geo.Mc[key], Ps, P).scale(m) - U.scale(geo.sq[key])
    return out, kin, S


def lagrangian_value(alg, geo, comps, m, lam, mu3=0):
    L, K, S = lagrangian(alg, geo, comps, m, lam, mu3, keys=[()])
    return L[()], K[()], S


def current(alg, geo, comps, key=()):
    """sqrt|g| j^mu = sqrt|g| Psibar gamma^mu Psi (list over mu)."""
    return [form(alg, geo.A[mu][key], comps["Ps"], comps["P"]) for mu in range(8)]


def current_jet(alg, geo, comps):
    return [{key: form(alg, geo.A[mu][key], comps["Ps"], comps["P"]) for key in JET_KEYS} for mu in range(8)]


def jet_total_derivative(alg, jet, js, mu):
    """(d_mu F)(0) = explicit coefficient derivative + derivation on the field jets."""
    return jet.get((mu,), alg()) + js.total_derivative(jet[()], mu)


def euler_lagrange_generic(alg, Ljet, js, species):
    """E_a = d_L L/d theta_{s,a} - sum_mu d_mu (d_L L/d theta_{s,a;mu}) at the point (own code)."""
    res = []
    for a in range(16):
        g0 = js.idx(species, a)
        E = Ljet[()].left_derivative(g0)
        for mu in range(8):
            g = js.idx(species, a, (mu,))
            pi_val = Ljet[()].left_derivative(g)
            pi_mu = Ljet[(mu,)].left_derivative(g)
            E = E - (pi_mu + js.total_derivative(pi_val, mu))
        res.append(E)
    return res


def transform_components(alg, comps, R, anti=False, Lam=None, phase=None):
    """Psi'(x) = R Psi(Lam x) (linear) or R Psi^*(Lam x) (antilinear); R an exact matrix (Python
    numbers), Lam an 8 x 8 matrix (None = identity).  Returns the jets of Psi' at x = 0 as
    algebra elements (Psi'^* uses the complex conjugate matrix)."""
    Rl = [[v for v in row] for row in R]
    if phase is not None:
        Rl = [[v * phase for v in row] for row in Rl]
    Rc = [[conj_scalar(v) for v in row] for row in Rl]
    if Lam is None:
        Lam = [[int(i == j) for j in range(8)] for i in range(8)]
    src, srcs = ("Ps", "P") if anti else ("P", "Ps")
    dsrc, dsrcs = ("dPs", "dP") if anti else ("dP", "dPs")
    P = matvec_elements(alg, Rl, comps[src])
    Ps = matvec_elements(alg, Rc, comps[srcs])
    RdP = [matvec_elements(alg, Rl, comps[dsrc][b]) for b in range(8)]
    RdPs = [matvec_elements(alg, Rc, comps[dsrcs][b]) for b in range(8)]
    dP, dPs = [], []
    for a in range(8):
        acc = [alg() for _ in range(16)]
        accs = [alg() for _ in range(16)]
        for b in range(8):
            lv = Lam[b][a]
            if lv != 0:
                acc = add_elements(acc, scale_elements(RdP[b], lv))
                accs = add_elements(accs, scale_elements(RdPs[b], lv))
        dP.append(acc)
        dPs.append(accs)
    return {"P": P, "Ps": Ps, "dP": dP, "dPs": dPs}


def conj_scalar(c):
    return c.conjugate() if isinstance(c, GaussianRational) else c


def emt(alg, geo, comps, m, lam):
    """T_{mu nu} at the point (STAGE5_SPEC section 2 / CONTRACT section 7), list of 36 (mu <= nu)."""
    P, Ps, dP, dPs = comps["P"], comps["Ps"], comps["dP"], comps["dPs"]
    C = geo.C
    Om = [to_lists(geo.Omega[mu]) for mu in range(8)]
    DP = [add_elements(dP[nu], matvec_elements(alg, Om[nu], P)) for nu in range(8)]
    Ct = to_lists(C.T)
    DPb = []
    for nu in range(8):
        COmT = to_lists(C.dot(geo.Omega[nu]).T)
        DPb.append(add_elements(matvec_elements(alg, Ct, dPs[nu]), scale_elements(matvec_elements(alg, COmT, Ps), -1)))
    L, K, S = lagrangian(alg, geo, comps, m, lam, 0, keys=[()])
    Ls = L[()].scale(Fraction(1) / geo.sqrtg)
    Cgl = [to_lists(C.dot(geo.glow[mu])) for mu in range(8)]
    gl = [to_lists(geo.glow[mu]) for mu in range(8)]
    out = {}
    for mu in range(8):
        for nu in range(mu, 8):
            br = form(alg, Cgl[mu], Ps, DP[nu]) + form(alg, Cgl[nu], Ps, DP[mu]) \
                - form(alg, gl[nu], DPb[mu], P) - form(alg, gl[mu], DPb[nu], P)
            T = br.scale(Fraction(-1, 4)) + Ls.scale(geo.g0[mu, nu])
            out[(mu, nu)] = T
    return out


def derivative_table(alg, F):
    """{g: d_L F / d theta_g} for every generator g of F, in one pass (both statistics)."""
    out = {}
    if alg is Grassmann:
        for m, c in F.terms.items():
            for pos, g in enumerate(m):
                d = out.setdefault(g, Grassmann())
                d._iadd_term(m[:pos] + m[pos + 1:], c if pos % 2 == 0 else -c)
    else:
        for m, c in F.terms.items():
            seen = set()
            for pos, g in enumerate(m):
                if g in seen:
                    continue
                seen.add(g)
                d = out.setdefault(g, CPoly())
                d._iadd_term(m[:pos] + m[pos + 1:], c * m.count(g))
    return out


def euler_lagrange_fast(alg, Ljet, js, species):
    """Same as euler_lagrange_generic, with one derivative table per jet part."""
    tables = {key: derivative_table(alg, Ljet[key]) for key in JET_KEYS}
    empty = alg()
    res = []
    for a in range(16):
        E = tables[()].get(js.idx(species, a), empty).copy()
        for mu in range(8):
            g = js.idx(species, a, (mu,))
            E = E - (tables[(mu,)].get(g, empty) + js.total_derivative(tables[()].get(g, empty), mu))
        res.append(E)
    return res


# ---------------------------------------------------------------------------
# 6. M1: U(1) invariance, Noether current, current conservation in curved fields
# ---------------------------------------------------------------------------

def el_targets(alg, geo, comps, m, lam, mu3, stat_sign):
    """Closed forms: E^{Psi^*}_a = sqrt|g| (C (gamma^mu D_mu Psi - (m + U'(S)) Psi))_a and
    E^{Psi}_a = s sqrt|g| ((D_mu Psibar) gamma^mu + (m + U'(S)) Psibar)_a with s = +1 (Grassmann,
    left derivative) or -1 (commuting)."""
    P, Ps, dP, dPs = comps["P"], comps["Ps"], comps["dP"], comps["dPs"]
    S = scalar_S(alg, geo, comps)
    _, Up = potential(alg, S, lam, mu3)
    Meff = Up + alg.scalar(m) if m != 0 else Up
    CPsi = matvec_elements(alg, geo.Mc[()], P)                       # sqrt|g| C Psi
    PsbarRow = matvec_elements(alg, [list(r) for r in zip(*geo.Mc[()])], Ps)   # sqrt|g| (Psi^dagger C)_a
    tpsis, tpsi = [], []
    for a in range(16):
        t = alg()
        for mu in range(8):
            t = t + linear_combo(alg, geo.A[mu][()][a], dP[mu])
        t = t + linear_combo(alg, geo.Bm[()][a], P)
        t = t - Meff * CPsi[a]
        tpsis.append(t)
        u = alg()
        for mu in range(8):
            u = u + linear_combo(alg, [geo.A[mu][()][i][a] for i in range(16)], dPs[mu])
        u = u - linear_combo(alg, [geo.Bp[()][i][a] for i in range(16)], Ps)
        u = u + Meff * PsbarRow[a]
        tpsi.append(u.scale(stat_sign))
    return tpsis, tpsi


def linear_combo(alg, coeffs, elems):
    acc = alg()
    for c, e in zip(coeffs, elems):
        if c != 0:
            for mm, cc in e.terms.items():
                acc._iadd_term(mm, cc * c)
    return acc


def check_M1(alg, quick=False, geos=None):
    rec = Recorder("M1")
    if geos is None:
        geos = [geometry_generic(alg)] + ([] if quick else [geometry_diagonal(alg)])
    stats = {}
    for geo in geos:
        gchk = geo.matrix_checks()
        rec.check("geometry_%s" % geo.name, gchk["inverseMetric"] and gchk["omegaAntisymmetric"] and
                  gchk["gammaCovariantlyConstant"] and gchk["divergenceIdentity"] and
                  gchk["gammaMuOmegaMuNonzeroEntries"] > 0, gchk)
        for stat in STATISTICS:
            A = ALGEBRAS[stat]
            tag = "%s_%s" % (stat, geo.name)
            js = JetSpace(["psi", "psis"], max_deriv=2)
            comps = field_components(A, js)
            Ljet, Kjet, S = lagrangian(A, geo, comps, MASS, LAMBDA, MU3, keys=JET_KEYS)
            info = {"lagrangianMonomials": Ljet[()].nterms(), "U": "(lam/2) S^2 + (mu3/3) S^3",
                    "m": str(MASS), "lam": str(LAMBDA), "mu3": str(MU3)}
            # (1) finite U(1): Psi -> e^{i alpha} Psi, cos alpha = 3/5
            I16 = [[Fraction(int(i == j)) for j in range(16)] for i in range(16)]
            tc = transform_components(A, comps, I16, phase=PHASE)
            Lt, Kt, St = lagrangian(A, geo, tc, MASS, LAMBDA, MU3, keys=JET_KEYS)
            u1 = all(elements_equal(Lt[k], Ljet[k]) and elements_equal(Kt[k], Kjet[k]) for k in JET_KEYS) \
                and elements_equal(St, S) and not elements_equal(tc["P"][0], comps["P"][0])
            rec.check("u1Invariance_%s" % tag, u1 and Ljet[()].nterms() > 0)
            # (2) Noether current N^mu = sum_a [dPsi_a dL/d(d_mu Psi_a) + dPsi^*_a dL/d(d_mu Psi^*_a)]
            tables = {key: derivative_table(A, Ljet[key]) for key in JET_KEYS}
            empty = A()
            dpsi = [p.scale(I_UNIT) for p in comps["P"]]
            dpsis = [p.scale(-I_UNIT) for p in comps["Ps"]]
            N = []
            for mu in range(8):
                jet = {}
                for key in JET_KEYS:
                    acc = A()
                    for a in range(16):
                        acc = acc + dpsi[a] * tables[key].get(js.idx("psi", a, (mu,)), empty) + \
                            dpsis[a] * tables[key].get(js.idx("psis", a, (mu,)), empty)
                    jet[key] = acc
                N.append(jet)
            jj = current_jet(A, geo, comps)
            noether_form = all(elements_equal(N[mu][key], jj[mu][key].scale(I_UNIT)) for mu in range(8)
                               for key in JET_KEYS) and all(jj[mu][()].nterms() > 0 for mu in range(8))
            rec.check("noetherCurrentIsISqrtgPsibarGammaPsi_%s" % tag, noether_form)
            # (3) Euler-Lagrange expressions: own code, grassmann_algebra cross-check, closed forms
            Epsi = euler_lagrange_fast(A, Ljet, js, "psi")
            Epsis = euler_lagrange_fast(A, Ljet, js, "psis")
            cross = True
            if A is Grassmann:
                ref_psi = euler_lagrange_all(JetGrassmann(dict(Ljet)), js, "psi")
                ref_psis = euler_lagrange_all(JetGrassmann(dict(Ljet)), js, "psis")
                cross = all(elements_equal(x, y) for x, y in zip(Epsi, ref_psi)) and \
                    all(elements_equal(x, y) for x, y in zip(Epsis, ref_psis))
            if quick is False or A is CPoly:
                slow = euler_lagrange_generic(A, Ljet, js, "psis")
                cross = cross and all(elements_equal(x, y) for x, y in zip(slow, Epsis))
            rec.check("eulerLagrangeCrossCheck_%s" % tag, cross)
            ssign = 1 if A is Grassmann else -1
            tpsis, tpsi = el_targets(A, geo, comps, MASS, LAMBDA, MU3, ssign)
            rec.check("eulerLagrangeClosedForm_%s" % tag,
                      all(elements_equal(Epsis[a], tpsis[a]) and elements_equal(Epsi[a], tpsi[a]) for a in range(16))
                      and all(Epsis[a].nterms() > 0 for a in range(16)))
            # (4) off-shell Noether identity: d_mu N^mu = -sum_a (dPsi_a E^Psi_a + dPsi^*_a E^Psi*_a)
            divN = A()
            for mu in range(8):
                divN = divN + jet_total_derivative(A, N[mu], js, mu)
            rhs = A()
            for a in range(16):
                rhs = rhs - dpsi[a] * Epsi[a] - dpsis[a] * Epsis[a]
            rec.check("noetherIdentity_%s" % tag, elements_equal(divN, rhs) and divN.nterms() > 0)
            # (5) direct: d_mu(sqrt|g| j^mu) = sqrt|g| [(D Psibar) gamma Psi + Psibar gamma D Psi]
            #             = sum_a Psi^*_a E^Psi*_a + s sum_a E^Psi_a Psi_a   (vanishes on shell)
            divj = A()
            for mu in range(8):
                divj = divj + jet_total_derivative(A, jj[mu], js, mu)
            explicit = A()
            for mu in range(8):
                explicit = explicit + form(A, geo.A[mu][()], comps["dPs"][mu], comps["P"]) + \
                    form(A, geo.A[mu][()], comps["Ps"], comps["dP"][mu])
            diffB = [[x - y for x, y in zip(r1, r2)] for r1, r2 in zip(geo.Bm[()], geo.Bp[()])]
            explicit = explicit + form(A, diffB, comps["Ps"], comps["P"])
            onshell = A()
            for a in range(16):
                onshell = onshell + comps["Ps"][a] * Epsis[a] + (Epsi[a] * comps["P"][a]).scale(ssign)
            rec.check("currentDivergenceIdentity_%s" % tag, elements_equal(divj, explicit) and
                      elements_equal(divj, onshell) and elements_equal(divN, divj.scale(I_UNIT)))
            # (6) Hermiticity: L^* = L, (sqrt|g| j^mu)^* = - sqrt|g| j^mu (J^mu = -i j^mu Hermitian)
            cmap = js.conj_map({"psi": "psis", "psis": "psi"})
            herm = all(elements_equal(Ljet[key].conjugate(cmap), Ljet[key]) for key in JET_KEYS)
            anti = all(elements_equal(jj[mu][()].conjugate(cmap), -jj[mu][()]) for mu in range(8))
            rec.check("hermiticity_%s" % tag, herm and anti)
            info.update({"noetherDivergenceMonomials": divN.nterms(), "currentMonomials_mu4": jj[4][()].nterms(),
                         "eulerLagrangePsiStarMonomials_a0": Epsis[0].nterms(),
                         "eulerLagrangeSignConvention": "E^Psi uses the %s derivative: sign %+d" %
                         ("left Grassmann" if A is Grassmann else "ordinary", ssign)})
            stats[tag] = info
    rec.measure("perStatisticsAndGeometry", stats)
    # (7) the divergence identity for ARBITRARY first vielbein jets (linearity proof)
    identity = [[int(i == j) for j in range(8)] for i in range(8)]
    unimodular = [[int(i == j) for j in range(8)] for i in range(8)]
    for (i, j, v) in ((0, 4, 1), (1, 5, -1), (2, 3, 1), (4, 6, 1), (3, 7, -1), (5, 6, 1), (0, 2, -1), (6, 7, 1)):
        unimodular[i][j] = v
    proofs = {"E0_identity": divergence_identity_all_directions(alg, identity),
              "E0_unimodular_nondiagonal": divergence_identity_all_directions(alg, unimodular)}
    neg = divergence_identity_all_directions(alg, identity, notebook_contraction=True)
    rec.check("divergenceIdentityAllFirstJets", all(p["divergenceIdentity"] and p["gammaCovariantlyConstant"] and
                                                     p["omegaAntisymmetric"] for p in proofs.values()) and
              not neg["gammaCovariantlyConstant"],
              {"proofs": proofs, "negativeControlNotebookContraction": neg,
               "argument": "both sides are linear in the 512 first derivatives d_l e_nu^a at fixed e(0); all 512 "
                           "basis directions verified exactly; a constant GL(8) change of coordinates brings any "
                           "e(0) to the identity, under which both sides are scalar densities"})
    rec.measure("chargeConservation",
                "d_4 (sqrt|g| j^4) = - sum_{i != 4} d_i (sqrt|g| j^i) on shell (Noether identity above); "
                "Q = integral over a slice x4 = const of sqrt|g| j^4 (times i for the Hermitian J^4) is "
                "x4-independent when the flux through the boundary of the slice vanishes (assumption: decay "
                "or periodicity); hence no process described by L changes Q inside one universe")
    rec.measure("kohnShamRemark", "the Kohn-Sham states of Stages 4/5 are computed at fixed particle number N "
                                  "(chemical potential from N): cited from STAGE4_SPEC/STAGE5_SPEC, not recomputed here")
    return rec
