#!/usr/bin/env python3
"""Exact, sympy-based geometry engine for dirac16complex.

This module is an independent (non-Wolfram) implementation of the machinery fixed
in CONTRACT.md sections 1 and 4-7:

* the notebook gammas ``gamma^a := T16^A[a]`` built from the split-octonion
  blocks ``tau``/``taubar`` with sympy Integer matrices;
* ``C := sigma16 = gamma^0 gamma^1 gamma^2 gamma^3`` and ``S^{ab} = [gamma^a,gamma^b]/4``;
* vielbein ``e_mu^a`` (rows mu), metric, Levi-Civita Christoffels, the canonical
  spin connection ``omega_mu^a_b = e_b^nu (Gamma^rho_{mu nu} e_rho^a - d_mu e_nu^a)``
  and, independently, the same connection from the anholonomy (Ricci rotation)
  formula, which never uses Christoffels;
* ``Omega_mu = (1/2) omega_{mu ab} S^{ab}`` with ``omega_{mu ab} = eta_ac omega_mu^c_b``
  and the notebook contraction ``(1/2) omega_mu^a_b S^{ab}``;
* Riemann tensor, Ricci scalar, Einstein tensor, spinor curvature;
* the dirac16complex Lagrangian of CONTRACT section 5 (commuting proxy for the
  bilinear part), Euler-Lagrange derivatives in jet space, and the covariant
  energy-momentum tensor of CONTRACT section 7.

Exactness
---------
Everything is computed with exact arithmetic: sympy ``QQ`` (gmpy2 ``mpq``) for
rational evaluation points, and sympy rational-function fields
``QQ(w, c, E, A1, A2, A3, H)`` (or fields of symbolic metric components) for
symbolic evaluation.  No floating point number is created anywhere; the helper
``assert_exact`` is used by the verifiers to prove that.

Jets
----
Identities involving arbitrary functions are checked in jet space: every
quantity is represented by its truncated Taylor polynomial around the evaluation
point ``p`` (class ``TJet``), with exact coefficients.  The vielbein jets are
obtained by exact symbolic differentiation with sympy followed by exact
substitution of the evaluation point; all other jets follow by exact truncated
power-series arithmetic (products, matrix inverse by the Neumann series,
determinant by exp(tr log)).  Field jets (Psi_a, d_mu Psi_a, d_mu d_nu Psi_a)
are independent exact random rationals drawn from fixed seeds.

Conventions (CONTRACT.md): zero-based indices; eta = diag(1,1,1,1,-1,-1,-1,-1);
x4 is the evolution time; Taylor coefficient for the sorted multi-index
``alpha`` is ``d^alpha f(p) / alpha!``.
"""

from __future__ import annotations

import itertools
import math
import random
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np
import sympy as sp
from sympy import QQ

DIM = 8
NSPIN = 16
ETA_DIAG = (1, 1, 1, 1, -1, -1, -1, -1)
INF_ORDER = 10 ** 9
TIME_INDEX = 4

X = sp.symbols("x0:8")


# ---------------------------------------------------------------------------
# exact domains
# ---------------------------------------------------------------------------


class ExactDomain:
    """Wrapper around an exact sympy domain (QQ or a rational function field).

    ``relations`` is an optional list of sympy polynomial expressions (in the
    field generators) that vanish at the evaluation point; ``is_zero`` first
    tests exact zero and only then reduces the numerator modulo the ideal
    generated by the relations.  Every use of a relation is counted in
    ``relation_uses`` so the reports can state it honestly.
    """

    def __init__(self, K, name: str, relations: Optional[Sequence[sp.Expr]] = None):
        self.K = K
        self.name = name
        self.relation_uses = 0
        self._rel = []
        if relations:
            ring = K.field.ring
            self._rel = [ring.from_expr(r) for r in relations]
        self.one = K.one
        self.zero = K.zero

    def conv(self, x) -> object:
        """Convert a sympy number/expression (or int) into the domain."""
        if isinstance(x, int):
            return self.K.convert(x)
        return self.K.from_sympy(sp.sympify(x))

    def frac(self, p: int, q: int = 1):
        return self.K.convert(QQ(p, q)) if self.K != QQ else QQ(p, q)

    def is_zero(self, x) -> bool:
        if isinstance(x, bool):
            raise TypeError("boolean in exact array")
        if isinstance(x, int):
            return x == 0
        if x == 0:
            return True
        if not self._rel:
            return False
        num = x.numer
        if num.rem(self._rel) == 0:
            self.relation_uses += 1
            return True
        return False

    def to_sympy(self, x) -> sp.Expr:
        if isinstance(x, int):
            return sp.Integer(x)
        return self.K.to_sympy(x)

    def to_str(self, x) -> str:
        e = self.to_sympy(x)
        if e.is_Rational:
            return str(e)
        return str(sp.factor(e))


def make_qq_domain() -> ExactDomain:
    return ExactDomain(QQ, "QQ")


def assert_exact(arr) -> None:
    """Raise if any element is a float/complex (proof that no float leaked in)."""
    a = np.asarray(arr, dtype=object)
    for v in a.flat:
        if isinstance(v, (float, complex)):
            raise AssertionError("floating point value found in exact computation")
        tn = type(v).__name__
        if tn in ("mpfr", "mpc", "Float", "float64", "float32"):
            raise AssertionError("floating point value found: %r" % (v,))


def to_obj(a, dom: ExactDomain) -> np.ndarray:
    """Convert a sympy Matrix / nested list of ints/Rationals into a domain array."""
    arr = np.array(a, dtype=object)
    out = np.empty(arr.shape, dtype=object)
    for idx, v in np.ndenumerate(arr):
        out[idx] = dom.conv(v)
    return out


def arr_is_zero(a, dom: ExactDomain) -> bool:
    return all(dom.is_zero(v) for v in np.asarray(a, dtype=object).flat)


def count_nonzero(a, dom: ExactDomain) -> int:
    return sum(0 if dom.is_zero(v) else 1 for v in np.asarray(a, dtype=object).flat)


def _norm(x) -> np.ndarray:
    return np.asarray(x, dtype=object)


# ---------------------------------------------------------------------------
# notebook gamma matrices (CONTRACT section 1), sympy Integer matrices
# ---------------------------------------------------------------------------


def mathematica_signature(seq: Sequence[int]) -> int:
    seq = list(seq)
    if len(set(seq)) < len(seq):
        return 0
    sign = 1
    for i in range(len(seq)):
        for j in range(i + 1, len(seq)):
            if seq[i] > seq[j]:
                sign = -sign
    return sign


def notebook_gamma_sympy():
    """Return (gammas, sigma16, tau, taubar, sigma8) as sympy Integer matrices.

    Qa[h,p,q] = Signature[{h,p,q,4}], Qb[h,p,q] = d_{p4} d_{qh} - d_{ph} d_{q4}
    (1-based p,q,h as in the notebook), s4 = Qa - Qb, t4 = Qa + Qb,
    tau[0] = I8, tau[h] = [[0,s4],[s4,0]], tau[7-h] = [[0,t4],[-t4,0]] (h=1..3),
    tau[7] = tau1...tau6, sigma = [[0,I4],[I4,0]], taubar[A] = sigma tau[A]^T sigma,
    gamma^a = [[0, taubar[a]], [tau[a], 0]].
    """
    I4 = sp.eye(4)
    I8 = sp.eye(8)
    Z4 = sp.zeros(4, 4)
    Z8 = sp.zeros(8, 8)

    def delta(i, j):
        return 1 if i == j else 0

    def Qa(h, p, q):
        return mathematica_signature([h, p, q, 4])

    def Qb(h, p, q):
        return delta(p, 4) * delta(q, h) - delta(p, h) * delta(q, 4)

    s4 = {h: sp.Matrix(4, 4, lambda p, q: Qa(h, p + 1, q + 1) - Qb(h, p + 1, q + 1)) for h in (1, 2, 3)}
    t4 = {h: sp.Matrix(4, 4, lambda p, q: Qa(h, p + 1, q + 1) + Qb(h, p + 1, q + 1)) for h in (1, 2, 3)}
    tau = {0: I8}
    for h in (1, 2, 3):
        tau[h] = sp.Matrix(sp.BlockMatrix([[Z4, s4[h]], [s4[h], Z4]]))
        tau[7 - h] = sp.Matrix(sp.BlockMatrix([[Z4, t4[h]], [-t4[h], Z4]]))
    tau[7] = tau[1] * tau[2] * tau[3] * tau[4] * tau[5] * tau[6]
    sig = sp.Matrix(sp.BlockMatrix([[Z4, I4], [I4, Z4]]))
    taub = {0: I8}
    for A in range(1, 8):
        taub[A] = sig * tau[A].T * sig
    gam = [sp.Matrix(sp.BlockMatrix([[Z8, taub[A]], [tau[A], Z8]])) for A in range(8)]
    sig16 = sp.Matrix(sp.BlockMatrix([[-sig, Z8], [Z8, sig]]))
    return gam, sig16, tau, taub, sig


class GammaData:
    """Notebook gammas, C, S^{ab}, eta, chirality as exact domain arrays."""

    def __init__(self, dom: ExactDomain):
        self.dom = dom
        gam_s, sig16_s, tau_s, taub_s, sig_s = notebook_gamma_sympy()
        self.gam_sympy = gam_s
        self.sig16_sympy = sig16_s
        self.GAM = np.stack([to_obj(g.tolist(), dom) for g in gam_s])  # (8,16,16)
        self.C = to_obj((gam_s[0] * gam_s[1] * gam_s[2] * gam_s[3]).tolist(), dom)
        self.SIG16 = to_obj(sig16_s.tolist(), dom)
        self.ID16 = to_obj(sp.eye(16).tolist(), dom)
        self.ETA = to_obj(sp.diag(*ETA_DIAG).tolist(), dom)
        quarter = dom.frac(1, 4)
        S = np.empty((8, 8, 16, 16), dtype=object)
        for a in range(8):
            for b in range(8):
                S[a, b] = (self.GAM[a].dot(self.GAM[b]) - self.GAM[b].dot(self.GAM[a])) * quarter
        self.S = S
        chi = self.ID16
        for a in range(8):
            chi = chi.dot(self.GAM[a])
        self.CHI = chi


# ---------------------------------------------------------------------------
# exact linear algebra on object arrays
# ---------------------------------------------------------------------------


def mat_inv(M: np.ndarray, dom: ExactDomain) -> np.ndarray:
    n = M.shape[0]
    A = [[M[i, j] for j in range(n)] + [dom.one if i == j else dom.zero for j in range(n)] for i in range(n)]
    for col in range(n):
        piv = None
        for r in range(col, n):
            if not dom.is_zero(A[r][col]):
                piv = r
                break
        if piv is None:
            raise ZeroDivisionError("singular matrix")
        A[col], A[piv] = A[piv], A[col]
        pv = A[col][col]
        A[col] = [x / pv for x in A[col]]
        for r in range(n):
            if r != col:
                f = A[r][col]
                if f != 0:
                    A[r] = [x - f * y for x, y in zip(A[r], A[col])]
    return np.array([row[n:] for row in A], dtype=object)


def mat_det(M: np.ndarray, dom: ExactDomain):
    n = M.shape[0]
    A = [[M[i, j] for j in range(n)] for i in range(n)]
    det = dom.one
    for col in range(n):
        piv = None
        for r in range(col, n):
            if not dom.is_zero(A[r][col]):
                piv = r
                break
        if piv is None:
            return dom.zero
        if piv != col:
            A[col], A[piv] = A[piv], A[col]
            det = -det
        pv = A[col][col]
        det = det * pv
        for r in range(col + 1, n):
            f = A[r][col]
            if f != 0:
                q = f / pv
                A[r] = [x - q * y for x, y in zip(A[r], A[col])]
    return det


def symmetric_signature_rational(M: np.ndarray) -> Tuple[int, int, int]:
    """(n_plus, n_minus, n_zero) of a rational symmetric matrix, exactly.

    Uses the exact characteristic polynomial and Descartes' rule of signs, which
    is exact for polynomials whose roots are all real (real symmetric matrix).
    """
    Ms = sp.Matrix(M.shape[0], M.shape[1], lambda i, j: sp.Rational(int(M[i, j].numerator), int(M[i, j].denominator)))
    lam = sp.Symbol("lam")
    p = sp.Poly(Ms.charpoly(lam).as_expr(), lam)
    coeffs = p.all_coeffs()  # highest first
    nzero = 0
    while coeffs and coeffs[-1] == 0:
        coeffs.pop()
        nzero += 1

    def changes(cs):
        s = [c for c in cs if c != 0]
        return sum(1 for u, v in zip(s, s[1:]) if (u > 0) != (v > 0))

    npos = changes(coeffs)
    deg = len(coeffs) - 1
    neg_coeffs = [c * (-1) ** (deg - i) for i, c in enumerate(coeffs)]
    nneg = changes(neg_coeffs)
    return npos, nneg, nzero


# ---------------------------------------------------------------------------
# truncated Taylor jets
# ---------------------------------------------------------------------------


def multi_indices(order: int, n: int = DIM) -> List[Tuple[int, ...]]:
    out: List[Tuple[int, ...]] = [()]
    for k in range(1, order + 1):
        out.extend(itertools.combinations_with_replacement(range(n), k))
    return out


def alpha_factorial(alpha: Tuple[int, ...]) -> int:
    f = 1
    for i in set(alpha):
        f *= math.factorial(alpha.count(i))
    return f


class TJet:
    """Truncated Taylor polynomial sum_alpha c_alpha dx^alpha, |alpha| <= order.

    ``c`` maps sorted multi-index tuples to exact object arrays of one common
    shape; the key () (value at the point) is always present.
    """

    __slots__ = ("order", "c")

    def __init__(self, order: int, c: Dict[Tuple[int, ...], np.ndarray]):
        self.order = order
        self.c = c

    @staticmethod
    def const(value, order: int = INF_ORDER) -> "TJet":
        return TJet(order, {(): _norm(value)})

    @property
    def shape(self):
        return self.c[()].shape

    def value(self) -> np.ndarray:
        return self.c[()]

    def coeff(self, alpha: Tuple[int, ...]) -> np.ndarray:
        alpha = tuple(sorted(alpha))
        if alpha in self.c:
            return self.c[alpha]
        return np.zeros(self.shape, dtype=object)

    def partial(self, alpha: Tuple[int, ...]) -> np.ndarray:
        """The partial derivative d^alpha f(p) (= alpha! * Taylor coefficient)."""
        alpha = tuple(sorted(alpha))
        return _norm(self.coeff(alpha) * alpha_factorial(alpha))

    def truncate(self, order: int) -> "TJet":
        order = min(order, self.order)
        return TJet(order, {k: v for k, v in self.c.items() if len(k) <= order})

    def map(self, f: Callable) -> "TJet":
        return TJet(self.order, {k: _norm(f(v)) for k, v in self.c.items()})

    def __add__(self, other) -> "TJet":
        if not isinstance(other, TJet):
            other = TJet.const(other)
        order = min(self.order, other.order)
        c: Dict[Tuple[int, ...], np.ndarray] = {}
        for k, v in self.c.items():
            if len(k) <= order:
                c[k] = v
        for k, v in other.c.items():
            if len(k) <= order:
                c[k] = _norm(c[k] + v) if k in c else v
        return TJet(order, c)

    __radd__ = __add__

    def __neg__(self) -> "TJet":
        return self.map(lambda v: -v)

    def __sub__(self, other) -> "TJet":
        if not isinstance(other, TJet):
            other = TJet.const(other)
        return self + (-other)

    def __rsub__(self, other) -> "TJet":
        return (-self) + other

    def scale(self, s) -> "TJet":
        return self.map(lambda v: v * s)

    def d(self, mu: int) -> "TJet":
        order = self.order - 1 if self.order < INF_ORDER else INF_ORDER
        if order < 0:
            raise ValueError("derivative of an order-0 jet is not available")
        c: Dict[Tuple[int, ...], np.ndarray] = {}
        for k, v in self.c.items():
            cnt = k.count(mu)
            if cnt == 0:
                continue
            lst = list(k)
            lst.remove(mu)
            beta = tuple(lst)
            if len(beta) <= order:
                c[beta] = _norm(v * cnt)
        if () not in c:
            c[()] = np.zeros(self.shape, dtype=object)
        return TJet(order, c)

    def grad(self) -> "TJet":
        """Stack of d_mu (new leading axis mu = 0..7)."""
        ds = [self.d(mu) for mu in range(DIM)]
        order = ds[0].order
        keys = set()
        for dj in ds:
            keys.update(dj.c.keys())
        c = {}
        for k in keys:
            c[k] = _norm(np.stack([dj.coeff(k) for dj in ds]))
        return TJet(order, c)


def jprod(A: TJet, B: TJet, op: Callable) -> TJet:
    order = min(A.order, B.order)
    c: Dict[Tuple[int, ...], np.ndarray] = {}
    for ka, va in A.c.items():
        la = len(ka)
        if la > order:
            continue
        for kb, vb in B.c.items():
            if la + len(kb) > order:
                continue
            k = tuple(sorted(ka + kb))
            r = _norm(op(va, vb))
            c[k] = _norm(c[k] + r) if k in c else r
    if () not in c:
        c[()] = _norm(op(A.value(), B.value()))
    return TJet(order, c)


def jein(spec: str, A, B) -> TJet:
    """einsum product of two jets (either may be a constant array)."""
    if not isinstance(A, TJet):
        A = TJet.const(A)
    if not isinstance(B, TJet):
        B = TJet.const(B)
    if A.order >= INF_ORDER and len(A.c) == 1:
        a0 = A.value()
        return B.map(lambda v: np.einsum(spec, a0, v))
    if B.order >= INF_ORDER and len(B.c) == 1:
        b0 = B.value()
        return A.map(lambda v: np.einsum(spec, v, b0))
    return jprod(A, B, lambda a, b: np.einsum(spec, a, b))


def jmul(A, B) -> TJet:
    """Elementwise/scalar product of jets (broadcasting)."""
    if not isinstance(A, TJet):
        A = TJet.const(A)
    if not isinstance(B, TJet):
        B = TJet.const(B)
    return jprod(A, B, lambda a, b: a * b)


def jet_zero_like(order: int, shape) -> TJet:
    return TJet(order, {(): np.zeros(shape, dtype=object)})


def jinv(A: TJet, dom: ExactDomain) -> TJet:
    """Inverse of a square-matrix jet: sum_k (-A0^{-1} N)^k A0^{-1}."""
    A0 = A.value()
    n = A0.shape[0]
    A0i = mat_inv(A0, dom)
    N = A - TJet.const(A0)
    Xj = jein("ij,jk->ik", -A0i, N)
    res = TJet.const(A0i, order=A.order)
    term = TJet.const(to_identity(n, dom), order=A.order)
    for _ in range(1, A.order + 1 if A.order < INF_ORDER else 1):
        term = jein("ij,jk->ik", term, Xj)
        res = res + jein("ij,jk->ik", term, A0i)
    return res


def to_identity(n: int, dom: ExactDomain) -> np.ndarray:
    I = np.empty((n, n), dtype=object)
    for i in range(n):
        for j in range(n):
            I[i, j] = dom.one if i == j else dom.zero
    return I


def jdet(A: TJet, dom: ExactDomain) -> TJet:
    """det of a square-matrix jet: det(A0) exp(tr log(1 + A0^{-1} N))."""
    A0 = A.value()
    n = A0.shape[0]
    d0 = mat_det(A0, dom)
    K = A.order if A.order < INF_ORDER else 0
    if K == 0:
        return TJet.const(d0, order=A.order)
    A0i = mat_inv(A0, dom)
    Y = jein("ij,jk->ik", A0i, A - TJet.const(A0))
    Lg = jet_zero_like(K, (n, n))
    P = TJet.const(to_identity(n, dom), order=K)
    for k in range(1, K + 1):
        P = jein("ij,jk->ik", P, Y)
        coef = dom.frac((-1) ** (k + 1), k)
        Lg = Lg + P.scale(coef)
    tau = Lg.map(lambda v: np.trace(v))
    Ex = TJet.const(dom.one, order=K)
    T = TJet.const(dom.one, order=K)
    for j in range(1, K + 1):
        T = jmul(T, tau)
        Ex = Ex + T.scale(dom.frac(1, math.factorial(j)))
    return Ex.scale(d0)


def jet_is_zero(J: TJet, dom: ExactDomain, max_order: Optional[int] = None) -> bool:
    for k, v in J.c.items():
        if max_order is not None and len(k) > max_order:
            continue
        if not arr_is_zero(v, dom):
            return False
    return True


# ---------------------------------------------------------------------------
# vielbein jets for the test geometries
# ---------------------------------------------------------------------------


def g1_vielbein_sympy() -> sp.Matrix:
    """(G1): e_mu^a = delta + P_mu^a, the generic non-diagonal test vielbein."""
    R = sp.Rational

    def P(mu, a):
        if mu != a:
            return (R(1, 10) * ((mu + 1) * X[a] - (a + 1) * X[mu]) + R(1, 20) * X[mu] * X[a]
                    + R(1, 30) * X[(mu + a) % 8] ** 2)
        return R(1, 10) * X[mu] ** 2 + R(1, 40) * X[(mu + 1) % 8]

    return sp.Matrix(8, 8, lambda mu, a: (1 if mu == a else 0) + P(mu, a))


G1_POINTS = {
    "p1": (sp.Rational(1, 7), sp.Rational(-2, 9), sp.Rational(1, 5), sp.Rational(3, 11), sp.Rational(-1, 13),
           sp.Rational(2, 17), sp.Rational(-3, 19), sp.Rational(1, 23)),
    "p2": (sp.Rational(-1, 3), sp.Rational(1, 4), sp.Rational(2, 7), sp.Rational(-1, 5), sp.Rational(1, 6),
           sp.Rational(-2, 11), sp.Rational(1, 9), sp.Rational(3, 13)),
    "p3": (sp.Rational(2, 9), sp.Rational(1, 8), sp.Rational(-1, 7), sp.Rational(1, 10), sp.Rational(-3, 14),
           sp.Rational(1, 12), sp.Rational(2, 15), sp.Rational(-1, 16)),
}


def g3_vielbein_sympy() -> sp.Matrix:
    """(G3): diagonal Gaussian-normal x4-only vielbein h_i = 1 + x4^2/(i+2), h_4 = 1."""
    h = [1 + X[4] ** 2 / sp.Integer(i + 2) if i != TIME_INDEX else sp.Integer(1) for i in range(8)]
    return sp.diag(*h)


G3_POINTS = {
    "q1": tuple([sp.Integer(0)] * 4 + [sp.Rational(1, 3)] + [sp.Integer(0)] * 3),
    "q2": tuple([sp.Integer(0)] * 4 + [sp.Rational(-2, 5)] + [sp.Integer(0)] * 3),
    "q3": tuple([sp.Integer(0)] * 4 + [sp.Rational(3, 7)] + [sp.Integer(0)] * 3),
}


def vielbein_jet_from_sympy(emat: sp.Matrix, point: Sequence[sp.Rational], order: int, dom: ExactDomain) -> TJet:
    """Exact symbolic differentiation, then exact substitution of the point."""
    subs = dict(zip(X, point))
    c = {}
    for alpha in multi_indices(order):
        arr = np.empty((8, 8), dtype=object)
        fact = alpha_factorial(alpha)
        for i in range(8):
            for j in range(8):
                f = emat[i, j]
                if alpha:
                    f = sp.diff(f, *[X[k] for k in alpha])
                val = f.subs(subs) if f.free_symbols else f
                if not val.is_Rational:
                    raise AssertionError("non-rational jet value")
                val = val / fact
                arr[i, j] = dom.conv(val)
        c[alpha] = arr
    return TJet(order, c)


# G2 -------------------------------------------------------------------------

G2_W = sp.Symbol("w", positive=True)   # w = sin(z)^(1/6) > 0, z = 6 H x0 in (0, pi/2)
G2_C = sp.Symbol("c", positive=True)   # c = cos(z) > 0
G2_E = sp.Symbol("E", positive=True)   # E = exp(a4(t)) = exp(A0), t = H x4
G2_A1, G2_A2, G2_A3 = sp.symbols("A1 A2 A3")  # a4'(t), a4''(t), a4'''(t)
G2_H = sp.Symbol("H", positive=True)
G2_GENS = (G2_W, G2_C, G2_E, G2_A1, G2_A2, G2_A3, G2_H)
G2_RELATION = G2_W ** 12 + G2_C ** 2 - 1  # sin^2 z + cos^2 z = 1 with sin z = w^6


def make_g2_domain() -> ExactDomain:
    K = QQ.frac_field(*G2_GENS)
    return ExactDomain(K, "QQ(w,c,E,A1,A2,A3,H) mod (w^12+c^2-1)", relations=[G2_RELATION])


def g2_vielbein_zt():
    """Primordial vielbein (CONTRACT section 9) as functions of z = 6 H x0, t = H x4."""
    z, t = sp.symbols("z t")
    a4 = sp.Function("a4")
    s = sp.sin(z)
    h = [sp.cos(z) / s] + [s ** sp.Rational(1, 6) * sp.exp(a4(t))] * 3 + [sp.Integer(1)] + \
        [s ** sp.Rational(1, 6) * sp.exp(-a4(t))] * 3
    return z, t, a4, h


def g2_vielbein_jet(order: int, dom: ExactDomain) -> TJet:
    """Exact jets of the primordial vielbein at a symbolic point.

    d/dx0 = 6H d/dz, d/dx4 = H d/dt.  After symbolic differentiation:
    a4'''(t) -> A3, a4''(t) -> A2, a4'(t) -> A1, a4(t) -> log(E),
    sin z -> w^6, cos z -> c (w > 0), i.e. sin(z)^(1/6) -> w exactly.
    """
    z, t, a4, h = g2_vielbein_zt()
    c = {}
    for alpha in multi_indices(order):
        arr = np.empty((8, 8), dtype=object)
        for i in range(8):
            for j in range(8):
                arr[i, j] = dom.zero
        n0 = alpha.count(0)
        n4 = alpha.count(4)
        if n0 + n4 == len(alpha):
            fact = alpha_factorial(alpha)
            for i in range(8):
                f = h[i]
                if n0:
                    f = sp.diff(f, z, n0)
                if n4:
                    f = sp.diff(f, t, n4)
                f = f * (6 * G2_H) ** n0 * G2_H ** n4 / fact
                f = f.subs(sp.Derivative(a4(t), (t, 3)), G2_A3).subs(sp.Derivative(a4(t), (t, 2)), G2_A2)
                f = f.subs(sp.Derivative(a4(t), t), G2_A1).subs(a4(t), sp.log(G2_E))
                f = f.subs({sp.sin(z): G2_W ** 6, sp.cos(z): G2_C})
                f = sp.powsimp(sp.expand_power_base(f, force=False))
                if f.free_symbols - set(G2_GENS):
                    raise AssertionError("unexpected symbols in G2 jet: %s" % f)
                arr[i, i] = dom.conv(f)
        c[alpha] = arr
    return TJet(order, c)


def generic_diagonal_jet(hvals: Sequence, dh: Dict[Tuple[int, int], object], dom: ExactDomain) -> TJet:
    """Order-1 jet of a diagonal vielbein diag(h) with d_nu h_mu = dh[(mu, nu)]."""
    c = {}
    v = np.empty((8, 8), dtype=object)
    for i in range(8):
        for j in range(8):
            v[i, j] = hvals[i] if i == j else dom.zero
    c[()] = v
    for nu in range(8):
        a = np.empty((8, 8), dtype=object)
        for i in range(8):
            for j in range(8):
                a[i, j] = dom.zero
        for mu in range(8):
            a[mu, mu] = dh.get((mu, nu), dom.zero)
        c[(nu,)] = a
    return TJet(1, c)


# ---------------------------------------------------------------------------
# geometry
# ---------------------------------------------------------------------------


class Geometry:
    """All geometric objects of CONTRACT section 4 as exact jets at one point."""

    def __init__(self, e: TJet, gd: GammaData, dom: ExactDomain, name: str,
                 sqrtg_sign: Optional[int] = None, curvature: bool = True):
        self.name = name
        self.dom = dom
        self.gd = gd
        self.e = e
        half = dom.frac(1, 2)
        ETA = gd.ETA
        self.einv = jinv(e, dom)                                    # [a, mu] = e_a^mu
        self.g = jein("mb,nb->mn", jein("ma,ab->mb", e, ETA), e)   # g_mu nu = e_mu^a eta_ab e_nu^b
        self.ginv = jinv(self.g, dom)
        # Christoffel symbols
        dg = self.g.grad()                                           # [l, m, n] = d_l g_mn
        t1 = dg.map(lambda a: np.einsum("mns->smn", a))              # d_m g_ns
        t2 = dg.map(lambda a: np.einsum("nms->smn", a))              # d_n g_ms
        gam1 = (t1 + t2 - dg).scale(half)                            # Gamma_{s m n}
        self.Gamma = jein("rs,smn->rmn", self.ginv, gam1)           # Gamma^r_{mn}
        # canonical spin connection (Christoffel route)
        self.de = e.grad()                                           # [m, n, a] = d_m e_n^a
        inner = jein("rmn,ra->mna", self.Gamma, e) - self.de
        self.omega_mixed = jein("bn,mna->mab", self.einv, inner)    # omega_mu^a_b
        self.omega_low = jein("ac,mcb->mab", ETA, self.omega_mixed)  # omega_{mu a b}
        # independent anholonomy route: omega_{cad} = (T_cda + T_acd - T_dac)/2,
        # T_cda = - e_c^mu e_d^nu (d_mu e_{nu a} - d_nu e_{mu a})
        eL = jein("nb,ba->na", e, ETA)
        deL = eL.grad()                                              # [m, n, a]
        Fm = deL - deL.map(lambda a: np.einsum("nma->mna", a))
        Tt = jein("cm,mna->cna", self.einv, Fm)
        Tt = jein("dn,cna->cda", self.einv, Tt).scale(-1)
        X1 = Tt.map(lambda a: np.einsum("cda->cad", a))
        X2 = Tt.map(lambda a: np.einsum("acd->cad", a))
        X3 = Tt.map(lambda a: np.einsum("dac->cad", a))
        omF = (X1 + X2 - X3).scale(half)                             # omega_{c a d} (frame)
        self.omega_low_anh = jein("mc,cab->mab", e, omF)             # omega_{mu a b}
        ETAinv = ETA  # eta^{-1} = eta
        self.omega_mixed_anh = jein("ac,mcb->mab", ETAinv, self.omega_low_anh)
        # spinor connections
        self.Omega = jein("mab,abij->mij", self.omega_low, gd.S).scale(half)
        self.Omega_nb = jein("mab,abij->mij", self.omega_mixed, gd.S).scale(half)
        # curved gammas gamma^mu = e_a^mu gamma^a
        self.gam = jein("am,aij->mij", self.einv, gd.GAM)
        self.gam_low = jein("mn,nij->mij", self.g, self.gam)
        # sqrt|g| = |det e|
        dete = jdet(e, dom)
        self.det_e = dete
        if sqrtg_sign is None:
            d0 = dete.value()[()]
            sqrtg_sign = 1 if d0 > 0 else -1
        self.sqrtg_sign = sqrtg_sign
        self.sqrtg = dete.scale(sqrtg_sign)
        self.detg = jdet(self.g, dom)
        self.curvature_done = False
        if curvature and self.Gamma.order >= 1:
            self._curvature()

    # -- curvature -----------------------------------------------------------
    def _curvature(self):
        dom = self.dom
        G0 = self.Gamma.value()
        dG = self.Gamma.grad().value()                               # [m, r, n, s] = d_m Gamma^r_ns
        R = (np.einsum("mrns->rsmn", dG) - np.einsum("nrms->rsmn", dG)
             + np.einsum("rml,lns->rsmn", G0, G0) - np.einsum("rnl,lms->rsmn", G0, G0))
        self.Riem = _norm(R)                                          # R^r_{s m n}
        self.Ric = _norm(np.einsum("rsrn->sn", R))
        ginv0 = self.ginv.value()
        self.Rscalar = np.einsum("sn,sn->", ginv0, self.Ric)
        half = dom.frac(1, 2)
        self.Gmixed = _norm(np.einsum("mr,rn->mn", ginv0, self.Ric) - to_identity(8, dom) * (self.Rscalar * half))
        e0 = self.e.value()
        einv0 = self.einv.value()
        Rf = np.einsum("ra,rsmn,bs->abmn", e0, R, einv0)             # R^a_{b m n}
        self.Rframe_mixed = _norm(Rf)
        self.Rframe_low = _norm(np.einsum("ac,cbmn->abmn", self.gd.ETA, Rf))
        # curvature of the frame connection omega
        om0 = self.omega_mixed.value()
        dom_ = self.omega_mixed.grad().value()                       # [m, n, a, b] = d_m omega_n^a_b
        Rw = (np.einsum("mnab->abmn", dom_) - np.einsum("nmab->abmn", dom_)
              + np.einsum("mac,ncb->abmn", om0, om0) - np.einsum("nac,mcb->abmn", om0, om0))
        self.Romega_mixed = _norm(Rw)
        # spinor curvature
        Om0 = self.Omega.value()
        dOm = self.Omega.grad().value()                              # [m, n, i, j] = d_m Omega_n
        F = (np.einsum("mnij->mnij", dOm) - np.einsum("nmij->mnij", dOm)
             + np.einsum("mij,njk->mnik", Om0, Om0) - np.einsum("nij,mjk->mnik", Om0, Om0))
        self.Fspin = _norm(F)
        self.curvature_done = True

    # -- derived checks ------------------------------------------------------
    def vielbein_postulate(self, which: str = "christoffel") -> TJet:
        om = self.omega_mixed if which == "christoffel" else self.omega_mixed_anh
        return self.de - jein("rmn,ra->mna", self.Gamma, self.e) + jein("mab,nb->mna", om, self.e)

    def omega_antisym_defect(self) -> TJet:
        return self.omega_low + self.omega_low.map(lambda a: np.einsum("mab->mba", a))

    def gamma_covariant_derivative(self, notebook: bool = False, max_order: Optional[int] = None) -> TJet:
        """D_mu gamma^nu = d_mu gamma^nu + Gamma^nu_{mu l} gamma^l + [Omega_mu, gamma^nu] as a jet
        (``max_order`` truncates the inputs so that only the requested jet order is computed)."""
        Om = self.Omega_nb if notebook else self.Omega
        gam, Gam = self.gam, self.Gamma
        if max_order is not None:
            gam = gam.truncate(max_order + 1)
            Om = Om.truncate(max_order)
            Gam = Gam.truncate(max_order)
        dgam = gam.grad()                                            # [m, n, i, j] = d_m gamma^n
        gam = gam.truncate(dgam.order)
        conn = jein("nml,lij->mnij", Gam, gam)
        comm = jein("mij,njk->mnik", Om, gam) - jein("nij,mjk->mnik", gam, Om)
        return dgam + conn + comm

    def divergence_identity_defect(self, notebook: bool = False, max_order: Optional[int] = None) -> TJet:
        """sum_mu d_mu(sqrt|g| gamma^mu) - sqrt|g| sum_mu [gamma^mu, Omega_mu] as a jet."""
        Om = self.Omega_nb if notebook else self.Omega
        sg, gam = self.sqrtg, self.gam
        if max_order is not None:
            sg = sg.truncate(max_order + 1)
            gam = gam.truncate(max_order + 1)
            Om = Om.truncate(max_order)
        sg_gam = jmul(sg, gam)                                       # scalar * (8,16,16)
        lhs = sg_gam.grad().map(lambda a: np.einsum("mmij->ij", a))  # sum_mu d_mu (sqrtg gamma^mu)
        gam = gam.truncate(lhs.order)
        comm = jein("mij,mjk->ik", gam, Om) - jein("mij,mjk->ik", Om, gam)
        rhs = jmul(sg.truncate(comm.order), comm)
        return lhs - rhs

    def truncated(self, order: int) -> "TruncatedGeometry":
        """Geometric jets truncated to ``order`` (cached); used to avoid computing unused orders."""
        if not hasattr(self, "_trunc_cache"):
            self._trunc_cache = {}
        if order not in self._trunc_cache:
            self._trunc_cache[order] = TruncatedGeometry(self, order)
        return self._trunc_cache[order]

    def slash_omega(self, notebook: bool = False) -> np.ndarray:
        Om = self.Omega_nb if notebook else self.Omega
        return _norm(np.einsum("mij,mjk->ik", self.gam.value(), Om.value()))


class TruncatedGeometry:
    """Same interface as Geometry for the spinor functions, with jets truncated to one order."""

    def __init__(self, geo: Geometry, order: int):
        self.dom = geo.dom
        self.gd = geo.gd
        self.order = order
        self.gam = geo.gam.truncate(order)
        self.gam_low = geo.gam_low.truncate(order)
        self.Omega = geo.Omega.truncate(order)
        self.Omega_nb = geo.Omega_nb.truncate(order)
        self.sqrtg = geo.sqrtg.truncate(order)
        self.g = geo.g.truncate(order)


# ---------------------------------------------------------------------------
# spinor fields, Lagrangian, Euler-Lagrange, EMT (commuting proxy)
# ---------------------------------------------------------------------------


def rand_rational(rng: random.Random, nonzero: bool = True) -> sp.Rational:
    while True:
        p = rng.randint(-9, 9)
        q = rng.randint(1, 9)
        if p != 0 or not nonzero:
            return sp.Rational(p, q)


def random_spinor_jet(rng: random.Random, dom: ExactDomain, order: int,
                      dirs: Optional[Sequence[int]] = None) -> TJet:
    """Independent exact random rational jets Psi_a, d_mu Psi_a, ... (Taylor coeffs)."""
    c = {}
    for alpha in multi_indices(order):
        arr = np.empty((NSPIN,), dtype=object)
        allowed = dirs is None or all(k in dirs for k in alpha)
        for i in range(NSPIN):
            arr[i] = dom.conv(rand_rational(rng)) if allowed else dom.zero
        c[alpha] = arr
    return TJet(order, c)


def covariant_derivative_psi(geo: Geometry, psi: TJet, dpsi: TJet, notebook: bool = False) -> TJet:
    Om = geo.Omega_nb if notebook else geo.Omega
    return dpsi + jein("mij,...j->...mi", Om, psi)


def covariant_derivative_psibar(geo: Geometry, pb: TJet, dpb: TJet) -> TJet:
    return dpb - jein("...i,mij->...mj", pb, geo.Omega)


def lagrangian_scalar(geo: Geometry, pb: TJet, dpb: TJet, psi: TJet, dpsi: TJet, m, lam) -> Dict[str, TJet]:
    """L_s = (1/2)(Psibar gamma^mu D_mu Psi - (D_mu Psibar) gamma^mu Psi) - m S - (lam/2) S^2.

    pb (Psibar = Psi^dagger C, row), dpb (its partial derivatives) and psi, dpsi
    are passed separately, so partial derivatives with respect to the jet
    variables can be taken by linearity (jet-space Euler-Lagrange).  A leading
    batch axis (``...``) is allowed on either the Psibar slot or the Psi slot.
    """
    dom = geo.dom
    half = dom.frac(1, 2)
    Dpsi = covariant_derivative_psi(geo, psi, dpsi)
    Dpb = covariant_derivative_psibar(geo, pb, dpb)
    t1 = jein("...mj,...mj->...", jein("...i,mij->...mj", pb, geo.gam), Dpsi)   # Psibar gamma^mu D_mu Psi
    t2 = jein("...j,...j->...", jein("...mi,mij->...j", Dpb, geo.gam), psi)      # (D_mu Psibar) gamma^mu Psi
    kin = (t1 - t2).scale(half)
    S = jein("...i,...i->...", pb, psi)
    Ls = kin - S.scale(m) - jmul(S, S).scale(lam * half)
    return {"Dpsi": Dpsi, "Dpb": Dpb, "kin": kin, "S": S, "Ls": Ls}


def psibar_from_chi(geo: Geometry, chi: TJet) -> TJet:
    """Psibar = chi^T C with chi standing for Psi^* (commuting proxy)."""
    return jein("...i,ij->...j", chi, geo.gd.C)


def euler_lagrange_psibar(geo: Geometry, psi: TJet, m, lam=0) -> np.ndarray:
    """EL_a = dL/dchi_a - d_mu dL/d(d_mu chi_a), chi_a := Psi^*_a (commuting proxy).

    L = sqrt|g| L_s is linear in (chi, d chi) for lam = 0, so the partial derivatives
    are the evaluations of L on unit jets (batched): P_a with chi = e_a, d chi = 0;
    Q^mu_a with chi = 0, d_nu chi = delta_{nu mu} e_a.  The total derivative d_mu Q^mu_a
    is the exact derivative of the jet Q^mu_a(x), which carries the x-dependence of
    the geometry and of Psi(x).
    """
    dom = geo.dom
    C = geo.gd.C
    if psi.order < 2:
        raise ValueError("Psi jets of order >= 2 are required (Q^mu_a is needed to first order)")
    dpsi = psi.grad()
    # P (value only): batch over a
    g0 = geo.truncated(0)
    pbP = TJet.const(_norm(C.copy()), order=0)                             # rows: e_a^T C
    dpbP = TJet.const(np.zeros((16, 8, 16), dtype=object), order=0)
    LP = lagrangian_scalar(g0, pbP, dpbP, psi.truncate(0), dpsi.truncate(0), m, lam)["Ls"]
    LP = jmul(g0.sqrtg, LP)
    P = LP.value()                                                         # (16,)
    # Q (first order): batch over (a, mu)
    g1 = geo.truncated(1)
    pbQ = TJet.const(np.zeros((16 * 8, 16), dtype=object), order=1)
    dq = np.zeros((16 * 8, 8, 16), dtype=object)
    for a in range(16):
        for mu in range(8):
            dq[a * 8 + mu, mu, :] = C[a, :]
    dpbQ = TJet.const(dq, order=1)
    LQ = lagrangian_scalar(g1, pbQ, dpbQ, psi.truncate(1), dpsi.truncate(1), m, lam)["Ls"]
    LQ = jmul(g1.sqrtg, LQ)                                                # jet, shape (128,)
    divQ = np.empty((16,), dtype=object)
    for a in range(16):
        s = dom.zero
        for mu in range(8):
            s = s + LQ.d(mu).value()[a * 8 + mu]
        divQ[a] = s
    return _norm(P - divQ)


def euler_lagrange_psi(geo: Geometry, chi: TJet, m, lam=0) -> np.ndarray:
    """EL w.r.t. Psi_a (commuting proxy): dL/dPsi_a - d_mu dL/d(d_mu Psi_a)."""
    dom = geo.dom
    if chi.order < 2:
        raise ValueError("chi jets of order >= 2 are required")
    pb = psibar_from_chi(geo, chi)
    dpb = pb.grad()
    I16 = to_identity(16, dom)
    g0 = geo.truncated(0)
    psiP = TJet.const(I16, order=0)
    dpsiP = TJet.const(np.zeros((16, 8, 16), dtype=object), order=0)
    LP = jmul(g0.sqrtg, lagrangian_scalar(g0, pb.truncate(0), dpb.truncate(0), psiP, dpsiP, m, lam)["Ls"])
    P = LP.value()
    g1 = geo.truncated(1)
    psiQ = TJet.const(np.zeros((128, 16), dtype=object), order=1)
    dq = np.zeros((128, 8, 16), dtype=object)
    for a in range(16):
        for mu in range(8):
            dq[a * 8 + mu, mu, a] = dom.one
    dpsiQ = TJet.const(dq, order=1)
    LQ = jmul(g1.sqrtg, lagrangian_scalar(g1, pb.truncate(1), dpb.truncate(1), psiQ, dpsiQ, m, lam)["Ls"])
    divQ = np.empty((16,), dtype=object)
    for a in range(16):
        s = dom.zero
        for mu in range(8):
            s = s + LQ.d(mu).value()[a * 8 + mu]
        divQ[a] = s
    return _norm(P - divQ)


def dirac_operator(geo: Geometry, psi: TJet, notebook: bool = False) -> TJet:
    """gamma^mu D_mu Psi."""
    Dpsi = covariant_derivative_psi(geo, psi, psi.grad(), notebook=notebook)
    return jein("mij,mj->i", geo.gam, Dpsi)


def field_equations(geo: Geometry, psi: TJet, chi: TJet, m, lam) -> Tuple[TJet, TJet, Dict[str, TJet]]:
    """E = gamma^mu D_mu Psi - (m + U'(S)) Psi, Ebar = (D_mu Psibar) gamma^mu + (m + U'(S)) Psibar,
    U(S) = (lam/2) S^2, S = Psibar Psi, Psibar = chi^T C."""
    pb = psibar_from_chi(geo, chi)
    parts = lagrangian_scalar(geo, pb, pb.grad(), psi, psi.grad(), m, lam)
    S = parts["S"]
    mU = S.scale(lam) + TJet.const(m)                                     # m + U'(S)
    E = jein("mij,mj->i", geo.gam, parts["Dpsi"]) - jmul(mU, psi)
    Ebar = jein("mi,mij->j", parts["Dpb"], geo.gam) + jmul(mU, pb)
    parts["pb"] = pb
    return E, Ebar, parts


def solve_onshell(geo: Geometry, psi: TJet, chi: TJet, m, lam, max_order: int = 1) -> Tuple[TJet, TJet]:
    """Replace the d_4-containing Taylor coefficients of Psi and chi so that the field
    equations hold at the point (max_order=1) or to first order (max_order=2)."""
    dom = geo.dom
    C = geo.gd.C
    psi = TJet(psi.order, {k: v.copy() for k, v in psi.c.items()})
    chi = TJet(chi.order, {k: v.copy() for k, v in chi.c.items()})
    G4 = geo.gam.value()[TIME_INDEX]
    G4i = mat_inv(G4, dom)
    half = dom.frac(1, 2)

    def correct(key, r, rb, factor):
        psi.c[key] = _norm(psi.c[key] - G4i.dot(r) * factor)
        chi.c[key] = _norm(chi.c[key] - (rb.dot(G4i)).dot(C) * factor)

    E, Eb, _ = field_equations(geo, psi, chi, m, lam)
    correct((TIME_INDEX,), E.value(), Eb.value(), dom.one)
    if max_order >= 2:
        E, Eb, _ = field_equations(geo, psi, chi, m, lam)
        for nu in range(8):
            if nu == TIME_INDEX:
                continue
            key = tuple(sorted((nu, TIME_INDEX)))
            correct(key, E.coeff((nu,)), Eb.coeff((nu,)), dom.one)
        E, Eb, _ = field_equations(geo, psi, chi, m, lam)
        correct((TIME_INDEX, TIME_INDEX), E.coeff((TIME_INDEX,)), Eb.coeff((TIME_INDEX,)), half)
    return psi, chi


def emt_covariant(geo: Geometry, pb: TJet, Dpb: TJet, psi: TJet, Dpsi: TJet, Ls: TJet) -> TJet:
    """T_mu nu of CONTRACT section 7 (all indices down)."""
    dom = geo.dom
    A = jein("mj,nj->mn", jein("i,mij->mj", pb, geo.gam_low), Dpsi)       # Psibar gamma_m D_n Psi
    B = jein("mnj,j->mn", jein("mi,nij->mnj", Dpb, geo.gam_low), psi)     # (D_m Psibar) gamma_n Psi
    AT = A.map(lambda a: a.T)
    BT = B.map(lambda a: a.T)
    kin = (A + AT - B - BT).scale(dom.frac(-1, 4))
    return kin + jmul(geo.g, Ls)


def emt_from_fields(geo: Geometry, psi: TJet, chi: TJet, m, lam) -> Dict[str, TJet]:
    pb = psibar_from_chi(geo, chi)
    parts = lagrangian_scalar(geo, pb, pb.grad(), psi, psi.grad(), m, lam)
    T = emt_covariant(geo, pb, parts["Dpb"], psi, parts["Dpsi"], parts["Ls"])
    parts["T"] = T
    parts["pb"] = pb
    return parts


def emt_divergence(geo: Geometry, T: TJet) -> np.ndarray:
    """nabla^mu T_mu nu at the point."""
    ginv0 = geo.ginv.value()
    G0 = geo.Gamma.value()
    dT = T.grad().value()                                                  # [r, m, n] = d_r T_mn
    T0 = T.value()
    cov = dT - np.einsum("lrm,ln->rmn", G0, T0) - np.einsum("lrn,ml->rmn", G0, T0)
    return _norm(np.einsum("mr,rmn->n", ginv0, cov))


def box_psi(geo: Geometry, psi: TJet) -> np.ndarray:
    """g^{mu nu} nabla_mu D_nu Psi = g^{mu nu}(d_mu D_nu Psi + Omega_mu D_nu Psi - Gamma^l_{mu nu} D_l Psi)."""
    Dpsi = covariant_derivative_psi(geo, psi, psi.grad())                  # [n, i]
    dD = Dpsi.grad().value()                                               # [m, n, i]
    Om0 = geo.Omega.value()
    D0 = Dpsi.value()
    G0 = geo.Gamma.value()
    inner = dD + np.einsum("mij,nj->mni", Om0, D0) - np.einsum("lmn,li->mni", G0, D0)
    return _norm(np.einsum("mn,mni->i", geo.ginv.value(), inner))


def jet_to_json_number(x, dom: ExactDomain) -> str:
    return dom.to_str(x)
