//! GKD: the generalized Kronecker delta, a pure-Rust refactoring of the author's
//! Wolfram Language definition (notebook "Generalized _Kronecker_Delta_4+4.nb"):
//!
//! ```text
//! kδ[lower_, upper_] /; Length[lower] == Length[upper] := Det[Outer[delta, lower, upper]]
//! ```
//!
//! For index lists lower = (l_1, ..., l_p) and upper = (u_1, ..., u_p) the matrix
//! Outer[delta, lower, upper] has the entries M_ij = delta(l_i, u_j) (1 if l_i = u_j,
//! else 0), and kδ is its determinant:
//!
//! ```text
//! δ^{u_1 ... u_p}_{l_1 ... l_p} = det[ delta(l_i, u_j) ]_{i,j = 1..p}.
//! ```
//!
//! Why GKD can avoid the determinant (proof, used by the implementation):
//!  (a) if two lower indices are equal, two rows of M are equal, so det M = 0;
//!  (b) if two upper indices are equal, two columns are equal, so det M = 0;
//!  (c) if some lower index l_i is not among the upper indices, row i is zero, det M = 0;
//!  (d) otherwise both lists consist of p distinct indices and every l_i equals exactly
//!      one u_{σ(i)}; σ is a permutation of {1..p} and M has a single 1 in each row i,
//!      in column σ(i): M is the permutation matrix of σ, and det M = sign(σ) by the
//!      Leibniz formula (only the term of σ survives).
//! So GKD costs O(p^2) integer operations (p <= 64) instead of a p x p determinant.
//! `kdelta_det` below is a literal transcription of the author's definition (Leibniz
//! determinant of the 0/1 matrix); the tests compare the two exhaustively.

/// GKD(lower, upper) = δ^{upper}_{lower} = Det[Outer[delta, lower, upper]].
/// Indices are coordinate labels 0..63. Panics if the lengths differ (the author's
/// definition is conditional on equal lengths and stays unevaluated otherwise).
#[allow(non_snake_case)]
pub fn GKD(lower: &[usize], upper: &[usize]) -> i32 {
    assert_eq!(lower.len(), upper.len(), "GKD: Length[lower] != Length[upper]");
    let p = lower.len();
    // position of each upper index; duplicates in `upper` give zero (case b)
    let mut pos = [u8::MAX; 64];
    for (j, &u) in upper.iter().enumerate() {
        assert!(u < 64, "GKD: index out of range");
        if pos[u] != u8::MAX {
            return 0;
        }
        pos[u] = j as u8;
    }
    // sigma(i) = position of l_i among the upper indices (cases a and c give zero)
    let mut sigma = [0u8; 64];
    let mut seen: u64 = 0;
    for (i, &l) in lower.iter().enumerate() {
        assert!(l < 64, "GKD: index out of range");
        let j = pos[l];
        if j == u8::MAX {
            return 0;
        }
        if seen & (1u64 << j) != 0 {
            return 0;
        }
        seen |= 1u64 << j;
        sigma[i] = j;
    }
    // sign(sigma) = (-1)^(number of inversions)  (case d)
    let mut inversions = 0usize;
    for a in 0..p {
        for b in (a + 1)..p {
            if sigma[a] > sigma[b] {
                inversions += 1;
            }
        }
    }
    if inversions.is_multiple_of(2) {
        1
    } else {
        -1
    }
}

/// Literal transcription of the author's definition: the Leibniz determinant of the
/// p x p matrix M_ij = delta(lower_i, upper_j). Used only to test GKD.
pub fn kdelta_det(lower: &[usize], upper: &[usize]) -> i64 {
    assert_eq!(lower.len(), upper.len());
    let p = lower.len();
    let m: Vec<Vec<i64>> = (0..p)
        .map(|i| (0..p).map(|j| if lower[i] == upper[j] { 1 } else { 0 }).collect())
        .collect();
    // Leibniz: sum over all permutations pi of sign(pi) prod_i M[i][pi(i)], generated by
    // Heap's algorithm (each swap flips the sign).
    let mut perm: Vec<usize> = (0..p).collect();
    let mut c = vec![0usize; p];
    let mut sign: i64 = 1;
    let mut total: i64 = (0..p).map(|i| m[i][perm[i]]).product::<i64>() * sign;
    let mut i = 0;
    while i < p {
        if c[i] < i {
            if i % 2 == 0 {
                perm.swap(0, i);
            } else {
                perm.swap(c[i], i);
            }
            sign = -sign;
            total += sign * (0..p).map(|r| m[r][perm[r]]).product::<i64>();
            c[i] += 1;
            i = 0;
        } else {
            c[i] = 0;
            i += 1;
        }
    }
    total
}

/// Exhaustive comparison of GKD with the literal determinant for all pairs of index
/// lists of length `p` over the values 0..dim-1. Returns (pairs compared, mismatches).
pub fn compare_exhaustive(p: usize, dim: usize) -> (u64, u64) {
    let total = (dim as u64).pow(2 * p as u32);
    let mut lower = vec![0usize; p];
    let mut upper = vec![0usize; p];
    let mut mismatches = 0u64;
    for code in 0..total {
        let mut c = code;
        for x in lower.iter_mut() {
            *x = (c % dim as u64) as usize;
            c /= dim as u64;
        }
        for x in upper.iter_mut() {
            *x = (c % dim as u64) as usize;
            c /= dim as u64;
        }
        if GKD(&lower, &upper) as i64 != kdelta_det(&lower, &upper) {
            mismatches += 1;
        }
    }
    (total, mismatches)
}

/// Deterministic pseudo-random comparison (xorshift64*) for longer index lists; half of
/// the samples are permutations (where GKD is nonzero), half arbitrary lists.
pub fn compare_random(p: usize, dim: usize, samples: u64, seed: u64) -> (u64, u64, u64) {
    let mut state = seed | 1;
    let mut next = move || {
        state ^= state >> 12;
        state ^= state << 25;
        state ^= state >> 27;
        state.wrapping_mul(0x2545F4914F6CDD1D)
    };
    let mut mismatches = 0u64;
    let mut nonzero = 0u64;
    for s in 0..samples {
        let upper: Vec<usize> = (0..p).map(|_| (next() % dim as u64) as usize).collect();
        let lower: Vec<usize> = if s % 2 == 0 {
            // a random permutation of `upper` (Fisher-Yates)
            let mut l = upper.clone();
            for i in (1..p).rev() {
                let j = (next() % (i as u64 + 1)) as usize;
                l.swap(i, j);
            }
            l
        } else {
            (0..p).map(|_| (next() % dim as u64) as usize).collect()
        };
        let g = GKD(&lower, &upper) as i64;
        if g != 0 {
            nonzero += 1;
        }
        if g != kdelta_det(&lower, &upper) {
            mismatches += 1;
        }
    }
    (samples, mismatches, nonzero)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn small_values() {
        // δ^{α}_{a}
        assert_eq!(GKD(&[0], &[0]), 1);
        assert_eq!(GKD(&[0], &[1]), 0);
        // δ^{αβ}_{ab} = δ^α_a δ^β_b - δ^β_a δ^α_b
        assert_eq!(GKD(&[0, 1], &[0, 1]), 1);
        assert_eq!(GKD(&[0, 1], &[1, 0]), -1);
        assert_eq!(GKD(&[0, 0], &[0, 0]), 0);
        // a 3-cycle is even, a transposition odd
        assert_eq!(GKD(&[0, 1, 2], &[1, 2, 0]), 1);
        assert_eq!(GKD(&[0, 1, 2], &[0, 2, 1]), -1);
        // more indices than dimensions: always zero (pigeonhole)
        assert_eq!(GKD(&[0, 1, 2, 3, 4, 5, 6, 7, 0], &[0, 1, 2, 3, 4, 5, 6, 7, 0]), 0);
    }

    #[test]
    fn exhaustive_up_to_three_indices_in_eight_dimensions() {
        for p in 1..=3 {
            let (n, bad) = compare_exhaustive(p, 8);
            assert_eq!(bad, 0, "p = {p}: {bad} of {n} mismatches");
        }
    }

    #[test]
    fn random_up_to_eight_indices() {
        for p in 4..=8 {
            let (n, bad, nonzero) = compare_random(p, 8, 4000, 0x9E3779B97F4A7C15 ^ p as u64);
            assert_eq!(bad, 0, "p = {p}: {bad} of {n} mismatches");
            assert!(nonzero > 0);
        }
    }
}
